# Import libarires

In [2]:
import pandas as pd
import numpy as np
import json
import os

In [3]:
orders = pd.read_csv("../datasets/orders.csv")

In [4]:
# Verify It Loaded

orders.head(2)

,order_id,customer_id,product_id,quantity,order_date,origin_hub,origin_city,destination_city,destination_state,destination_pincode,...,delivery_priority,payment_mode,order_value_inr,weather_condition_at_dest,assigned_vehicle_id,promised_eta_hours,actual_delivery_hours,delivery_cost_inr,transport_mode,order_status
0,ORD-011545,CUST-02608,PRD-00356,3,06-05-2024,HUB-LUC,Lucknow,CHANDIGARH,CH,160017,...,ECONOMY,Card,"₹79,382.91",Cloudy,VEH-0680,22.6,17.72,1682.59,truck,DELIVERED
1,ORD-008131,CUST-03997,PRD-00200,3,2024-12-27T12:23:00Z,HUB-CHE,Chennai,Chennai,TN,600001,...,EXPRESS,UPI,225352.59,Fog,VEH-0421,3.2,3.01,188.03,Van,delivered

 Understand the Dataset

In [5]:

orders.shape

(15650, 28)

In [6]:
orders.columns

Index(['order_id', 'customer_id', 'product_id', 'quantity', 'order_date',
       'origin_hub', 'origin_city', 'destination_city', 'destination_state',
       'destination_pincode', 'destination_lat', 'destination_lon',
       'distance_km', 'package_weight', 'package_dimensions_cm', 'is_fragile',
       'is_hazmat', 'cold_chain_required', 'delivery_priority', 'payment_mode',
       'order_value_inr', 'weather_condition_at_dest', 'assigned_vehicle_id',
       'promised_eta_hours', 'actual_delivery_hours', 'delivery_cost_inr',
       'transport_mode', 'order_status'],
      dtype='str')

In [7]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 15650 entries, 0 to 15649
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   order_id                   15650 non-null  str
 1   customer_id                15476 non-null  str
 2   product_id                 15650 non-null  str
 3   quantity                   15650 non-null  int64
 4   order_date                 15463 non-null  str
 5   origin_hub                 15650 non-null  str
 6   origin_city                15650 non-null  str
 7   destination_city           15650 non-null  str
 8   destination_state          15650 non-null  str
 9   destination_pincode        15650 non-null  int64
 10  destination_lat            15473 non-null  str
 11  destination_lon            15458 non-null  str
 12  distance_km                15451 non-null  str
 13  package_weight             15380 non-null  str
 14  package_dimensions_cm      11758 non-null  str
 15  is_fragile                 15650 non-null  str
 16  is_hazmat                  15650 non-null  int64
 17  cold_chain_required        15650 non-null  bool
 18  delivery_priority          15650 non-null  str
 19  payment_mode               15650 non-null  str
 20  order_value_inr            15650 non-null  str
 21  weather_condition_at_dest  15201 non-null  str
 22  assigned_vehicle_id        15015 non-null  str
 23  promised_eta_hours         15650 non-null  float64
 24  actual_delivery_hours      15252 non-null  str
 25  delivery_cost_inr          15402 non-null  str
 26  transport_mode             15378 non-null  str
 27  order_status               15650 non-null  str
dtypes: bool(1), float64(1), int64(3), str(23)
memory usage: 5.8 MB

Check null values

In [8]:
orders.isnull().sum()

order_id                        0
customer_id                   174
product_id                      0
quantity                        0
order_date                    187
origin_hub                      0
origin_city                     0
destination_city                0
destination_state               0
destination_pincode             0
destination_lat               177
destination_lon               192
distance_km                   199
package_weight                270
package_dimensions_cm        3892
is_fragile                      0
is_hazmat                       0
cold_chain_required             0
delivery_priority               0
payment_mode                    0
order_value_inr                 0
weather_condition_at_dest     449
assigned_vehicle_id           635
promised_eta_hours              0
actual_delivery_hours         398
delivery_cost_inr             248
transport_mode                272
order_status                    0
dtype: int64

percentage of each column is missing

In [9]:
missing_percentage = (orders.isnull().sum() / len(orders)) * 100
missing_percentage.sort_values(ascending=False)

package_dimensions_cm        24.869010
assigned_vehicle_id           4.057508
weather_condition_at_dest     2.869010
actual_delivery_hours         2.543131
transport_mode                1.738019
package_weight                1.725240
delivery_cost_inr             1.584665
distance_km                   1.271565
destination_lon               1.226837
order_date                    1.194888
destination_lat               1.130990
customer_id                   1.111821
destination_state             0.000000
destination_pincode           0.000000
origin_city                   0.000000
destination_city              0.000000
origin_hub                    0.000000
order_id                      0.000000
product_id                    0.000000
quantity                      0.000000
payment_mode                  0.000000
delivery_priority             0.000000
cold_chain_required           0.000000
is_hazmat                     0.000000
is_fragile                    0.000000
order_value_inr               0.000000
promised_eta_hours            0.000000
order_status                  0.000000
dtype: float64

In [10]:
orders["package_dimensions_cm"].head(10)

0             NaN
1        40x25x10
2        85x30x49
3             NaN
4        84x13x31
5        67*20*47
6        83x26x32
7        41*38*30
8        70*46*50
9    48 x 31 x 43
Name: package_dimensions_cm, dtype: str

In [11]:
orders.describe(include="all")

,order_id,customer_id,product_id,quantity,order_date,origin_hub,origin_city,destination_city,destination_state,destination_pincode,...,delivery_priority,payment_mode,order_value_inr,weather_condition_at_dest,assigned_vehicle_id,promised_eta_hours,actual_delivery_hours,delivery_cost_inr,transport_mode,order_status
count,15650,15476,15650,15650.000000,15463,15650,15650,15650,15650,15650.000000,...,15650,15650,15650,15201,15015,15650.000000,15252,15402,15378,15650
unique,15000,4756,1011,NaN,13592,20,20,40,15,NaN,...,16,6,6099,13,736,NaN,4331,14057,22,7
top,ORD-012155,-,PRD-00811,NaN,,HUB-LUC,Lucknow,Ahmedabad,MH,NaN,...,Standard,COD,296662.46,Clear,VEH-0701,NaN,0.3,unknown,Truck,Delivered
freq,3,44,36,NaN,52,840,840,790,2355,NaN,...,2013,2657,10,3715,108,NaN,399,68,4123,8140
mean,NaN,NaN,NaN,2.491565,NaN,NaN,NaN,NaN,NaN,471745.990671,...,NaN,NaN,NaN,NaN,NaN,18.804613,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,1.120436,NaN,NaN,NaN,NaN,NaN,203217.692343,...,NaN,NaN,NaN,NaN,NaN,22.245521,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,110001.000000,...,NaN,NaN,NaN,NaN,NaN,0.300000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,302001.000000,...,NaN,NaN,NaN,NaN,NaN,2.200000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,500001.000000,...,NaN,NaN,NaN,NaN,NaN,10.100000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,625001.000000,...,NaN,NaN,NaN,NaN,NaN,30.300000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,781001.000000,...,NaN,NaN,NaN,NaN,NaN,153.500000,NaN,NaN,NaN,NaN

In [12]:
orders['quantity'].value_counts()

quantity
1    3993
3    3938
4    3874
2    3845
Name: count, dtype: int64

In [13]:
orders['transport_mode'].value_counts(dropna=False)

transport_mode
Truck        4123
Bike         2399
Van          1441
truck        1083
TRUCK        1044
Air Cargo     995
bike          615
BIKE          603
Drone         553
van           374
Air_Cargo     363
AIR CARGO     362
VAN           362
air cargo     323
NaN           272
Ship          167
DRONE         142
drone         135
unknown        81
-              65
SHIP           55
               53
ship           40
Name: count, dtype: int64

In [14]:
orders['transport_mode'] = orders['transport_mode'].str.strip()

In [15]:
orders['transport_mode'] = (
    orders['transport_mode']
    .str.lower()
    .str.replace('_', ' ')
    .str.strip()
)

In [16]:
orders['transport_mode'].value_counts(dropna=False)

transport_mode
truck        6250
bike         3617
van          2177
air cargo    2043
drone         830
NaN           272
ship          262
unknown        81
-              65
               53
Name: count, dtype: int64

In [17]:
orders['transport_mode'] = orders['transport_mode'].replace(['unknown', '-', ''], np.nan)

In [18]:
orders['transport_mode'].value_counts(dropna=False)

transport_mode
truck        6250
bike         3617
van          2177
air cargo    2043
drone         830
NaN           471
ship          262
Name: count, dtype: int64

transport_mode is our target variable

In [19]:
orders = orders.dropna(subset=['transport_mode'])

In [20]:
orders['transport_mode'].isnull().sum()

np.int64(0)

Fix package_weight

In [21]:
def clean_package_weight(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    # Missing / invalid values
    if value.lower() in ["unknown", "-", ""]:
        return np.nan

    # Values explicitly in grams
    if value.lower().endswith("g") and not value.lower().endswith("kg"):
        try:
            weight = float(value[:-1].strip()) / 1000
            return weight if weight >= 0 else np.nan
        except:
            return np.nan

    # Values explicitly in kilograms
    if value.lower().endswith("kg"):
        try:
            weight = float(value[:-2].strip())
            return weight if weight >= 0 else np.nan
        except:
            return np.nan

    # Values without a unit → assume kg
    try:
        weight = float(value)
        return weight if weight >= 0 else np.nan
    except:
        return np.nan


orders["package_weight"] = orders["package_weight"].apply(clean_package_weight)

In [22]:
orders["package_weight"].describe()

count    14267.000000
mean       796.917449
std       2543.445242
min          0.180000
25%          3.120000
50%         10.590000
75%         80.730000
max      17623.680000
Name: package_weight, dtype: float64

In [23]:
print("Missing weights:", orders["package_weight"].isna().sum())
print("Negative weights:", (orders["package_weight"] < 0).sum())

Missing weights: 912
Negative weights: 0

Don't remove the large values yet

In [24]:
print("Weights > 1000 kg:", (orders['package_weight'] > 1000).sum())
print("Weights > 5000 kg:", (orders['package_weight'] > 5000).sum())
print("Weights > 10000 kg:", (orders['package_weight'] > 10000).sum())

Weights > 1000 kg: 1644
Weights > 5000 kg: 865
Weights > 10000 kg: 389

In [25]:
raw_check = pd.read_csv("../datasets/orders.csv")

In [26]:
large_ids = orders.loc[
    orders['package_weight'] > 10000,
    'order_id'
].head(20)

raw_check[raw_check['order_id'].isin(large_ids)][
    ['order_id', 'package_weight']
]

        order_id package_weight
27    ORD-004895        12897.0
60    ORD-001580       10256.24
111   ORD-009199       14923.48
146   ORD-012473     10641320 g
196   ORD-001659     16461240 g
217   ORD-000870       15006.28
231   ORD-009857     12897.00KG
282   ORD-003692    12067.65 kg
382   ORD-006328     11578680 g
409   ORD-002088       13217.76
419   ORD-003170     15477.28KG
526   ORD-013682       13545.12
549   ORD-012386     13550.08KG
575   ORD-014700    10888.41 kg
602   ORD-004871    14908.32 kg
666   ORD-014101       11829.64
682   ORD-009763       17623.68
710   ORD-006493     13896.32KG
739   ORD-007859        12084.8
774   ORD-010792     12728.76KG
9673  ORD-014101       11829.64

Check the corrected column for duplicates and missing

In [27]:
print("Missing package weights:", orders['package_weight'].isna().sum())
print("Negative package weights:", (orders['package_weight'] < 0).sum())
print("Zero package weights:", (orders['package_weight'] == 0).sum())

Missing package weights: 912
Negative package weights: 0
Zero package weights: 0

In [28]:
orders['package_weight'].describe()

count    14267.000000
mean       796.917449
std       2543.445242
min          0.180000
25%          3.120000
50%         10.590000
75%         80.730000
max      17623.680000
Name: package_weight, dtype: float64

Now create orders_cleaned

In [29]:
orders_cleaned = orders.copy()

In [30]:
orders_cleaned.shape

(15179, 28)

In [31]:
orders_cleaned.info()

<class 'pandas.DataFrame'>
Index: 15179 entries, 0 to 15649
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   order_id                   15179 non-null  str
 1   customer_id                15011 non-null  str
 2   product_id                 15179 non-null  str
 3   quantity                   15179 non-null  int64
 4   order_date                 14999 non-null  str
 5   origin_hub                 15179 non-null  str
 6   origin_city                15179 non-null  str
 7   destination_city           15179 non-null  str
 8   destination_state          15179 non-null  str
 9   destination_pincode        15179 non-null  int64
 10  destination_lat            15004 non-null  str
 11  destination_lon            14997 non-null  str
 12  distance_km                14984 non-null  str
 13  package_weight             14267 non-null  float64
 14  package_dimensions_cm      11407 non-null  str
 15  is_fragile                 15179 non-null  str
 16  is_hazmat                  15179 non-null  int64
 17  cold_chain_required        15179 non-null  bool
 18  delivery_priority          15179 non-null  str
 19  payment_mode               15179 non-null  str
 20  order_value_inr            15179 non-null  str
 21  weather_condition_at_dest  14741 non-null  str
 22  assigned_vehicle_id        14563 non-null  str
 23  promised_eta_hours         15179 non-null  float64
 24  actual_delivery_hours      14789 non-null  str
 25  delivery_cost_inr          14935 non-null  str
 26  transport_mode             15179 non-null  str
 27  order_status               15179 non-null  str
dtypes: bool(1), float64(2), int64(3), str(22)
memory usage: 5.6 MB

In [32]:
orders[['order_id', 'package_weight']].head(20)

      order_id  package_weight
0   ORD-011545           16.89
1   ORD-008131           87.54
2   ORD-005235          104.66
3   ORD-001394           59.44
4   ORD-011091           96.92
5   ORD-005379            1.54
6   ORD-011641            6.08
7   ORD-006654           11.58
8   ORD-012807            0.59
9   ORD-002865            2.66
10  ORD-007668           78.88
11  ORD-013904             NaN
12  ORD-007410            0.95
13  ORD-014936            1.12
14  ORD-004601           65.56
16  ORD-009316          111.52
17  ORD-000677            5.25
18  ORD-008718            1.36
19  ORD-010155             NaN
20  ORD-009823            2.40

# Create a cleaning function

In [33]:
import numpy as np

def clean_package_weight(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    if value.lower() in ['unknown', '-', '', 'nan']:
        return np.nan

    if value.lower().endswith('kg'):
        try:
            weight = float(value[:-2].strip())
            return weight if weight >= 0 else np.nan
        except:
            return np.nan

    if value.lower().endswith('g'):
        try:
            weight = float(value[:-1].strip()) / 1000
            return weight if weight >= 0 else np.nan
        except:
            return np.nan

    try:
        weight = float(value)
        return weight if weight >= 0 else np.nan
    except:
        return np.nan

In [34]:
orders['package_weight'] = orders['package_weight'].apply(
    clean_package_weight
)

In [35]:
orders[['order_id', 'package_weight']].head(20)

      order_id  package_weight
0   ORD-011545           16.89
1   ORD-008131           87.54
2   ORD-005235          104.66
3   ORD-001394           59.44
4   ORD-011091           96.92
5   ORD-005379            1.54
6   ORD-011641            6.08
7   ORD-006654           11.58
8   ORD-012807            0.59
9   ORD-002865            2.66
10  ORD-007668           78.88
11  ORD-013904             NaN
12  ORD-007410            0.95
13  ORD-014936            1.12
14  ORD-004601           65.56
16  ORD-009316          111.52
17  ORD-000677            5.25
18  ORD-008718            1.36
19  ORD-010155             NaN
20  ORD-009823            2.40

Check the corrected statistics

In [36]:
orders['package_weight'].describe()

count    14267.000000
mean       796.917449
std       2543.445242
min          0.180000
25%          3.120000
50%         10.590000
75%         80.730000
max      17623.680000
Name: package_weight, dtype: float64

In [37]:
orders.loc[
    orders['package_weight'] > 1000,
    ['order_id', 'quantity', 'package_weight', 'transport_mode', 'order_value_inr']
].sort_values('package_weight', ascending=False).head(20)

           order_id  quantity  package_weight transport_mode order_value_inr
682      ORD-009763         4        17623.68          truck       446445.28
2231     ORD-008900         4        17623.68          truck     ₹446,445.28
9208     ORD-009186         4        17623.68          truck     ₹446,445.28
1178     ORD-012529         4        17623.68          truck     ₹446,445.28
1999     ORD-005709         4        17623.68          truck       446445.28
9211     ORD-007848         4        17572.28            van       241732.72
14622    ORD-007918         4        17572.28          truck       241732.72
5432     ORD-012048         4        17572.28          truck       241732.72
13103    ORD-010159         4        17572.28          drone       241732.72
8047    ORD-010995          4        17555.32          truck        186319.8
7571     ORD-003389         4        17555.32          truck     ₹186,319.80
14228    ORD-011793         4        17555.32          truck       186319.80
9048     ORD-001895         4        17555.32          truck     ₹186,319.80
9325     ORD-011322         4        17023.84          truck       302221.68
6591     ORD-005891         4        17023.84          truck       302221.68
12705    ORD-004785         4        17023.84          truck     ₹302,221.68
11674    ORD-007034         4        16971.68          truck       384144.32
2195     ord-011417         4        16971.68          truck     ₹384,144.32
9057     ORD-005229         4        16971.68          truck     ₹384,144.32
12923    ORD-014002         4        16971.68          truck       384144.32

In [38]:
orders.loc[
    orders['order_id'].isin([
        'ORD-009763',
        'ORD-008900',
        'ORD-009186',
        'ORD-012529',
        'ORD-005709'
    ]),
    ['order_id', 'quantity', 'package_weight', 'transport_mode', 'order_value_inr']
]

        order_id  quantity  package_weight transport_mode order_value_inr
682   ORD-009763         4        17623.68          truck       446445.28
1178  ORD-012529         4        17623.68          truck     ₹446,445.28
1999  ORD-005709         4        17623.68          truck       446445.28
2231  ORD-008900         4        17623.68          truck     ₹446,445.28
9208  ORD-009186         4        17623.68          truck     ₹446,445.28

In [39]:
print("Missing weights:", orders['package_weight'].isna().sum())
print("Negative weights:", (orders['package_weight'] < 0).sum())

Missing weights: 912
Negative weights: 0

In [40]:
orders['delivery_priority'] = (
    orders['delivery_priority']
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        'std': 'standard',
        'exp': 'express',
        'eco': 'economy',
        'same-day': 'same-day',
        'sameday': 'same-day'
    })
)

In [41]:
print(orders['delivery_priority'].value_counts())

delivery_priority
standard    7589
express     4176
same-day    1870
economy     1544
Name: count, dtype: int64

In [42]:
orders['payment_mode'] = (
    orders['payment_mode']
    .astype(str)
    .str.strip()
    .str.lower()
)

In [43]:
print(orders['payment_mode'].value_counts())

payment_mode
cod        5129
prepaid    4993
card       2555
upi        2502
Name: count, dtype: int64

In [44]:
orders['weather_condition_at_dest'] = (
    orders['weather_condition_at_dest']
    .astype('string')
    .str.strip()
    .str.lower()
)

orders['weather_condition_at_dest'] = orders['weather_condition_at_dest'].replace({
    '-': pd.NA,
    'unknown': pd.NA,
    '': pd.NA
})

In [45]:
print(orders['weather_condition_at_dest'].value_counts(dropna=False))

weather_condition_at_dest
clear           5070
cloudy          2874
rain            2579
sunny           1329
fog              910
heavy rain       903
<NA>             770
thunderstorm     744
Name: count, dtype: int64[pyarrow]

In [46]:
orders['order_status'] = (
    orders['order_status']
    .astype('string')
    .str.strip()
    .str.lower()
)

In [47]:
print(orders['order_status'].value_counts())

order_status
delivered     9888
in transit    2703
pending        914
cancelled      890
returned       784
Name: count, dtype: int64[pyarrow]

Save the cleaned dataset

In [48]:
orders.to_csv("../datasets/orders_cleaned.csv", index=False)

# Load the cleaned dataset

In [49]:
orders_clean = pd.read_csv("../datasets/orders_cleaned.csv")

In [50]:
orders_cleaned = orders.copy()

In [51]:
orders_clean.shape

(15179, 28)

Check the Data Types

In [52]:
orders_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 15179 entries, 0 to 15178
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   order_id                   15179 non-null  str
 1   customer_id                15011 non-null  str
 2   product_id                 15179 non-null  str
 3   quantity                   15179 non-null  int64
 4   order_date                 14999 non-null  str
 5   origin_hub                 15179 non-null  str
 6   origin_city                15179 non-null  str
 7   destination_city           15179 non-null  str
 8   destination_state          15179 non-null  str
 9   destination_pincode        15179 non-null  int64
 10  destination_lat            15004 non-null  str
 11  destination_lon            14997 non-null  str
 12  distance_km                14984 non-null  str
 13  package_weight             14267 non-null  float64
 14  package_dimensions_cm      11407 non-null  str
 15  is_fragile                 15179 non-null  str
 16  is_hazmat                  15179 non-null  int64
 17  cold_chain_required        15179 non-null  bool
 18  delivery_priority          15179 non-null  str
 19  payment_mode               15179 non-null  str
 20  order_value_inr            15179 non-null  str
 21  weather_condition_at_dest  14409 non-null  str
 22  assigned_vehicle_id        14563 non-null  str
 23  promised_eta_hours         15179 non-null  float64
 24  actual_delivery_hours      14789 non-null  str
 25  delivery_cost_inr          14935 non-null  str
 26  transport_mode             15179 non-null  str
 27  order_status               15179 non-null  str
dtypes: bool(1), float64(2), int64(3), str(22)
memory usage: 5.5 MB

Inspect the numeric columns

In [53]:
orders_clean[['order_value_inr',
              'distance_km',
              'package_weight',
              'delivery_cost_inr']].head(10)

  order_value_inr distance_km  package_weight delivery_cost_inr
0      ₹79,382.91      596.23           16.89           1682.59
1       225352.59    15.32 km           87.54            188.03
2        49417.12       11.98          104.66            283.37
3     ₹200,811.44        3.24           59.44            212.46
4       523513.96     1962.16           96.92           5397.55
5     ₹374,218.58        5.01            1.54             18.01
6       750203.20     1274.31            6.08          12399.36
7       210888.00         6.7           11.58             70.85
8     ₹150,012.06      1998.4            0.59          19237.85
9       334400.18        3.45            2.66             -1.26

order_value_inr

In [54]:
orders_clean['order_value_inr'] = (
    orders_clean['order_value_inr']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
)

orders_clean['order_value_inr'] = pd.to_numeric(
    orders_clean['order_value_inr'],
    errors='coerce'
)

In [55]:
orders_clean['order_value_inr'].head(10)

0     79382.91
1    225352.59
2     49417.12
3    200811.44
4    523513.96
5    374218.58
6    750203.20
7    210888.00
8    150012.06
9    334400.18
Name: order_value_inr, dtype: float64

distance_km

In [56]:
orders_clean['distance_km'] = (
    orders_clean['distance_km']
    .astype(str)
    .str.replace(' km', '', regex=False)
)

orders_clean['distance_km'] = pd.to_numeric(
    orders_clean['distance_km'],
    errors='coerce'
)

In [57]:
orders_clean['distance_km'].head(10)

0     596.23
1      15.32
2      11.98
3       3.24
4    1962.16
5       5.01
6    1274.31
7       6.70
8    1998.40
9       3.45
Name: distance_km, dtype: float64

package_weight

In [58]:
orders_clean['package_weight'] = (
    orders_clean['package_weight']
    .astype(str)
    .str.lower()
    .str.replace('kg', '', regex=False)
    .str.replace('g', '', regex=False)
    .str.strip()
)

orders_clean['package_weight'] = pd.to_numeric(
    orders_clean['package_weight'],
    errors='coerce'
)

In [59]:
orders_clean['package_weight'].head(10)

0     16.89
1     87.54
2    104.66
3     59.44
4     96.92
5      1.54
6      6.08
7     11.58
8      0.59
9      2.66
Name: package_weight, dtype: float64

Convert all values to kilograms (kg)

In [60]:
mask_g = orders_clean['package_weight'].astype(str).str.contains(r'\bg\b', case=False, na=False)

In [61]:
orders_clean['package_weight'] = (
    orders_clean['package_weight']
    .astype(str)
    .str.replace('KG', '', case=False, regex=False)
    .str.replace('g', '', case=False, regex=False)
    .str.strip()
)

orders_clean['package_weight'] = pd.to_numeric(
    orders_clean['package_weight'],
    errors='coerce'
)

orders_clean.loc[mask_g, 'package_weight'] /= 1000

In [62]:
orders_clean[['package_weight']].head(10)

   package_weight
0           16.89
1           87.54
2          104.66
3           59.44
4           96.92
5            1.54
6            6.08
7           11.58
8            0.59
9            2.66

delivery_cost_inr

In [63]:
orders_clean['delivery_cost_inr'] = pd.to_numeric(
    orders_clean['delivery_cost_inr'],
    errors='coerce'
)

In [64]:
(orders_clean['delivery_cost_inr'] < 0).sum()

np.int64(261)

treat negative delivery costs as invalid data

In [65]:
orders_clean.loc[
    orders_clean['delivery_cost_inr'] < 0,
    'delivery_cost_inr'
] = np.nan

In [66]:
orders_clean['delivery_cost_inr'].isnull().sum()

np.int64(691)

delivery_cost_inr fill them with the median

In [67]:
orders_clean['delivery_cost_inr'] = orders_clean['delivery_cost_inr'].fillna(
    orders_clean['delivery_cost_inr'].median()
)

In [68]:
orders_clean['delivery_cost_inr'].isnull().sum()

np.int64(0)

Clean order_date

In [69]:
orders_clean['order_date'].sample(10, random_state=42)

14928        2024/05/04 19:00
8473         21/11/2024 08:44
13342     2024-12-28 12:44:00
3344      2024-02-04 17:05:00
7061     2024-12-02T18:05:00Z
351       2024-11-21 13:05:00
2054               1727451840
3322      2024-04-19 18:12:00
339       2024-01-05 18:00:00
2039      2024-11-04 11:58:00
Name: order_date, dtype: str

find out how many Unix timestamps (10-digit numbers) are present

In [70]:
orders_clean['order_date'].astype(str).str.fullmatch(r'\d{10}').sum()

np.int64(716)

In [71]:
orders_clean['order_date_raw'] = orders_clean['order_date']

In [72]:
mask_unix = orders_clean['order_date'].astype(str).str.fullmatch(r'\d{10}')

orders_clean.loc[mask_unix, 'order_date'] = (
    pd.to_datetime(
        orders_clean.loc[mask_unix, 'order_date'].astype('int64'),
        unit='s'
    ).dt.strftime('%Y-%m-%d %H:%M:%S')
)

In [73]:
orders_clean.loc[mask_unix, ['order_date_raw', 'order_date']].head()

    order_date_raw           order_date
7       1736093520  2025-01-05 16:12:00
9       1708513200  2024-02-21 11:00:00
100     1721402580  2024-07-19 15:23:00
206     1736158620  2025-01-06 10:17:00
231     1729261860  2024-10-18 14:31:00

remaining date formats

In [74]:
orders_clean['order_date'] = pd.to_datetime(
    orders_clean['order_date'],
    format='mixed',
    dayfirst=True,
    utc=True,
    errors='coerce'
)

In [75]:
orders_clean['order_date'].head()

0   2024-05-06 00:00:00+00:00
1   2024-12-27 12:23:00+00:00
2   2024-11-18 12:58:00+00:00
3   2024-08-29 11:05:00+00:00
4   2025-04-28 21:44:00+00:00
Name: order_date, dtype: datetime64[us, UTC]

In [76]:
orders_clean['order_date'].isnull().sum()

np.int64(322)

In [77]:
orders_clean.loc[
    orders_clean['order_date'].isna(),
    'order_date_raw'
].head(20)

12         NaN
24         NaN
53           -
95         NaN
102        NaN
121        NaN
139        NaN
157    unknown
234        NaN
317        NaN
390        NaN
508    unknown
536          -
555          -
598        NaN
639    unknown
651        NaN
697
720        NaN
721    unknown
Name: order_date_raw, dtype: str

In [78]:
orders_clean['order_date'] = orders_clean['order_date'].fillna(pd.NaT)

In [79]:
orders_clean['order_date'].isnull().sum()

np.int64(322)

Clean the Remaining Missing Values

In [80]:
orders_clean.isnull().sum().sort_values(ascending=False)

package_dimensions_cm        3772
distance_km                   954
package_weight                912
weather_condition_at_dest     770
assigned_vehicle_id           616
actual_delivery_hours         390
order_date                    322
destination_lon               182
order_date_raw                180
destination_lat               175
customer_id                   168
quantity                        0
product_id                      0
destination_pincode             0
origin_city                     0
destination_city                0
destination_state               0
origin_hub                      0
order_id                        0
is_fragile                      0
is_hazmat                       0
order_value_inr                 0
payment_mode                    0
delivery_priority               0
cold_chain_required             0
promised_eta_hours              0
delivery_cost_inr               0
transport_mode                  0
order_status                    0
dtype: int64

In [81]:
orders_clean = orders_clean.drop(columns=['assigned_vehicle_id'])

In [82]:
'assigned_vehicle_id' in orders_clean.columns

False

Fill numeric columns with the median

In [83]:
orders_clean[['distance_km',
              'package_weight',
              'destination_lat',
              'destination_lon',
              'actual_delivery_hours']].dtypes

distance_km              float64
package_weight           float64
destination_lat              str
destination_lon              str
actual_delivery_hours        str
dtype: object

In [84]:
orders_clean['destination_lat'] = pd.to_numeric(
    orders_clean['destination_lat'], errors='coerce'
)

orders_clean['destination_lon'] = pd.to_numeric(
    orders_clean['destination_lon'], errors='coerce'
)

orders_clean['actual_delivery_hours'] = pd.to_numeric(
    orders_clean['actual_delivery_hours'], errors='coerce'
)

In [85]:
# Convert string columns to numeric

orders_clean['destination_lat'] = pd.to_numeric(
    orders_clean['destination_lat'], errors='coerce'
)

orders_clean['destination_lon'] = pd.to_numeric(
    orders_clean['destination_lon'], errors='coerce'
)

# Fill missing values with median
orders_clean['distance_km'] = orders_clean['distance_km'].fillna(
    orders_clean['distance_km'].median()
)

orders_clean['package_weight'] = orders_clean['package_weight'].fillna(
    orders_clean['package_weight'].median()
)

orders_clean['destination_lat'] = orders_clean['destination_lat'].fillna(
    orders_clean['destination_lat'].median()
)

orders_clean['destination_lon'] = orders_clean['destination_lon'].fillna(
    orders_clean['destination_lon'].median()
)

orders_clean['actual_delivery_hours'] = orders_clean['actual_delivery_hours'].fillna(
    orders_clean['actual_delivery_hours'].median()
)

In [86]:
orders_clean[['distance_km',
              'package_weight',
              'destination_lat',
              'destination_lon',
              'actual_delivery_hours']].isnull().sum()

distance_km              0
package_weight           0
destination_lat          0
destination_lon          0
actual_delivery_hours    0
dtype: int64

In [87]:
orders_clean.isnull().sum().sort_values(ascending=False)

package_dimensions_cm        3772
weather_condition_at_dest     770
order_date                    322
order_date_raw                180
customer_id                   168
quantity                        0
origin_city                     0
destination_city                0
destination_state               0
origin_hub                      0
product_id                      0
order_id                        0
destination_lon                 0
destination_lat                 0
destination_pincode             0
distance_km                     0
is_hazmat                       0
cold_chain_required             0
package_weight                  0
is_fragile                      0
payment_mode                    0
delivery_priority               0
promised_eta_hours              0
order_value_inr                 0
actual_delivery_hours           0
delivery_cost_inr               0
transport_mode                  0
order_status                    0
dtype: int64

Fill the remaining useful columns

In [88]:
orders_clean['weather_condition_at_dest'] = orders_clean['weather_condition_at_dest'].fillna(
    orders_clean['weather_condition_at_dest'].mode()[0]
)

orders_clean['customer_id'] = orders_clean['customer_id'].fillna('UNKNOWN')

Drop unnecessary columns

In [89]:
orders_clean = orders_clean.drop(
    columns=['package_dimensions_cm', 'order_date_raw']
)

In [90]:
orders_clean = orders_clean.dropna(subset=['order_date'])

orders_clean.shape

(14857, 26)

In [91]:
orders_clean = orders_clean.drop_duplicates().copy()

In [92]:
orders_clean.shape

(14427, 26)

In [93]:
orders_clean.duplicated().sum()

np.int64(0)

In [94]:
orders_clean = orders_clean.reset_index(drop=True)

In [95]:
orders_clean.index

RangeIndex(start=0, stop=14427, step=1)

In [96]:
orders_cleaned = orders.copy()

# Drop columns we decided not to keep
orders_cleaned = orders_cleaned.drop(
    columns=['package_dimensions_cm', 'assigned_vehicle_id'],
    errors='ignore'
)

# Convert columns to numeric
numeric_cols = [
    'destination_pincode',
    'destination_lat',
    'destination_lon',
    'distance_km',
    'order_value_inr',
    'actual_delivery_hours',
    'delivery_cost_inr'
]

for col in numeric_cols:
    orders_cleaned[col] = pd.to_numeric(
        orders_cleaned[col],
        errors='coerce'
    )

# Convert order date
orders_cleaned['order_date'] = pd.to_datetime(
    orders_cleaned['order_date'],
    errors='coerce'
)

# Remove rows with missing values
orders_cleaned = orders_cleaned.dropna().reset_index(drop=True)

# Remove duplicate rows
orders_cleaned = orders_cleaned.drop_duplicates().reset_index(drop=True)

In [97]:
print("Rows:", len(orders_cleaned))
print("Columns:", len(orders_cleaned.columns))
print("Missing values:", orders_cleaned.isna().sum().sum())
print("Duplicate rows:", orders_cleaned.duplicated().sum())

Rows: 193
Columns: 26
Missing values: 0
Duplicate rows: 0

In [98]:
orders_cleaned["package_weight"].describe()

count      193.000000
mean       736.028238
std       2194.516593
min          0.260000
25%          3.860000
50%         16.560000
75%         94.340000
max      12418.160000
Name: package_weight, dtype: float64

# Save the order cleaned dataset

In [99]:
import os

os.makedirs("../cleaned_data", exist_ok=True)

In [100]:
orders_clean.to_csv("../cleaned_data/orders_cleaned.csv", index=False)

print("Saved successfully")

Saved successfully

# 2. Customers dataset

In [101]:
customers = pd.read_csv("../datasets/customers.csv")

In [102]:
customers.head(2)

,customer_id,customer_name,email,phone,city,state,pincode,signup_date,customer_segment,is_prime_member,lifetime_orders,avg_rating_given
0,CUST-00922,Rahul Chowdhury,rahul.chowdhury28@outlook.com,09709931145,Pune,MH,411001,2021-08-12 00:00:00,SMB,Yes,17,2.3
1,CUST-04911,bhavana patel,bhavana.patel521@gmail.com,91 98945-07693,Nagpur,MH,440001,25/07/2023 00:00,Enterprise,N,133,4.6

In [103]:
customers.shape

(5120, 12)

In [104]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5120 entries, 0 to 5119
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5120 non-null   str
 1   customer_name     5077 non-null   str
 2   email             5033 non-null   str
 3   phone             5012 non-null   str
 4   city              5120 non-null   str
 5   state             5120 non-null   str
 6   pincode           5120 non-null   int64
 7   signup_date       5120 non-null   str
 8   customer_segment  5120 non-null   str
 9   is_prime_member   5120 non-null   str
 10  lifetime_orders   5065 non-null   str
 11  avg_rating_given  4941 non-null   str
dtypes: int64(1), str(11)
memory usage: 973.6 KB

In [105]:
customers.isnull().sum()

customer_id           0
customer_name        43
email                87
phone               108
city                  0
state                 0
pincode               0
signup_date           0
customer_segment      0
is_prime_member       0
lifetime_orders      55
avg_rating_given    179
dtype: int64

In [106]:
customers.duplicated().sum()

np.int64(120)

In [107]:
customers = customers.drop_duplicates().copy()

In [108]:
customers.shape

(5000, 12)

In [109]:
customers.info()

<class 'pandas.DataFrame'>
Index: 5000 entries, 0 to 5119
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   str
 1   customer_name     4957 non-null   str
 2   email             4914 non-null   str
 3   phone             4894 non-null   str
 4   city              5000 non-null   str
 5   state             5000 non-null   str
 6   pincode           5000 non-null   int64
 7   signup_date       5000 non-null   str
 8   customer_segment  5000 non-null   str
 9   is_prime_member   5000 non-null   str
 10  lifetime_orders   4946 non-null   str
 11  avg_rating_given  4825 non-null   str
dtypes: int64(1), str(11)
memory usage: 993.4 KB

In [110]:
customers.isnull().sum()

customer_id           0
customer_name        43
email                86
phone               106
city                  0
state                 0
pincode               0
signup_date           0
customer_segment      0
is_prime_member       0
lifetime_orders      54
avg_rating_given    175
dtype: int64

In [111]:
# Customer Segment

customers['customer_segment'].value_counts(dropna=False)

customer_segment
SMB           892
Business      841
retail        833
BUSINESS      830
Enterprise    804
Retail        800
Name: count, dtype: int64

In [112]:
customers['customer_segment'] = customers['customer_segment'].str.strip().str.title()

In [113]:
customers['customer_segment'] = customers['customer_segment'].replace({'Smb': 'SMB'})

In [114]:
customers['customer_segment'].value_counts()

customer_segment
Business      1671
Retail        1633
SMB            892
Enterprise     804
Name: count, dtype: int64

Inspect is_prime_member

In [115]:
customers['is_prime_member'].value_counts(dropna=False)

is_prime_member
N        536
Yes      524
Y        515
False    513
No       506
0        504
True     501
no       469
yes      469
1        463
Name: count, dtype: int64

In [116]:
customers['is_prime_member'] = (
    customers['is_prime_member']
    .replace({
        'Y': 'Yes',
        'yes': 'Yes',
        'True': 'Yes',
        '1': 'Yes',
        'N': 'No',
        'no': 'No',
        'False': 'No',
        '0': 'No'
    })
)

In [117]:
customers['is_prime_member'].value_counts()

is_prime_member
No     2528
Yes    2472
Name: count, dtype: int64

Inspect customer_name

In [118]:
customers['customer_name'].head(10)

0      Rahul Chowdhury
1        bhavana patel
2         aravind bose
3         SURESH MEHTA
4      Karthik Mehta
5          kavya mehta
6          Rahul Raman
7          Arjun Raman
8         revathi iyer
9          Meera Reddy
Name: customer_name, dtype: str

In [119]:
customers['customer_name'].sample(10, random_state=42)

1512     vikram reddy
2613      Vikram Nair
2680    Ananya Sharma
1059      Ananya Nair
706       LAKSHMI DAS
106        Deepa Iyer
590         Rahul Das
2491       Manish Das
2436    Sāthish Menon
1612     Nithin Kumar
Name: customer_name, dtype: str

Clean customer_name

In [120]:
customers['customer_name'] = customers['customer_name'].str.strip().str.title()

In [121]:
customers['customer_name'].head(10)

0    Rahul Chowdhury
1      Bhavana Patel
2       Aravind Bose
3       Suresh Mehta
4      Karthik Mehta
5        Kavya Mehta
6        Rahul Raman
7        Arjun Raman
8       Revathi Iyer
9        Meera Reddy
Name: customer_name, dtype: str

Check missing customer_name

In [122]:
customers['customer_name'].isna().sum()

np.int64(43)

Fill missing names

In [123]:
customers['customer_name'] = customers['customer_name'].fillna('Unknown')

Check email

In [124]:
customers['email'].head(10)

0     rahul.chowdhury28@outlook.com
1        bhavana.patel521@gmail.com
2       aravind.bose368@outlook.com
3         suresh.mehta950@gmail.com
4        karthik.mehta781@gmail.com
5     kavya.mehta444@protonmail.com
6     rahul.raman597@protonmail.com
7      arjun.raman98@protonmail.com
8    revathi.iyer149@protonmail.com
9     meera.reddy541@protonmail.com
Name: email, dtype: str

In [125]:
customers['email'].isna().sum()

np.int64(86)

Fill missing emails

In [126]:
customers['email'] = customers['email'].fillna('Not Available')

Check phone

In [127]:
customers['phone'].head(10)

0       09709931145
1    91 98945-07693
2        9815078433
3        9871475729
4        9712649259
5        9929222515
6    91 97944-08032
7        9712860477
8        9685610992
9        9980843297
Name: phone, dtype: str

Remove formatting characters

In [128]:
customers['phone'] = (
    customers['phone']
    .str.replace(r'\D', '', regex=True)
)

In [129]:
customers['phone'].head(10)

0     09709931145
1    919894507693
2      9815078433
3      9871475729
4      9712649259
5      9929222515
6    919794408032
7      9712860477
8      9685610992
9      9980843297
Name: phone, dtype: str

In [130]:
customers['phone'].str.len().value_counts()

phone
10.0    2400
12.0    1684
11.0     511
9.0      214
0.0       85
Name: count, dtype: int64

Inspect the 9- and 11-digit numbers

In [131]:
customers.loc[
    customers['phone'].str.len().isin([9, 11]),
    'phone'
].head(20)

0      09709931145
20     09773348667
24       957843460
32       914193605
37     09637923586
44       693908022
47       872251460
50     09736753447
60       631299586
65     09602342259
72     09792885514
97     09910076090
102    09901559230
114    09637863860
117      610918485
133    09803585426
137    09710149470
152      718026153
163    09937852744
171      728339562
Name: phone, dtype: str

In [132]:
customers.loc[
    customers['phone'].str.len() == 12,
    'phone'
].head(20)

1     919894507693
6     919794408032
10    919972889372
14    919905913341
15    919899971404
19    919964284290
27    919924055829
31    919989699902
41    919622587958
42    919902907446
45    919859658788
48    919965680703
49    919809485176
52    919861519048
53    919757567916
54    919825028003
56    919954571095
57    919889660567
61    919658720488
63    919707220616
Name: phone, dtype: str

Remove the 91 country code

In [133]:
customers.loc[
    customers['phone'].str.len() == 12,
    'phone'
].head()

1     919894507693
6     919794408032
10    919972889372
14    919905913341
15    919899971404
Name: phone, dtype: str

In [134]:
mask_12 = customers['phone'].str.len() == 12

customers.loc[mask_12, 'phone'] = (
    customers.loc[mask_12, 'phone'].str[2:]
)

In [135]:
customers['phone'].str.len().value_counts()

phone
10.0    4084
11.0     511
9.0      214
0.0       85
Name: count, dtype: int64

In [136]:
customers.loc[
    customers['phone'].str.len() == 11,
    'phone'
].head(20)

0      09709931145
20     09773348667
37     09637923586
50     09736753447
65     09602342259
72     09792885514
97     09910076090
102    09901559230
114    09637863860
133    09803585426
137    09710149470
163    09937852744
184    09860029838
203    09907371820
215    09793089090
220    09943107340
221    09666194071
228    09844454845
231    09688542861
233    09658364151
Name: phone, dtype: str

In [137]:
mask_11 = customers['phone'].str.match(r'^0\d{10}$', na=False)

customers.loc[mask_11, 'phone'] = (
    customers.loc[mask_11, 'phone'].str[1:]
)

In [138]:
customers['phone'].str.len().value_counts()

phone
10.0    4595
9.0      214
0.0       85
Name: count, dtype: int64

In [139]:
customers.loc[
    customers['phone'].str.match(r'^\d{9}$', na=False),
    'phone'
].head(20)

24     957843460
32     914193605
44     693908022
47     872251460
60     631299586
117    610918485
152    718026153
171    728339562
178    817633273
193    809334432
202    889945758
237    975005399
245    822822420
249    870239604
264    878218520
275    931384589
289    786547224
295    795739901
318    960841291
326    776907446
Name: phone, dtype: str

Mark 9-digit numbers as missing

In [140]:
mask_9 = customers['phone'].str.match(r'^\d{9}$', na=False)

customers.loc[mask_9, 'phone'] = pd.NA

In [141]:
customers['phone'].str.len().value_counts()

phone
10.0    4595
0.0       85
Name: count, dtype: int64

In [142]:
customers['phone'].isna().sum()

np.int64(320)

In [143]:
customers['phone'] = customers['phone'].fillna('Not Available')

In [144]:
customers['phone'].isna().sum()

np.int64(0)

lifetime_orders

In [145]:
customers['lifetime_orders'].head(10)

0     17
1    133
2    142
3     62
4     94
5    138
6     83
7    220
8    150
9    170
Name: lifetime_orders, dtype: str

Convert it to numeric

In [146]:
customers['lifetime_orders'] = pd.to_numeric(
    customers['lifetime_orders'],
    errors='coerce'
)

In [147]:
customers['lifetime_orders'].dtype

dtype('float64')

In [148]:
customers['lifetime_orders'].isna().sum()

np.int64(96)

Check the median first

In [149]:
customers['lifetime_orders'].median()

np.float64(120.0)

In [150]:
customers['lifetime_orders'] = customers['lifetime_orders'].fillna(120)

In [151]:
customers['lifetime_orders'].isna().sum()

np.int64(0)

avg_rating_given

In [152]:
customers['avg_rating_given'].head(10)

0    2.3
1    4.6
2    3.2
3    4.5
4    2.3
5    4.4
6    3.7
7    4.1
8    4.6
9    2.1
Name: avg_rating_given, dtype: str

avg_rating_given to numeric

In [153]:
customers['avg_rating_given'] = pd.to_numeric(
    customers['avg_rating_given'],
    errors='coerce'
)

In [154]:
customers['avg_rating_given'].dtype

dtype('float64')

Check missing values

In [155]:
customers['avg_rating_given'].isna().sum()

np.int64(317)

In [156]:
customers['avg_rating_given'].median()

np.float64(3.5)

In [157]:
customers['avg_rating_given'] = customers['avg_rating_given'].fillna(3.5)

signup_date

In [158]:
customers['signup_date'].head(10)

0    2021-08-12 00:00:00
1       25/07/2023 00:00
2             10-03-2023
3    2023-08-04 00:00:00
4             29-07-2023
5    2023-07-17 00:00:00
6    2022-05-09 00:00:00
7    2022-11-02 00:00:00
8             13-03-2023
9    2021-12-23 00:00:00
Name: signup_date, dtype: str

Convert signup_date

In [159]:
customers['signup_date'] = pd.to_datetime(
    customers['signup_date'],
    dayfirst=True,
    errors='coerce'
)

In [160]:
customers['signup_date'].dtype

dtype('<M8[us]')

Check whether conversion created missing dates

In [161]:
customers['signup_date'].isna().sum()

np.int64(4382)

In [162]:
customers_raw = pd.read_csv("../datasets/customers.csv")

In [163]:
customers_raw['signup_date'].head(10)

0    2021-08-12 00:00:00
1       25/07/2023 00:00
2             10-03-2023
3    2023-08-04 00:00:00
4             29-07-2023
5    2023-07-17 00:00:00
6    2022-05-09 00:00:00
7    2022-11-02 00:00:00
8             13-03-2023
9    2021-12-23 00:00:00
Name: signup_date, dtype: str

In [164]:
customers['signup_date'] = customers_raw.loc[customers.index, 'signup_date']

In [165]:
customers['signup_date'].head(10)

0    2021-08-12 00:00:00
1       25/07/2023 00:00
2             10-03-2023
3    2023-08-04 00:00:00
4             29-07-2023
5    2023-07-17 00:00:00
6    2022-05-09 00:00:00
7    2022-11-02 00:00:00
8             13-03-2023
9    2021-12-23 00:00:00
Name: signup_date, dtype: str

Parse the dates using mixed formats

In [166]:
customers['signup_date'] = pd.to_datetime(
    customers['signup_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [167]:
customers['signup_date'].isna().sum()

np.int64(0)

In [168]:
customers.info()

<class 'pandas.DataFrame'>
Index: 5000 entries, 0 to 5119
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   str
 1   customer_name     5000 non-null   str
 2   email             5000 non-null   str
 3   phone             5000 non-null   str
 4   city              5000 non-null   str
 5   state             5000 non-null   str
 6   pincode           5000 non-null   int64
 7   signup_date       5000 non-null   datetime64[us]
 8   customer_segment  5000 non-null   str
 9   is_prime_member   5000 non-null   str
 10  lifetime_orders   5000 non-null   float64
 11  avg_rating_given  5000 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(1), str(8)
memory usage: 883.9 KB

In [169]:
customers.isnull().sum()

customer_id         0
customer_name       0
email               0
phone               0
city                0
state               0
pincode             0
signup_date         0
customer_segment    0
is_prime_member     0
lifetime_orders     0
avg_rating_given    0
dtype: int64

In [170]:
customers.duplicated().sum()

np.int64(0)

In [171]:
customers.shape

(5000, 12)

# Save the customer cleaned dataset

In [172]:
customers.to_csv("../cleaned_data/customers_cleaned.csv", index=False)

# 3. delivery_logs.csv

In [173]:
delivery_logs = pd.read_csv("../datasets/delivery_logs.csv")

In [174]:
delivery_logs.shape

(79656, 11)

In [175]:
delivery_logs.info()

<class 'pandas.DataFrame'>
RangeIndex: 79656 entries, 0 to 79655
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   log_id           79656 non-null  str
 1   order_id         79656 non-null  str
 2   event_seq        77229 non-null  float64
 3   event_type       79656 non-null  str
 4   event_timestamp  78742 non-null  str
 5   hub_code         79656 non-null  str
 6   vehicle_id       79656 non-null  str
 7   scanned_by_emp   79656 non-null  str
 8   location_city    79656 non-null  str
 9   remarks          55729 non-null  str
 10  exception_code   11800 non-null  str
dtypes: float64(1), str(10)
memory usage: 14.5 MB

inspect event_seq

In [176]:
delivery_logs['event_seq'].head(20)

0     1.0
1     2.0
2     3.0
3     2.0
4     2.0
5     4.0
6     3.0
7     2.0
8     2.0
9     5.0
10    5.0
11    2.0
12    5.0
13    6.0
14    5.0
15    4.0
16    4.0
17    3.0
18    1.0
19    2.0
Name: event_seq, dtype: float64

In [177]:
delivery_logs['event_seq'].describe()

count    77229.000000
mean         3.189268
std          1.591174
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          6.000000
Name: event_seq, dtype: float64

In [178]:
delivery_logs.loc[
    delivery_logs['event_seq'].isna(),
    'event_type'
].value_counts(dropna=False)

event_type
ORDER_PLACED        449
PICKED_UP           415
DELIVERED           360
AT_HUB              351
OUT_FOR_DELIVERY    342
IN_TRANSIT          322
FAILED_ATTEMPT       41
RTO_INITIATED        36
Delivered            22
At Hub               20
Picked Up            19
Out For Delivery     18
Order Placed         18
In Transit           14
Name: count, dtype: int64

Keep missing event_seq as missing

In [179]:
delivery_logs['event_seq'] = delivery_logs['event_seq'].astype('Int64')

In [180]:
delivery_logs['event_seq'].dtype

Int64Dtype()

In [181]:
delivery_logs['event_type'].value_counts(dropna=False)

event_type
ORDER_PLACED        14416
PICKED_UP           14415
DELIVERED           12244
AT_HUB              10880
IN_TRANSIT          10812
OUT_FOR_DELIVERY    10758
FAILED_ATTEMPT       1250
RTO_INITIATED         876
Picked Up             762
Order Placed          750
Delivered             662
In Transit            572
Out For Delivery      572
At Hub                567
Failed Attempt         72
Rto Initiated          48
Name: count, dtype: int64

Standardize event_type

In [182]:
delivery_logs['event_type'] = (
    delivery_logs['event_type']
    .str.strip()
    .str.upper()
    .str.replace(' ', '_')
)

In [183]:
delivery_logs['event_type'].value_counts()

event_type
PICKED_UP           15177
ORDER_PLACED        15166
DELIVERED           12906
AT_HUB              11447
IN_TRANSIT          11384
OUT_FOR_DELIVERY    11330
FAILED_ATTEMPT       1322
RTO_INITIATED         924
Name: count, dtype: int64

# event_timestamp

In [184]:
delivery_logs['event_timestamp'].head(10)

0              1730297579
1     2025-06-08 01:09:42
2     2024-11-10 09:07:36
3    2025-02-27T01:56:46Z
4     2024-10-23 02:12:58
5        2024/09/14 02:43
6        04/03/2024 21:17
7    Apr 12 2024 05:45 PM
8    Dec 16 2024 01:41 PM
9     2024-07-08 07:04:38
Name: event_timestamp, dtype: str

In [185]:
delivery_logs['event_timestamp'].str.len().value_counts(dropna=False).head(20)

event_timestamp
19.0    35040
20.0    18115
16.0    14762
10.0    10106
NaN       914
1.0       249
2.0       237
7.0       233
Name: count, dtype: int64

In [186]:
delivery_logs.loc[
    delivery_logs['event_timestamp'].str.len() <= 10,
    'event_timestamp'
].value_counts().head(30)

event_timestamp
-             249
              237
unknown       233
03-02-2025     24
09-12-2024     23
12-01-2025     23
03-03-2025     22
25-01-2024     22
01-05-2024     22
09-05-2024     22
01-09-2024     21
01-03-2025     20
28-10-2024     20
01-04-2025     20
07-03-2025     20
22-02-2024     20
08-09-2024     20
08-08-2024     20
11-04-2024     20
27-08-2024     20
26-01-2025     20
14-02-2024     19
14-10-2024     19
18-02-2024     19
12-04-2024     19
31-01-2024     19
23-04-2024     18
13-03-2025     18
29-07-2024     18
08-01-2025     18
Name: count, dtype: int64

replace invalid timestamp placeholders

In [187]:
delivery_logs['event_timestamp'] = delivery_logs['event_timestamp'].replace(
    ['-', 'unknown'],
    pd.NA
)

In [188]:
delivery_logs['event_timestamp'].isna().sum()

np.int64(1396)

Convert the remaining timestamps

In [189]:
delivery_logs['event_timestamp'] = pd.to_datetime(
    delivery_logs['event_timestamp'],
    format='mixed',
    dayfirst=True,
    errors='coerce',
    utc=True
)

In [190]:
delivery_logs['event_timestamp'].isna().sum()

np.int64(5579)

In [191]:
delivery_logs_raw = pd.read_csv("../datasets/delivery_logs.csv")

In [192]:
delivery_logs['event_timestamp'] = delivery_logs_raw.loc[
    delivery_logs.index, 'event_timestamp'
]

In [193]:
delivery_logs['event_timestamp'].head(10)

0              1730297579
1     2025-06-08 01:09:42
2     2024-11-10 09:07:36
3    2025-02-27T01:56:46Z
4     2024-10-23 02:12:58
5        2024/09/14 02:43
6        04/03/2024 21:17
7    Apr 12 2024 05:45 PM
8    Dec 16 2024 01:41 PM
9     2024-07-08 07:04:38
Name: event_timestamp, dtype: str

In [194]:
delivery_logs.loc[
    delivery_logs['event_timestamp'].str.fullmatch(r'\d+'),
    'event_timestamp'
].head(20)

0      1730297579
20     1709559645
43     1716469742
66     1737830868
85     1713335364
109    1712071445
117    1741734922
127    1734455601
133    1708383432
140    1716646056
176    1730281543
237    1707159208
242    1738325915
246    1751359751
252    1732690406
255    1715264181
257    1718469778
265    1736616532
298    1747764457
309    1739221301
Name: event_timestamp, dtype: str

In [195]:
unix_mask = delivery_logs['event_timestamp'].str.fullmatch(r'\d+', na=False)

unix_dates = pd.to_datetime(
    delivery_logs.loc[unix_mask, 'event_timestamp'].astype('int64'),
    unit='s',
    utc=True
)

In [196]:
unix_dates.head(10)

0     2024-10-30 14:12:59+00:00
20    2024-03-04 13:40:45+00:00
43    2024-05-23 13:09:02+00:00
66    2025-01-25 18:47:48+00:00
85    2024-04-17 06:29:24+00:00
109   2024-04-02 15:24:05+00:00
117   2025-03-11 23:15:22+00:00
127   2024-12-17 17:13:21+00:00
133   2024-02-19 22:57:12+00:00
140   2024-05-25 14:07:36+00:00
Name: event_timestamp, dtype: datetime64[s, UTC]

In [197]:
unix_mask.sum()

np.int64(3946)

In [198]:
non_unix_mask = ~unix_mask & delivery_logs['event_timestamp'].notna()

In [199]:
non_unix_mask.sum()

np.int64(74796)

In [200]:
delivery_logs.loc[non_unix_mask, 'event_timestamp'].head(20)

1      2025-06-08 01:09:42
2      2024-11-10 09:07:36
3     2025-02-27T01:56:46Z
4      2024-10-23 02:12:58
5         2024/09/14 02:43
6         04/03/2024 21:17
7     Apr 12 2024 05:45 PM
8     Dec 16 2024 01:41 PM
9      2024-07-08 07:04:38
10    2025-03-31T14:51:46Z
11    Feb 05 2024 06:18 AM
12              22-04-2024
13     2024-03-25 13:56:40
14    2025-01-10T13:14:05Z
15    2025-05-26T17:56:44Z
16    2024-06-29T12:07:34Z
17     2024-11-05 00:41:18
18    2024-01-24T14:54:18Z
19    2025-06-18T20:21:57Z
21
Name: event_timestamp, dtype: str

In [201]:
(delivery_logs['event_timestamp'].str.strip() == '').sum()

np.int64(237)

Count all invalid/missing timestamps

In [202]:
delivery_logs['event_timestamp'] = delivery_logs['event_timestamp'].replace(
    ['-', 'unknown', ''],
    pd.NA
)

In [203]:
delivery_logs['event_timestamp'].isna().sum()

np.int64(1396)

In [204]:
test_dates = pd.to_datetime(
    delivery_logs.loc[non_unix_mask, 'event_timestamp'],
    format='mixed',
    dayfirst=True,
    errors='coerce',
    utc=True
)

In [205]:
test_dates.isna().sum()

np.int64(719)

In [206]:
valid_timestamp_values = delivery_logs['event_timestamp'].dropna()

valid_timestamp_values = valid_timestamp_values[
    ~valid_timestamp_values.str.fullmatch(r'\d+', na=False)
]

test_dates = pd.to_datetime(
    valid_timestamp_values,
    format='mixed',
    dayfirst=True,
    errors='coerce',
    utc=True
)

test_dates.isna().sum()

np.int64(237)

In [207]:
valid_timestamp_values = valid_timestamp_values[
    valid_timestamp_values.str.strip() != ''
]

test_dates = pd.to_datetime(
    valid_timestamp_values,
    format='mixed',
    dayfirst=True,
    errors='coerce',
    utc=True
)

test_dates.isna().sum()

np.int64(0)

In [208]:
final_timestamps = pd.Series(pd.NaT, index=delivery_logs.index, dtype='datetime64[ns, UTC]')

final_timestamps.loc[unix_dates.index] = unix_dates
final_timestamps.loc[test_dates.index] = test_dates

delivery_logs['event_timestamp'] = final_timestamps

In [209]:
delivery_logs['event_timestamp'].isna().sum()

np.int64(1633)

In [210]:
print("Total:", len(delivery_logs))
print("Unix:", unix_mask.sum())
print("Parsed non-Unix:", test_dates.notna().sum())
print("Missing:", delivery_logs['event_timestamp'].isna().sum())

Total: 79656
Unix: 3946
Parsed non-Unix: 74077
Missing: 1633

verify the datatype

In [211]:
delivery_logs['event_timestamp'].dtype

datetime64[ns, UTC]

# hub_code

In [212]:
delivery_logs['hub_code'].value_counts(dropna=False)

hub_code
HUB-KOL    4138
HUB-COI    4081
HUB-VIS    4069
HUB-HYD    4066
HUB-KOC    4060
HUB-MUM    4058
HUB-JAI    4043
HUB-DEL    4024
HUB-MYS    3997
HUB-NAG    3971
HUB-GUW    3969
HUB-CHA    3968
HUB-LUC    3955
HUB-GUR    3944
HUB-BHU    3937
HUB-PUN    3927
HUB-AHM    3925
HUB-CHE    3865
HUB-BEN    3850
HUB-MAD    3809
Name: count, dtype: int64

# vehicle_id

In [213]:
delivery_logs['vehicle_id'].value_counts(dropna=False).head(20)

vehicle_id
VEH-0701    528
VEH-0706    519
VEH-0719    515
VEH-0709    507
VEH-0714    507
VEH-0702    501
VEH-0712    498
VEH-0722    498
VEH-0717    496
VEH-0711    496
VEH-0708    493
VEH-0718    490
VEH-0707    486
VEH-0720    485
VEH-0716    485
VEH-0713    479
VEH-0721    473
VEH-0703    470
VEH-0704    465
VEH-0710    458
Name: count, dtype: int64

# scanned_by_emp

In [214]:
delivery_logs['scanned_by_emp'].value_counts(dropna=False).head(20)

scanned_by_emp
EMP-0129    91
EMP-0396    90
EMP-0827    89
EMP-0619    89
EMP-0905    88
EMP-0519    87
EMP-0719    87
EMP-0911    87
EMP-0073    87
EMP-0628    87
EMP-0237    86
EMP-0567    86
EMP-1034    86
EMP-0568    86
EMP-0410    86
EMP-0722    85
EMP-0086    85
EMP-0278    84
EMP-0293    84
EMP-0871    84
Name: count, dtype: int64

# location_city

In [215]:
delivery_logs['location_city'].value_counts(dropna=False)

location_city
Ahmedabad        4203
Chandigarh       4188
Gurugram         4174
Bhubaneswar      4170
Pune             4162
Kochi            4092
Hyderabad        4057
Lucknow          4039
Nagpur           3991
Mysuru           3965
Delhi            3963
Guwahati         3951
Jaipur           3942
Chennai          3938
Coimbatore       3887
Madurai          3864
Bengaluru        3854
Mumbai           3831
Visakhapatnam    3698
Kolkata          3687
Name: count, dtype: int64

# remarks

In [216]:
delivery_logs['remarks'].value_counts(dropna=False).head(20)

remarks
NaN                                              23927
Address unclear,\nrider called customer twice     8025
Customer unavailable, left with security          8017
Drone aborted landing, obstacle detected          7998
Handed over to last-mile partner                  7997
Consignee said "call before arrival"              7942
Weather hold - heavy rain at hub                  7887
OK                                                7863
Name: count, dtype: int64

In [217]:
delivery_logs['remarks'].dropna().str.strip().value_counts()

remarks
Address unclear,\nrider called customer twice    8025
Customer unavailable, left with security         8017
Drone aborted landing, obstacle detected         7998
Handed over to last-mile partner                 7997
Consignee said "call before arrival"             7942
Weather hold - heavy rain at hub                 7887
OK                                               7863
Name: count, dtype: int64

Clean the missing remarks

In [218]:
delivery_logs['remarks'] = delivery_logs['remarks'].fillna('No remark')

In [219]:
delivery_logs['remarks'].isna().sum()

np.int64(0)

# exception_code

In [220]:
delivery_logs['exception_code'].value_counts(dropna=False)

exception_code
NaN      67856
EX-01     4679
EX-07     3970
EX-12     3151
Name: count, dtype: int64

In [221]:
delivery_logs['exception_code'] = delivery_logs['exception_code'].fillna('NO_EXCEPTION')

In [222]:
delivery_logs['exception_code'].isna().sum()

np.int64(0)

In [223]:
delivery_logs.info()

<class 'pandas.DataFrame'>
RangeIndex: 79656 entries, 0 to 79655
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   log_id           79656 non-null  str
 1   order_id         79656 non-null  str
 2   event_seq        77229 non-null  Int64
 3   event_type       79656 non-null  str
 4   event_timestamp  78023 non-null  datetime64[ns, UTC]
 5   hub_code         79656 non-null  str
 6   vehicle_id       79656 non-null  str
 7   scanned_by_emp   79656 non-null  str
 8   location_city    79656 non-null  str
 9   remarks          79656 non-null  str
 10  exception_code   79656 non-null  str
dtypes: Int64(1), datetime64[ns, UTC](1), str(9)
memory usage: 14.2 MB

In [224]:
delivery_logs = delivery_logs.drop_duplicates().copy()

print("Shape after removing duplicates:", delivery_logs.shape)
print("Duplicate rows:", delivery_logs.duplicated().sum())

Shape after removing duplicates: (78756, 11)
Duplicate rows: 0

In [225]:
print(delivery_logs.shape)
print("Duplicate rows:", delivery_logs.duplicated().sum())

(78756, 11)
Duplicate rows: 0

# Save the delivery_log cleaned dataset

In [226]:
delivery_logs.to_csv(
    "../cleaned_data/delivery_logs_clean.csv",
    index=False
)


print("delivery_logs cleaned and saved successfully")

delivery_logs cleaned and saved successfully

# 4. drone_telemetry.csv

In [227]:
drone_telemetry = pd.read_csv("../datasets/drone_telemetry.csv")

In [228]:
drone_telemetry.info()

<class 'pandas.DataFrame'>
RangeIndex: 42629 entries, 0 to 42628
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   flight_id                42629 non-null  str
 1   drone_id                 42629 non-null  str
 2   flight_timestamp         42150 non-null  str
 3   flight_duration_min      41358 non-null  float64
 4   cumulative_flight_hours  42629 non-null  float64
 5   battery_cycles           42629 non-null  int64
 6   battery_start_pct        42629 non-null  float64
 7   battery_end_pct          41627 non-null  str
 8   battery_health_pct       42629 non-null  float64
 9   motor_temp_c             42629 non-null  str
 10  vibration_rms            41396 non-null  str
 11  payload_kg               42629 non-null  str
 12  max_altitude_m           42629 non-null  float64
 13  wind_speed_kmph          42629 non-null  float64
 14  gps_signal_quality       42629 non-null  str
 15  rotor_rpm_avg            41884 non-null  str
 16  error_codes              17740 non-null  str
 17  route_deviation_m        42629 non-null  float64
 18  maintenance_required     42629 non-null  int64
dtypes: float64(7), int64(2), str(10)
memory usage: 8.8 MB

flight_timestamp

In [229]:
drone_telemetry['flight_timestamp'].head(20)

0                      NaN
1      2024-06-04 07:14:50
2         29/05/2024 19:07
3      2024-07-06 06:50:42
4         11/05/2024 11:10
5      2024-05-12 04:25:53
6         15/09/2024 14:09
7               30-03-2024
8      2024-05-12 11:50:00
9      2024-05-15 03:45:37
10        2024/07/27 12:35
11              28-10-2024
12        30/05/2024 00:00
13              03-03-2024
14    2024-01-24T19:36:20Z
15     2024-09-25 14:19:28
16    2024-08-18T06:59:36Z
17        27/02/2024 19:43
18     2024-05-17 11:00:29
19        29/01/2024 09:05
Name: flight_timestamp, dtype: str

In [230]:
flight_dates = pd.to_datetime(
    drone_telemetry['flight_timestamp'],
    format='mixed',
    dayfirst=True,
    errors='coerce',
    utc=True
)

flight_dates.isna().sum()

np.int64(2935)

In [231]:
drone_telemetry.loc[
    drone_telemetry['flight_timestamp'].notna() & flight_dates.isna(),
    'flight_timestamp'
].value_counts().head(30)

flight_timestamp
unknown       135
              133
-             132
1714536600      2
1717310047      2
1710047195      2
1712498675      2
1725246574      2
1717794341      2
1711935714      2
1705314748      2
1720306234      2
1719669686      2
1706427163      2
1724882002      2
1727335011      2
1717627243      2
1716179362      2
1708575210      2
1708545437      2
1712837516      2
1711266264      2
1706380863      2
1708871164      2
1709306354      2
1711144400      2
1712119483      2
1714043380      2
1716736060      2
1722157613      2
Name: count, dtype: int64

identify Unix timestamps

In [232]:
flight_unix_mask = drone_telemetry['flight_timestamp'].astype('string').str.fullmatch(
    r'\d+',
    na=False
)

flight_unix_mask.sum()

np.int64(2056)

In [233]:
flight_unix_dates = pd.to_datetime(
    drone_telemetry.loc[flight_unix_mask, 'flight_timestamp'].astype('int64'),
    unit='s',
    utc=True
)

In [234]:
flight_unix_dates.head(10)

30    2024-06-19 14:50:35+00:00
40    2024-05-08 22:47:17+00:00
41    2024-07-17 17:26:41+00:00
56    2024-07-10 02:07:20+00:00
131   2024-08-04 20:12:04+00:00
150   2024-02-25 10:26:08+00:00
204   2024-08-16 07:42:02+00:00
213   2024-06-27 17:32:20+00:00
217   2024-03-18 08:54:00+00:00
226   2024-07-27 17:11:05+00:00
Name: flight_timestamp, dtype: datetime64[s, UTC]

In [235]:
flight_non_unix = drone_telemetry.loc[
    ~flight_unix_mask,
    'flight_timestamp'
].replace(['unknown', '-'], pd.NA)

flight_non_unix_dates = pd.to_datetime(
    flight_non_unix,
    format='mixed',
    dayfirst=True,
    errors='coerce',
    utc=True
)

flight_non_unix_dates.isna().sum()

np.int64(879)

In [236]:
flight_non_unix[
    flight_non_unix_dates.isna()
].value_counts(dropna=False)

flight_timestamp
NaN    746
       133
Name: count, dtype: int64

In [237]:
print("Total rows:", len(drone_telemetry))
print("Unix timestamps:", flight_unix_dates.notna().sum())
print("Valid non-Unix:", flight_non_unix_dates.notna().sum())
print("Missing/invalid:", flight_non_unix_dates.isna().sum())

Total rows: 42629
Unix timestamps: 2056
Valid non-Unix: 39694
Missing/invalid: 879

In [238]:
flight_final_dates = pd.Series(
    pd.NaT,
    index=drone_telemetry.index,
    dtype='datetime64[ns, UTC]'
)

flight_final_dates.loc[flight_unix_dates.index] = flight_unix_dates
flight_final_dates.loc[flight_non_unix_dates.index] = flight_non_unix_dates

drone_telemetry['flight_timestamp'] = flight_final_dates

In [239]:
drone_telemetry['flight_timestamp'].dtype

datetime64[ns, UTC]

# flight_duration_min

In [240]:
drone_telemetry['flight_duration_min'].head(20)

0     18.2
1     33.5
2     13.3
3      5.6
4     13.9
5     21.8
6      NaN
7      NaN
8     23.6
9      4.8
10     7.0
11    37.4
12    36.9
13    34.8
14     4.6
15    16.0
16    22.0
17    15.0
18    29.8
19    18.6
Name: flight_duration_min, dtype: float64

In [241]:
drone_telemetry['flight_duration_min'].describe()

count    41358.000000
mean        20.938851
std          9.765856
min          4.000000
25%         12.500000
50%         20.900000
75%         29.400000
max         38.000000
Name: flight_duration_min, dtype: float64

# cumulative_flight_hours

In [242]:
drone_telemetry['cumulative_flight_hours'].head(20)

0      53.37
1     942.57
2     620.88
3     708.77
4     529.80
5     495.01
6     384.96
7     795.42
8     916.34
9     618.41
10    787.18
11    798.00
12    500.92
13    425.82
14    104.96
15    472.00
16    728.83
17    861.77
18    153.48
19    568.40
Name: cumulative_flight_hours, dtype: float64

In [243]:
drone_telemetry['cumulative_flight_hours'].describe()

count    42629.000000
mean       500.143479
std        255.375465
min         24.260000
25%        273.420000
50%        511.650000
75%        701.260000
max       1002.490000
Name: cumulative_flight_hours, dtype: float64

# battery_cycles

In [244]:
drone_telemetry['battery_cycles'].describe()

count    42629.000000
mean      1049.800605
std        536.290191
min         50.000000
25%        574.000000
50%       1074.000000
75%       1472.000000
max       2105.000000
Name: battery_cycles, dtype: float64

# battery_start_pct

In [245]:
drone_telemetry['battery_start_pct'].describe()

count    42629.000000
mean        95.663492
std          3.455454
min         78.600000
25%         93.300000
50%         96.000000
75%         98.700000
max        100.000000
Name: battery_start_pct, dtype: float64

# battery_end_pct

In [246]:
drone_telemetry['battery_end_pct'].head(20)

0     24.6
1        2
2     55.8
3     81.8
4     44.9
5     24.3
6        2
7      3.6
8      3.0
9     89.3
10    77.7
11       2
12       2
13       2
14    85.6
15    39.1
16    11.3
17    44.8
18    40.6
19    31.1
Name: battery_end_pct, dtype: str

In [247]:
battery_end_numeric = pd.to_numeric(
    drone_telemetry['battery_end_pct'],
    errors='coerce'
)

print("Original missing:", drone_telemetry['battery_end_pct'].isna().sum())
print("After numeric conversion:", battery_end_numeric.isna().sum())
print("New conversion failures:",
      battery_end_numeric.isna().sum() - drone_telemetry['battery_end_pct'].isna().sum())

Original missing: 1002
After numeric conversion: 1744
New conversion failures: 742

In [248]:
drone_telemetry.loc[
    drone_telemetry['battery_end_pct'].notna() & battery_end_numeric.isna(),
    'battery_end_pct'
].value_counts(dropna=False).head(30)

battery_end_pct
-          267
           258
unknown    217
Name: count, dtype: int64

In [249]:
drone_telemetry.loc[
    drone_telemetry['battery_end_pct'].isin(['-', 'unknown', '258']),
    ['drone_id', 'flight_timestamp', 'battery_start_pct', 'battery_end_pct']
].head(20)

      drone_id          flight_timestamp  battery_start_pct battery_end_pct
163   VEH-0136 2024-10-07 09:25:42+00:00               93.4         unknown
238   VEH-0114 2024-03-25 16:42:00+00:00               95.4               -
343   VEH-0046                       NaT               94.4               -
629   VEH-0010 2024-08-19 00:00:00+00:00               99.8               -
730   VEH-0058 2024-09-04 19:22:21+00:00              100.0         unknown
794   VEH-0137 2024-02-15 13:47:30+00:00               99.4         unknown
863   VEH-0106 2024-03-17 04:27:01+00:00              100.0         unknown
1020  VEH-0037 2024-01-06 00:53:00+00:00               92.9               -
1153  VEH-0101 2024-01-23 00:00:00+00:00               98.5               -
1294  VEH-0087 2024-08-21 06:37:54+00:00               93.6         unknown
1305  VEH-0078 2024-11-08 04:57:05+00:00               97.7               -
1496  VEH-0037 2024-06-13 07:14:46+00:00               96.2               -
1565  VEH-0031 2024-07-31 07:04:20+00:00               95.5         unknown
1593  VEH-0011 2024-06-21 21:31:00+00:00               91.0         unknown
1701  VEH-0084 2024-05-31 10:43:00+00:00               96.9               -
1802  VEH-0133 2024-11-03 14:10:00+00:00               91.7         unknown
1842  VEH-0086 2024-02-25 02:11:39+00:00               95.9         unknown
1927  VEH-0045 2024-02-07 00:00:00+00:00               95.9         unknown
1945  VEH-0071 2024-02-17 10:53:31+00:00               95.5               -
1957  VEH-0086 2024-02-24 03:12:11+00:00               92.1               -

In [250]:
print(
    drone_telemetry.loc[
        drone_telemetry['battery_end_pct'].isin(['-', 'unknown', '258']),
        ['drone_id', 'flight_timestamp', 'battery_start_pct', 'battery_end_pct']
    ].head(20).to_string(index=False)
)

drone_id          flight_timestamp  battery_start_pct battery_end_pct
VEH-0136 2024-10-07 09:25:42+00:00               93.4         unknown
VEH-0114 2024-03-25 16:42:00+00:00               95.4               -
VEH-0046                       NaT               94.4               -
VEH-0010 2024-08-19 00:00:00+00:00               99.8               -
VEH-0058 2024-09-04 19:22:21+00:00              100.0         unknown
VEH-0137 2024-02-15 13:47:30+00:00               99.4         unknown
VEH-0106 2024-03-17 04:27:01+00:00              100.0         unknown
VEH-0037 2024-01-06 00:53:00+00:00               92.9               -
VEH-0101 2024-01-23 00:00:00+00:00               98.5               -
VEH-0087 2024-08-21 06:37:54+00:00               93.6         unknown
VEH-0078 2024-11-08 04:57:05+00:00               97.7               -
VEH-0037 2024-06-13 07:14:46+00:00               96.2               -
VEH-0031 2024-07-31 07:04:20+00:00               95.5         unknown
VEH-0011 2024-06-21 21:31:00+00:00               91.0         unknown
VEH-0084 2024-05-31 10:43:00+00:00               96.9               -
VEH-0133 2024-11-03 14:10:00+00:00               91.7         unknown
VEH-0086 2024-02-25 02:11:39+00:00               95.9         unknown
VEH-0045 2024-02-07 00:00:00+00:00               95.9         unknown
VEH-0071 2024-02-17 10:53:31+00:00               95.5               -
VEH-0086 2024-02-24 03:12:11+00:00               92.1               -

In [251]:
drone_telemetry['battery_end_pct'] = pd.to_numeric(
    drone_telemetry['battery_end_pct'].replace(['unknown', '-', '258'], pd.NA),
    errors='coerce'
)

In [252]:
print(drone_telemetry['battery_end_pct'].dtype)
print(drone_telemetry['battery_end_pct'].isna().sum())
print(drone_telemetry['battery_end_pct'].describe())

float64
1744
count    40885.000000
mean        35.335111
std         27.017913
min          2.000000
25%          6.600000
50%         34.000000
75%         58.900000
max         92.800000
Name: battery_end_pct, dtype: float64

# battery_health_pct

In [253]:
drone_telemetry['battery_health_pct'].describe()

count    42629.000000
mean        62.815417
std         15.795998
min         40.000000
25%         49.500000
50%         61.600000
75%         76.900000
max         97.700000
Name: battery_health_pct, dtype: float64

# motor_temp_c

In [254]:
drone_telemetry['motor_temp_c'].head(20)

0     83.7
1     88.6
2     79.8
3     64.7
4     84.8
5     83.5
6     84.4
7     81.2
8     78.2
9     71.5
10    79.8
11    94.7
12    68.8
13    87.4
14    73.6
15    96.7
16    84.2
17    66.4
18    68.2
19    75.2
Name: motor_temp_c, dtype: str

In [255]:
motor_temp_numeric = pd.to_numeric(
    drone_telemetry['motor_temp_c'],
    errors='coerce'
)

print("Original missing:", drone_telemetry['motor_temp_c'].isna().sum())
print("After numeric conversion:", motor_temp_numeric.isna().sum())
print(
    "New conversion failures:",
    motor_temp_numeric.isna().sum()
    - drone_telemetry['motor_temp_c'].isna().sum()
)

Original missing: 0
After numeric conversion: 2558
New conversion failures: 2558

In [256]:
drone_telemetry.loc[
    motor_temp_numeric.isna(),
    'motor_temp_c'
].value_counts(dropna=False).head(30)

motor_temp_c
162.0F    12
165.7F    12
175.1F    12
167.7F    11
157.0F    11
166.1F    10
180.7F    10
180.3F    10
176.2F    10
173.6F    10
173.1F    10
176.7F    10
170.8F    10
163.7F    10
171.2F    10
154.9F     9
159.3F     9
160.7F     9
165.0F     9
158.3F     9
177.7F     9
178.8F     8
162.7F     8
164.4F     8
158.4F     8
162.5F     8
172.6F     8
172.0F     8
187.3F     8
197.6F     8
Name: count, dtype: int64

In [257]:
motor_f_mask = drone_telemetry['motor_temp_c'].astype('string').str.fullmatch(
    r'\d+(\.\d+)?F',
    na=False
)

print("Fahrenheit values:", motor_f_mask.sum())
print("Other invalid values:", motor_temp_numeric.isna().sum() - motor_f_mask.sum())

Fahrenheit values: 2558
Other invalid values: 0

In [258]:
# Convert normal numeric values
motor_temp_clean = pd.to_numeric(
    drone_telemetry['motor_temp_c'],
    errors='coerce'
)

# Convert Fahrenheit values to Celsius
motor_temp_clean.loc[motor_f_mask] = (
    pd.to_numeric(
        drone_telemetry.loc[motor_f_mask, 'motor_temp_c']
        .str.rstrip('F')
    ) - 32
) * 5 / 9

# Replace original column
drone_telemetry['motor_temp_c'] = motor_temp_clean

In [259]:
print(drone_telemetry['motor_temp_c'].dtype)
print(drone_telemetry['motor_temp_c'].isna().sum())
print(drone_telemetry['motor_temp_c'].describe())

float64
0
count    42629.000000
mean        77.383039
std         10.254483
min         42.600000
25%         70.000000
50%         77.300000
75%         84.611111
max        114.100000
Name: motor_temp_c, dtype: float64

# vibration_rms

In [260]:
drone_telemetry['vibration_rms'].head(20)

0     2.991
1     4.067
2     2.486
3     2.033
4     3.818
5      3.14
6     2.876
7     2.888
8     2.005
9     2.766
10    3.075
11
12    2.272
13    3.277
14      NaN
15    4.246
16    3.075
17    2.094
18    2.507
19    2.145
Name: vibration_rms, dtype: str

In [261]:
vibration_numeric = pd.to_numeric(
    drone_telemetry['vibration_rms'],
    errors='coerce'
)

print("Original missing:", drone_telemetry['vibration_rms'].isna().sum())
print("Blank strings:", (drone_telemetry['vibration_rms'].str.strip() == '').sum())
print("After numeric conversion:", vibration_numeric.isna().sum())
print(
    "Other conversion failures:",
    vibration_numeric.isna().sum()
    - drone_telemetry['vibration_rms'].isna().sum()
    - (drone_telemetry['vibration_rms'].str.strip() == '').sum()
)

Original missing: 1233
Blank strings: 315
After numeric conversion: 2177
Other conversion failures: 629

In [262]:
drone_telemetry.loc[
    vibration_numeric.isna()
    & drone_telemetry['vibration_rms'].notna()
    & (drone_telemetry['vibration_rms'].str.strip() != ''),
    'vibration_rms'
].value_counts(dropna=False).head(30)

vibration_rms
unknown    326
-          303
Name: count, dtype: int64

In [263]:
invalid_vibration = drone_telemetry.loc[
    vibration_numeric.isna()
    & drone_telemetry['vibration_rms'].notna()
    & (drone_telemetry['vibration_rms'].str.strip() != ''),
    'vibration_rms'
].value_counts(dropna=False).head(30)

print(invalid_vibration.to_string())

vibration_rms
unknown    326
-          303

In [264]:
print(drone_telemetry.loc[
    vibration_numeric.isna(),
    'vibration_rms'
].unique()[:30])

<ArrowStringArray>
['  ', nan, '-', 'unknown']
Length: 4, dtype: str

In [265]:
drone_telemetry['vibration_rms'] = pd.to_numeric(
    drone_telemetry['vibration_rms'].replace(r'^\s*$', pd.NA, regex=True),
    errors='coerce'
)

In [266]:
print(drone_telemetry['vibration_rms'].dtype)
print("Missing:", drone_telemetry['vibration_rms'].isna().sum())
print(drone_telemetry['vibration_rms'].describe())

float64
Missing: 2177
count    40452.000000
mean         2.691036
std          0.737174
min          0.323000
25%          2.147000
50%          2.681000
75%          3.221000
max          5.298000
Name: vibration_rms, dtype: float64

# payload_kg

In [267]:
drone_telemetry['payload_kg'].head(20)

0       5.39
1       4.47
2       2.73
3       0.35
4     3.42kg
5       3.33
6       4.99
7     3.56kg
8       4.74
9       0.64
10      2.63
11      0.83
12      5.48
13       3.0
14    1.81kg
15      3.11
16      4.95
17      5.63
18      0.21
19      4.23
Name: payload_kg, dtype: str

In [268]:
payload_numeric = pd.to_numeric(
    drone_telemetry['payload_kg'],
    errors='coerce'
)

payload_kg_mask = drone_telemetry['payload_kg'].astype('string').str.fullmatch(
    r'\d+(\.\d+)?kg',
    na=False
)

print("Original missing:", drone_telemetry['payload_kg'].isna().sum())
print("Values with kg suffix:", payload_kg_mask.sum())
print("After numeric conversion:", payload_numeric.isna().sum())
print(
    "Other non-numeric values:",
    payload_numeric.isna().sum()
    - drone_telemetry['payload_kg'].isna().sum()
    - payload_kg_mask.sum()
)

Original missing: 0
Values with kg suffix: 3408
After numeric conversion: 3408
Other non-numeric values: 0

In [269]:
drone_telemetry['payload_kg'] = pd.to_numeric(
    drone_telemetry['payload_kg'].astype('string').str.replace('kg', '', regex=False),
    errors='coerce'
)

In [270]:
print(drone_telemetry['payload_kg'].dtype)
print("Missing:", drone_telemetry['payload_kg'].isna().sum())
print(drone_telemetry['payload_kg'].describe())

Float64
Missing: 0
count     42629.0
mean     3.006299
std      1.613371
min           0.2
25%          1.61
50%          3.02
75%           4.4
max           5.8
Name: payload_kg, dtype: Float64

# gps_signal_quality

In [271]:
drone_telemetry['gps_signal_quality'].value_counts(dropna=False)

gps_signal_quality
Fair    8607
Good    8583
GOOD    8538
Poor    8503
good    8398
Name: count, dtype: int64

In [272]:
drone_telemetry['gps_signal_quality'] = (
    drone_telemetry['gps_signal_quality']
    .str.strip()
    .str.title()
)

In [273]:
print(drone_telemetry['gps_signal_quality'].value_counts(dropna=False))

gps_signal_quality
Good    25519
Fair     8607
Poor     8503
Name: count, dtype: int64

# rotor_rpm_avg

In [274]:
drone_telemetry['rotor_rpm_avg'].head(20)

0     6355
1     6755
2     6584
3     7154
4     6063
5     7176
6     6413
7     5290
8     6502
9     5958
10    5851
11    5011
12    6299
13    6193
14    6546
15    6089
16    6476
17    6581
18    6118
19    6053
Name: rotor_rpm_avg, dtype: str

In [275]:
rotor_rpm_numeric = pd.to_numeric(
    drone_telemetry['rotor_rpm_avg'],
    errors='coerce'
)

print("Original missing:", drone_telemetry['rotor_rpm_avg'].isna().sum())
print("After numeric conversion:", rotor_rpm_numeric.isna().sum())
print(
    "New conversion failures:",
    rotor_rpm_numeric.isna().sum()
    - drone_telemetry['rotor_rpm_avg'].isna().sum()
)

Original missing: 745
After numeric conversion: 1321
New conversion failures: 576

In [276]:
print(
    "Original missing:",
    drone_telemetry['rotor_rpm_avg'].isna().sum(),
    "| After conversion:",
    rotor_rpm_numeric.isna().sum(),
    "| New failures:",
    rotor_rpm_numeric.isna().sum()
    - drone_telemetry['rotor_rpm_avg'].isna().sum()
)

Original missing: 745 | After conversion: 1321 | New failures: 576

In [277]:
print(
    drone_telemetry.loc[
        rotor_rpm_numeric.isna()
        & drone_telemetry['rotor_rpm_avg'].notna(),
        'rotor_rpm_avg'
    ].value_counts().head(30).to_string()
)

rotor_rpm_avg
-          204
           188
unknown    184

In [278]:
drone_telemetry['rotor_rpm_avg'] = pd.to_numeric(
    drone_telemetry['rotor_rpm_avg'].replace(
        ['-', 'unknown', ''],
        pd.NA
    ),
    errors='coerce'
)

In [279]:
print(drone_telemetry['rotor_rpm_avg'].dtype)
print("Missing:", drone_telemetry['rotor_rpm_avg'].isna().sum())
print(drone_telemetry['rotor_rpm_avg'].describe())

float64
Missing: 1321
count    41308.000000
mean      6201.331776
std        398.464839
min       4553.000000
25%       5936.000000
50%       6200.000000
75%       6468.000000
max       7808.000000
Name: rotor_rpm_avg, dtype: float64

# error_codes

In [280]:
drone_telemetry['error_codes'].value_counts(dropna=False).head(30)

error_codes
NaN                           24889
E-BATT                         8650
E-THERM;E-VIB                  1884
E-THERM                        1783
E-THERM;E-VIB;E-BATT           1649
E-THERM;E-BATT                 1274
E-GPS                           785
E-VIB                           775
E-VIB;E-BATT                    479
E-BATT;E-GPS                    244
E-THERM;E-VIB;E-GPS              55
E-THERM;E-VIB;E-BATT;E-GPS       45
E-THERM;E-GPS                    45
E-THERM;E-BATT;E-GPS             35
E-VIB;E-GPS                      26
E-VIB;E-BATT;E-GPS               11
Name: count, dtype: int64

In [281]:
valid_error_codes = {'E-BATT', 'E-THERM', 'E-VIB', 'E-GPS'}

unexpected_errors = set()

for value in drone_telemetry['error_codes'].dropna():
    unexpected_errors.update(
        code for code in value.split(';')
        if code not in valid_error_codes
    )

print("Unexpected error codes:", unexpected_errors)

Unexpected error codes: set()

# route_deviation_m

In [282]:
drone_telemetry['route_deviation_m'].describe()

count    42629.000000
mean        17.156417
std         10.845250
min          0.000000
25%          8.600000
50%         16.000000
75%         24.200000
max         73.000000
Name: route_deviation_m, dtype: float64

# maintenance_required

In [283]:
drone_telemetry['maintenance_required'].value_counts(dropna=False)

maintenance_required
0    37907
1     4722
Name: count, dtype: int64

In [284]:
print(drone_telemetry.info())

<class 'pandas.DataFrame'>
RangeIndex: 42629 entries, 0 to 42628
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   flight_id                42629 non-null  str
 1   drone_id                 42629 non-null  str
 2   flight_timestamp         41750 non-null  datetime64[ns, UTC]
 3   flight_duration_min      41358 non-null  float64
 4   cumulative_flight_hours  42629 non-null  float64
 5   battery_cycles           42629 non-null  int64
 6   battery_start_pct        42629 non-null  float64
 7   battery_end_pct          40885 non-null  float64
 8   battery_health_pct       42629 non-null  float64
 9   motor_temp_c             42629 non-null  float64
 10  vibration_rms            40452 non-null  float64
 11  payload_kg               42629 non-null  Float64
 12  max_altitude_m           42629 non-null  float64
 13  wind_speed_kmph          42629 non-null  float64
 14  gps_signal_quality       42629 non-null  str
 15  rotor_rpm_avg            41308 non-null  float64
 16  error_codes              17740 non-null  str
 17  route_deviation_m        42629 non-null  float64
 18  maintenance_required     42629 non-null  int64
dtypes: Float64(1), datetime64[ns, UTC](1), float64(11), int64(2), str(4)
memory usage: 7.3 MB
None

In [285]:
print(drone_telemetry.isna().sum())

flight_id                      0
drone_id                       0
flight_timestamp             879
flight_duration_min         1271
cumulative_flight_hours        0
battery_cycles                 0
battery_start_pct              0
battery_end_pct             1744
battery_health_pct             0
motor_temp_c                   0
vibration_rms               2177
payload_kg                     0
max_altitude_m                 0
wind_speed_kmph                0
gps_signal_quality             0
rotor_rpm_avg               1321
error_codes                24889
route_deviation_m              0
maintenance_required           0
dtype: int64

In [286]:
print("Duplicate rows:", drone_telemetry.duplicated().sum())

Duplicate rows: 700

In [287]:
print("Rows before removing duplicates:", len(drone_telemetry))

drone_telemetry = drone_telemetry.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", len(drone_telemetry))
print("Duplicates remaining:", drone_telemetry.duplicated().sum())

Rows before removing duplicates: 42629
Rows after removing duplicates: 41929
Duplicates remaining: 0

In [288]:
print(drone_telemetry.info())

<class 'pandas.DataFrame'>
RangeIndex: 41929 entries, 0 to 41928
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   flight_id                41929 non-null  str
 1   drone_id                 41929 non-null  str
 2   flight_timestamp         41076 non-null  datetime64[ns, UTC]
 3   flight_duration_min      40677 non-null  float64
 4   cumulative_flight_hours  41929 non-null  float64
 5   battery_cycles           41929 non-null  int64
 6   battery_start_pct        41929 non-null  float64
 7   battery_end_pct          40217 non-null  float64
 8   battery_health_pct       41929 non-null  float64
 9   motor_temp_c             41929 non-null  float64
 10  vibration_rms            39789 non-null  float64
 11  payload_kg               41929 non-null  Float64
 12  max_altitude_m           41929 non-null  float64
 13  wind_speed_kmph          41929 non-null  float64
 14  gps_signal_quality       41929 non-null  str
 15  rotor_rpm_avg            40628 non-null  float64
 16  error_codes              17446 non-null  str
 17  route_deviation_m        41929 non-null  float64
 18  maintenance_required     41929 non-null  int64
dtypes: Float64(1), datetime64[ns, UTC](1), float64(11), int64(2), str(4)
memory usage: 7.2 MB
None

# Save the drone_telemetry cleaned dataset

In [289]:
drone_telemetry.to_csv(
    "../cleaned_data/drone_telemetry_cleaned.csv",
    index=False
)

print("Saved successfully")

Saved successfully

# 5. fleet_vehicles.csv

In [290]:
fleet_vehicles = pd.read_csv("../datasets/fleet_vehicles.csv")

In [291]:
fleet_vehicles.head()

,vehicle_id,vehicle_type,model_name,capacity_kg,max_range_km,avg_speed_kmph,hub_code,purchase_date,odometer_km,fleet_status,driver_id,battery_capacity_wh,last_service_date,insurance_expiry,ownership
0,VEH-0001,Drone,Tamira-879,1.4,16.6,54,HUB-GUR,17-12-2021,62287.3,In Service,NaN,5660.0,10-07-2024,23-01-2025,3PL Partner
1,VEH-0002,Drone,Tamira-998,2.8,10.5,51,HUB-NAG,26-06-2019,228496.0,Maintenance,NaN,5154.0,2024-07-09 00:00:00,21-06-2024,Leased
2,VEH-0003,Drone,Nexon-730,5.8,22.7,60,HUB-JAI,26-05-2023,56173.9,under maintenance,NaN,6978.0,16-06-2025,20-09-2024,Owned
3,VEH-0004,Drone,Tamira-332,5.4,10.7,57,HUB-JAI,2021-06-03 00:00:00,62245.1,Idle,NaN,3879.0,01-05-2025,16-12-2024,Owned
4,VEH-0005,Drone,Kaveri-271,5.3,14.9,59,HUB-DEL,31/12/2018 00:00,256229.3,under maintenance,NaN,5856.0,26-01-2025,29-02-2024,Leased

In [292]:
fleet_vehicles.info()

<class 'pandas.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   vehicle_id           761 non-null    str
 1   vehicle_type         761 non-null    str
 2   model_name           761 non-null    str
 3   capacity_kg          761 non-null    str
 4   max_range_km         761 non-null    float64
 5   avg_speed_kmph       761 non-null    int64
 6   hub_code             761 non-null    str
 7   purchase_date        761 non-null    str
 8   odometer_km          738 non-null    str
 9   fleet_status         761 non-null    str
 10  driver_id            618 non-null    str
 11  battery_capacity_wh  143 non-null    float64
 12  last_service_date    761 non-null    str
 13  insurance_expiry     761 non-null    str
 14  ownership            761 non-null    str
dtypes: float64(2), int64(1), str(12)
memory usage: 166.6 KB

In [293]:
fleet_vehicles.isnull().sum()

vehicle_id               0
vehicle_type             0
model_name               0
capacity_kg              0
max_range_km             0
avg_speed_kmph           0
hub_code                 0
purchase_date            0
odometer_km             23
fleet_status             0
driver_id              143
battery_capacity_wh    618
last_service_date        0
insurance_expiry         0
ownership                0
dtype: int64

In [294]:
fleet_vehicles.duplicated().sum()

np.int64(25)

In [295]:
print(
    fleet_vehicles.groupby('vehicle_type')['battery_capacity_wh']
    .agg(['count', 'size'])
)

              count  size
vehicle_type
Air Cargo         0    22
BIKE              0     9
Bike              0   245
DRONE             2     2
Drone           136   136
Ship              0    13
TRUCK             0     5
Truck             0   113
VAN               0     4
Van               0   188
bike              0    11
drone             5     5
ship              0     1
truck             0     4
van               0     3

In [296]:
fleet_vehicles['vehicle_type'] = (
    fleet_vehicles['vehicle_type']
    .str.strip()
    .str.title()
)

print(fleet_vehicles['vehicle_type'].value_counts())

vehicle_type
Bike         265
Van          195
Drone        143
Truck        122
Air Cargo     22
Ship          14
Name: count, dtype: int64

# capacity_kg

In [297]:
fleet_vehicles['capacity_kg'].head()

0    1.4
1    2.8
2    5.8
3    5.4
4    5.3
Name: capacity_kg, dtype: str

In [298]:
capacity_numeric = pd.to_numeric(
    fleet_vehicles['capacity_kg'],
    errors='coerce'
)

print("Original missing:", fleet_vehicles['capacity_kg'].isna().sum())
print("After conversion:", capacity_numeric.isna().sum())
print(
    "New conversion failures:",
    capacity_numeric.isna().sum()
    - fleet_vehicles['capacity_kg'].isna().sum()
)

Original missing: 0
After conversion: 190
New conversion failures: 190

In [299]:
print(
    fleet_vehicles.loc[
        capacity_numeric.isna(),
        'capacity_kg'
    ].value_counts(dropna=False).to_string()
)

capacity_kg
1.9 kg         3
5.7 kg         2
5.4 kg         2
3.0KG          2
29.6 kg        2
31.3 kg        2
18.7 kg        2
31.2 kg        2
28.7 kg        2
797.7KG        2
1188.9KG       2
1059.6 kg      2
4300 g         1
1.5 kg         1
4000 g         1
4.7KG          1
3.2KG          1
3700 g         1
4.0 kg         1
4.1 kg         1
1000 g         1
5.0KG          1
2600 g         1
2900 g         1
5.9 kg         1
4800 g         1
5300 g         1
1.1KG          1
4.6 kg         1
5.7KG          1
2.9KG          1
5.3KG          1
5.1KG          1
1.3KG          1
14.3KG         1
14.0KG         1
24.0 kg        1
10.6 kg        1
21.0KG         1
21.6KG         1
34.4 kg        1
13.4 kg        1
26.7 kg        1
14.6KG         1
29.1 kg        1
18.8 kg        1
22.3KG         1
21.8 kg        1
11.8 kg        1
21.7 kg        1
12.4 kg        1
30.1 kg        1
22.5 kg        1
34.2KG         1
24.6 kg        1
14.1 kg        1
25.1KG         1
17.5KG         1
21.3 kg        1
17.4KG         1
21.2KG         1
26.6 kg        1
20.1 kg        1
17.6 kg        1
12.7 kg        1
11.7 kg        1
13.6 kg        1
15.0 kg        1
12.2KG         1
16.5 kg        1
28.6 kg        1
30.2 kg        1
33.7 kg        1
19.0KG         1
21.3KG         1
16.8 kg        1
33.9 kg        1
15.2KG         1
22.0KG         1
32.0 kg        1
30.8KG         1
10.8KG         1
25.3KG         1
1171.9 kg      1
902.5 kg       1
674.0 kg       1
994.5KG        1
668.1KG        1
1115.1KG       1
1048.2 kg      1
564.2 kg       1
706.4KG        1
732.0KG        1
771.5 kg       1
727.4 kg       1
656.3KG        1
1151.3 kg      1
522.5 kg       1
502.4 kg       1
696.3 kg       1
472.8KG        1
1182.0 kg      1
879.8 kg       1
886.5KG        1
544.8KG        1
550.6KG        1
408.3 kg       1
893.3KG        1
647.0 kg       1
798.1 kg       1
1104.3 kg      1
547.5 kg       1
570.3KG        1
484.3 kg       1
1029.0 kg      1
696.5 kg       1
770.0 kg       1
574.3KG        1
1133.5 kg      1
1166.9 kg      1
1144.6 kg      1
745.2 kg       1
657.5KG        1
655.6 kg       1
1088.3 kg      1
1042.0KG       1
1127.4 kg      1
741.7 kg       1
954.2KG        1
14176.3 kg     1
13637.9 kg     1
13245.0KG      1
4691.8KG       1
8311.1 kg      1
16057.3 kg     1
10728.2 kg     1
8081.6 kg      1
17630.6 kg     1
11852.5KG      1
6744.9KG       1
6011.6KG       1
10620.7 kg     1
3129.7 kg      1
5403.3KG       1
14471.8 kg     1
4849.8KG       1
10074.4 kg     1
5247.3KG       1
10414.1 kg     1
15599.8 kg     1
17793.4 kg     1
15083.1 kg     1
9790.4 kg      1
12259.9 kg     1
8437.5 kg      1
17011.7KG      1
4059.7 kg      1
14906.3 kg     1
9335.1 kg      1
10307.2KG      1
15350.1KG      1
5995.2 kg      1
13439.5 kg     1
15363.7 kg     1
10764.6KG      1
10537.2KG      1
17137.0KG      1
9924.4 kg      1
26822.4 kg     1
21728.4 kg     1
33645.3 kg     1
13007.5 kg     1
17700.7 kg     1
14689.2 kg     1
570157.7KG     1
694195.4 kg    1
211701.5 kg    1

In [300]:
def clean_capacity(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip().lower()

    # kilograms — check BEFORE grams
    if value.endswith('kg'):
        return float(value[:-2].strip())

    # grams → kilograms
    if value.endswith('g'):
        return float(value[:-1].strip()) / 1000

    # plain numeric value
    return float(value)


fleet_vehicles['capacity_kg'] = fleet_vehicles['capacity_kg'].apply(
    clean_capacity
)

In [301]:
print(fleet_vehicles['capacity_kg'].dtype)
print("Missing:", fleet_vehicles['capacity_kg'].isna().sum())
print(fleet_vehicles['capacity_kg'].describe())

float64
Missing: 0
count       761.000000
mean      10842.412352
std       67176.386177
min           1.000000
25%          13.700000
50%          32.300000
75%        1073.300000
max      842658.100000
Name: capacity_kg, dtype: float64

In [302]:
print(
    fleet_vehicles.groupby('vehicle_type')['capacity_kg']
    .agg(['count', 'min', 'median', 'max'])
    .sort_values('max', ascending=False)
)

              count       min     median       max
vehicle_type
Ship             14  114321.3  456751.10  842658.1
Air Cargo        22    9924.4   27417.35   44040.3
Truck           122    3129.7   11703.55   17899.3
Van             195     400.3     786.50    1189.0
Bike            265      10.0      21.20      34.9
Drone           143       1.0       3.80       6.0

# odometer_km

In [303]:
fleet_vehicles['odometer_km'].head()

0     62287.3
1    228496.0
2     56173.9
3     62245.1
4    256229.3
Name: odometer_km, dtype: str

In [304]:
odometer_numeric = pd.to_numeric(
    fleet_vehicles['odometer_km'],
    errors='coerce'
)

print("Original missing:", fleet_vehicles['odometer_km'].isna().sum())
print("After conversion:", odometer_numeric.isna().sum())
print(
    "New conversion failures:",
    odometer_numeric.isna().sum()
    - fleet_vehicles['odometer_km'].isna().sum()
)

Original missing: 23
After conversion: 37
New conversion failures: 14

In [305]:
print(
    fleet_vehicles.loc[
        odometer_numeric.isna()
        & fleet_vehicles['odometer_km'].notna(),
        'odometer_km'
    ].value_counts(dropna=False).to_string()
)

odometer_km
-          8
unknown    4
           2

In [306]:
print(
    fleet_vehicles.loc[
        fleet_vehicles['odometer_km'].astype(str).str.strip() == '2',
        ['vehicle_id', 'vehicle_type', 'model_name', 'odometer_km']
    ]
)

Empty DataFrame
Columns: [vehicle_id, vehicle_type, model_name, odometer_km]
Index: []

In [307]:
bad_odometer = fleet_vehicles.loc[
    odometer_numeric.isna()
    & fleet_vehicles['odometer_km'].notna(),
    'odometer_km'
]

for value in bad_odometer.unique():
    print(repr(value))

'-'
'unknown'
'  '

In [308]:
fleet_vehicles['odometer_km'] = pd.to_numeric(
    fleet_vehicles['odometer_km']
    .replace(['-', 'unknown'], pd.NA)
    .replace(r'^\s*$', pd.NA, regex=True),
    errors='coerce'
)

In [309]:
print(fleet_vehicles['odometer_km'].dtype)
print("Missing:", fleet_vehicles['odometer_km'].isna().sum())
print(fleet_vehicles['odometer_km'].describe())

float64
Missing: 37
count       724.000000
mean     127430.649309
std       75428.459683
min         878.200000
25%       58855.675000
50%      126735.750000
75%      191263.850000
max      259612.500000
Name: odometer_km, dtype: float64

In [310]:
print(fleet_vehicles['fleet_status'].value_counts(dropna=False))

fleet_status
Active               108
Retired              108
Idle                 107
ACTIVE               105
Maintenance           92
under maintenance     83
active                82
In Service            76
Name: count, dtype: int64

In [311]:
fleet_vehicles['fleet_status'] = (
    fleet_vehicles['fleet_status']
    .str.strip()
    .str.lower()
    .replace({
        'active': 'Active',
        'maintenance': 'Maintenance',
        'under maintenance': 'Maintenance',
        'idle': 'Idle',
        'in service': 'In Service',
        'retired': 'Retired'
    })
)

print(fleet_vehicles['fleet_status'].value_counts())

fleet_status
Active         295
Maintenance    175
Retired        108
Idle           107
In Service      76
Name: count, dtype: int64

# driver_id

In [312]:
print(
    fleet_vehicles.groupby('fleet_status')['driver_id']
    .agg(['count', 'size'])
)

              count  size
fleet_status
Active          238   295
Idle             85   107
In Service       65    76
Maintenance     146   175
Retired          84   108

# battery_capacity_wh

In [313]:
print(
    fleet_vehicles.loc[
        fleet_vehicles['vehicle_type'] == 'Drone',
        'battery_capacity_wh'
    ].describe()
)

count     143.000000
mean     5398.958042
std      1921.815020
min      2016.000000
25%      3775.000000
50%      5447.000000
75%      6821.000000
max      8978.000000
Name: battery_capacity_wh, dtype: float64

# purchase_date

In [314]:
purchase_date_numeric = pd.to_datetime(
    fleet_vehicles['purchase_date'],
    errors='coerce',
    dayfirst=True
)

print("Original missing:", fleet_vehicles['purchase_date'].isna().sum())
print("After conversion:", purchase_date_numeric.isna().sum())
print(
    "New conversion failures:",
    purchase_date_numeric.isna().sum()
    - fleet_vehicles['purchase_date'].isna().sum()
)

Original missing: 0
After conversion: 508
New conversion failures: 508

In [315]:
invalid_purchase_dates = fleet_vehicles.loc[
    purchase_date_numeric.isna(),
    'purchase_date'
]

print(invalid_purchase_dates.value_counts(dropna=False).head(30).to_string())

purchase_date
2023-10-14 00:00:00    3
09/06/2023 00:00       3
01/02/2020 00:00       2
09/11/2021 00:00       2
04/05/2018 00:00       2
2017-08-24 00:00:00    2
14/06/2020 00:00       2
03/09/2017 00:00       2
2021-05-17 00:00:00    2
29/01/2018 00:00       2
2019-06-01 00:00:00    2
2022-03-20 00:00:00    2
2018-09-19 00:00:00    2
04/04/2020 00:00       2
2018-05-21 00:00:00    2
18/10/2019 00:00       2
2021-10-10 00:00:00    2
23/06/2019 00:00       2
22/08/2020 00:00       2
18/10/2021 00:00       2
2021-09-12 00:00:00    2
2018-06-11 00:00:00    2
2023-02-03 00:00:00    2
2018-05-07 00:00:00    2
2018-01-29 00:00:00    2
2021-05-11 00:00:00    2
2020-08-26 00:00:00    2
2022-05-20 00:00:00    2
2017-08-19 00:00:00    2
2023-04-22 00:00:00    2

In [316]:
purchase_date_clean = pd.to_datetime(
    fleet_vehicles['purchase_date'],
    errors='coerce',
    format='mixed',
    dayfirst=True
)

print("Missing after conversion:", purchase_date_clean.isna().sum())
print(purchase_date_clean.head(10))

Missing after conversion: 0
0   2021-12-17
1   2019-06-26
2   2023-05-26
3   2021-03-06
4   2018-12-31
5   2021-08-27
6   2018-10-17
7   2017-10-11
8   2022-07-14
9   2017-07-08
Name: purchase_date, dtype: datetime64[us]

In [317]:
fleet_vehicles['purchase_date'] = purchase_date_clean

print(fleet_vehicles['purchase_date'].dtype)
print("Missing:", fleet_vehicles['purchase_date'].isna().sum())

datetime64[us]
Missing: 0

# last_service_date

In [318]:
last_service_clean = pd.to_datetime(
    fleet_vehicles['last_service_date'],
    errors='coerce',
    format='mixed',
    dayfirst=True
)

print("Original missing:", fleet_vehicles['last_service_date'].isna().sum())
print("Missing after conversion:", last_service_clean.isna().sum())

Original missing: 0
Missing after conversion: 0

In [319]:
fleet_vehicles['last_service_date'] = last_service_clean

print(fleet_vehicles['last_service_date'].dtype)
print("Missing:", fleet_vehicles['last_service_date'].isna().sum())

datetime64[us]
Missing: 0

# insurance_expiry

In [320]:
insurance_clean = pd.to_datetime(
    fleet_vehicles['insurance_expiry'],
    errors='coerce',
    format='mixed',
    dayfirst=True
)

print("Original missing:", fleet_vehicles['insurance_expiry'].isna().sum())
print("Missing after conversion:", insurance_clean.isna().sum())

Original missing: 0
Missing after conversion: 0

In [321]:
fleet_vehicles['insurance_expiry'] = insurance_clean

print(fleet_vehicles['insurance_expiry'].dtype)
print("Missing:", fleet_vehicles['insurance_expiry'].isna().sum())

datetime64[us]
Missing: 0

In [322]:
print(fleet_vehicles.info())
print("\nMissing values:")
print(fleet_vehicles.isna().sum())

print("\nDuplicate rows:", fleet_vehicles.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   vehicle_id           761 non-null    str
 1   vehicle_type         761 non-null    str
 2   model_name           761 non-null    str
 3   capacity_kg          761 non-null    float64
 4   max_range_km         761 non-null    float64
 5   avg_speed_kmph       761 non-null    int64
 6   hub_code             761 non-null    str
 7   purchase_date        761 non-null    datetime64[us]
 8   odometer_km          724 non-null    float64
 9   fleet_status         761 non-null    str
 10  driver_id            618 non-null    str
 11  battery_capacity_wh  143 non-null    float64
 12  last_service_date    761 non-null    datetime64[us]
 13  insurance_expiry     761 non-null    datetime64[us]
 14  ownership            761 non-null    str
dtypes: datetime64[us](3), float64(4), int64(1), str(7)
memory usage: 127.4 KB
None

Missing values:
vehicle_id               0
vehicle_type             0
model_name               0
capacity_kg              0
max_range_km             0
avg_speed_kmph           0
hub_code                 0
purchase_date            0
odometer_km             37
fleet_status             0
driver_id              143
battery_capacity_wh    618
last_service_date        0
insurance_expiry         0
ownership                0
dtype: int64

Duplicate rows: 25

In [323]:
fleet_vehicles = fleet_vehicles.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", len(fleet_vehicles))
print("Duplicates remaining:", fleet_vehicles.duplicated().sum())

Rows after removing duplicates: 736
Duplicates remaining: 0

# Save the fleet_vechicles cleaned dataset

In [324]:
fleet_vehicles.to_csv("../cleaned_data/fleet_vehicles_cleaned.csv", index=False)

# 6. customer_reviews.json

In [325]:
customer_reviews = pd.read_json(
    '../datasets/customer_reviews.jsonl',
    lines=True
)

print(customer_reviews.info())

<class 'pandas.DataFrame'>
RangeIndex: 12150 entries, 0 to 12149
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   review_id                  12150 non-null  str
 1   order_id                   11903 non-null  str
 2   product_id                 12150 non-null  str
 3   customer_id                12150 non-null  str
 4   rating                     12150 non-null  object
 5   review_title               9716 non-null   str
 6   review_text                11678 non-null  str
 7   review_date                12150 non-null  str
 8   verified_purchase          12150 non-null  object
 9   helpful_votes              8153 non-null   float64
 10  delivery_mode_experienced  10129 non-null  str
 11  sentiment_label            7885 non-null   str
dtypes: float64(1), object(2), str(9)
memory usage: 2.6+ MB
None

Look at the actual values

In [326]:
print(customer_reviews['rating'].value_counts(dropna=False))
print("\nVerified purchase:")
print(customer_reviews['verified_purchase'].value_counts(dropna=False))

rating
5          2628
3          1596
4          1342
1           868
2           854
5           537
5 stars     536
five        372
3           344
5/5         338
3 stars     310
4 stars     259
4           251
three       224
3/5         196
four        190
1           178
2           176
4/5         173
1 stars     167
2 stars     149
2/5         125
1/5         122
one         108
two         107
Name: count, dtype: int64

Verified purchase:
verified_purchase
True     4107
0        4039
true     2031
false    1973
Name: count, dtype: int64

Clean rating

In [327]:
rating_map = {
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5
}

customer_reviews['rating'] = (
    customer_reviews['rating']
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(' stars', '', regex=False)
    .str.replace('/5', '', regex=False)
    .replace(rating_map)
    .astype(int)
)

In [328]:
print(customer_reviews['rating'].value_counts().sort_index())
print(customer_reviews['rating'].dtype)

rating
1    1443
2    1411
3    2670
4    2215
5    4411
Name: count, dtype: int64
int64

Clean verified_purchase

In [329]:
customer_reviews['verified_purchase'] = (
    customer_reviews['verified_purchase']
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        'true': True,
        'false': False,
        '0': False,
        '1': True
    })
)

In [330]:
print(customer_reviews['verified_purchase'].value_counts(dropna=False))
print(customer_reviews['verified_purchase'].dtype)

verified_purchase
True     6138
False    6012
Name: count, dtype: int64
bool

# Fix review_date

In [331]:
review_date_clean = pd.to_datetime(
    customer_reviews['review_date'],
    errors='coerce',
    format='mixed',
    dayfirst=True,
    utc=True
)

print("Missing after conversion:", review_date_clean.isna().sum())
print(review_date_clean.head())

Missing after conversion: 618
0                         NaT
1   2025-03-21 00:00:00+00:00
2   2024-05-27 20:05:00+00:00
3   2024-08-15 06:00:00+00:00
4   2024-03-03 07:23:00+00:00
Name: review_date, dtype: datetime64[us, UTC]

In [332]:
invalid_dates = customer_reviews.loc[
    review_date_clean.isna(),
    'review_date'
]

print(invalid_dates.value_counts().head(10))

review_date
1727258700    2
1735244580    2
1722086220    2
1705647600    2
1735076640    1
1723921500    1
1719578640    1
1747657860    1
1726042620    1
1733932800    1
Name: count, dtype: int64

Convert the Unix timestamps

In [333]:
unix_dates = pd.to_datetime(
    pd.to_numeric(
        customer_reviews.loc[review_date_clean.isna(), 'review_date'],
        errors='coerce'
    ),
    unit='s',
    errors='coerce',
    utc=True
)

print(unix_dates.head())
print("Still invalid:", unix_dates.isna().sum())

0    2024-12-24 21:44:00+00:00
16   2024-08-17 19:05:00+00:00
25   2024-06-28 12:44:00+00:00
42   2025-05-19 12:31:00+00:00
45   2024-09-11 08:17:00+00:00
Name: review_date, dtype: datetime64[s, UTC]
Still invalid: 0

Put them together

In [334]:
customer_reviews['review_date'] = review_date_clean

customer_reviews.loc[
    review_date_clean.isna(),
    'review_date'
] = unix_dates

In [335]:
print("Missing review dates:", customer_reviews['review_date'].isna().sum())
print(customer_reviews['review_date'].head())
print(customer_reviews['review_date'].dtype)

Missing review dates: 0
0   2024-12-24 21:44:00+00:00
1   2025-03-21 00:00:00+00:00
2   2024-05-27 20:05:00+00:00
3   2024-08-15 06:00:00+00:00
4   2024-03-03 07:23:00+00:00
Name: review_date, dtype: datetime64[us, UTC]
datetime64[us, UTC]

Check missing values

In [336]:
print(customer_reviews.isna().sum())

review_id                       0
order_id                      247
product_id                      0
customer_id                     0
rating                          0
review_title                 2434
review_text                   472
review_date                     0
verified_purchase               0
helpful_votes                3997
delivery_mode_experienced    2021
sentiment_label              4265
dtype: int64

Check duplicates

In [337]:
print("Duplicate rows:", customer_reviews.duplicated().sum())

Duplicate rows: 150

Remove duplicates

In [338]:
customer_reviews = customer_reviews.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", len(customer_reviews))
print("Duplicates remaining:", customer_reviews.duplicated().sum())

Rows after removing duplicates: 12000
Duplicates remaining: 0

# helpful_votes

In [339]:
print(customer_reviews['helpful_votes'].describe())
print("\nSample values:")
print(customer_reviews['helpful_votes'].head(10))

count    8053.000000
mean       45.001490
std        26.316943
min         0.000000
25%        22.000000
50%        45.000000
75%        68.000000
max        90.000000
Name: helpful_votes, dtype: float64

Sample values:
0     NaN
1     NaN
2    63.0
3    78.0
4    17.0
5     NaN
6    31.0
7    56.0
8     8.0
9    75.0
Name: helpful_votes, dtype: float64

In [340]:
print(
    customer_reviews.groupby('verified_purchase')['helpful_votes']
    .agg(['count', 'mean'])
)

                   count       mean
verified_purchase
False               4002  45.082959
True                4051  44.921007

# delivery_mode_experienced

In [341]:
print(
    customer_reviews['delivery_mode_experienced']
    .value_counts(dropna=False)
)

delivery_mode_experienced
Van      2058
Drone    2017
NaN      2001
Truck    1981
drone    1975
Bike     1968
Name: count, dtype: int64

# Standardize delivery mode

In [342]:
customer_reviews['delivery_mode_experienced'] = (
    customer_reviews['delivery_mode_experienced']
    .str.strip()
    .str.title()
)

In [343]:
print(
    customer_reviews['delivery_mode_experienced']
    .value_counts(dropna=False)
)

delivery_mode_experienced
Drone    3992
Van      2058
NaN      2001
Truck    1981
Bike     1968
Name: count, dtype: int64

In [344]:
print("Missing ratings:", customer_reviews['rating'].isna().sum())

Missing ratings: 0

# verified_purchase

In [345]:
customer_reviews['verified_purchase'] = (
    customer_reviews['verified_purchase']
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        'true': True,
        '1': True,
        'false': False,
        '0': False
    })
)

In [346]:
print(customer_reviews['verified_purchase'].value_counts(dropna=False))
print(customer_reviews['verified_purchase'].dtype)

verified_purchase
True     6060
False    5940
Name: count, dtype: int64
bool

# sentiment_label

In [347]:
print(
    customer_reviews['sentiment_label']
    .value_counts(dropna=False)
)

sentiment_label
pos    4240
NaN    4217
neg    1839
neu    1704
Name: count, dtype: int64

# Final null check

In [348]:
print(customer_reviews.isna().sum())

review_id                       0
order_id                      246
product_id                      0
customer_id                     0
rating                          0
review_title                 2403
review_text                   464
review_date                     0
verified_purchase               0
helpful_votes                3947
delivery_mode_experienced    2001
sentiment_label              4217
dtype: int64

In [349]:
print(customer_reviews.info())

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   review_id                  12000 non-null  str
 1   order_id                   11754 non-null  str
 2   product_id                 12000 non-null  str
 3   customer_id                12000 non-null  str
 4   rating                     12000 non-null  int64
 5   review_title               9597 non-null   str
 6   review_text                11536 non-null  str
 7   review_date                12000 non-null  datetime64[us, UTC]
 8   verified_purchase          12000 non-null  bool
 9   helpful_votes              8053 non-null   float64
 10  delivery_mode_experienced  9999 non-null   str
 11  sentiment_label            7783 non-null   str
dtypes: bool(1), datetime64[us, UTC](1), float64(1), int64(1), str(8)
memory usage: 2.3 MB
None

In [350]:
print("Duplicate rows:", customer_reviews.duplicated().sum())

Duplicate rows: 0

# save the customer_reviews cleaned dataset

In [351]:
customer_reviews.to_csv(
    '../cleaned_data/customer_reviews_cleaned.csv',
    index=False
)

print("Customer reviews cleaned file saved.")

Customer reviews cleaned file saved.

# 7. gps_routes.json

In [352]:
gps_routes = pd.read_json("../datasets/gps_routes.json")

In [353]:
print(gps_routes.info())

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   route_id              4000 non-null   str
 1   vehicle_id            4000 non-null   str
 2   vehicle_type          4000 non-null   str
 3   route_date            4000 non-null   str
 4   order_ids             4000 non-null   object
 5   planned_distance_km   4000 non-null   float64
 6   actual_distance_km    3745 non-null   float64
 7   planned_duration_min  4000 non-null   float64
 8   actual_duration_min   4000 non-null   float64
 9   stops_planned         4000 non-null   int64
 10  stops_completed       4000 non-null   int64
 11  waypoints             4000 non-null   object
 12  fuel_or_energy_used   4000 non-null   object
 13  driver_id             3030 non-null   str
dtypes: float64(4), int64(2), object(3), str(5)
memory usage: 583.8+ KB
None

Inspect a few values

In [354]:
print(gps_routes[['order_ids', 'waypoints', 'fuel_or_energy_used']].head())

                                           order_ids  \
0  [ORD-004958, ORD-011321, ORD-012786, ORD-00885...
1  [ORD-003588, ORD-002005, ORD-012829, ORD-00727...
2  [ORD-008327, ORD-006093, ORD-008581, ORD-01317...
3                           [ORD-011835, ORD-012480]
4  [ORD-000996, ORD-005341, ORD-008309, ORD-00869...

                                           waypoints fuel_or_energy_used
0  [{'seq': 1, 'lat': 28.620097, 'lon': 77.207826...              7.81 L
1  [{'seq': 1, 'lat': 12.931875, 'lon': 77.596949...             45.98 L
2  [{'seq': 1, 'lat': 18.569008, 'lon': 73.821999...            881.0 Wh
3  [{'seq': 1, 'lat': 13.099905, 'lon': 80.315177...             45.22 L
4  [{'seq': 1, 'lat': 17.683166, 'lon': 83.238398...              51.3 L

# fuel_or_energy_used

In [355]:
print(
    gps_routes['fuel_or_energy_used']
    .value_counts(dropna=False).head(20)
)

fuel_or_energy_used
1909.0 Wh    5
1725.0 Wh    4
2080.0 Wh    4
697.0 Wh     4
855.0 Wh     4
432.0 Wh     4
1842.0 Wh    4
1900.0 Wh    4
2019.0 Wh    3
17.18        3
448.0 Wh     3
730.0 Wh     3
58.24        3
1336.0 Wh    3
16.11 L      3
703.0 Wh     3
764.0 Wh     3
300.0 Wh     3
1536.0 Wh    3
33.63 L      3
Name: count, dtype: int64

Find all formats

In [356]:
print(
    gps_routes['fuel_or_energy_used']
    .astype(str)
    .str.extract(r'([A-Za-z]+)$')[0]
    .value_counts(dropna=False)
)

0
Wh     1374
NaN    1331
L      1295
Name: count, dtype: int64

Inspect unitless values

In [357]:
unitless = gps_routes[
    ~gps_routes['fuel_or_energy_used']
    .astype(str)
    .str.contains(r'(L|Wh)$', regex=True)
]

print(unitless['fuel_or_energy_used'].head(20))

7     44.17
8     40.55
12    10.94
13     25.7
15     28.7
16    39.01
17    20.85
19    17.69
21    43.38
22    48.99
26    25.91
32    57.31
33    47.65
34    18.14
37    10.89
42    31.04
46    48.29
47     1.95
49    10.67
50    17.18
Name: fuel_or_energy_used, dtype: object

C:\Users\hp\AppData\Local\Temp\ipykernel_13152\3463951835.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(r'(L|Wh)$', regex=True)

Check whether the unitless values depend on vehicle type

In [358]:
print(
    unitless.groupby('vehicle_type')['fuel_or_energy_used']
    .agg(['count', 'min', 'max'])
)

              count   min    max
vehicle_type
Bike            370  0.51  59.99
Drone           325  0.52  59.98
Truck           328   0.7  59.99
Van             308  0.54  59.76

# route_date

In [359]:
route_date_clean = pd.to_datetime(
    gps_routes['route_date'],
    errors='coerce',
    format='mixed',
    dayfirst=True,
    utc=True
)

print("Missing after conversion:", route_date_clean.isna().sum())
print(route_date_clean.head())

Missing after conversion: 0
0   2024-02-02 00:00:00+00:00
1   2024-06-03 00:00:00+00:00
2   2024-11-10 00:00:00+00:00
3   2024-05-15 00:00:00+00:00
4   2024-04-27 00:00:00+00:00
Name: route_date, dtype: datetime64[us, UTC]

Check missing values

In [360]:
print(gps_routes.isna().sum())

route_id                  0
vehicle_id                0
vehicle_type              0
route_date                0
order_ids                 0
planned_distance_km       0
actual_distance_km      255
planned_duration_min      0
actual_duration_min       0
stops_planned             0
stops_completed           0
waypoints                 0
fuel_or_energy_used       0
driver_id               970
dtype: int64

Check duplicates

In [361]:
gps_check = gps_routes.copy()

gps_check['order_ids'] = gps_check['order_ids'].astype(str)
gps_check['waypoints'] = gps_check['waypoints'].astype(str)

print("Duplicate rows:", gps_check.duplicated().sum())

Duplicate rows: 0

Apply the cleaned date

In [362]:
gps_routes['route_date'] = route_date_clean

In [363]:
print(gps_routes['route_date'].dtype)
print("Missing route dates:", gps_routes['route_date'].isna().sum())

datetime64[us, UTC]
Missing route dates: 0

Final check

In [364]:
print(gps_routes.info())

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   route_id              4000 non-null   str
 1   vehicle_id            4000 non-null   str
 2   vehicle_type          4000 non-null   str
 3   route_date            4000 non-null   datetime64[us, UTC]
 4   order_ids             4000 non-null   object
 5   planned_distance_km   4000 non-null   float64
 6   actual_distance_km    3745 non-null   float64
 7   planned_duration_min  4000 non-null   float64
 8   actual_duration_min   4000 non-null   float64
 9   stops_planned         4000 non-null   int64
 10  stops_completed       4000 non-null   int64
 11  waypoints             4000 non-null   object
 12  fuel_or_energy_used   4000 non-null   object
 13  driver_id             3030 non-null   str
dtypes: datetime64[us, UTC](1), float64(4), int64(2), object(3), str(4)
memory usage: 544.7+ KB
None

In [365]:
print("\nMissing values:")
print(gps_routes.isna().sum())

print("\nDuplicate rows:", gps_check.duplicated().sum())

Missing values:
route_id                  0
vehicle_id                0
vehicle_type              0
route_date                0
order_ids                 0
planned_distance_km       0
actual_distance_km      255
planned_duration_min      0
actual_duration_min       0
stops_planned             0
stops_completed           0
waypoints                 0
fuel_or_energy_used       0
driver_id               970
dtype: int64

Duplicate rows: 0

# save the gps_routes cleaned dataset

In [366]:
gps_routes.to_csv(
    '../cleaned_data/gps_routes_cleaned.csv',
    index=False
)

print("GPS routes cleaned file saved.")

GPS routes cleaned file saved.

# 8. maintenance_history.csv

In [367]:
maintenance_history = pd.read_csv(
    '../datasets/maintenance_history.csv'
)

print(maintenance_history.info())

<class 'pandas.DataFrame'>
RangeIndex: 2074 entries, 0 to 2073
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   work_order_id     2074 non-null   str
 1   vehicle_id        2074 non-null   str
 2   service_date      2074 non-null   str
 3   service_type      2074 non-null   str
 4   parts_replaced    1486 non-null   str
 5   labour_hours      2021 non-null   str
 6   cost_inr          2074 non-null   str
 7   downtime_hours    2074 non-null   float64
 8   failure_reported  1647 non-null   str
 9   technician_id     2074 non-null   str
dtypes: float64(1), str(9)
memory usage: 320.9 KB
None

Inspect the values

In [368]:
print(maintenance_history[
    ['labour_hours', 'cost_inr', 'failure_reported', 'parts_replaced']
].head(20))

   labour_hours      cost_inr failure_reported     parts_replaced
0           4.9     38,026.84              yes         Motor, ESC
1           6.9   INR 3248.84                N                NaN
2           2.9      17940.67              yes                NaN
3           0.7  INR 34331.71               no                NaN
4           1.8     23,779.23               no  Brake Pads, Fluid
5           4.8  INR 15061.16              NaN                NaN
6           3.1     11,186.15              yes  Brake Pads, Fluid
7          11.3     24,178.97                Y                NaN
8          11.0     46,944.87              NaN       Battery Pack
9          10.5      43895.28               no                NaN
10          3.3      39747.03               no       Propeller x2
11          3.5     38,791.85               no                NaN
12         13.4  INR 34503.72                Y       Landing Skid
13          1.2      3,615.50              NaN       Battery Pack
14          3.3  INR 16818.55                N       Landing Skid
15          6.0       16138.0              yes                NaN
16          5.7     17,260.20              NaN       Propeller x2
17          4.6  INR 38695.39               no                NaN
18          2.6     24,792.95                N       Propeller x2
19          1.6      44619.43              NaN  Brake Pads, Fluid

# Clean labour_hours and cost_inr

In [369]:
maintenance_history['labour_hours'] = pd.to_numeric(
    maintenance_history['labour_hours'],
    errors='coerce'
)

maintenance_history['cost_inr'] = (
    maintenance_history['cost_inr']
    .str.replace('INR', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

maintenance_history['cost_inr'] = pd.to_numeric(
    maintenance_history['cost_inr'],
    errors='coerce'
)

print(maintenance_history[['labour_hours', 'cost_inr']].head())
print(maintenance_history[['labour_hours', 'cost_inr']].dtypes)

   labour_hours  cost_inr
0           4.9  38026.84
1           6.9   3248.84
2           2.9  17940.67
3           0.7  34331.71
4           1.8  23779.23
labour_hours    float64
cost_inr        float64
dtype: object

# Clean failure_reported

In [370]:
maintenance_history['failure_reported'] = (
    maintenance_history['failure_reported']
    .astype('string')
    .str.strip()
    .str.lower()
    .map({
        'yes': True,
        'y': True,
        'no': False,
        'n': False
    })
)

print(maintenance_history['failure_reported'].value_counts(dropna=False))

failure_reported
False    825
True     822
NaN      427
Name: count, dtype: int64

# Clean service_date

In [371]:
service_date_clean = pd.to_datetime(
    maintenance_history['service_date'],
    errors='coerce',
    format='mixed',
    dayfirst=True,
    utc=True
)

print("Missing after conversion:", service_date_clean.isna().sum())
print(service_date_clean.head())

Missing after conversion: 0
0   2024-05-14 00:00:00+00:00
1   2024-05-27 00:00:00+00:00
2   2024-12-12 00:00:00+00:00
3   2025-04-10 00:00:00+00:00
4   2024-12-12 00:00:00+00:00
Name: service_date, dtype: datetime64[us, UTC]

# Apply the cleaned date

In [372]:
maintenance_history['service_date'] = service_date_clean

In [373]:
print(maintenance_history['service_date'].dtype)

datetime64[us, UTC]

# Check duplicates

In [374]:
print("Duplicate rows:", maintenance_history.duplicated().sum())

Duplicate rows: 60

Remove duplicates

In [375]:
maintenance_history = maintenance_history.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", len(maintenance_history))
print("Duplicates remaining:", maintenance_history.duplicated().sum())

Rows after removing duplicates: 2014
Duplicates remaining: 0

# Check remaining missing values

In [376]:
print(maintenance_history.isna().sum())

work_order_id         0
vehicle_id            0
service_date          0
service_type          0
parts_replaced      574
labour_hours         86
cost_inr              0
downtime_hours        0
failure_reported    412
technician_id         0
dtype: int64

Final check

In [377]:
print(maintenance_history.info())

<class 'pandas.DataFrame'>
RangeIndex: 2014 entries, 0 to 2013
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   work_order_id     2014 non-null   str
 1   vehicle_id        2014 non-null   str
 2   service_date      2014 non-null   datetime64[us, UTC]
 3   service_type      2014 non-null   str
 4   parts_replaced    1440 non-null   str
 5   labour_hours      1928 non-null   float64
 6   cost_inr          2014 non-null   float64
 7   downtime_hours    2014 non-null   float64
 8   failure_reported  1602 non-null   object
 9   technician_id     2014 non-null   str
dtypes: datetime64[us, UTC](1), float64(3), object(1), str(5)
memory usage: 255.3+ KB
None

In [378]:
print("Duplicate rows:", maintenance_history.duplicated().sum())

Duplicate rows: 0

# Save the maintenance_history cleaned dataset

In [379]:
maintenance_history.to_csv(
    '../cleaned_data/maintenance_history_cleaned.csv',
    index=False
)

print("Maintenance history cleaned file saved.")

Maintenance history cleaned file saved.

In [3]:
import pandas as pd

# 9. product_catalog.json

In [4]:
product_catalog = pd.read_json("../datasets/product_catalog.json")

In [7]:
print(product_catalog['products'].head())

0    {'product_id': 'PRD-00453', 'product_name': 'Z...
1    {'product_id': 'PRD-00517', 'product_name': 'N...
2    {'product_id': 'PRD-00524', 'product_name': 'M...
3    {'product_id': 'PRD-00190', 'product_name': 'K...
4    {'product_id': 'PRD-00107', 'product_name': 'M...
Name: products, dtype: object

See the product fields

In [8]:
print(product_catalog['products'].iloc[0].keys())

dict_keys(['product_id', 'product_name', 'category', 'sub_category', 'specs', 'price', 'is_fragile', 'is_hazmat', 'requires_cold_chain', 'stock_qty', 'avg_rating', 'tags', 'launch_date'])

In [9]:
products = pd.json_normalize(product_catalog['products'])

print(products.info())

<class 'pandas.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  878 non-null    str
 1   product_name                878 non-null    str
 2   category                    878 non-null    str
 3   sub_category                878 non-null    str
 4   is_fragile                  878 non-null    bool
 5   is_hazmat                   878 non-null    bool
 6   requires_cold_chain         878 non-null    bool
 7   stock_qty                   878 non-null    int64
 8   avg_rating                  835 non-null    float64
 9   tags                        878 non-null    object
 10  launch_date                 878 non-null    str
 11  specs.weight_kg             832 non-null    object
 12  specs.battery_included      558 non-null    object
 13  price.currency              878 non-null    str
 14  price.amount                878 non-null    object
 15  specs.dimensions_cm.length  801 non-null    float64
 16  specs.dimensions_cm.width   801 non-null    float64
 17  specs.dimensions_cm.height  801 non-null    float64
 18  specs                       0 non-null      float64
dtypes: bool(3), float64(5), int64(1), object(4), str(6)
memory usage: 170.0+ KB
None

Inspect the potentially messy values

In [11]:
print(products[
    ['specs.weight_kg', 'specs.battery_included', 'price.amount', 'launch_date']
].head(20))

   specs.weight_kg specs.battery_included price.amount          launch_date
0             0.74                   None    93,078.54           04-07-2022
1             0.89                  False    133860.89           27-11-2020
2             0.79                   None     25610.55  2022-06-17 00:00:00
3            43.13                   True    163381.89  2022-03-15 00:00:00
4             1.28                   None    157038.82  2023-07-10 00:00:00
5             0.51                  False   130,910.39  2021-05-08 00:00:00
6             2.41                   None     27962.75  2023-04-19 00:00:00
7             1.35                   None    104599.98  2023-10-24 00:00:00
8            37.67                   None    32,818.52           22-12-2022
9             1.42                  False     29861.59           02-02-2021
10            6.04                  False     40947.97           14-05-2021
11            7.23                   None    150591.56           09-02-2022
12         3882.82                   None   112,502.53  2022-12-08 00:00:00
13            1.47                  False     50929.68           08-06-2021
14         3009.54                   None    146848.92  2022-12-26 00:00:00
15           21.78                   None      92991.6           30-04-2023
16         3901.35                   True    74,728.70           19-02-2022
17           21.07                   True   141,087.17           26-10-2021
18           22.38                   True    23,158.92           31-10-2022
19             NaN                    NaN   173,302.33  2021-11-06 00:00:00

Clean price

In [12]:
products['price.amount'] = (
    products['price.amount']
    .astype('string')
    .str.replace(',', '', regex=False)
    .str.strip()
)

products['price.amount'] = pd.to_numeric(
    products['price.amount'],
    errors='coerce'
)

print(products['price.amount'].dtype)
print(products['price.amount'].head())

Float64
0     93078.54
1    133860.89
2     25610.55
3    163381.89
4    157038.82
Name: price.amount, dtype: Float64

Clean launch_date

In [13]:
products['launch_date'] = pd.to_datetime(
    products['launch_date'],
    errors='coerce',
    format='mixed',
    dayfirst=True,
    utc=True
)

print("Missing launch dates:", products['launch_date'].isna().sum())
print(products['launch_date'].head())
print(products['launch_date'].dtype)

Missing launch dates: 0
0   2022-07-04 00:00:00+00:00
1   2020-11-27 00:00:00+00:00
2   2022-06-17 00:00:00+00:00
3   2022-03-15 00:00:00+00:00
4   2023-10-07 00:00:00+00:00
Name: launch_date, dtype: datetime64[us, UTC]
datetime64[us, UTC]

Check specs.weight_kg

In [14]:
print(products['specs.weight_kg'].head(20))
print(products['specs.weight_kg'].dtype)

0        0.74
1        0.89
2        0.79
3       43.13
4        1.28
5        0.51
6        2.41
7        1.35
8       37.67
9        1.42
10       6.04
11       7.23
12    3882.82
13       1.47
14    3009.54
15      21.78
16    3901.35
17      21.07
18      22.38
19        NaN
Name: specs.weight_kg, dtype: object
object

Convert weight to numeric

In [15]:
products['specs.weight_kg'] = pd.to_numeric(
    products['specs.weight_kg'],
    errors='coerce'
)

print(products['specs.weight_kg'].dtype)
print("Missing weights:", products['specs.weight_kg'].isna().sum())

float64
Missing weights: 66

Check avg_rating

In [16]:
print(products['avg_rating'].describe())
print("\nMissing:", products['avg_rating'].isna().sum())

count    835.000000
mean       3.770958
std        0.734267
min        2.500000
25%        3.120000
50%        3.780000
75%        4.460000
max        5.000000
Name: avg_rating, dtype: float64

Missing: 43

Check tags

In [17]:
print(products['tags'].head(10))
print(products['tags'].dtype)

0                   [bestseller]
1    [fragile-handle, clearance]
2     [eco, new, fragile-handle]
3                 [premium, new]
4                             []
5                          [new]
6                             []
7              [eco, bestseller]
8                          [eco]
9          [fragile-handle, eco]
Name: tags, dtype: object
object

Remove the empty specs column

In [18]:
products = products.drop(columns=['specs'])

print(products.shape)

(878, 18)

Check duplicates

In [19]:
products_check = products.copy()

products_check['tags'] = products_check['tags'].astype(str)

print("Duplicate rows:", products_check.duplicated().sum())

Duplicate rows: 2

Remove the 2 duplicates

In [20]:
products = products.drop_duplicates(
    subset=[
        'product_id',
        'product_name',
        'category',
        'sub_category'
    ]
).reset_index(drop=True)

print("Rows after removing duplicates:", len(products))

Rows after removing duplicates: 838

In [21]:
print("Duplicate product IDs:", products['product_id'].duplicated().sum())

Duplicate product IDs: 0

In [22]:
products = products_check.copy()

print("Rows restored:", len(products))

Rows restored: 878

Check the tags column

In [23]:
print(products['tags'].head())
print(products['tags'].dtype)

0                      ['bestseller']
1     ['fragile-handle', 'clearance']
2    ['eco', 'new', 'fragile-handle']
3                  ['premium', 'new']
4                                  []
Name: tags, dtype: str
str

Convert tags back to lists

In [24]:
import ast

products['tags'] = products['tags'].apply(ast.literal_eval)

print(products['tags'].head())
print(products['tags'].dtype)

0                   [bestseller]
1    [fragile-handle, clearance]
2     [eco, new, fragile-handle]
3                 [premium, new]
4                             []
Name: tags, dtype: object
object

Check duplicates correctly

In [25]:
products_check = products.copy()
products_check['tags'] = products_check['tags'].astype(str)

print("Duplicate rows:", products_check.duplicated().sum())

Duplicate rows: 2

Remove only those 2 duplicates

In [26]:
products = products_check.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", len(products))
print("Duplicates remaining:", products.duplicated().sum())

Rows after removing duplicates: 876
Duplicates remaining: 0

Check missing values

In [27]:
print(products.isna().sum())

product_id                      0
product_name                    0
category                        0
sub_category                    0
is_fragile                      0
is_hazmat                       0
requires_cold_chain             0
stock_qty                       0
avg_rating                     43
tags                            0
launch_date                     0
specs.weight_kg                64
specs.battery_included        318
price.currency                  0
price.amount                    0
specs.dimensions_cm.length     75
specs.dimensions_cm.width      75
specs.dimensions_cm.height     75
dtype: int64

In [29]:
print(products.duplicated().sum())

0

In [30]:
# PRODUCT CATALOG - MISSING VALUE ANALYSIS

missing_count = products.isnull().sum()
missing_percentage = (products.isnull().mean() * 100).round(2)

missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_percentage": missing_percentage
})

display(missing_summary[missing_summary["missing_count"] > 0])

                            missing_count  missing_percentage
avg_rating                             43                4.91
specs.weight_kg                        64                7.31
specs.battery_included                318               36.30
specs.dimensions_cm.length             75                8.56
specs.dimensions_cm.width              75                8.56
specs.dimensions_cm.height             75                8.56

In [31]:
# PRODUCT CATALOG - MISSING VALUE DISTRIBUTION

print("Average Rating Statistics:")
print(products["avg_rating"].describe())

print("\nWeight Statistics:")
print(products["specs.weight_kg"].describe())

print("\nBattery Included Values:")
print(products["specs.battery_included"].value_counts(dropna=False))

print("\nDimension Statistics:")
display(
    products[
        [
            "specs.dimensions_cm.length",
            "specs.dimensions_cm.width",
            "specs.dimensions_cm.height"
        ]
    ].describe()
)

Average Rating Statistics:
count    833.000000
mean       3.770096
std        0.734934
min        2.500000
25%        3.120000
50%        3.780000
75%        4.460000
max        5.000000
Name: avg_rating, dtype: float64

Weight Statistics:
count    8.120000e+02
mean     1.061077e+04
std      2.002327e+05
min      2.000000e-01
25%      1.500000e+00
50%      4.545000e+00
75%      4.196000e+01
max      4.405920e+06
Name: specs.weight_kg, dtype: float64

Battery Included Values:
specs.battery_included
False    311
None     274
True     247
NaN       44
Name: count, dtype: int64

Dimension Statistics:

,specs.dimensions_cm.length,specs.dimensions_cm.width,specs.dimensions_cm.height
count,801.000000,801.000000,801.000000
mean,93.649064,62.009863,76.756055
std,49.587086,32.964996,44.832213
min,5.200000,5.000000,2.200000
25%,50.600000,34.600000,34.100000
50%,96.200000,60.200000,78.800000
75%,134.600000,92.800000,117.500000
max,179.300000,119.300000,149.900000

In [32]:
# PRODUCT CATALOG - WEIGHT OUTLIER CHECK

print("Weight values above 100 kg:")
display(
    products[
        products["specs.weight_kg"] > 100
    ][
        [
            "product_id",
            "product_name",
            "category",
            "sub_category",
            "specs.weight_kg"
        ]
    ].sort_values("specs.weight_kg", ascending=False)
)

print("\nNumber of products above 100 kg:")
print(
    (products["specs.weight_kg"] > 100).sum()
)

Weight values above 100 kg:

,product_id,product_name,category,sub_category,specs.weight_kg
128,PRD-00687,Kaveri Generator Unit Max,Industrial,Generator Unit,4405920.00
618,PRD-00650,UrbanCraft Generator Unit,Industrial,Generator Unit,3629470.00
842,PRD-00217,Aravind Study Table Pro,Furniture,Study Table,103990.00
427,PRD-00207,Vayu Recliner,Furniture,Recliner,84290.00
262,PRD-00144,Aravind Mixer Grinder,Home Appliance,Mixer Grinder,36490.00
...,...,...,...,...,...
809,PRD-00256,Kaveri Office Chair Classic,furniture,Office Chair,106.46
441,PRD-00237,Zenith Study Table 2024,Furniture,Study Table,106.20
82,PRD-00279,Aravind Office Chair,furniture,Office Chair,106.03
729,PRD-00222,Tamira Recliner Lite,Furniture,Recliner,104.66
478,PRD-00227,Nexon Study Table Max,Furniture,Study Table,102.70

Number of products above 100 kg:
149

In [33]:
# PRODUCT CATALOG - EXTREME WEIGHT ANALYSIS

weight_check = (
    products
    .groupby(["category", "sub_category"])["specs.weight_kg"]
    .agg(["count", "min", "median", "max"])
    .sort_values("max", ascending=False)
)

display(weight_check.head(20))

                               count      min    median         max
category       sub_category
Industrial     Generator Unit     29   326.44  2682.380  4405920.00
Furniture      Study Table        23    12.19    70.570   103990.00
               Recliner           27    13.16   104.660    84290.00
Home Appliance Mixer Grinder      22     5.03    21.245    36490.00
               Microwave          18     4.92    21.870    22440.00
               Air Purifier       22     5.42    29.685    17440.00
Pharma         Vaccine Box        28     0.20     3.720     4470.00
Industrial     Motor Assembly     33   259.92  2448.990     4393.07
               Steel Coil         35   839.37  3143.940     4255.96
Electronics    Smartwatch         21     0.48     1.040     2790.00
Books          Textbook           39     0.46     2.030     2770.00
Pharma         Insulin Pack       27     0.35     1.980     2670.00
Electronics    Headphones         20     0.71     2.185     2410.00
Apparel        T-Shirt            26     0.34     1.125     1810.00
industrial     Steel Coil          2   521.97  1127.130     1732.29
               Generator Unit      1  1393.25  1393.250     1393.25
Apparel        Saree              29     0.24     1.120      950.00
furniture      Study Table         1   119.67   119.670      119.67
Furniture      Office Chair       20    13.13    84.885      117.58
               Bookshelf          28    12.06    52.150      113.03

In [34]:
# PRODUCT CATALOG - IDENTIFY SUSPICIOUS WEIGHTS

group_median = (
    products
    .groupby(["category", "sub_category"])["specs.weight_kg"]
    .transform("median")
)

products["weight_median_ratio"] = (
    products["specs.weight_kg"] / group_median
)

suspicious_weights = products[
    products["weight_median_ratio"] > 100
].copy()

print("Potentially suspicious weight records:")
print(suspicious_weights.shape[0])

display(
    suspicious_weights[
        [
            "product_id",
            "product_name",
            "category",
            "sub_category",
            "specs.weight_kg",
            "weight_median_ratio"
        ]
    ].sort_values(
        "weight_median_ratio",
        ascending=False
    )
)

Potentially suspicious weight records:
18

,product_id,product_name,category,sub_category,specs.weight_kg,weight_median_ratio
479,PRD-00097,Aravind Smartwatch,Electronics,Smartwatch,2790.0,2682.692308
262,PRD-00144,Aravind Mixer Grinder,Home Appliance,Mixer Grinder,36490.0,1717.580607
128,PRD-00687,Kaveri Generator Unit Max,Industrial,Generator Unit,4405920.0,1642.541325
37,PRD-00482,Aravind T-Shirt,Apparel,T-Shirt,1810.0,1608.888889
842,PRD-00217,Aravind Study Table Pro,Furniture,Study Table,103990.0,1473.572340
351,PRD-00797,UrbanCraft Textbook Classic,Books,Textbook,2770.0,1364.532020
618,PRD-00650,UrbanCraft Generator Unit,Industrial,Generator Unit,3629470.0,1353.078236
807,PRD-00575,Tamira Insulin Pack Pro,Pharma,Insulin Pack,2670.0,1348.484848
560,PRD-00548,UrbanCraft Vaccine Box Pro,Pharma,Vaccine Box,4470.0,1201.612903
818,PRD-00038,Nexon Headphones,Electronics,Headphones,2410.0,1102.974828
800,PRD-00168,Meridian Microwave,Home Appliance,Microwave,22440.0,1026.063100
503,PRD-00034,Kaveri Headphones,Electronics,Headphones,2080.0,951.945080
332,PRD-00494,Kaveri Saree Classic,Apparel,Saree,950.0,848.214286
427,PRD-00207,Vayu Recliner,Furniture,Recliner,84290.0,805.369769
270,PRD-00132,Kaveri Air Purifier Max,Home Appliance,Air Purifier,17440.0,587.502105
533,PRD-00238,UrbanCraft Study Table,Furniture,Study Table,22960.0,325.350716
116,PRD-00455,Tamira Saree,Apparel,Saree,260.0,232.142857
474,PRD-00306,Aravind Recliner Lite,Furniture,Recliner,19270.0,184.120008

In [36]:
# PRODUCT CATALOG - INSPECT SUSPICIOUS WEIGHTS

display(
    suspicious_weights[
        [
            "product_id",
            "product_name",
            "category",
            "sub_category",
            "specs.weight_kg",
            "specs.dimensions_cm.length",
            "specs.dimensions_cm.width",
            "specs.dimensions_cm.height",
            "price.amount",
            "tags"
        ]
    ]
)

,product_id,product_name,category,sub_category,specs.weight_kg,specs.dimensions_cm.length,specs.dimensions_cm.width,specs.dimensions_cm.height,price.amount,tags
37,PRD-00482,Aravind T-Shirt,Apparel,T-Shirt,1810.0,108.5,63.6,93.7,64289.07,[]
116,PRD-00455,Tamira Saree,Apparel,Saree,260.0,106.4,52.3,20.5,111503.47,"['new', 'bestseller']"
128,PRD-00687,Kaveri Generator Unit Max,Industrial,Generator Unit,4405920.0,61.5,73.1,62.8,111611.32,"['new', 'clearance', 'fragile-handle']"
262,PRD-00144,Aravind Mixer Grinder,Home Appliance,Mixer Grinder,36490.0,23.6,10.7,89.4,154848.0,['clearance']
270,PRD-00132,Kaveri Air Purifier Max,Home Appliance,Air Purifier,17440.0,57.7,27.8,137.8,124909.81,[]
332,PRD-00494,Kaveri Saree Classic,Apparel,Saree,950.0,141.4,61.3,149.2,100930.1,"['fragile-handle', 'eco']"
351,PRD-00797,UrbanCraft Textbook Classic,Books,Textbook,2770.0,81.0,22.2,126.5,157774.48,"['eco', 'premium', 'fragile-handle']"
427,PRD-00207,Vayu Recliner,Furniture,Recliner,84290.0,137.3,65.5,62.0,56969.27,"['bestseller', 'premium']"
474,PRD-00306,Aravind Recliner Lite,Furniture,Recliner,19270.0,26.1,102.9,149.9,180159.92,[]
479,PRD-00097,Aravind Smartwatch,Electronics,Smartwatch,2790.0,80.7,89.3,98.7,88408.65,"['fragile-handle', 'clearance']"
503,PRD-00034,Kaveri Headphones,Electronics,Headphones,2080.0,46.9,58.6,40.4,147219.72,"['bestseller', 'clearance', 'premium']"
533,PRD-00238,UrbanCraft Study Table,Furniture,Study Table,22960.0,24.6,24.2,124.4,145960.99,"['eco', 'fragile-handle', 'new']"
560,PRD-00548,UrbanCraft Vaccine Box Pro,Pharma,Vaccine Box,4470.0,137.4,54.8,69.0,9503.8,[]
618,PRD-00650,UrbanCraft Generator Unit,Industrial,Generator Unit,3629470.0,98.7,67.1,126.7,177968.18,"['eco', 'bestseller']"
800,PRD-00168,Meridian Microwave,Home Appliance,Microwave,22440.0,177.9,51.3,45.1,13816.18,['fragile-handle']
807,PRD-00575,Tamira Insulin Pack Pro,Pharma,Insulin Pack,2670.0,58.4,37.7,13.3,38962.65,[]
818,PRD-00038,Nexon Headphones,Electronics,Headphones,2410.0,30.7,5.4,138.6,22066.79,"['eco', 'premium', 'fragile-handle']"
842,PRD-00217,Aravind Study Table Pro,Furniture,Study Table,103990.0,159.7,96.7,36.7,140418.41,[]

Correct suspicious weights

In [37]:
# PRODUCT CATALOG - CORRECT SUSPICIOUS WEIGHTS

products["weight_median"] = (
    products
    .groupby(["category", "sub_category"])["specs.weight_kg"]
    .transform("median")
)

products["weight_median_ratio"] = (
    products["specs.weight_kg"] / products["weight_median"]
)

suspicious_mask = products["weight_median_ratio"] > 100

print("Suspicious weights identified:", suspicious_mask.sum())

products.loc[
    suspicious_mask,
    "specs.weight_kg"
] = products.loc[
    suspicious_mask,
    "weight_median"
]

print("Suspicious weights corrected successfully.")

products.drop(
    columns=["weight_median", "weight_median_ratio"],
    inplace=True
)

Suspicious weights identified: 18
Suspicious weights corrected successfully.

In [38]:
# PRODUCT CATALOG - VERIFY WEIGHT CLEANING

print("Maximum weight after cleaning:")
print(products["specs.weight_kg"].max())

print("\nWeight statistics after cleaning:")
print(products["specs.weight_kg"].describe())

Maximum weight after cleaning:
4393.07

Weight statistics after cleaning:
count     812.000000
mean      319.293861
std       914.996004
min         0.200000
25%         1.477500
50%         4.290000
75%        39.432500
max      4393.070000
Name: specs.weight_kg, dtype: float64

# clean avg_rating

In [39]:
# PRODUCT CATALOG - CLEAN AVG RATING

rating_median = products["avg_rating"].median()

print("Median rating:", rating_median)

products["avg_rating"] = products["avg_rating"].fillna(rating_median)

print("Missing ratings after cleaning:")
print(products["avg_rating"].isnull().sum())

Median rating: 3.7800000000000002
Missing ratings after cleaning:
0

specs.battery_included

In [40]:
# PRODUCT CATALOG - BATTERY INFORMATION ANALYSIS

battery_by_category = (
    products
    .groupby(["category", "sub_category"])["specs.battery_included"]
    .value_counts(dropna=False)
    .unstack(fill_value=0)
)

display(battery_by_category)

specs.battery_included         NaN  False  True
category       sub_category
Apparel        Jacket           10     15     8
               Running Shoes    11      8     6
               Saree            11     12     9
               T-Shirt          15      8     6
Books          Comic Set         8     15     6
               Novel            11     10     8
               Textbook         14     19     7
Electronics    Headphones       12      8     4
               Laptop            2     12     5
               Smartphone        7     11     7
               Smartwatch        9      7     6
               Tablet            5      7     8
Furniture      Bookshelf        11     10     8
               Office Chair      7      5    10
               Recliner         15     11     5
               Study Table       9     10     6
Groceries      Cooking Oil      11     10    15
               Dry Fruits       10      7    10
               Rice Bag          7      2     8
               Spice Pack        8      9     9
Home Appliance Air Purifier     11      6     8
               Microwave         6      7     6
               Mixer Grinder     5     12     5
               Vacuum Cleaner    9      8     8
Industrial     Generator Unit   10     12     8
               Motor Assembly   13     11    11
               Steel Coil       22     11     8
Pharma         Insulin Pack     10     11     6
               Medical Kit      13     10    12
               Vaccine Box      15     10     7
apparel        Jacket            0      0     1
               Running Shoes     0      1     1
               Saree             0      2     0
               T-Shirt           1      0     0
books          Textbook          0      2     0
electronics    Headphones        1      0     0
               Laptop            1      0     1
               Smartphone        1      0     0
               Tablet            0      1     0
furniture      Bookshelf         0      0     2
               Office Chair      1      0     1
               Study Table       0      1     0
groceries      Cooking Oil       1      2     0
               Dry Fruits        0      1     0
               Rice Bag          0      1     0
               Spice Pack        1      0     0
home appliance Air Purifier      1      1     0
               Microwave         0      1     1
               Mixer Grinder     0      0     1
               Vacuum Cleaner    0      0     1
industrial     Generator Unit    0      0     1
               Steel Coil        0      1     1
pharma         Insulin Pack      1      0     1
               Medical Kit       0      1     5
               Vaccine Box       2      2     0

In [41]:
# PRODUCT CATALOG - CLEAN BATTERY INFORMATION

products["specs.battery_included"] = (
    products["specs.battery_included"]
    .fillna("Unknown")
)

print("Battery values after cleaning:")
print(products["specs.battery_included"].value_counts())

print("\nMissing battery values:")
print(products["specs.battery_included"].isnull().sum())

Battery values after cleaning:
specs.battery_included
Unknown    318
False      311
True       247
Name: count, dtype: int64

Missing battery values:
0

# Clean the dimensions

In [42]:
# PRODUCT CATALOG - DIMENSION ANALYSIS

dimension_columns = [
    "specs.dimensions_cm.length",
    "specs.dimensions_cm.width",
    "specs.dimensions_cm.height"
]

print("Missing values by dimension:")
print(products[dimension_columns].isnull().sum())

print("\nDimension statistics:")
display(products[dimension_columns].describe())

print("\nRows with any missing dimension:")
print(products[dimension_columns].isnull().any(axis=1).sum())

print("\nRows with all dimensions missing:")
print(products[dimension_columns].isnull().all(axis=1).sum())

Missing values by dimension:
specs.dimensions_cm.length    75
specs.dimensions_cm.width     75
specs.dimensions_cm.height    75
dtype: int64

Dimension statistics:

,specs.dimensions_cm.length,specs.dimensions_cm.width,specs.dimensions_cm.height
count,801.000000,801.000000,801.000000
mean,93.649064,62.009863,76.756055
std,49.587086,32.964996,44.832213
min,5.200000,5.000000,2.200000
25%,50.600000,34.600000,34.100000
50%,96.200000,60.200000,78.800000
75%,134.600000,92.800000,117.500000
max,179.300000,119.300000,149.900000

Rows with any missing dimension:
75

Rows with all dimensions missing:
75

# Fill Missing Dimensions

In [43]:
# PRODUCT CATALOG - FILL MISSING DIMENSIONS

for column in dimension_columns:
    category_median = (
        products
        .groupby(["category", "sub_category"])[column]
        .transform("median")
    )

    products[column] = products[column].fillna(category_median)

print("Missing dimensions after category-wise cleaning:")

print(
    products[dimension_columns]
    .isnull()
    .sum()
)

Missing dimensions after category-wise cleaning:
specs.dimensions_cm.length    1
specs.dimensions_cm.width     1
specs.dimensions_cm.height    1
dtype: int64

In [44]:
# PRODUCT CATALOG - INSPECT REMAINING DIMENSION MISSING VALUE

remaining_dimension_missing = products[
    products[dimension_columns].isnull().any(axis=1)
]

display(
    remaining_dimension_missing[
        [
            "product_id",
            "product_name",
            "category",
            "sub_category"
        ] + dimension_columns
    ]
)

,product_id,product_name,category,sub_category,specs.dimensions_cm.length,specs.dimensions_cm.width,specs.dimensions_cm.height
604,PRD-00025,Kaveri Smartphone Pro,electronics,Smartphone,NaN,NaN,NaN

In [45]:
# PRODUCT CATALOG - STANDARDIZE CATEGORY VALUES

products["category"] = products["category"].str.strip().str.title()

print("Unique categories after standardization:")
print(sorted(products["category"].unique()))

Unique categories after standardization:
['Apparel', 'Books', 'Electronics', 'Furniture', 'Groceries', 'Home Appliance', 'Industrial', 'Pharma']

In [46]:
# PRODUCT CATALOG - COMPLETE MISSING DIMENSIONS

for column in dimension_columns:
    category_median = (
        products
        .groupby(["category", "sub_category"])[column]
        .transform("median")
    )

    products[column] = products[column].fillna(category_median)

print("Missing dimensions after final cleaning:")
print(products[dimension_columns].isnull().sum())

Missing dimensions after final cleaning:
specs.dimensions_cm.length    0
specs.dimensions_cm.width     0
specs.dimensions_cm.height    0
dtype: int64

In [48]:
# PRODUCT CATALOG - FILL MISSING WEIGHTS

weight_median = (
    products
    .groupby(["category", "sub_category"])["specs.weight_kg"]
    .transform("median")
)

products["specs.weight_kg"] = (
    products["specs.weight_kg"]
    .fillna(weight_median)
)

print("Missing weights after category-wise cleaning:")
print(products["specs.weight_kg"].isnull().sum())

Missing weights after category-wise cleaning:
0

In [49]:
# PRODUCT CATALOG - FINAL DATA VALIDATION

print("Final Shape:")
print(products.shape)

print("\nTotal Missing Values:")
print(products.isnull().sum().sum())

print("\nMissing Values by Column:")
print(products.isnull().sum())

print("\nData Types:")
print(products.dtypes)

Final Shape:
(876, 18)

Total Missing Values:
0

Missing Values by Column:
product_id                    0
product_name                  0
category                      0
sub_category                  0
is_fragile                    0
is_hazmat                     0
requires_cold_chain           0
stock_qty                     0
avg_rating                    0
tags                          0
launch_date                   0
specs.weight_kg               0
specs.battery_included        0
price.currency                0
price.amount                  0
specs.dimensions_cm.length    0
specs.dimensions_cm.width     0
specs.dimensions_cm.height    0
dtype: int64

Data Types:
product_id                                    str
product_name                                  str
category                                      str
sub_category                                  str
is_fragile                                   bool
is_hazmat                                    bool
requires_cold_chain                          bool
stock_qty                                   int64
avg_rating                                float64
tags                                          str
launch_date                   datetime64[us, UTC]
specs.weight_kg                           float64
specs.battery_included                     object
price.currency                                str
price.amount                              Float64
specs.dimensions_cm.length                float64
specs.dimensions_cm.width                 float64
specs.dimensions_cm.height                float64
dtype: object

Final check

In [50]:
print(products.info())

<class 'pandas.DataFrame'>
RangeIndex: 876 entries, 0 to 875
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  876 non-null    str
 1   product_name                876 non-null    str
 2   category                    876 non-null    str
 3   sub_category                876 non-null    str
 4   is_fragile                  876 non-null    bool
 5   is_hazmat                   876 non-null    bool
 6   requires_cold_chain         876 non-null    bool
 7   stock_qty                   876 non-null    int64
 8   avg_rating                  876 non-null    float64
 9   tags                        876 non-null    str
 10  launch_date                 876 non-null    datetime64[us, UTC]
 11  specs.weight_kg             876 non-null    float64
 12  specs.battery_included      876 non-null    object
 13  price.currency              876 non-null    str
 14  price.amount                876 non-null    Float64
 15  specs.dimensions_cm.length  876 non-null    float64
 16  specs.dimensions_cm.width   876 non-null    float64
 17  specs.dimensions_cm.height  876 non-null    float64
dtypes: Float64(1), bool(3), datetime64[us, UTC](1), float64(5), int64(1), object(1), str(6)
memory usage: 167.5+ KB
None

Final duplicate check

In [53]:
# PRODUCT CATALOG - FINAL DUPLICATE PRODUCT ID CHECK

duplicate_product_ids = products[
    products["product_id"].duplicated(keep=False)
].sort_values("product_id")

print(
    "Number of rows with duplicate product IDs:",
    len(duplicate_product_ids)
)

print(
    "Number of unique duplicated product IDs:",
    duplicate_product_ids["product_id"].nunique()
)

display(
    duplicate_product_ids[
        [
            "product_id",
            "product_name",
            "category",
            "sub_category",
            "stock_qty",
            "avg_rating",
            "specs.weight_kg",
            "price.amount"
        ]
    ]
)

Number of rows with duplicate product IDs: 76
Number of unique duplicated product IDs: 38

,product_id,product_name,category,sub_category,stock_qty,avg_rating,specs.weight_kg,price.amount
244,PRD-00007,Tamira Smartwatch Classic,Electronics,Smartwatch,728,4.34,0.64,139086.3
652,PRD-00007,Tamira Smartwatch Classic,Electronics,Smartwatch,767,4.34,0.64,139086.3
73,PRD-00091,Aravind Laptop,Electronics,Laptop,85,3.86,1.98,124148.79
86,PRD-00091,Aravind Laptop,Electronics,Laptop,-11,3.86,1.98,124148.79
133,PRD-00099,Nexon Laptop 2024,Electronics,Laptop,544,3.26,1.92,102218.1
...,...,...,...,...,...,...,...,...
662,PRD-00767,Kaveri Textbook Lite,Books,Textbook,408,3.05,3.94,163296.05
121,PRD-00819,UrbanCraft Textbook Classic,Books,Textbook,688,4.62,1.58,176735.16
812,PRD-00819,UrbanCraft Textbook Classic,Books,Textbook,25,4.62,1.58,176735.16
104,PRD-00824,Kaveri Comic Set Pro,Books,Comic Set,-9,4.93,0.81,105947.43
834,PRD-00824,Kaveri Comic Set Pro,Books,Comic Set,847,4.93,0.81,105947.43

# Negative Stock Check

In [54]:
# PRODUCT CATALOG - NEGATIVE STOCK CHECK

negative_stock = products[
    products["stock_qty"] < 0
]

print("Number of negative stock records:")
print(len(negative_stock))

print("\nNegative stock records:")

display(
    negative_stock[
        [
            "product_id",
            "product_name",
            "category",
            "sub_category",
            "stock_qty"
        ]
    ]
)

Number of negative stock records:
23

Negative stock records:

,product_id,product_name,category,sub_category,stock_qty
13,PRD-00458,UrbanCraft Running Shoes,Apparel,Running Shoes,-11
33,PRD-00825,Nexon Novel Classic,Books,Novel,-8
66,PRD-00614,Kaveri Insulin Pack Lite,Pharma,Insulin Pack,-4
86,PRD-00091,Aravind Laptop,Electronics,Laptop,-11
98,PRD-00779,Meridian Textbook Lite,Books,Textbook,-11
104,PRD-00824,Kaveri Comic Set Pro,Books,Comic Set,-9
134,PRD-00427,Kaveri T-Shirt Pro,Apparel,T-Shirt,-2
201,PRD-00534,Tamira Running Shoes 2024,Apparel,Running Shoes,-19
250,PRD-00579,Zenith Medical Kit Max,Pharma,Medical Kit,-5
400,PRD-00401,Aravind Cooking Oil Max,Groceries,Cooking Oil,-13
414,PRD-00183,Tamira Mixer Grinder Lite,Home Appliance,Mixer Grinder,-16
420,PRD-00012,Vayu Smartphone Pro,Electronics,Smartphone,-2
446,PRD-00365,Zenith Cooking Oil Lite,Groceries,Cooking Oil,-13
471,PRD-00277,Zenith Study Table Max,Furniture,Study Table,-6
476,PRD-00083,Tamira Headphones Lite,Electronics,Headphones,-4
488,PRD-00511,Aravind Jacket 2024,Apparel,Jacket,-19
565,PRD-00509,Nexon Jacket Classic,Apparel,Jacket,-9
566,PRD-00740,Zenith Motor Assembly 2024,Industrial,Motor Assembly,-19
607,PRD-00127,Aravind Air Purifier 2024,Home Appliance,Air Purifier,-17
732,PRD-00420,Tamira T-Shirt,Apparel,T-Shirt,-18
773,PRD-00013,Nexon Headphones Max,Electronics,Headphones,-20
814,PRD-00147,Tamira Vacuum Cleaner Lite,Home Appliance,Vacuum Cleaner,-20
832,PRD-00612,UrbanCraft Medical Kit 2024,Pharma,Medical Kit,-20

In [55]:
# PRODUCT CATALOG - CLEAN NEGATIVE STOCK

negative_stock_count = (products["stock_qty"] < 0).sum()

print("Negative stock records before cleaning:", negative_stock_count)

products.loc[
    products["stock_qty"] < 0,
    "stock_qty"
] = 0

print(
    "Negative stock records after cleaning:",
    (products["stock_qty"] < 0).sum()
)

Negative stock records before cleaning: 23
Negative stock records after cleaning: 0

# consolidate duplicate Product IDs

In [56]:
# PRODUCT CATALOG - CONSOLIDATE DUPLICATE PRODUCT IDs

duplicate_id_count = products["product_id"].duplicated().sum()

print("Duplicate product rows before consolidation:", duplicate_id_count)

# Save stock totals for each product ID
stock_totals = (
    products
    .groupby("product_id")["stock_qty"]
    .sum()
)

# Keep the first occurrence of each product
products = products.drop_duplicates(
    subset="product_id",
    keep="first"
).copy()

# Apply the combined stock quantity
products["stock_qty"] = (
    products["product_id"]
    .map(stock_totals)
)

print("Duplicate product rows after consolidation:")
print(products["product_id"].duplicated().sum())

print("\nFinal product shape:")
print(products.shape)

Duplicate product rows before consolidation: 38
Duplicate product rows after consolidation:
0

Final product shape:
(838, 18)

# Final validation

In [57]:
# PRODUCT CATALOG - FINAL VALIDATION AFTER CONSOLIDATION

print("Final Shape:")
print(products.shape)

print("\nDuplicate Rows:")
print(products.duplicated().sum())

print("\nDuplicate Product IDs:")
print(products["product_id"].duplicated().sum())

print("\nNegative Stock:")
print((products["stock_qty"] < 0).sum())

print("\nTotal Missing Values:")
print(products.isnull().sum().sum())

print("\nMissing Values by Column:")
print(products.isnull().sum())

Final Shape:
(838, 18)

Duplicate Rows:
0

Duplicate Product IDs:
0

Negative Stock:
0

Total Missing Values:
0

Missing Values by Column:
product_id                    0
product_name                  0
category                      0
sub_category                  0
is_fragile                    0
is_hazmat                     0
requires_cold_chain           0
stock_qty                     0
avg_rating                    0
tags                          0
launch_date                   0
specs.weight_kg               0
specs.battery_included        0
price.currency                0
price.amount                  0
specs.dimensions_cm.length    0
specs.dimensions_cm.width     0
specs.dimensions_cm.height    0
dtype: int64

In [58]:
products_check = products.copy()
products_check['tags'] = products_check['tags'].astype(str)

print("Duplicate rows:", products_check.duplicated().sum())

Duplicate rows: 0

# save the product_catalog cleaned dataset

In [59]:
products.to_csv(
    '../cleaned_data/product_catalog_cleaned.csv',
    index=False
)

print("Product catalog cleaned file saved.")

Product catalog cleaned file saved.

# 10. Traffic data. csv

In [404]:
traffic_data = pd.read_csv('../datasets/traffic_data.csv')

print(traffic_data.info())

<class 'pandas.DataFrame'>
RangeIndex: 20328 entries, 0 to 20327
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   record_date        20328 non-null  str
 1   hour_of_day        20328 non-null  str
 2   city               20328 non-null  str
 3   corridor           20328 non-null  str
 4   congestion_index   20328 non-null  float64
 5   avg_speed_kmph     19967 non-null  str
 6   incident_reported  20328 non-null  str
 7   road_closure       18879 non-null  str
dtypes: float64(1), str(7)
memory usage: 2.0 MB
None

# Inspect hour_of_day and avg_speed_kmph

In [405]:
print(traffic_data[['hour_of_day', 'avg_speed_kmph']].head(20))

   hour_of_day avg_speed_kmph
0            7           31.9
1           10           37.7
2           13           40.5
3           17           15.5
4           20           21.6
5           23           38.8
6            7            NaN
7           10           13.1
8           13           27.6
9           17           17.9
10          20           23.6
11          23           12.6
12           7           14.1
13          10           38.4
14          13           48.0
15       17:00           31.5
16          20           19.1
17          23           36.7
18           7           19.8
19          10           55.7

# Clean hour_of_day

In [406]:
traffic_data['hour_of_day'] = (
    traffic_data['hour_of_day']
    .astype(str)
    .str.replace(':00', '', regex=False)
)

traffic_data['hour_of_day'] = pd.to_numeric(
    traffic_data['hour_of_day'],
    errors='coerce'
)

print(traffic_data['hour_of_day'].head(20))
print(traffic_data['hour_of_day'].dtype)

0      7
1     10
2     13
3     17
4     20
5     23
6      7
7     10
8     13
9     17
10    20
11    23
12     7
13    10
14    13
15    17
16    20
17    23
18     7
19    10
Name: hour_of_day, dtype: int64
int64

# Clean avg_speed_kmph

In [407]:
traffic_data['avg_speed_kmph'] = pd.to_numeric(
    traffic_data['avg_speed_kmph'],
    errors='coerce'
)

print(traffic_data['avg_speed_kmph'].dtype)
print("Missing speed:", traffic_data['avg_speed_kmph'].isna().sum())

float64
Missing speed: 600

Check the speed values

In [408]:
print(traffic_data['avg_speed_kmph'].describe())

count    19728.000000
mean        32.731595
std         11.863074
min          4.000000
25%         24.300000
50%         32.700000
75%         41.200000
max         68.500000
Name: avg_speed_kmph, dtype: float64

Convert record_date

In [409]:
traffic_data['record_date'] = pd.to_datetime(
    traffic_data['record_date'],
    errors='coerce',
    format='mixed',
    utc=True
)

print("Missing after conversion:", traffic_data['record_date'].isna().sum())
print(traffic_data['record_date'].head())
print(traffic_data['record_date'].dtype)

Missing after conversion: 0
0   2024-01-01 00:00:00+00:00
1   2024-01-01 00:00:00+00:00
2   2024-01-01 00:00:00+00:00
3   2024-01-01 00:00:00+00:00
4   2024-01-01 00:00:00+00:00
Name: record_date, dtype: datetime64[us, UTC]
datetime64[us, UTC]

# Check incident_reported values

In [410]:
print(traffic_data['incident_reported'].value_counts(dropna=False))

incident_reported
0        11148
1         2450
FALSE     2381
Yes       1691
No        1415
TRUE      1243
Name: count, dtype: int64

Standardize incident_reported

In [411]:
traffic_data['incident_reported'] = (
    traffic_data['incident_reported']
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        '0': False,
        'false': False,
        'no': False,
        '1': True,
        'true': True,
        'yes': True
    })
)

print(traffic_data['incident_reported'].value_counts(dropna=False))
print(traffic_data['incident_reported'].dtype)

incident_reported
False    14944
True      5384
Name: count, dtype: int64
bool

# Check road_closure

In [412]:
print(traffic_data['road_closure'].value_counts(dropna=False))

road_closure
N      17947
NaN     1449
Y        932
Name: count, dtype: int64

Standardize road_closure

In [413]:
traffic_data['road_closure'] = (
    traffic_data['road_closure']
    .astype('string')
    .str.strip()
    .str.upper()
    .map({
        'Y': True,
        'N': False
    })
)

print(traffic_data['road_closure'].value_counts(dropna=False))
print(traffic_data['road_closure'].dtype)

road_closure
False    17947
NaN       1449
True       932
Name: count, dtype: int64
object

Convert to nullable boolean

In [414]:
traffic_data['road_closure'] = traffic_data['road_closure'].astype('boolean')

print(traffic_data['road_closure'].value_counts(dropna=False))
print(traffic_data['road_closure'].dtype)

road_closure
False    17947
<NA>      1449
True       932
Name: count, dtype: Int64
boolean

# Check duplicates

In [415]:
print("Duplicate rows:", traffic_data.duplicated().sum())

Duplicate rows: 600

Inspect the duplicates

In [416]:
duplicates = traffic_data[traffic_data.duplicated(keep=False)]

print("Duplicate rows:", len(duplicates))
print(duplicates.head(10))

Duplicate rows: 1200
                  record_date  hour_of_day        city         corridor  \
33  2024-01-01 00:00:00+00:00           17        Pune  Old Town Bypass
40  2024-01-01 00:00:00+00:00           20     Chennai   Port Access Rd
54  2024-01-01 00:00:00+00:00            7   Ahmedabad        Ring Road
128 2024-01-03 00:00:00+00:00           13     Madurai      IT Corridor
134 2024-01-03 00:00:00+00:00           13       Kochi   Central Market
157 2024-01-05 00:00:00+00:00           10     Madurai   Central Market
209 2024-01-05 00:00:00+00:00           23  Coimbatore        Ring Road
212 2024-01-05 00:00:00+00:00           13     Lucknow  Old Town Bypass
242 2024-01-07 00:00:00+00:00           13   Hyderabad        Ring Road
276 2024-01-07 00:00:00+00:00            7    Gurugram  Old Town Bypass

     congestion_index  avg_speed_kmph  incident_reported  road_closure
33              0.366             NaN              False         False
40              0.329            44.8               True         False
54              0.652            21.1               True         False
128            47.400            27.1              False         False
134             0.185            44.7              False         False
157            47.200            29.6              False          <NA>
209             0.030            60.9              False         False
212             0.474            30.4               True          <NA>
242             0.205            48.6              False         False
276             0.578            25.6              False         False

Remove duplicates

In [417]:
traffic_data = traffic_data.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", len(traffic_data))
print("Duplicates remaining:", traffic_data.duplicated().sum())

Rows after removing duplicates: 19728
Duplicates remaining: 0

# Check missing values

In [418]:
print(traffic_data.isna().sum())

record_date             0
hour_of_day             0
city                    0
corridor                0
congestion_index        0
avg_speed_kmph        579
incident_reported       0
road_closure         1409
dtype: int64

# Check the final structure

In [419]:
print(traffic_data.info())

<class 'pandas.DataFrame'>
RangeIndex: 19728 entries, 0 to 19727
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   record_date        19728 non-null  datetime64[us, UTC]
 1   hour_of_day        19728 non-null  int64
 2   city               19728 non-null  str
 3   corridor           19728 non-null  str
 4   congestion_index   19728 non-null  float64
 5   avg_speed_kmph     19149 non-null  float64
 6   incident_reported  19728 non-null  bool
 7   road_closure       18319 non-null  boolean
dtypes: bool(1), boolean(1), datetime64[us, UTC](1), float64(2), int64(1), str(2)
memory usage: 1.4 MB
None

# save the traffic_data cleaned dataset

In [420]:
traffic_data.to_csv(
    '../cleaned_data/traffic_data_cleaned.csv',
    index=False
)

print("Traffic data cleaned file saved.")

Traffic data cleaned file saved.

# 11. weather_data.csv

In [421]:
weather_data = pd.read_csv('../datasets/weather_data.csv')

print(weather_data.info())

<class 'pandas.DataFrame'>
RangeIndex: 11149 entries, 0 to 11148
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                11149 non-null  str
 1   City Name           11149 non-null  str
 2   temp                10974 non-null  str
 3   Temp Unit           8411 non-null   str
 4   humidity_%          10891 non-null  str
 5   Precipitation (mm)  11149 non-null  float64
 6   wind_speed_kmph     11030 non-null  str
 7   Visibility_KM       11149 non-null  float64
 8   condition           11149 non-null  str
 9   storm_alert         10643 non-null  str
dtypes: float64(2), str(8)
memory usage: 1.2 MB
None

# Inspect the mixed-format columns

In [422]:
print(weather_data[['Date', 'temp', 'Temp Unit', 'humidity_%',
                    'wind_speed_kmph', 'storm_alert']].head(20))

          Date  temp Temp Unit humidity_% wind_speed_kmph storm_alert
0   01-01-2024  65.3         F         58            26.6           N
1   02-01-2024  87.7         F         77            14.2           N
2   2024-01-03  25.8         C         39            28.3           N
3   04-01-2024  77.1         F         61            30.2           N
4   05-01-2024  24.2         C         96            23.0           N
5   06-01-2024  80.4         F         36            12.0           N
6   2024-01-07  22.9       NaN         86            24.9           N
7   2024-01-08  22.9       NaN         50             2.7           N
8   09-01-2024  27.1       NaN         75            35.1         yes
9   2024-01-10  27.0       NaN         86            39.7           N
10  11-01-2024  23.4         C         56             2.0           N
11  12-01-2024  29.5       NaN         74             2.3           N
12  2024-01-13  31.5       NaN         96            20.0           N
13  14-01-2024  24.5         C         96            29.2           N
14  15-01-2024  24.4         C         52            18.8           N
15  2024-01-16  23.1       NaN         61            21.2           N
16  2024-01-17  26.6       NaN         35            33.7           N
17  18-01-2024  26.7         C         44            18.4           N
18  19-01-2024  22.5         C        NaN            19.8           N
19  20-01-2024  23.4         C         70            35.1           N

# Check temperature by unit

In [423]:
print(weather_data.groupby('Temp Unit')['temp'].describe())
print()
print(weather_data['Temp Unit'].value_counts(dropna=False))

          count unique   top freq
Temp Unit
C          7254    309  30.8   65
F          1027    394  85.2   10

Temp Unit
C      7369
NaN    2738
F      1042
Name: count, dtype: int64

# Inspect temperatures where the unit is missing

In [424]:
print(
    weather_data.loc[
        weather_data['Temp Unit'].isna(),
        'temp'
    ].describe()
)

count     2693
unique     499
top       26.8
freq        26
Name: temp, dtype: object

# Check missing-unit temperature range

In [425]:
missing_unit_temp = pd.to_numeric(
    weather_data.loc[weather_data['Temp Unit'].isna(), 'temp'],
    errors='coerce'
)

print("Min:", missing_unit_temp.min())
print("Max:", missing_unit_temp.max())
print()
print("Values > 50:", (missing_unit_temp > 50).sum())
print("Values <= 50:", (missing_unit_temp <= 50).sum())

Min: 8.5
Max: 103.9

Values > 50: 324
Values <= 50: 2335

# Convert temp to numeric

In [426]:
weather_data['temp'] = pd.to_numeric(
    weather_data['temp'],
    errors='coerce'
)

print(weather_data['temp'].dtype)
print("Missing temperatures:", weather_data['temp'].isna().sum())

float64
Missing temperatures: 320

# Create a standardized Celsius temperature column

In [427]:
weather_data['temp_celsius'] = weather_data['temp']

# Convert Fahrenheit to Celsius where the unit is F
f_mask = weather_data['Temp Unit'].eq('F')

weather_data.loc[f_mask, 'temp_celsius'] = (
    weather_data.loc[f_mask, 'temp'] - 32
) * 5 / 9

# Keep only temperatures with a known unit
unknown_mask = weather_data['Temp Unit'].isna()
weather_data.loc[unknown_mask, 'temp_celsius'] = pd.NA

print(weather_data[['temp', 'Temp Unit', 'temp_celsius']].head(20))
print()
print("Missing standardized temperatures:",
      weather_data['temp_celsius'].isna().sum())

    temp Temp Unit  temp_celsius
0   65.3         F     18.500000
1   87.7         F     30.944444
2   25.8         C     25.800000
3   77.1         F     25.055556
4   24.2         C     24.200000
5   80.4         F     26.888889
6   22.9       NaN           NaN
7   22.9       NaN           NaN
8   27.1       NaN           NaN
9   27.0       NaN           NaN
10  23.4         C     23.400000
11  29.5       NaN           NaN
12  31.5       NaN           NaN
13  24.5         C     24.500000
14  24.4         C     24.400000
15  23.1       NaN           NaN
16  26.6       NaN           NaN
17  26.7         C     26.700000
18  22.5         C     22.500000
19  23.4         C     23.400000

Missing standardized temperatures: 2979

# Check humidity_%

In [428]:
weather_data['humidity_%'] = pd.to_numeric(
    weather_data['humidity_%'],
    errors='coerce'
)

print(weather_data['humidity_%'].dtype)
print("Missing humidity:", weather_data['humidity_%'].isna().sum())
print(weather_data['humidity_%'].describe())

float64
Missing humidity: 450
count    10699.000000
mean        63.164034
std         20.489703
min         28.000000
25%         45.000000
50%         63.000000
75%         81.000000
max         98.000000
Name: humidity_%, dtype: float64

# Convert wind_speed_kmph

In [429]:
weather_data['wind_speed_kmph'] = pd.to_numeric(
    weather_data['wind_speed_kmph'],
    errors='coerce'
)

print(weather_data['wind_speed_kmph'].dtype)
print("Missing wind speed:", weather_data['wind_speed_kmph'].isna().sum())
print(weather_data['wind_speed_kmph'].describe())

float64
Missing wind speed: 220
count    10929.000000
mean        23.534898
std         12.545658
min          2.000000
25%         12.600000
50%         23.700000
75%         34.500000
max         45.000000
Name: wind_speed_kmph, dtype: float64

# Standardize storm_alert

In [430]:
print(weather_data['storm_alert'].value_counts(dropna=False))

storm_alert
N      9259
NaN     506
Y       478
yes     456
no      450
Name: count, dtype: int64

In [431]:
weather_data['storm_alert'] = (
    weather_data['storm_alert']
    .astype('string')
    .str.strip()
    .str.lower()
    .map({
        'y': True,
        'yes': True,
        'n': False,
        'no': False
    })
    .astype('boolean')
)

print(weather_data['storm_alert'].value_counts(dropna=False))
print(weather_data['storm_alert'].dtype)

storm_alert
False    9709
True      934
<NA>      506
Name: count, dtype: Int64
boolean

# Convert Date to datetime

In [432]:
weather_data['Date'] = pd.to_datetime(
    weather_data['Date'],
    dayfirst=True,
    errors='coerce',
    utc=True
)

print("Missing dates:", weather_data['Date'].isna().sum())
print(weather_data['Date'].head())
print(weather_data['Date'].dtype)

Missing dates: 5487
0   2024-01-01 00:00:00+00:00
1   2024-01-02 00:00:00+00:00
2                         NaT
3   2024-01-04 00:00:00+00:00
4   2024-01-05 00:00:00+00:00
Name: Date, dtype: datetime64[us, UTC]
datetime64[us, UTC]

# Fix the date conversion

In [433]:
weather_data['Date'] = pd.to_datetime(
    weather_data['Date'].astype(str),
    format='mixed',
    dayfirst=True,
    errors='coerce',
    utc=True
)

print("Missing dates:", weather_data['Date'].isna().sum())
print(weather_data['Date'].head(10))
print(weather_data['Date'].dtype)

Missing dates: 5487
0   2024-01-01 00:00:00+00:00
1   2024-02-01 00:00:00+00:00
2                         NaT
3   2024-04-01 00:00:00+00:00
4   2024-05-01 00:00:00+00:00
5   2024-06-01 00:00:00+00:00
6                         NaT
7                         NaT
8   2024-09-01 00:00:00+00:00
9                         NaT
Name: Date, dtype: datetime64[us, UTC]
datetime64[us, UTC]

# Restore and correctly convert Date

In [434]:
# Reload the original Date column
original_dates = pd.read_csv('../datasets/weather_data.csv')['Date']

# Parse both YYYY-MM-DD and DD-MM-YYYY formats
weather_data['Date'] = pd.to_datetime(
    original_dates,
    format='mixed',
    errors='coerce',
    utc=True
)

print("Missing dates:", weather_data['Date'].isna().sum())
print(weather_data['Date'].head(10))
print(weather_data['Date'].dtype)

Missing dates: 0
0   2024-01-01 00:00:00+00:00
1   2024-02-01 00:00:00+00:00
2   2024-01-03 00:00:00+00:00
3   2024-04-01 00:00:00+00:00
4   2024-05-01 00:00:00+00:00
5   2024-06-01 00:00:00+00:00
6   2024-01-07 00:00:00+00:00
7   2024-01-08 00:00:00+00:00
8   2024-09-01 00:00:00+00:00
9   2024-01-10 00:00:00+00:00
Name: Date, dtype: datetime64[us, UTC]
datetime64[us, UTC]

# Check duplicates

In [435]:
print("Duplicate rows:", weather_data.duplicated().sum())

Duplicate rows: 400

# Remove duplicates

In [436]:
weather_data = weather_data.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", len(weather_data))
print("Duplicates remaining:", weather_data.duplicated().sum())

Rows after removing duplicates: 10749
Duplicates remaining: 0

# Check the remaining missing values

In [437]:
print(weather_data.isna().sum())

Date                     0
City Name                0
temp                   308
Temp Unit             2637
humidity_%             434
Precipitation (mm)       0
wind_speed_kmph        208
Visibility_KM            0
condition                0
storm_alert            488
temp_celsius          2868
dtype: int64

# Handle Temp Unit

In [438]:
weather_data = weather_data.drop(columns=['Temp Unit'])

print(weather_data.columns)
print(weather_data.shape)

Index(['Date', 'City Name', 'temp', 'humidity_%', 'Precipitation (mm)',
       'wind_speed_kmph', 'Visibility_KM', 'condition', 'storm_alert',
       'temp_celsius'],
      dtype='str')
(10749, 10)

# Check the remaining missing values

In [439]:
print(weather_data.isna().sum())

Date                     0
City Name                0
temp                   308
humidity_%             434
Precipitation (mm)       0
wind_speed_kmph        208
Visibility_KM            0
condition                0
storm_alert            488
temp_celsius          2868
dtype: int64

In [440]:
weather_data = weather_data.drop(columns=['temp'])

print(weather_data.columns)
print(weather_data.shape)

Index(['Date', 'City Name', 'humidity_%', 'Precipitation (mm)',
       'wind_speed_kmph', 'Visibility_KM', 'condition', 'storm_alert',
       'temp_celsius'],
      dtype='str')
(10749, 9)

# Standardize condition

In [449]:
weather_data['condition'] = (
    weather_data['condition']
    .str.strip()
    .str.title()
)

In [450]:
print(weather_data['condition'].value_counts())

condition
Clear           3781
Cloudy          2103
Rain            1956
Sunny           1001
Fog              717
Heavy Rain       634
Thunderstorm     557
Name: count, dtype: int64

# Fill missing humidity_%

In [442]:
weather_data['humidity_%'] = weather_data['humidity_%'].fillna(
    weather_data['humidity_%'].median()
)

print("Missing humidity:", weather_data['humidity_%'].isna().sum())

Missing humidity: 0

# Fill missing wind_speed_kmph

In [443]:
weather_data['wind_speed_kmph'] = weather_data['wind_speed_kmph'].fillna(
    weather_data['wind_speed_kmph'].median()
)

print("Missing wind speed:", weather_data['wind_speed_kmph'].isna().sum())

Missing wind speed: 0

# Handle storm_alert

In [444]:
print(weather_data['storm_alert'].value_counts(dropna=False))

storm_alert
False    9365
True      896
<NA>      488
Name: count, dtype: Int64

# Check temp_celsius

In [445]:
print(weather_data['temp_celsius'].describe())
print("Missing temperature:", weather_data['temp_celsius'].isna().sum())

count    7881.000000
mean       25.666483
std         6.198440
min         4.000000
25%        21.100000
50%        26.500000
75%        30.500000
max        41.833333
Name: temp_celsius, dtype: float64
Missing temperature: 2868

# Final missing-value check

In [446]:
print(weather_data.isna().sum())

Date                     0
City Name                0
humidity_%               0
Precipitation (mm)       0
wind_speed_kmph          0
Visibility_KM            0
condition                0
storm_alert            488
temp_celsius          2868
dtype: int64

# Final validation

In [447]:
print(weather_data.info())
print()
print("Duplicate rows:", weather_data.duplicated().sum())
print()
print("Rows:", len(weather_data))
print("Columns:", len(weather_data.columns))

<class 'pandas.DataFrame'>
RangeIndex: 10749 entries, 0 to 10748
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                10749 non-null  datetime64[us, UTC]
 1   City Name           10749 non-null  str
 2   humidity_%          10749 non-null  float64
 3   Precipitation (mm)  10749 non-null  float64
 4   wind_speed_kmph     10749 non-null  float64
 5   Visibility_KM       10749 non-null  float64
 6   condition           10749 non-null  str
 7   storm_alert         10261 non-null  boolean
 8   temp_celsius        7881 non-null   float64
dtypes: boolean(1), datetime64[us, UTC](1), float64(5), str(2)
memory usage: 834.0 KB
None

Duplicate rows: 0

Rows: 10749
Columns: 9

# Save the cleaned weather dataset

In [451]:
weather_data.to_csv(
    '../cleaned_data/weather_data_cleaned.csv',
    index=False
)

print("Weather dataset saved successfully.")

Weather dataset saved successfully.