# verify the project path

In [2]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nData folder:")
print(os.listdir("../data"))

Current working directory:
c:\Users\hp\Desktop\DS_Project_6\notebooks

Data folder:
['drone_dataset_YOLO', 'drone_payload_optimization.csv', 'drone_yolo', 'orders_analysis_final.csv', 'orders_consolidated.csv', 'orders_eta_ready.csv', 'orders_maintenance_ready.csv', 'orders_ml_ready.csv', 'orders_routes_optimized.csv']

# Inspect the main dataset

In [3]:
import pandas as pd

orders = pd.read_csv("../data/orders_analysis_final.csv")

print("Shape:", orders.shape)

display(orders.head())

Shape: (14243, 73)

,order_id,customer_id,product_id,quantity,order_date,origin_hub,origin_city,destination_city,destination_state,destination_pincode,...,max_range_km,vehicle_avg_speed_kmph,fleet_status,ownership,distance_per_delivery_hour,vehicle_capacity_utilization_pct,eta_buffer_hours,traffic_vehicle_speed_ratio,weight_exceeds_capacity,distance_level
0,ORD-011545,CUST-02608,PRD-00356,3,2024-05-06 00:00:00+00:00,HUB-LUC,Lucknow,Chandigarh,CH,160017,...,1634.5,52.0,Active,Owned,33.647291,0.137653,4.88,0.609434,False,Very Long
1,ORD-008131,CUST-03997,PRD-00200,3,2024-12-27 12:23:00+00:00,HUB-CHE,Chennai,Chennai,TN,600001,...,346.5,45.0,Active,Owned,5.089701,10.060913,0.19,0.609434,False,Very Short
2,ORD-005235,CUST-00315,PRD-00222,1,2024-11-18 12:58:00+00:00,HUB-BEN,Bengaluru,Bengaluru,KA,560001,...,311.8,42.0,Active,3PL Partner,9.286822,14.177730,0.31,0.609434,False,Very Short
3,ORD-001394,CUST-04067,PRD-00155,4,2024-08-29 11:05:00+00:00,HUB-MAD,Madurai,Madurai,TN,625001,...,1991.3,56.0,Active,Leased,0.588022,0.385889,0.29,0.609434,False,Very Short
4,ORD-011091,CUST-04320,PRD-00201,4,2025-04-28 21:44:00+00:00,HUB-AHM,Ahmedabad,Guwahati,AS,781001,...,1126.1,46.0,Retired,Owned,34.059365,1.038232,17.49,0.609434,False,Very Long

In [4]:
missing = orders.isnull().sum()

missing_summary = pd.DataFrame({
    "column": missing.index,
    "missing_count": missing.values,
    "missing_pct": (missing.values / len(orders) * 100).round(2)
})

missing_summary = missing_summary.sort_values(
    "missing_count",
    ascending=False
)

display(missing_summary)

                              column  missing_count  missing_pct
0                           order_id              0          0.0
1                        customer_id              0          0.0
2                         product_id              0          0.0
3                           quantity              0          0.0
4                         order_date              0          0.0
..                               ...            ...          ...
68  vehicle_capacity_utilization_pct              0          0.0
69                  eta_buffer_hours              0          0.0
70       traffic_vehicle_speed_ratio              0          0.0
71           weight_exceeds_capacity              0          0.0
72                    distance_level              0          0.0

[73 rows x 3 columns]

# Inspect the actual data types

In [5]:
dtype_summary = pd.DataFrame({
    "column": orders.columns,
    "data_type": orders.dtypes.astype(str).values,
    "unique_values": orders.nunique(dropna=True).values
})

display(dtype_summary)

                              column data_type  unique_values
0                           order_id       str          14243
1                        customer_id       str           4707
2                         product_id       str           1000
3                           quantity     int64              4
4                         order_date       str          12423
..                               ...       ...            ...
68  vehicle_capacity_utilization_pct   float64          12059
69                  eta_buffer_hours   float64           4352
70       traffic_vehicle_speed_ratio   float64           1012
71           weight_exceeds_capacity      bool              2
72                    distance_level       str              4

[73 rows x 3 columns]

# create a column grouping

In [6]:
# Group the 73 columns by the role they play in the SmartLogix system

groups = {
    "order_customer": [
        "order_id", "customer_id", "product_id", "quantity",
        "order_date", "origin_hub", "origin_city",
        "destination_city", "destination_state",
        "destination_pincode", "delivery_priority",
        "payment_mode", "order_value_inr"
    ],

    "package_delivery": [
        "package_weight", "is_fragile", "is_hazmat",
        "cold_chain_required", "promised_eta_hours",
        "actual_delivery_hours", "delivery_cost_inr",
        "transport_mode", "order_status",
        "delivery_delay_hours", "delivery_delay_pct",
        "on_time"
    ],

    "delivery_events": [
        "delivery_event_count", "failed_attempt_count",
        "rto_count", "hub_event_count",
        "delivery_log_start", "delivery_log_end"
    ],

    "location_route": [
        "destination_lat", "destination_lon",
        "distance_km", "distance_level"
    ],

    "traffic_weather": [
        "weather_condition_at_dest", "traffic_date",
        "traffic_hour", "city_x", "hour_of_day",
        "congestion_index", "traffic_avg_speed_kmph",
        "incident_reported", "road_closure",
        "weather_date", "weather_city",
        "humidity_pct", "precipitation_mm",
        "wind_speed_kmph", "visibility_km",
        "temp_celsius", "storm_alert", "condition"
    ],

    "customer": [
        "customer_segment", "is_prime_member",
        "lifetime_orders", "avg_rating_given"
    ],

    "vehicle_fleet": [
        "vehicle_id", "vehicle_type", "capacity_kg",
        "max_range_km", "vehicle_avg_speed_kmph",
        "fleet_status", "ownership"
    ],

    "analytics": [
        "distance_per_delivery_hour",
        "vehicle_capacity_utilization_pct",
        "eta_buffer_hours",
        "traffic_vehicle_speed_ratio",
        "weight_exceeds_capacity"
    ]
}

for group, columns in groups.items():
    print(f"\n{group.upper()} ({len(columns)} columns)")
    print(columns)

ORDER_CUSTOMER (13 columns)
['order_id', 'customer_id', 'product_id', 'quantity', 'order_date', 'origin_hub', 'origin_city', 'destination_city', 'destination_state', 'destination_pincode', 'delivery_priority', 'payment_mode', 'order_value_inr']

PACKAGE_DELIVERY (12 columns)
['package_weight', 'is_fragile', 'is_hazmat', 'cold_chain_required', 'promised_eta_hours', 'actual_delivery_hours', 'delivery_cost_inr', 'transport_mode', 'order_status', 'delivery_delay_hours', 'delivery_delay_pct', 'on_time']

DELIVERY_EVENTS (6 columns)
['delivery_event_count', 'failed_attempt_count', 'rto_count', 'hub_event_count', 'delivery_log_start', 'delivery_log_end']

LOCATION_ROUTE (4 columns)
['destination_lat', 'destination_lon', 'distance_km', 'distance_level']

TRAFFIC_WEATHER (18 columns)
['weather_condition_at_dest', 'traffic_date', 'traffic_hour', 'city_x', 'hour_of_day', 'congestion_index', 'traffic_avg_speed_kmph', 'incident_reported', 'road_closure', 'weather_date', 'weather_city', 'humidity_pct', 'precipitation_mm', 'wind_speed_kmph', 'visibility_km', 'temp_celsius', 'storm_alert', 'condition']

CUSTOMER (4 columns)
['customer_segment', 'is_prime_member', 'lifetime_orders', 'avg_rating_given']

VEHICLE_FLEET (7 columns)
['vehicle_id', 'vehicle_type', 'capacity_kg', 'max_range_km', 'vehicle_avg_speed_kmph', 'fleet_status', 'ownership']

ANALYTICS (5 columns)
['distance_per_delivery_hour', 'vehicle_capacity_utilization_pct', 'eta_buffer_hours', 'traffic_vehicle_speed_ratio', 'weight_exceeds_capacity']

# Install the PostgreSQL Python driver

In [7]:
%pip install psycopg2-binary sqlalchemy pandas

Requirement already satisfied: psycopg2-binary in c:\Users\hp\Desktop\DS_Project_6\.venv\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\Users\hp\Desktop\DS_Project_6\.venv\Lib\site-packages (2.0.52)
Requirement already satisfied: pandas in c:\Users\hp\Desktop\DS_Project_6\.venv\Lib\site-packages (3.0.5)
Requirement already satisfied: greenlet>=1 in c:\Users\hp\Desktop\DS_Project_6\.venv\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\hp\Desktop\DS_Project_6\.venv\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\hp\Desktop\DS_Project_6\.venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\hp\Desktop\DS_Project_6\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\hp\Desktop\DS_Project_6\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\hp\Desktop\DS_Project_6\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

# Test the PostgreSQL connection

In [8]:
import pandas as pd
from sqlalchemy import create_engine, text

# PostgreSQL connection
engine = create_engine(
    "postgresql+psycopg2://postgres:data123@localhost:5432/smartlogix_db"
)

# Test connection
with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.fetchone())

print("PostgreSQL connection successful!")

('PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit',)
PostgreSQL connection successful!

# Load the main dataset into Python

In [9]:
import os
import pandas as pd

data_path = "../data/orders_analysis_final.csv"

print("File exists:", os.path.exists(data_path))

orders_df = pd.read_csv(data_path)

print("Shape:", orders_df.shape)
print("\nNumber of columns:", len(orders_df.columns))
print("\nFirst 10 columns:")
print(orders_df.columns[:10].tolist())

File exists: True
Shape: (14243, 73)

Number of columns: 73

First 10 columns:
['order_id', 'customer_id', 'product_id', 'quantity', 'order_date', 'origin_hub', 'origin_city', 'destination_city', 'destination_state', 'destination_pincode']

# Create the raw SQL table

In [10]:
# Create a raw/staging table in PostgreSQL

table_name = "orders_raw"

orders_df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Table '{table_name}' created successfully!")

Table 'orders_raw' created successfully!

# Verify the table

In [11]:
from sqlalchemy import text

with engine.connect() as connection:
    count = connection.execute(
        text("SELECT COUNT(*) FROM orders_raw")
    ).scalar()

print("Rows in orders_raw:", count)

Rows in orders_raw: 14243

# Verify the SQL table structure

In [12]:
from sqlalchemy import inspect

inspector = inspect(engine)

columns = inspector.get_columns("orders_raw")

sql_schema = pd.DataFrame({
    "column": [col["name"] for col in columns],
    "sql_type": [str(col["type"]) for col in columns],
    "nullable": [col["nullable"] for col in columns]
})

display(sql_schema)

                              column          sql_type  nullable
0                           order_id              TEXT      True
1                        customer_id              TEXT      True
2                         product_id              TEXT      True
3                           quantity            BIGINT      True
4                         order_date              TEXT      True
..                               ...               ...       ...
68  vehicle_capacity_utilization_pct  DOUBLE PRECISION      True
69                  eta_buffer_hours  DOUBLE PRECISION      True
70       traffic_vehicle_speed_ratio  DOUBLE PRECISION      True
71           weight_exceeds_capacity           BOOLEAN      True
72                    distance_level              TEXT      True

[73 rows x 3 columns]

# Check the keys

In [13]:
# Check uniqueness of the fields that may become primary/foreign keys

key_columns = [
    "order_id",
    "customer_id",
    "product_id",
    "vehicle_id"
]

for col in key_columns:
    total = orders_df[col].notna().sum()
    unique = orders_df[col].nunique(dropna=True)
    duplicates = total - unique

    print(f"\n{col}")
    print(f"  Non-null values : {total}")
    print(f"  Unique values   : {unique}")
    print(f"  Duplicate rows  : {duplicates}")

order_id
  Non-null values : 14243
  Unique values   : 14243
  Duplicate rows  : 0

customer_id
  Non-null values : 14243
  Unique values   : 4707
  Duplicate rows  : 9536

product_id
  Non-null values : 14243
  Unique values   : 1000
  Duplicate rows  : 13243

vehicle_id
  Non-null values : 14243
  Unique values   : 736
  Duplicate rows  : 13507

# Create the customers table

In [14]:
customer_columns = [
    "customer_id",
    "customer_segment",
    "is_prime_member",
    "lifetime_orders",
    "avg_rating_given"
]

customers = (
    orders_df[customer_columns]
    .drop_duplicates(subset=["customer_id"])
    .reset_index(drop=True)
)

print("Customers:", len(customers))
print("Unique customer IDs:", customers["customer_id"].nunique())

display(customers.head())

Customers: 4707
Unique customer IDs: 4707

,customer_id,customer_segment,is_prime_member,lifetime_orders,avg_rating_given
0,CUST-02608,SMB,Yes,118.0,3.2
1,CUST-03997,SMB,No,152.0,2.6
2,CUST-00315,Retail,Yes,46.0,4.6
3,CUST-04067,Business,Yes,68.0,2.4
4,CUST-04320,Business,No,109.0,2.6

# Save customers to PostgreSQL

In [15]:
# Save customers table to PostgreSQL

customers.to_sql(
    "customers",
    engine,
    if_exists="replace",
    index=False
)

print("Customers table created successfully!")

Customers table created successfully!

In [16]:
pd.read_sql(
    "SELECT COUNT(*) AS customer_count FROM customers",
    engine
)

   customer_count
0            4707

# Verify the actual records

In [17]:
pd.read_sql(
    """
    SELECT *
    FROM customers
    LIMIT 5
    """,
    engine
)

,customer_id,customer_segment,is_prime_member,lifetime_orders,avg_rating_given
0,CUST-02608,SMB,Yes,118.0,3.2
1,CUST-03997,SMB,No,152.0,2.6
2,CUST-00315,Retail,Yes,46.0,4.6
3,CUST-04067,Business,Yes,68.0,2.4
4,CUST-04320,Business,No,109.0,2.6

# 2. create order_customer

In [18]:
order_customer_columns = [
    "order_id",
    "customer_id",
    "product_id",
    "quantity",
    "order_date",
    "origin_hub",
    "origin_city",
    "destination_city",
    "destination_state",
    "destination_pincode",
    "delivery_priority",
    "payment_mode",
    "order_value_inr"
]

order_customer = orders_df[order_customer_columns].copy()

print("Rows:", len(order_customer))
print("Columns:", len(order_customer.columns))

display(order_customer.head())

Rows: 14243
Columns: 13

,order_id,customer_id,product_id,quantity,order_date,origin_hub,origin_city,destination_city,destination_state,destination_pincode,delivery_priority,payment_mode,order_value_inr
0,ORD-011545,CUST-02608,PRD-00356,3,2024-05-06 00:00:00+00:00,HUB-LUC,Lucknow,Chandigarh,CH,160017,economy,card,79382.91
1,ORD-008131,CUST-03997,PRD-00200,3,2024-12-27 12:23:00+00:00,HUB-CHE,Chennai,Chennai,TN,600001,express,upi,225352.59
2,ORD-005235,CUST-00315,PRD-00222,1,2024-11-18 12:58:00+00:00,HUB-BEN,Bengaluru,Bengaluru,KA,560001,express,cod,49417.12
3,ORD-001394,CUST-04067,PRD-00155,4,2024-08-29 11:05:00+00:00,HUB-MAD,Madurai,Madurai,TN,625001,standard,prepaid,200811.44
4,ORD-011091,CUST-04320,PRD-00201,4,2025-04-28 21:44:00+00:00,HUB-AHM,Ahmedabad,Guwahati,AS,781001,standard,prepaid,523513.96

# Save order_customer to PostgreSQL

In [19]:
order_customer.to_sql(
    "order_customer",
    engine,
    if_exists="replace",
    index=False
)

print("order_customer table created successfully!")

order_customer table created successfully!

In [20]:
pd.read_sql(
    "SELECT COUNT(*) AS order_count FROM order_customer",
    engine
)

   order_count
0        14243

# Create package_delivery

In [21]:
package_delivery_columns = [
    "order_id",
    "package_weight",
    "is_fragile",
    "is_hazmat",
    "cold_chain_required",
    "promised_eta_hours",
    "actual_delivery_hours",
    "delivery_cost_inr",
    "transport_mode",
    "order_status",
    "delivery_delay_hours",
    "delivery_delay_pct",
    "on_time"
]

package_delivery = orders_df[package_delivery_columns].copy()

print("Rows:", len(package_delivery))
print("Columns:", len(package_delivery.columns))

display(package_delivery.head())

Rows: 14243
Columns: 13

,order_id,package_weight,is_fragile,is_hazmat,cold_chain_required,promised_eta_hours,actual_delivery_hours,delivery_cost_inr,transport_mode,order_status,delivery_delay_hours,delivery_delay_pct,on_time
0,ORD-011545,16.89,False,0,False,22.6,17.72,1682.59,truck,delivered,-4.88,-21.592920,True
1,ORD-008131,87.54,1,0,False,3.2,3.01,188.03,van,delivered,-0.19,-5.937500,True
2,ORD-005235,104.66,0,0,False,1.6,1.29,283.37,van,in transit,-0.31,-19.375000,True
3,ORD-001394,59.44,False,0,False,5.8,5.51,212.46,truck,delivered,-0.29,-5.000000,True
4,ORD-011091,96.92,1,0,False,75.1,57.61,5397.55,truck,delivered,-17.49,-23.288948,True

# Save package_delivery to PostgreSQL

In [22]:
package_delivery.to_sql(
    "package_delivery",
    engine,
    if_exists="replace",
    index=False
)

print("package_delivery table created successfully!")

package_delivery table created successfully!

In [23]:
pd.read_sql(
    "SELECT COUNT(*) AS package_delivery_count FROM package_delivery",
    engine
)

   package_delivery_count
0                   14243

# Create delivery_events

In [24]:
delivery_event_columns = [
    "order_id",
    "delivery_event_count",
    "failed_attempt_count",
    "rto_count",
    "hub_event_count",
    "delivery_log_start",
    "delivery_log_end"
]

delivery_events = orders_df[delivery_event_columns].copy()

print("Rows:", len(delivery_events))
print("Columns:", len(delivery_events.columns))

display(delivery_events.head())

Rows: 14243
Columns: 7

,order_id,delivery_event_count,failed_attempt_count,rto_count,hub_event_count,delivery_log_start,delivery_log_end
0,ORD-011545,5.0,0.0,0.0,1.0,2024-04-19 14:29:37+00:00,2024-04-20 07:20:54+00:00
1,ORD-008131,4.0,0.0,0.0,0.0,2024-11-28 00:00:00+00:00,2024-11-28 19:47:00+00:00
2,ORD-005235,6.0,0.0,0.0,1.0,2024-01-15 17:38:50+00:00,2024-01-15 18:43:00+00:00
3,ORD-001394,4.0,0.0,0.0,0.0,2024-02-11 15:54:47+00:00,2024-11-02 18:29:00+00:00
4,ORD-011091,5.0,0.0,0.0,1.0,2024-09-23 00:00:00+00:00,2024-09-25 02:57:17+00:00

# Save delivery_events to PostgreSQL

In [25]:
delivery_events.to_sql(
    "delivery_events",
    engine,
    if_exists="replace",
    index=False
)

print("delivery_events table created successfully!")

delivery_events table created successfully!

In [26]:
pd.read_sql(
    "SELECT COUNT(*) AS event_count FROM delivery_events",
    engine
)

   event_count
0        14243

# Create location_route

In [27]:
location_route_columns = [
    "order_id",
    "destination_lat",
    "destination_lon",
    "distance_km",
    "distance_level"
]

location_route = orders_df[location_route_columns].copy()

print("Rows:", len(location_route))
print("Columns:", len(location_route.columns))

display(location_route.head())

Rows: 14243
Columns: 5

     order_id  destination_lat  destination_lon  distance_km distance_level
0  ORD-011545        30.764098        76.766130       596.23      Very Long
1  ORD-008131        13.009263        80.390385        15.32     Very Short
2  ORD-005235        12.880754        77.535122        11.98     Very Short
3  ORD-001394         9.940250        78.145166         3.24     Very Short
4  ORD-011091        26.101207        91.694804      1962.16      Very Long

# Save location_route to PostgreSQL

In [28]:
location_route.to_sql(
    "location_route",
    engine,
    if_exists="replace",
    index=False
)

print("location_route table created successfully!")

location_route table created successfully!

In [29]:
pd.read_sql(
    "SELECT COUNT(*) AS route_count FROM location_route",
    engine
)

   route_count
0        14243

# Create traffic_weather

In [30]:
traffic_weather_columns = [
    "order_id",
    "weather_condition_at_dest",
    "traffic_date",
    "traffic_hour",
    "city_x",
    "hour_of_day",
    "congestion_index",
    "traffic_avg_speed_kmph",
    "incident_reported",
    "road_closure",
    "weather_date",
    "weather_city",
    "humidity_pct",
    "precipitation_mm",
    "wind_speed_kmph",
    "visibility_km",
    "temp_celsius",
    "storm_alert",
    "condition"
]

traffic_weather = orders_df[traffic_weather_columns].copy()

print("Rows:", len(traffic_weather))
print("Columns:", len(traffic_weather.columns))

display(traffic_weather.head())

Rows: 14243
Columns: 19

,order_id,weather_condition_at_dest,traffic_date,traffic_hour,city_x,hour_of_day,congestion_index,traffic_avg_speed_kmph,incident_reported,road_closure,weather_date,weather_city,humidity_pct,precipitation_mm,wind_speed_kmph,visibility_km,temp_celsius,storm_alert,condition
0,ORD-011545,cloudy,2024-05-06 00:00:00+00:00,0,Ahmedabad,13.0,0.552,30.5,False,False,2024-05-06 00:00:00+00:00,Chandigarh,41.0,1.8,32.9,5.4,28.000000,False,Cloudy
1,ORD-008131,fog,2024-12-27 00:00:00+00:00,12,Ahmedabad,13.0,0.552,30.5,False,False,2024-12-27 00:00:00+00:00,Chennai,39.0,0.7,43.0,6.7,25.900000,False,Clear
2,ORD-005235,clear,2024-11-18 00:00:00+00:00,12,Ahmedabad,13.0,0.552,30.5,False,False,2024-11-18 00:00:00+00:00,Bengaluru,93.0,0.8,34.4,6.9,26.333333,False,Cloudy
3,ORD-001394,rain,2024-08-29 00:00:00+00:00,11,Ahmedabad,13.0,0.552,30.5,False,False,2024-08-29 00:00:00+00:00,Madurai,56.0,0.2,34.2,9.5,26.333333,False,Clear
4,ORD-011091,heavy rain,2025-04-28 00:00:00+00:00,21,Ahmedabad,13.0,0.552,30.5,False,False,2025-04-28 00:00:00+00:00,Guwahati,86.0,19.8,32.3,8.8,30.800000,False,Rain

# Save traffic_weather to PostgreSQL

In [31]:
traffic_weather.to_sql(
    "traffic_weather",
    engine,
    if_exists="replace",
    index=False
)

print("traffic_weather table created successfully!")

traffic_weather table created successfully!

In [32]:
pd.read_sql(
    "SELECT COUNT(*) AS traffic_weather_count FROM traffic_weather",
    engine
)

   traffic_weather_count
0                  14243

# Create vehicle_fleet

In [33]:
vehicle_fleet_columns = [
    "vehicle_id",
    "vehicle_type",
    "capacity_kg",
    "max_range_km",
    "vehicle_avg_speed_kmph",
    "fleet_status",
    "ownership"
]

vehicle_fleet = orders_df[vehicle_fleet_columns].drop_duplicates(
    subset=["vehicle_id"]
).copy()

print("Rows:", len(vehicle_fleet))
print("Columns:", len(vehicle_fleet.columns))

display(vehicle_fleet.head())

Rows: 736
Columns: 7

,vehicle_id,vehicle_type,capacity_kg,max_range_km,vehicle_avg_speed_kmph,fleet_status,ownership
0,VEH-0698,Truck,12270.0,1634.5,52.0,Active,Owned
1,VEH-0478,Van,870.1,346.5,45.0,Active,Owned
2,VEH-0524,Van,738.2,311.8,42.0,Active,3PL Partner
3,VEH-0594,Truck,15403.4,1991.3,56.0,Active,Leased
4,VEH-0669,Truck,9335.1,1126.1,46.0,Retired,Owned

# Fix vehicle_fleet

In [34]:
vehicle_fleet = vehicle_fleet[
    vehicle_fleet["vehicle_id"].notna()
].copy()

print("Rows after removing missing vehicle_id:", len(vehicle_fleet))
print("Unique vehicle IDs:", vehicle_fleet["vehicle_id"].nunique())

display(vehicle_fleet.head())

Rows after removing missing vehicle_id: 736
Unique vehicle IDs: 736

,vehicle_id,vehicle_type,capacity_kg,max_range_km,vehicle_avg_speed_kmph,fleet_status,ownership
0,VEH-0698,Truck,12270.0,1634.5,52.0,Active,Owned
1,VEH-0478,Van,870.1,346.5,45.0,Active,Owned
2,VEH-0524,Van,738.2,311.8,42.0,Active,3PL Partner
3,VEH-0594,Truck,15403.4,1991.3,56.0,Active,Leased
4,VEH-0669,Truck,9335.1,1126.1,46.0,Retired,Owned

# Save vehicle_fleet to PostgreSQL

In [35]:
vehicle_fleet.to_sql(
    "vehicle_fleet",
    engine,
    if_exists="replace",
    index=False
)

print("vehicle_fleet table created successfully!")

vehicle_fleet table created successfully!

In [36]:
pd.read_sql(
    "SELECT COUNT(*) AS vehicle_count FROM vehicle_fleet",
    engine
)

   vehicle_count
0            736

# Analytics

In [37]:
analytics_columns = [
    "order_id",
    "distance_per_delivery_hour",
    "vehicle_capacity_utilization_pct",
    "eta_buffer_hours",
    "traffic_vehicle_speed_ratio",
    "weight_exceeds_capacity"
]

analytics = orders_df[analytics_columns].copy()

print("Rows:", len(analytics))
print("Columns:", len(analytics.columns))

display(analytics.head())

Rows: 14243
Columns: 6

,order_id,distance_per_delivery_hour,vehicle_capacity_utilization_pct,eta_buffer_hours,traffic_vehicle_speed_ratio,weight_exceeds_capacity
0,ORD-011545,33.647291,0.137653,4.88,0.609434,False
1,ORD-008131,5.089701,10.060913,0.19,0.609434,False
2,ORD-005235,9.286822,14.177730,0.31,0.609434,False
3,ORD-001394,0.588022,0.385889,0.29,0.609434,False
4,ORD-011091,34.059365,1.038232,17.49,0.609434,False

# Save analytics to PostgreSQL

In [38]:
analytics.to_sql(
    "analytics",
    engine,
    if_exists="replace",
    index=False
)

print("analytics table created successfully!")

analytics table created successfully!

In [39]:
pd.read_sql(
    "SELECT COUNT(*) AS analytics_count FROM analytics",
    engine
)

   analytics_count
0            14243

# Final SQL validation

In [40]:
tables = [
    "orders_raw",
    "customers",
    "order_customer",
    "package_delivery",
    "delivery_events",
    "location_route",
    "traffic_weather",
    "vehicle_fleet",
    "analytics"
]

table_counts = []

for table in tables:
    count = pd.read_sql(
        f"SELECT COUNT(*) AS row_count FROM {table}",
        engine
    ).iloc[0, 0]

    table_counts.append({
        "table": table,
        "row_count": count
    })

table_counts_df = pd.DataFrame(table_counts)

display(table_counts_df)

              table  row_count
0        orders_raw      14243
1         customers       4707
2    order_customer      14243
3  package_delivery      14243
4   delivery_events      14243
5    location_route      14243
6   traffic_weather      14243
7     vehicle_fleet        736
8         analytics      14243