# Install & import libraries

In [1]:
import pandas as pd
import numpy as np
import re

# Connect PostgreSQL

In [2]:
from sqlalchemy import create_engine, text

DB_USER = "postgres"
DB_PASSWORD = "data123"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "smartlogix_db"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{"data123"}@{DB_HOST}:{"5432"}/{"smartlogix_db"}"
)

with engine.connect() as connection:
    result = connection.execute(text("SELECT 1"))
    print("PostgreSQL connection successful!")

PostgreSQL connection successful!

In [3]:
from sqlalchemy import create_engine, text

DB_URL = "postgresql+psycopg2://postgres:data123@localhost:5432/smartlogix_db"

engine = create_engine(DB_URL)

connection = engine.connect()

print("PostgreSQL connection successful!")

PostgreSQL connection successful!

# Verify our actual data

In [4]:
query = """
SELECT
    order_id,
    package_weight,
    vehicle_type,
    capacity_kg,
    distance_km,
    max_range_km,
    weight_exceeds_capacity
FROM orders_raw
LIMIT 10
"""

df = pd.read_sql(query, engine)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df)

Shape: (10, 7)

Columns:
['order_id', 'package_weight', 'vehicle_type', 'capacity_kg', 'distance_km', 'max_range_km', 'weight_exceeds_capacity']

,order_id,package_weight,vehicle_type,capacity_kg,distance_km,max_range_km,weight_exceeds_capacity
0,ORD-011545,16.89,Truck,12270.0,596.23,1634.5,False
1,ORD-008131,87.54,Van,870.1,15.32,346.5,False
2,ORD-005235,104.66,Van,738.2,11.98,311.8,False
3,ORD-001394,59.44,Truck,15403.4,3.24,1991.3,False
4,ORD-011091,96.92,Truck,9335.1,1962.16,1126.1,False
5,ORD-005379,1.54,Drone,2.0,5.01,15.2,False
6,ORD-011641,6.08,Air Cargo,43580.2,1274.31,5933.8,False
7,ORD-006654,11.58,Bike,15.2,6.70,89.6,False
8,ORD-012807,0.59,Air Cargo,14076.3,1998.40,4781.7,False
9,ORD-002865,2.66,Drone,4.5,3.45,-8.6,False

# Verify the drone data

In [5]:
drone_df = df = pd.read_sql(
    """
    SELECT
        order_id,
        package_weight,
        vehicle_type,
        capacity_kg,
        distance_km,
        max_range_km,
        weight_exceeds_capacity
    FROM orders_raw
    WHERE LOWER(vehicle_type) = 'drone'
    """,
    engine
)

print("Total drone routes:", len(drone_df))

display(drone_df.head(10))

Total drone routes: 759

,order_id,package_weight,vehicle_type,capacity_kg,distance_km,max_range_km,weight_exceeds_capacity
0,ORD-005379,1.54,Drone,2.0,5.01,15.2,False
1,ORD-002865,2.66,Drone,4.5,3.45,-8.6,False
2,ORD-014884,2.39,Drone,4.8,10.60,14.8,False
3,ORD-003137,2.12,Drone,5.4,2.78,23.6,False
4,ORD-007665,4.26,Drone,6.0,141.47,8.2,False
5,ORD-002549,4.64,Drone,1.9,9.54,25.5,True
6,ORD-000415,2.91,Drone,3.6,1.68,8.9,False
7,ORD-008479,2.60,Drone,2.8,2.07,11.5,False
8,ORD-011188,1.81,Drone,4.4,8.99,14.7,False
9,ORD-004441,0.64,Drone,5.3,1.44,19.4,False

# Create the verified retrieval function

In [6]:
# RAG retrieval from PostgreSQL

def retrieve_routes(question):

    q = question.lower()

    # Q1: Feasible drone routes
    if "feasible" in q:
        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND package_weight <= capacity_kg
          AND distance_km <= max_range_km
        """

    # Q2: Routes exceeding capacity
    elif "exceed" in q and "capacity" in q:
        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND package_weight > capacity_kg
        """

    # Q3: Routes within maximum range
    elif "within" in q and "range" in q:
        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND distance_km <= max_range_km
        """

    # Q4/Q5: Specific order
    else:
        order_match = re.search(r'ORD-\d+', question.upper())

        if not order_match:
            return pd.DataFrame()

        order_id = order_match.group(0)

        sql = f"""
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE order_id = '{order_id}'
        """

    return pd.read_sql(sql, engine)

# Test retrieval WITHOUT LLM

In [7]:
# Test RAG retrieval

test_questions = [
    "Which drone routes are feasible based on vehicle capacity and maximum range?",
    "Which drone routes exceed their vehicle capacity?",
    "Which retrieved drone routes are within their maximum range?",
    "What is the package weight and vehicle capacity for ORD-013848?",
    "What is the maximum range of the vehicle assigned to ORD-007163?"
]

for i, question in enumerate(test_questions, 1):

    print("=" * 70)
    print(f"QUESTION {i}")
    print(question)

    results = retrieve_routes(question)

    print("Retrieved rows:", len(results))

    display(results)

======================================================================
QUESTION 1
Which drone routes are feasible based on vehicle capacity and maximum range?
Retrieved rows: 411

,order_id,package_weight,vehicle_type,capacity_kg,distance_km,max_range_km,weight_exceeds_capacity
0,ORD-005379,1.54,Drone,2.0,5.01,15.2,False
1,ORD-014884,2.39,Drone,4.8,10.60,14.8,False
2,ORD-003137,2.12,Drone,5.4,2.78,23.6,False
3,ORD-000415,2.91,Drone,3.6,1.68,8.9,False
4,ORD-008479,2.60,Drone,2.8,2.07,11.5,False
...,...,...,...,...,...,...,...
406,ORD-004892,1.58,Drone,5.7,1.50,23.3,False
407,ORD-010701,2.00,Drone,6.0,3.80,18.6,False
408,ORD-005388,3.48,Drone,3.8,0.57,19.2,False
409,ORD-008768,1.06,Drone,3.6,1.95,19.1,False
410,ORD-008813,0.88,Drone,5.3,4.61,20.2,False

======================================================================
QUESTION 2
Which drone routes exceed their vehicle capacity?
Retrieved rows: 288

,order_id,package_weight,vehicle_type,capacity_kg,distance_km,max_range_km,weight_exceeds_capacity
0,ORD-002549,4.64,Drone,1.9,9.54,25.5,True
1,ORD-012343,10.59,Drone,3.8,7.33,19.2,True
2,ORD-000680,3.14,Drone,1.0,2.73,13.9,True
3,ORD-009988,3.80,Drone,2.8,5.86,11.5,True
4,ORD-011103,26.28,Drone,4.8,342.20,26.4,True
...,...,...,...,...,...,...,...
283,ORD-010396,22.44,Drone,1.6,6.61,10.2,True
284,ORD-001138,15477.28,Drone,5.6,1044.11,21.1,True
285,ORD-000124,11913.03,Drone,1.4,4.58,23.9,True
286,ORD-005238,355.72,Drone,2.6,15.68,13.5,True
287,ORD-006315,3.81,Drone,3.8,9.61,19.2,True

======================================================================
QUESTION 3
Which retrieved drone routes are within their maximum range?
Retrieved rows: 602

,order_id,package_weight,vehicle_type,capacity_kg,distance_km,max_range_km,weight_exceeds_capacity
0,ORD-005379,1.54,Drone,2.0,5.01,15.2,False
1,ORD-014884,2.39,Drone,4.8,10.60,14.8,False
2,ORD-003137,2.12,Drone,5.4,2.78,23.6,False
3,ORD-002549,4.64,Drone,1.9,9.54,25.5,True
4,ORD-000415,2.91,Drone,3.6,1.68,8.9,False
...,...,...,...,...,...,...,...
597,ORD-000124,11913.03,Drone,1.4,4.58,23.9,True
598,ORD-005388,3.48,Drone,3.8,0.57,19.2,False
599,ORD-008768,1.06,Drone,3.6,1.95,19.1,False
600,ORD-006315,3.81,Drone,3.8,9.61,19.2,True
601,ORD-008813,0.88,Drone,5.3,4.61,20.2,False

======================================================================
QUESTION 4
What is the package weight and vehicle capacity for ORD-013848?
Retrieved rows: 1

,order_id,package_weight,vehicle_type,capacity_kg,distance_km,max_range_km,weight_exceeds_capacity
0,ORD-013848,1.84,Drone,5.7,8.51,20.8,False

======================================================================
QUESTION 5
What is the maximum range of the vehicle assigned to ORD-007163?
Retrieved rows: 1

,order_id,package_weight,vehicle_type,capacity_kg,distance_km,max_range_km,weight_exceeds_capacity
0,ORD-007163,3.12,Drone,5.2,11.98,17.9,False

In [8]:
def retrieve_drone_routes(question):

    q = question.lower()

    if "feasible" in q:
        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND package_weight <= capacity_kg
          AND distance_km <= max_range_km
        """

    elif "exceed their vehicle capacity" in q:
        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND package_weight > capacity_kg
        """

    elif "within their maximum range" in q:
        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND distance_km <= max_range_km
        """

    else:
        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE order_id = %s
        """

    return pd.read_sql(sql, connection)

# Run retrieve_drone_routes() cell

In [9]:
def format_retrieved_context(df):
    if df.empty:
        return "No relevant logistics information was found."

    rows = []

    for _, row in df.iterrows():
        rows.append(
            f"Order ID: {row['order_id']}\n"
            f"Vehicle type: {row['vehicle_type']}\n"
            f"Package weight: {row['package_weight']} kg\n"
            f"Vehicle capacity: {row['capacity_kg']} kg\n"
            f"Distance: {row['distance_km']} km\n"
            f"Maximum range: {row['max_range_km']} km\n"
            f"Weight exceeds capacity: {row['weight_exceeds_capacity']}"
        )

    return "\n\n".join(rows)

In [10]:
def format_context(df):
    if df.empty:
        return "No verified records found."

    records = []

    for _, row in df.iterrows():
        records.append(
            f"Order ID: {row['order_id']}\n"
            f"Vehicle Type: {row['vehicle_type']}\n"
            f"Package Weight: {row['package_weight']} kg\n"
            f"Vehicle Capacity: {row['capacity_kg']} kg\n"
            f"Distance: {row['distance_km']} km\n"
            f"Maximum Range: {row['max_range_km']} km\n"
            f"Weight Exceeds Capacity: {row['weight_exceeds_capacity']}"
        )

    return "\n\n".join(records)

# Test retrieval + context

In [11]:
question = "Which drone routes are within their maximum range?"

retrieved = retrieve_drone_routes(question)

print("Retrieved rows:", len(retrieved))
print()

context = format_context(retrieved)

print(context[:5000])

Retrieved rows: 602

Order ID: ORD-005379
Vehicle Type: Drone
Package Weight: 1.54 kg
Vehicle Capacity: 2.0 kg
Distance: 5.01 km
Maximum Range: 15.2 km
Weight Exceeds Capacity: False

Order ID: ORD-014884
Vehicle Type: Drone
Package Weight: 2.39 kg
Vehicle Capacity: 4.8 kg
Distance: 10.6 km
Maximum Range: 14.8 km
Weight Exceeds Capacity: False

Order ID: ORD-003137
Vehicle Type: Drone
Package Weight: 2.12 kg
Vehicle Capacity: 5.4 kg
Distance: 2.78 km
Maximum Range: 23.6 km
Weight Exceeds Capacity: False

Order ID: ORD-002549
Vehicle Type: Drone
Package Weight: 4.64 kg
Vehicle Capacity: 1.9 kg
Distance: 9.54 km
Maximum Range: 25.5 km
Weight Exceeds Capacity: True

Order ID: ORD-000415
Vehicle Type: Drone
Package Weight: 2.91 kg
Vehicle Capacity: 3.6 kg
Distance: 1.68 km
Maximum Range: 8.9 km
Weight Exceeds Capacity: False

Order ID: ORD-008479
Vehicle Type: Drone
Package Weight: 2.6 kg
Vehicle Capacity: 2.8 kg
Distance: 2.07 km
Maximum Range: 11.5 km
Weight Exceeds Capacity: False

Order ID: ORD-011188
Vehicle Type: Drone
Package Weight: 1.81 kg
Vehicle Capacity: 4.4 kg
Distance: 8.99 km
Maximum Range: 14.7 km
Weight Exceeds Capacity: False

Order ID: ORD-004441
Vehicle Type: Drone
Package Weight: 0.64 kg
Vehicle Capacity: 5.3 kg
Distance: 1.44 km
Maximum Range: 19.4 km
Weight Exceeds Capacity: False

Order ID: ORD-007387
Vehicle Type: Drone
Package Weight: 1.38 kg
Vehicle Capacity: 5.6 kg
Distance: 4.39 km
Maximum Range: 21.1 km
Weight Exceeds Capacity: False

Order ID: ORD-012343
Vehicle Type: Drone
Package Weight: 10.59 kg
Vehicle Capacity: 3.8 kg
Distance: 7.33 km
Maximum Range: 19.2 km
Weight Exceeds Capacity: True

Order ID: ORD-012665
Vehicle Type: Drone
Package Weight: 1.67 kg
Vehicle Capacity: 4.8 kg
Distance: 5.89 km
Maximum Range: 26.5 km
Weight Exceeds Capacity: False

Order ID: ORD-000680
Vehicle Type: Drone
Package Weight: 3.14 kg
Vehicle Capacity: 1.0 kg
Distance: 2.73 km
Maximum Range: 13.9 km
Weight Exceeds Capacity: True

Order ID: ORD-009988
Vehicle Type: Drone
Package Weight: 3.8 kg
Vehicle Capacity: 2.8 kg
Distance: 5.86 km
Maximum Range: 11.5 km
Weight Exceeds Capacity: True

Order ID: ORD-012992
Vehicle Type: Drone
Package Weight: 1.76 kg
Vehicle Capacity: 3.0 kg
Distance: 8.87 km
Maximum Range: 29.8 km
Weight Exceeds Capacity: False

Order ID: ORD-009872
Vehicle Type: Drone
Package Weight: 2.07 kg
Vehicle Capacity: 5.8 kg
Distance: 7.15 km
Maximum Range: 22.7 km
Weight Exceeds Capacity: False

Order ID: ORD-013759
Vehicle Type: Drone
Package Weight: 5.0 kg
Vehicle Capacity: 1.5 kg
Distance: 9.18 km
Maximum Range: 9.5 km
Weight Exceeds Capacity: True

Order ID: ORD-012142
Vehicle Type: Drone
Package Weight: 3.06 kg
Vehicle Capacity: 6.0 kg
Distance: 9.61 km
Maximum Range: 18.6 km
Weight Exceeds Capacity: False

Order ID: ORD-013768
Vehicle Type: Drone
Package Weight: 0.62 kg
Vehicle Capacity: 5.9 kg
Distance: 8.06 km
Maximum Range: 24.9 km
Weight Exceeds Capacity: False

Order ID: ORD-008918
Vehicle Type: Drone
Package Weight: 1.38 kg
Vehicle Capacity: 2.6 kg
Distance: 4.95 km
Maximum Range: 13.5 km
Weight Exceeds Capacity: False

Order ID: ORD-008532
Vehicle Type: Drone
Package Weight: 2.88 kg
Vehicle Capacity: 4.4 kg
Distance: 7.27 km
Maximum Range: 14.7 km
Weight Exceeds Capacity: False

Order ID: ORD-007438
Vehicle Type: Drone
Package Weight: 2.67 kg
Vehicle Capacity: 4.7 kg
Distance: 11.02 km
Maximum Range: 15.9 km
Weight Exceeds Capacity: False

Order ID: ORD-013850
Vehicle Type: Drone
Package Weight: 2.74 kg
Vehicle Capacity: 5.6 kg
Distance: 3.67 km
Maximum Range: 8.0 km
Weight Exceeds Capacity: False

Order ID: ORD-001348
Vehicle Type: Drone
Package Weight: 2.08 kg
Vehicle Capacity: 4.3 kg
Distance: 8.21 km
Maximum Range: 13.6 km
Weight Exceeds Capacity: False

Order ID: ORD-013534
Vehicle Type: Drone
Package Weight: 6.3 kg
Vehicle Capacity: 4.3 kg
Distance: 12.21 km
Maximum Range: 29.0 km
Weight Exceeds Capacity: True

Order ID: ORD-013888
Vehicle Type: Drone
Package Weight: 0.58 kg
Vehicle Capacity: 5.6 kg
Distance: 6.88 km
Maximum Range: 27.8 km
Weight Exceeds Capacity: False

Order ID: ORD-006961
Vehicle Type: Drone
Package Weight: 2.24 kg
Vehicle Capacity: 3.0 kg
Distance: 10.92 km
Maximum Range: 29.8 km
Weight Exceeds Capacity: False

Order ID: ORD-014531
Vehicle Type: Drone
Package Weight: 3.48 kg
Vehicle Capacity: 2.9 kg
Distance: 4.04 km
Maximum Range: 26.6 km
Weight Exceeds Capacity: True

Order ID: ORD-012792
Vehicle Type: Drone
Package Weight: 0.73 kg
Vehicle Capacity: 1.9 kg
Distance: 1.51 km
Maximum Range: 29.6 km
Weight Exceeds Capacity: False

Order ID: ORD-001245
Vehicle Type: Drone
Package Weight: 10.59 kg
Vehicle Capacity: 1.8 kg
Distance: 5.57 km
Maximum Range: 19.9 km
Weight Exceeds Capacity: True

Order ID: ORD-004237
Vehicle Type: Drone
Package Weight: 3.26 kg
Vehicle Capacity: 3.6 kg
Distance: 6.84 km
Maximum Range: 24.6 km
Weight Exceeds Capacity: False

Order ID: ORD-008067
Vehicle Type: Drone
Package Weight: 1.81 kg
Vehicle Capacity: 2.5 kg
Distance: 3.61 km
Maximum Rang

# Test retrieval + formatting

In [12]:
question = "Which drone routes are within their maximum range?"

retrieved = retrieve_drone_routes(question)

print("Retrieved rows:", len(retrieved))
print()
print(format_retrieved_context(retrieved.head(10)))

Retrieved rows: 602

Order ID: ORD-005379
Vehicle type: Drone
Package weight: 1.54 kg
Vehicle capacity: 2.0 kg
Distance: 5.01 km
Maximum range: 15.2 km
Weight exceeds capacity: False

Order ID: ORD-014884
Vehicle type: Drone
Package weight: 2.39 kg
Vehicle capacity: 4.8 kg
Distance: 10.6 km
Maximum range: 14.8 km
Weight exceeds capacity: False

Order ID: ORD-003137
Vehicle type: Drone
Package weight: 2.12 kg
Vehicle capacity: 5.4 kg
Distance: 2.78 km
Maximum range: 23.6 km
Weight exceeds capacity: False

Order ID: ORD-002549
Vehicle type: Drone
Package weight: 4.64 kg
Vehicle capacity: 1.9 kg
Distance: 9.54 km
Maximum range: 25.5 km
Weight exceeds capacity: True

Order ID: ORD-000415
Vehicle type: Drone
Package weight: 2.91 kg
Vehicle capacity: 3.6 kg
Distance: 1.68 km
Maximum range: 8.9 km
Weight exceeds capacity: False

Order ID: ORD-008479
Vehicle type: Drone
Package weight: 2.6 kg
Vehicle capacity: 2.8 kg
Distance: 2.07 km
Maximum range: 11.5 km
Weight exceeds capacity: False

Order ID: ORD-011188
Vehicle type: Drone
Package weight: 1.81 kg
Vehicle capacity: 4.4 kg
Distance: 8.99 km
Maximum range: 14.7 km
Weight exceeds capacity: False

Order ID: ORD-004441
Vehicle type: Drone
Package weight: 0.64 kg
Vehicle capacity: 5.3 kg
Distance: 1.44 km
Maximum range: 19.4 km
Weight exceeds capacity: False

Order ID: ORD-007387
Vehicle type: Drone
Package weight: 1.38 kg
Vehicle capacity: 5.6 kg
Distance: 4.39 km
Maximum range: 21.1 km
Weight exceeds capacity: False

Order ID: ORD-012343
Vehicle type: Drone
Package weight: 10.59 kg
Vehicle capacity: 3.8 kg
Distance: 7.33 km
Maximum range: 19.2 km
Weight exceeds capacity: True

# Test the answer generation

In [13]:
def generate_answer_without_llm(question, df):

    if df.empty:
        return "No relevant logistics information was found."

    q = question.lower()

    # Q1
    if "feasible" in q:
        orders = df["order_id"].tolist()

        return (
            "Based on vehicle capacity and maximum range, "
            "the feasible drone routes are:\n\n"
            + "\n".join(f"- {order_id}" for order_id in orders)
        )

    # Q2
    elif "exceed their vehicle capacity" in q:
        orders = df["order_id"].tolist()

        if not orders:
            return "No drone routes exceed their vehicle capacity."

        return (
            "The drone routes that exceed their vehicle capacity are:\n\n"
            + "\n".join(f"- {order_id}" for order_id in orders)
        )

    # Q3
    elif "within their maximum range" in q:
        orders = df["order_id"].tolist()

        return (
            "The drone routes within their maximum range are:\n\n"
            + "\n".join(f"- {order_id}" for order_id in orders)
        )

    # Q4
    elif "package weight" in q and "capacity" in q:
        row = df.iloc[0]

        return (
            f"For {row['order_id']}, the package weight is "
            f"{row['package_weight']} kg and the vehicle capacity is "
            f"{row['capacity_kg']} kg."
        )

    # Q5
    elif "maximum range" in q:
        row = df.iloc[0]

        return (
            f"The maximum range of the vehicle assigned to "
            f"{row['order_id']} is {row['max_range_km']} km."
        )

    return "The requested information is not available."

In [14]:
question = "Which retrieved drone routes are within their maximum range?"

retrieved = retrieve_drone_routes(question)

answer = generate_answer_without_llm(
    question,
    retrieved
)

print("QUESTION:")
print(question)

print("\nANSWER:")
print(answer)

QUESTION:
Which retrieved drone routes are within their maximum range?

ANSWER:
The drone routes within their maximum range are:

- ORD-005379
- ORD-014884
- ORD-003137
- ORD-002549
- ORD-000415
- ORD-008479
- ORD-011188
- ORD-004441
- ORD-007387
- ORD-012343
- ORD-012665
- ORD-000680
- ORD-009988
- ORD-012992
- ORD-009872
- ORD-013759
- ORD-012142
- ORD-013768
- ORD-008918
- ORD-008532
- ORD-007438
- ORD-013850
- ORD-001348
- ORD-013534
- ORD-013888
- ORD-006961
- ORD-014531
- ORD-012792
- ORD-001245
- ORD-004237
- ORD-008067
- ORD-004657
- ORD-011363
- ORD-001297
- ORD-007391
- ORD-000186
- ORD-008998
- ORD-004200
- ORD-014348
- ORD-006065
- ORD-009511
- ORD-011616
- ORD-012625
- ORD-008272
- ORD-005888
- ORD-011323
- ORD-010911
- ORD-009512
- ORD-009848
- ORD-005054
- ORD-003601
- ORD-012859
- ORD-014136
- ORD-000618
- ORD-013702
- ORD-011207
- ORD-009021
- ORD-008528
- ORD-009934
- ORD-014080
- ORD-011297
- ORD-001622
- ORD-011958
- ORD-009918
- ORD-003550
- ORD-002375
- ORD-002595
- ORD-011525
- ORD-010704
- ORD-006171
- ORD-002411
- ORD-004846
- ORD-014314
- ORD-008386
- ORD-000821
- ORD-013211
- ORD-008743
- ORD-005829
- ORD-006293
- ORD-005635
- ORD-013791
- ORD-000943
- ORD-010656
- ORD-007314
- ORD-009266
- ORD-007031
- ORD-010311
- ORD-003709
- ORD-010443
- ORD-012484
- ORD-001708
- ORD-012172
- ORD-002098
- ORD-010173
- ORD-007627
- ORD-004790
- ORD-005127
- ORD-006254
- ORD-006343
- ORD-006033
- ORD-003707
- ORD-013831
- ORD-012121
- ORD-010906
- ORD-010772
- ORD-008815
- ORD-005441
- ORD-001028
- ORD-007310
- ORD-004921
- ORD-000199
- ORD-008976
- ORD-005972
- ORD-007187
- ORD-004772
- ORD-008589
- ORD-012715
- ORD-010847
- ORD-002867
- ORD-012593
- ORD-014740
- ORD-003921
- ORD-011513
- ORD-014553
- ORD-011962
- ORD-007472
- ORD-014835
- ORD-005692
- ORD-012272
- ORD-007127
- ORD-006393
- ORD-010300
- ORD-014429
- ORD-007659
- ORD-008049
- ORD-004543
- ORD-002136
- ORD-002758
- ORD-009577
- ORD-001071
- ORD-003211
- ORD-006163
- ORD-001938
- ORD-009378
- ORD-003993
- ORD-014191
- ORD-008123
- ORD-011763
- ORD-004531
- ORD-008022
- ORD-008681
- ORD-008966
- ORD-002550
- ORD-007284
- ORD-014555
- ORD-013310
- ORD-012145
- ORD-002444
- ORD-014099
- ORD-009352
- ORD-007938
- ORD-003842
- ORD-007390
- ORD-007325
- ORD-012127
- ORD-008263
- ORD-004526
- ORD-008916
- ORD-009810
- ORD-009165
- ORD-002308
- ORD-008452
- ORD-014730
- ORD-005060
- ORD-001482
- ORD-004648
- ORD-011035
- ORD-011237
- ORD-003309
- ORD-013621
- ORD-001198
- ORD-009724
- ORD-000303
- ORD-011038
- ORD-009059
- ORD-002851
- ORD-005700
- ORD-009943
- ORD-005345
- ORD-013848
- ORD-006282
- ORD-006462
- ORD-008618
- ORD-006883
- ORD-000901
- ORD-012978
- ORD-000133
- ORD-010014
- ORD-008865
- ORD-004279
- ORD-000449
- ORD-000256
- ORD-002964
- ORD-003887
- ORD-012802
- ORD-009160
- ORD-003000
- ORD-001937
- ORD-007240
- ORD-002976
- ORD-005298
- ORD-003084
- ORD-007937
- ORD-010402
- ORD-014883
- ORD-004917
- ORD-006259
- ORD-007646
- ORD-007917
- ORD-005134
- ORD-011532
- ORD-000673
- ORD-005178
- ORD-006511
- ORD-008679
- ORD-014799
- ORD-001975
- ORD-008212
- ORD-012241
- ORD-009601
- ORD-002781
- ORD-004555
- ORD-014258
- ORD-007163
- ORD-010146
- ORD-004004
- ORD-011437
- ORD-014095
- ORD-004896
- ORD-013573
- ORD-006552
- ORD-013656
- ORD-002589
- ORD-014537
- ORD-014163
- ORD-009784
- ORD-010339
- ORD-010709
- ORD-008631
- ORD-011776
- ORD-006630
- ORD-011166
- ORD-012191
- ORD-014784
- ORD-006720
- ORD-009366
- ORD-004169
- ORD-003946
- ORD-003871
- ORD-004693
- ORD-005154
- ORD-006747
- ORD-011284
- ORD-011606
- ORD-000127
- ORD-004552
- ORD-005598
- ORD-007046
- ORD-007277
- ORD-008808
- ORD-013510
- ORD-001667
- ORD-010119
- ORD-012831
- ORD-006541
- ORD-011205
- ORD-000481
- ORD-001719
- ORD-012275
- ORD-001048
- ORD-014869
- ORD-012534
- ORD-004901
- ORD-008748
- ORD-011286
- ORD-007538
- ORD-002523
- ORD-014231
- ORD-005796
- ORD-004945
- ORD-002428
- ORD-008437
- ORD-013262
- ORD-014458
- ORD-012452
- ORD-009916
- ORD-014166
- ORD-003172
- ORD-000350
- ORD-008121
- ORD-006827
- ORD-003727
- ORD-002386
- ORD-008959
- ORD-005946
- ORD-010142
- ORD-007988
- ORD-012940
- ORD-005353
- ORD-004316
- ORD-014805
- ORD-003944
- ORD-001490
- ORD-013636
- ORD-000262
- ORD-006240
- ORD-007453
- ORD-004411
- ORD-014355
- ORD-007925
- ORD-010687
- ORD-005690
- ORD-009274
- ORD-009287
- ORD-004676
- ORD-010850
- ORD-006316
- ORD-014651
- ORD-014575
- ORD-010840
- ORD-014065
- ORD-002189
- ORD-009299
- ORD-011335
- ORD-012557
- ORD-010954
- ORD-010434
- ORD-002118
- ORD-006371
- ORD-011899
- ORD-002194
- ORD-011507
- ORD-003776
- ORD-001701
- ORD-006880
- ORD-009666
- ORD-004553
- ORD-006619
- ORD-014139
- ORD-005907
- ORD-007717
- ORD-002247
- ORD-012627
- ORD-002597
- ORD-014435
- ORD-011936
- ORD-002827
- ORD-002322
- ORD-009189
- ORD-011538
- ORD-008615
- ORD-011093
- ORD-006771
- ORD-014532
- ORD-007813
- ORD-003828
- ORD-008181
- ORD-012009
- ORD-010338
- ORD-013795
- ORD-003242
- ORD-002264
- ORD-000183
- ORD-013998
- ORD-013027
- ORD-010144
- ORD-014257
- ORD-004912
- ORD-004962
- ORD-014685
- ORD-009659
- ORD-000016
- ORD-014847
- ORD-014183
- ORD-006772
- ORD-006085
- ORD-013284
- ORD-004637
- ORD-010029
- ORD-014316
- ORD-006916
- ORD-008281
- ORD-009341
- ORD-005283
- ORD-014558
- ORD-005671
- ORD-014779
- ORD-002349
- ORD-008644
- ORD-013526
- ORD-001569
- ORD-009485
- ORD-005480
- ORD-000825
- ORD-002520
- ORD-010103
- ORD-007596
- ORD-010759
- ORD-000542
- ORD-014311
- ORD-007784
- ORD-000724
- ORD-014922
- ORD-001827
- ORD-006488
- ORD-001103
- ORD-004439
- ORD-000281
- ORD-006089
- ORD-005645
- ORD-000304
- ORD-014045
- ORD-008971
- ORD-000359
- ORD-010806
- ORD-006157
- ORD-000928
- ORD-012664
- ORD-006560
- ORD-000484
- ORD-011096
- ORD-008222
- ORD-014321
- ORD-005857
- ORD-012126
- ORD-013381
- ORD-004131
- ORD-006035
- ORD-000701
- ORD-011897
- ORD-014978
- ORD-014564
- ORD-005271
- ORD-011457
- ORD-011999
- ORD-000795
- ORD-012311
- ORD-006436
- ORD-009579
- ORD-013987
- ORD-003889
- ORD-007323
- ORD-001984
- ORD-009651
- ORD-007403
- ORD-006348
- ORD-006118
- ORD-014768
- ORD-003569
- ORD-013111
- ORD-009470
- ORD-000046
- ORD-000005
- ORD-011275
- ORD-000704
- ORD-012840
- ORD-007978
- ORD-009407
- ORD-013283
- ORD-011083
- ORD-007157
- ORD-003710
- ORD-005132
- ORD-000881
- ORD-013705
- ORD-010526
- ORD-011148
- ORD-002293
- ORD-012108
- ORD-007380
- ORD-012218
- ORD-011952
- ORD-009236
- ORD-001541
- ORD-014269
- ORD-006046
- ORD-001791
- ORD-007777
- ORD-005113
- ORD-009393
- ORD-008906
- ORD-006864
- ORD-007196
- ORD-001498
- ORD-002315
- ORD-006546
- ORD-014147
- ORD-002423
- ORD-013325
- ORD-010762
- ORD-000607
- ORD-007038
- ORD-012420
- ORD-000696
- ORD-001068
- ORD-007206
- ORD-005881
- ORD-014871
- ORD-003513
- ORD-012945
- ORD-013982
- ORD-014637
- ORD-003750
- ORD-005354
- ORD-000900
- ORD-013913
- ORD-004754
- ORD-012338
- ORD-001177
- ORD-013065
- ORD-014396
- ORD-000480
- ORD-004144
- ORD-008353
- ORD-008059
- ORD-009718
- ORD-013613
- ORD-013363
- ORD-001882
- ORD-003778
- ORD-011350
- ORD-003325
- ORD-008334
- ORD-005292
- ORD-007715
- ORD-000674
- ORD-007243
- ORD-014750
- ORD-001344
- ORD-011634
- ORD-005674
- ORD-000414
- ORD-004324
- ORD-013923
- ORD-009373
- ORD-006242
- ORD-003414
- ORD-005286
- ORD-008389
- ORD-014787
- ORD-003083
- ORD-008070
- ORD-010845
- ORD-007914
- ORD-008078
- ORD-009177
- ORD-014848
- ORD-006754
- ORD-008262
- ORD-012950
- ORD-008623
- ORD-002506
- ORD-007579
- ORD-005260
- ORD-012853
- ORD-013691
- ORD-003123
- ORD-010608
- ORD-002137
- ORD-008812
- ORD-007464
- ORD-003982
- ORD-002760
- ORD-006426
- ORD-014290
- ORD-002872
- ORD-006520
- ORD-004722
- ORD-007267
- ORD-009089
- ORD-009833
- ORD-013448
- ORD-007719
- ORD-013733
- ORD-008471
- ORD-005147
- ORD-008547
- ORD-014539
- ORD-011703
- ORD-010396
- ORD-000874
- ORD-001661
- ORD-013445
- ORD-006187
- ORD-009616
- ORD-004892
- ORD-010701
- ORD-000124
- ORD-005388
- ORD-008768
- ORD-006315
- ORD-008813

In [15]:
def prepare_llm_context(question, retrieved):

    if retrieved.empty:
        return "No verified records found."

    q = question.lower()

    if "within their maximum range" in q:
        return {
            "total_routes": len(retrieved),
            "route_ids": retrieved["order_id"].tolist()
        }

    elif "exceed their vehicle capacity" in q:
        return {
            "total_routes": len(retrieved),
            "route_ids": retrieved["order_id"].tolist()
        }

    elif "feasible" in q:
        return {
            "total_routes": len(retrieved),
            "route_ids": retrieved["order_id"].tolist()
        }

    else:
        return retrieved.to_dict(orient="records")

In [16]:
llm_context = prepare_llm_context(question, retrieved)

print("LLM context prepared successfully.")
print("Total routes:", llm_context["total_routes"])
print("First 10 routes:", llm_context["route_ids"][:10])

LLM context prepared successfully.
Total routes: 602
First 10 routes: ['ORD-005379', 'ORD-014884', 'ORD-003137', 'ORD-002549', 'ORD-000415', 'ORD-008479', 'ORD-011188', 'ORD-004441', 'ORD-007387', 'ORD-012343']

# Create the LLM prompt

In [17]:
def build_llm_prompt(question, llm_context):

    return f"""
You are a logistics data assistant.

Answer the user's question using ONLY the verified data provided below.

Do not invent order IDs, numbers, or facts.
Do not perform new database queries.
If the information is not available, say:
"The requested information is not available in the verified logistics context."

USER QUESTION:
{question}

VERIFIED DATA:
{llm_context}

Give a concise, direct answer.
"""

# Connect the LLM

In [18]:
import importlib.util

print("Checking local LLM support...")

if importlib.util.find_spec("ollama"):
    print("Ollama package: AVAILABLE")
else:
    print("Ollama package: NOT AVAILABLE")

Checking local LLM support...
Ollama package: NOT AVAILABLE

In [20]:
import requests

response = requests.get("http://localhost:11434/api/tags")

print("Ollama connection successful!")
print(response.json())

Ollama connection successful!
{'models': [{'name': 'deepseek-r1:7b', 'model': 'deepseek-r1:7b', 'modified_at': '2026-07-22T10:19:53.7101294+05:30', 'size': 4683075440, 'digest': '755ced02ce7befdb13b7ca74e1e4d08cddba4986afdb63a480f2c93d3140383f', 'details': {'parent_model': '', 'format': 'gguf', 'family': 'qwen2', 'families': ['qwen2'], 'parameter_size': '7.6B', 'quantization_level': 'Q4_K_M', 'context_length': 131072, 'embedding_length': 3584}, 'capabilities': ['completion', 'thinking']}]}

In [ ]:
import requests

def ask_ollama(prompt):
    response = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": "deepseek-r1:7b",
            "prompt": prompt,
            "stream": False
        }
    )

    response.raise_for_status()
    return response.json()["response"]


test_response = ask_ollama(
    "In one short sentence, say hello and confirm that you are ready."
)

print(test_response)

Hello! I'm ready to help.

# Create the RAG + Ollama answer function

In [ ]:
def generate_rag_answer(question):
    
    # 1. Retrieve verified data from PostgreSQL
    retrieved = retrieve_drone_routes(question)

    # 2. Prepare compact context
    llm_context = prepare_llm_context(question, retrieved)

    # 3. Build the prompt
    prompt = build_llm_prompt(question, llm_context)

    # 4. Ask local LLM
    answer = ask_ollama(prompt)

    return answer

# Test the complete RAG loop

In [ ]:
question = "Which drone routes are within their maximum range?"

answer = generate_rag_answer(question)

print("QUESTION:")
print(question)

print("\nANSWER:")
print(answer)

QUESTION:
Which drone routes are within their maximum range?

ANSWER:
There are 70 ORD codes listed in the provided data. If you need further assistance or clarification, please provide more details about what you're seeking.

# Make the LLM output structured

In [ ]:
def build_llm_prompt(question, llm_context):

    return f"""
You are answering a logistics database question.

IMPORTANT RULES:
1. Use ONLY the VERIFIED DATA below.
2. Do NOT invent or change any order IDs.
3. Do NOT count unrelated codes.
4. Do NOT use outside knowledge.
5. Return only information supported by the verified data.
6. Keep the answer short.

QUESTION:
{question}

VERIFIED DATA:
{llm_context}

TASK:
Answer the question directly using the verified order IDs.
"""

In [ ]:
import re
import pandas as pd
import requests


# ============================================================
# 1. DATABASE RETRIEVAL
# ============================================================

def retrieve_drone_routes(question):

    q = question.lower().strip()

    # --------------------------------------------------------
    # Detect specific order ID
    # --------------------------------------------------------

    order_match = re.search(
        r'\bord-\d+\b',
        q,
        re.IGNORECASE
    )

    # ========================================================
    # SPECIFIC ORDER
    # ========================================================

    if order_match:

        order_id = order_match.group(0).upper()

        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE UPPER(order_id) = %s
          AND LOWER(vehicle_type) = 'drone'
        """

        try:

            engine = connection.engine

            with engine.connect() as conn:

                return pd.read_sql_query(
                    sql,
                    conn,
                    params=(order_id,)
                )

        except Exception as e:

            print("Database retrieval error:", e)
            raise


    # ========================================================
    # GENERAL QUESTIONS
    # ========================================================

    # --------------------------------------------------------
    # Feasible drone routes
    # --------------------------------------------------------

    if "feasible" in q:

        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND package_weight <= capacity_kg
          AND distance_km <= max_range_km
        """


    # --------------------------------------------------------
    # Routes exceeding vehicle capacity
    # --------------------------------------------------------

    elif (
        "exceed their vehicle capacity" in q
        or "exceed capacity" in q
        or "over capacity" in q
        or "capacity exceeded" in q
    ):

        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND package_weight > capacity_kg
        """


    # --------------------------------------------------------
    # Routes within maximum range
    # --------------------------------------------------------

    elif (
        "within their maximum range" in q
        or "within maximum range" in q
        or "within range" in q
        or "maximum range" in q
    ):

        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND distance_km <= max_range_km
        """


    # --------------------------------------------------------
    # Unknown question
    # --------------------------------------------------------

    else:

        return pd.DataFrame()


    # ========================================================
    # EXECUTE GENERAL QUERY
    # ========================================================

    try:

        engine = connection.engine

        with engine.connect() as conn:

            return pd.read_sql_query(
                sql,
                conn
            )

    except Exception as e:

        print("Database retrieval error:", e)
        raise



# ============================================================
# 2. OLLAMA CONFIGURATION
# ============================================================

OLLAMA_URL = "http://localhost:11434/api/chat"

OLLAMA_MODEL = "deepseek-r1:7b"



# ============================================================
# 3. OLLAMA FUNCTION
# ============================================================

def ask_ollama(question, verified_context):

    prompt = f"""
You are a logistics data analysis assistant.

Use ONLY the verified database data provided below.

QUESTION:
{question}

VERIFIED DATABASE DATA:
{verified_context}

RULES:
1. Do not invent information.
2. Do not invent order IDs.
3. Do not modify order IDs.
4. Do not use outside knowledge.
5. Answer only from the verified data.
6. Keep the answer concise.
7. If the question asks for an explanation, explain using the values in the data.
"""

    payload = {

        "model": OLLAMA_MODEL,

        "messages": [
            {
                "role": "user",
                "content": prompt
            }
        ],

        "stream": False,

        "options": {
            "temperature": 0,
            "num_ctx": 4096
        }
    }


    try:

        response = requests.post(
            OLLAMA_URL,
            json=payload,
            timeout=300
        )

        print(
            "Ollama status:",
            response.status_code
        )

        response.raise_for_status()

        result = response.json()

        return result["message"]["content"].strip()


    except requests.exceptions.Timeout:

        return (
            "Ollama took too long to generate the response."
        )


    except requests.exceptions.RequestException as e:

        return f"Ollama error: {e}"



# ============================================================
# 4. HELPER FUNCTION
# ============================================================

def get_order_ids(df):

    if df.empty:

        return []

    return (
        df["order_id"]
        .astype(str)
        .str.strip()
        .str.upper()
        .tolist()
    )



# ============================================================
# 5. MAIN RAG FUNCTION
# ============================================================

def generate_rag_answer(question):

    q = question.lower().strip()


    # ========================================================
    # RETRIEVE DATA
    # ========================================================

    retrieved = retrieve_drone_routes(question)

    print(
        "Retrieved rows:",
        len(retrieved)
    )


    # ========================================================
    # NO RESULTS
    # ========================================================

    if retrieved.empty:

        return "No matching drone order was found."


    # ========================================================
    # SPECIFIC ORDER QUESTION
    # ========================================================

    order_match = re.search(
        r'\bord-\d+\b',
        question,
        re.IGNORECASE
    )


    if order_match:

        order_id = (
            order_match
            .group(0)
            .upper()
        )


        # ----------------------------------------------------
        # Safety check
        # ----------------------------------------------------

        if len(retrieved) == 0:

            return (
                f"No drone record was found for {order_id}."
            )


        row = retrieved.iloc[0]


        # ----------------------------------------------------
        # Convert numeric values safely
        # ----------------------------------------------------

        try:

            package_weight = float(
                row["package_weight"]
            )

            capacity_kg = float(
                row["capacity_kg"]
            )

            distance_km = float(
                row["distance_km"]
            )

            max_range_km = float(
                row["max_range_km"]
            )

        except (ValueError, TypeError):

            return (
                f"Unable to calculate feasibility for "
                f"{order_id} because required numeric data "
                f"is missing or invalid."
            )


        # ====================================================
        # SPECIFIC ORDER: FEASIBILITY
        # ====================================================

        if "feasible" in q:

            capacity_ok = (
                package_weight <= capacity_kg
            )

            range_ok = (
                distance_km <= max_range_km
            )

            feasible = (
                capacity_ok and range_ok
            )


            if feasible:

                return (
                    f"Yes, {order_id} is feasible."
                )


            reasons = []


            if not capacity_ok:

                reasons.append(
                    "package weight exceeds vehicle capacity"
                )


            if not range_ok:

                reasons.append(
                    "route exceeds maximum range"
                )


            return (
                f"No, {order_id} is not feasible because "
                + " and ".join(reasons)
                + "."
            )


        # ====================================================
        # SPECIFIC ORDER: CAPACITY
        # ====================================================

        if (
            "capacity" in q
            or "weight" in q
        ):

            if package_weight > capacity_kg:

                return (
                    f"No, {order_id} exceeds vehicle capacity "
                    f"({package_weight} kg > "
                    f"{capacity_kg} kg)."
                )


            return (
                f"No, {order_id} does not exceed vehicle "
                f"capacity "
                f"({package_weight} kg <= "
                f"{capacity_kg} kg)."
            )


        # ====================================================
        # SPECIFIC ORDER: RANGE
        # ====================================================

        if (
            "range" in q
            or "distance" in q
        ):

            if distance_km <= max_range_km:

                return (
                    f"Yes, {order_id} is within maximum range "
                    f"({distance_km} km <= "
                    f"{max_range_km} km)."
                )


            return (
                f"No, {order_id} exceeds maximum range "
                f"({distance_km} km > "
                f"{max_range_km} km)."
            )


        # ====================================================
        # SPECIFIC ORDER: DETAILS
        # ====================================================

        if (
            "details" in q
            or "information" in q
            or "show" in q
        ):

            return (
                f"Order: {order_id}\n"
                f"Package weight: {package_weight} kg\n"
                f"Vehicle: {row['vehicle_type']}\n"
                f"Vehicle capacity: {capacity_kg} kg\n"
                f"Distance: {distance_km} km\n"
                f"Maximum range: {max_range_km} km"
            )


    # ========================================================
    # GENERAL QUESTIONS
    # ========================================================


    # --------------------------------------------------------
    # GENERAL FEASIBLE ROUTES
    # --------------------------------------------------------

    if "feasible" in q:

        order_ids = get_order_ids(
            retrieved
        )

        print(
            "Total verified rows:",
            len(order_ids)
        )

        # Direct database answer.
        # Do NOT send hundreds of IDs to Ollama.

        return "\n".join(order_ids)


    # --------------------------------------------------------
    # GENERAL CAPACITY VIOLATIONS
    # --------------------------------------------------------

    if (
        "exceed their vehicle capacity" in q
        or "exceed capacity" in q
        or "over capacity" in q
        or "capacity exceeded" in q
    ):

        order_ids = get_order_ids(
            retrieved
        )

        print(
            "Total verified rows:",
            len(order_ids)
        )

        return "\n".join(order_ids)


    # --------------------------------------------------------
    # GENERAL RANGE QUESTIONS
    # --------------------------------------------------------

    if (
        "within their maximum range" in q
        or "within maximum range" in q
        or "within range" in q
        or "maximum range" in q
    ):

        order_ids = get_order_ids(
            retrieved
        )

        print(
            "Total verified rows:",
            len(order_ids)
        )

        return "\n".join(order_ids)


    # ========================================================
    # FALLBACK TO OLLAMA
    # ========================================================

    context_df = retrieved.head(20).copy()

    verified_context = context_df.to_string(
        index=False
    )


    print(
        "Context characters:",
        len(verified_context)
    )


    return ask_ollama(
        question,
        verified_context
    )



# ============================================================
# 6. TEST FUNCTION
# ============================================================

def test_drone_rag(question):

    print("=" * 70)

    print("QUESTION:")
    print(question)

    print("-" * 70)


    answer = generate_rag_answer(
        question
    )


    print("ANSWER:")
    print(answer)

    print("=" * 70)

    return answer



# ============================================================
# 7. TEST 1 — SPECIFIC ORDER
# ============================================================

question = "Is order ORD-005379 feasible?"

answer = test_drone_rag(
    question
)



# ============================================================
# 8. READY MESSAGE
# ============================================================

print(
    "\nRAG + PostgreSQL + Ollama pipeline is ready!"
)

======================================================================
QUESTION:
Is order ORD-005379 feasible?
----------------------------------------------------------------------
Retrieved rows: 1
ANSWER:
Yes, ORD-005379 is feasible.
======================================================================

RAG + PostgreSQL + Ollama pipeline is ready!

# Test the question type

In [ ]:
test_drone_rag("Does order ORD-005379 exceed capacity?")

======================================================================
QUESTION:
Does order ORD-005379 exceed capacity?
----------------------------------------------------------------------
Retrieved rows: 1
ANSWER:
No, ORD-005379 does not exceed vehicle capacity (1.54 kg <= 2.0 kg).
======================================================================

'No, ORD-005379 does not exceed vehicle capacity (1.54 kg <= 2.0 kg).'

In [ ]:
test_drone_rag("Is order ORD-005379 within maximum range?")

======================================================================
QUESTION:
Is order ORD-005379 within maximum range?
----------------------------------------------------------------------
Retrieved rows: 1
ANSWER:
Yes, ORD-005379 is within maximum range (5.01 km <= 15.2 km).
======================================================================

'Yes, ORD-005379 is within maximum range (5.01 km <= 15.2 km).'

In [ ]:
test_drone_rag("Which drone routes are feasible?")

======================================================================
QUESTION:
Which drone routes are feasible?
----------------------------------------------------------------------
Retrieved rows: 411
Total verified rows: 411
ANSWER:
ORD-005379
ORD-014884
ORD-003137
ORD-000415
ORD-008479
ORD-011188
ORD-004441
ORD-007387
ORD-012665
ORD-012992
ORD-009872
ORD-012142
ORD-013768
ORD-008918
ORD-008532
ORD-007438
ORD-013850
ORD-001348
ORD-013888
ORD-006961
ORD-012792
ORD-004237
ORD-008067
ORD-004657
ORD-011363
ORD-001297
ORD-007391
ORD-000186
ORD-008998
ORD-006065
ORD-009511
ORD-011616
ORD-009848
ORD-003601
ORD-012859
ORD-014136
ORD-000618
ORD-013702
ORD-011207
ORD-009021
ORD-014080
ORD-011297
ORD-009918
ORD-003550
ORD-002375
ORD-011525
ORD-006171
ORD-002411
ORD-014314
ORD-008386
ORD-013211
ORD-005829
ORD-006293
ORD-005635
ORD-010656
ORD-007314
ORD-009266
ORD-010311
ORD-012484
ORD-001708
ORD-012172
ORD-002098
ORD-010173
ORD-007627
ORD-004790
ORD-006343
ORD-006033
ORD-003707
ORD-013831
ORD-012121
ORD-010906
ORD-010772
ORD-008815
ORD-005441
ORD-001028
ORD-007310
ORD-008976
ORD-005972
ORD-004772
ORD-008589
ORD-012593
ORD-011513
ORD-014553
ORD-011962
ORD-007472
ORD-014835
ORD-012272
ORD-007127
ORD-006393
ORD-010300
ORD-007659
ORD-008049
ORD-002758
ORD-001071
ORD-003211
ORD-006163
ORD-001938
ORD-009378
ORD-003993
ORD-014191
ORD-004531
ORD-002550
ORD-013310
ORD-012145
ORD-014099
ORD-009352
ORD-003842
ORD-007390
ORD-007325
ORD-012127
ORD-008916
ORD-009810
ORD-009165
ORD-002308
ORD-014730
ORD-005060
ORD-004648
ORD-011035
ORD-011237
ORD-003309
ORD-013621
ORD-001198
ORD-009724
ORD-011038
ORD-009059
ORD-005700
ORD-009943
ORD-013848
ORD-006282
ORD-008618
ORD-006883
ORD-000901
ORD-012978
ORD-000133
ORD-010014
ORD-008865
ORD-004279
ORD-000449
ORD-000256
ORD-002964
ORD-012802
ORD-009160
ORD-003000
ORD-007937
ORD-010402
ORD-014883
ORD-004917
ORD-007646
ORD-007917
ORD-000673
ORD-006511
ORD-014799
ORD-001975
ORD-012241
ORD-002781
ORD-004555
ORD-007163
ORD-004004
ORD-014095
ORD-004896
ORD-013573
ORD-006552
ORD-014163
ORD-010339
ORD-011776
ORD-006630
ORD-011166
ORD-014784
ORD-006720
ORD-009366
ORD-004169
ORD-003946
ORD-003871
ORD-004693
ORD-005154
ORD-006747
ORD-011284
ORD-000127
ORD-004552
ORD-005598
ORD-007277
ORD-008808
ORD-001667
ORD-010119
ORD-012831
ORD-006541
ORD-011205
ORD-000481
ORD-001719
ORD-012275
ORD-001048
ORD-008748
ORD-011286
ORD-007538
ORD-002523
ORD-014231
ORD-005796
ORD-004945
ORD-002428
ORD-008437
ORD-013262
ORD-012452
ORD-009916
ORD-003172
ORD-000350
ORD-008121
ORD-006827
ORD-002386
ORD-008959
ORD-005946
ORD-010142
ORD-007988
ORD-012940
ORD-004316
ORD-014805
ORD-003944
ORD-013636
ORD-000262
ORD-006240
ORD-004411
ORD-014355
ORD-007925
ORD-010687
ORD-005690
ORD-009274
ORD-009287
ORD-010850
ORD-012557
ORD-010954
ORD-010434
ORD-002118
ORD-006371
ORD-011899
ORD-011507
ORD-006880
ORD-009666
ORD-004553
ORD-006619
ORD-014139
ORD-005907
ORD-007717
ORD-002247
ORD-012627
ORD-002597
ORD-002827
ORD-002322
ORD-009189
ORD-008615
ORD-011093
ORD-014532
ORD-007813
ORD-008181
ORD-012009
ORD-010338
ORD-013795
ORD-003242
ORD-002264
ORD-013998
ORD-013027
ORD-010144
ORD-014257
ORD-004912
ORD-004962
ORD-014685
ORD-009659
ORD-000016
ORD-014847
ORD-014183
ORD-013284
ORD-008281
ORD-009341
ORD-005283
ORD-005671
ORD-014779
ORD-002349
ORD-008644
ORD-013526
ORD-009485
ORD-000825
ORD-010103
ORD-007596
ORD-000542
ORD-014311
ORD-000724
ORD-014922
ORD-001827
ORD-006488
ORD-001103
ORD-004439
ORD-006089
ORD-000304
ORD-010806
ORD-012664
ORD-011096
ORD-014321
ORD-005857
ORD-012126
ORD-013381
ORD-006035
ORD-000701
ORD-011897
ORD-014978
ORD-011999
ORD-000795
ORD-012311
ORD-006436
ORD-009579
ORD-013987
ORD-001984
ORD-007403
ORD-006348
ORD-003569
ORD-013111
ORD-012840
ORD-009407
ORD-011083
ORD-007157
ORD-003710
ORD-011148
ORD-012108
ORD-007380
ORD-012218
ORD-011952
ORD-009236
ORD-001541
ORD-006046
ORD-007777
ORD-009393
ORD-008906
ORD-006864
ORD-007196
ORD-001498
ORD-002315
ORD-006546
ORD-014147
ORD-002423
ORD-010762
ORD-000607
ORD-007038
ORD-012420
ORD-000696
ORD-001068
ORD-007206
ORD-005881
ORD-014871
ORD-003513
ORD-013982
ORD-003750
ORD-013913
ORD-004754
ORD-012338
ORD-001177
ORD-013065
ORD-014396
ORD-000480
ORD-008353
ORD-008059
ORD-013613
ORD-013363
ORD-001882
ORD-011350
ORD-008334
ORD-005292
ORD-007715
ORD-000674
ORD-007243
ORD-005674
ORD-004324
ORD-005286
ORD-008389
ORD-014787
ORD-003083
ORD-010845
ORD-007914
ORD-014848
ORD-006754
ORD-008262
ORD-012950
ORD-008623
ORD-002506
ORD-005260
ORD-012853
ORD-013691
ORD-003123
ORD-010608
ORD-002137
ORD-003982
ORD-006426
ORD-014290
ORD-002872
ORD-006520
ORD-004722
ORD-007267
ORD-009089
ORD-009833
ORD-013448
ORD-007719
ORD-008471
ORD-005147
ORD-014539
ORD-011703
ORD-000874
ORD-001661
ORD-013445
ORD-006187
ORD-009616
ORD-004892
ORD-010701
ORD-005388
ORD-008768
ORD-008813
======================================================================

'ORD-005379\nORD-014884\nORD-003137\nORD-000415\nORD-008479\nORD-011188\nORD-004441\nORD-007387\nORD-012665\nORD-012992\nORD-009872\nORD-012142\nORD-013768\nORD-008918\nORD-008532\nORD-007438\nORD-013850\nORD-001348\nORD-013888\nORD-006961\nORD-012792\nORD-004237\nORD-008067\nORD-004657\nORD-011363\nORD-001297\nORD-007391\nORD-000186\nORD-008998\nORD-006065\nORD-009511\nORD-011616\nORD-009848\nORD-003601\nORD-012859\nORD-014136\nORD-000618\nORD-013702\nORD-011207\nORD-009021\nORD-014080\nORD-011297\nORD-009918\nORD-003550\nORD-002375\nORD-011525\nORD-006171\nORD-002411\nORD-014314\nORD-008386\nORD-013211\nORD-005829\nORD-006293\nORD-005635\nORD-010656\nORD-007314\nORD-009266\nORD-010311\nORD-012484\nORD-001708\nORD-012172\nORD-002098\nORD-010173\nORD-007627\nORD-004790\nORD-006343\nORD-006033\nORD-003707\nORD-013831\nORD-012121\nORD-010906\nORD-010772\nORD-008815\nORD-005441\nORD-001028\nORD-007310\nORD-008976\nORD-005972\nORD-004772\nORD-008589\nORD-012593\nORD-011513\nORD-014553\nORD-011962\nORD-007472\nORD-014835\nORD-012272\nORD-007127\nORD-006393\nORD-010300\nORD-007659\nORD-008049\nORD-002758\nORD-001071\nORD-003211\nORD-006163\nORD-001938\nORD-009378\nORD-003993\nORD-014191\nORD-004531\nORD-002550\nORD-013310\nORD-012145\nORD-014099\nORD-009352\nORD-003842\nORD-007390\nORD-007325\nORD-012127\nORD-008916\nORD-009810\nORD-009165\nORD-002308\nORD-014730\nORD-005060\nORD-004648\nORD-011035\nORD-011237\nORD-003309\nORD-013621\nORD-001198\nORD-009724\nORD-011038\nORD-009059\nORD-005700\nORD-009943\nORD-013848\nORD-006282\nORD-008618\nORD-006883\nORD-000901\nORD-012978\nORD-000133\nORD-010014\nORD-008865\nORD-004279\nORD-000449\nORD-000256\nORD-002964\nORD-012802\nORD-009160\nORD-003000\nORD-007937\nORD-010402\nORD-014883\nORD-004917\nORD-007646\nORD-007917\nORD-000673\nORD-006511\nORD-014799\nORD-001975\nORD-012241\nORD-002781\nORD-004555\nORD-007163\nORD-004004\nORD-014095\nORD-004896\nORD-013573\nORD-006552\nORD-014163\nORD-010339\nORD-011776\nORD-006630\nORD-011166\nORD-014784\nORD-006720\nORD-009366\nORD-004169\nORD-003946\nORD-003871\nORD-004693\nORD-005154\nORD-006747\nORD-011284\nORD-000127\nORD-004552\nORD-005598\nORD-007277\nORD-008808\nORD-001667\nORD-010119\nORD-012831\nORD-006541\nORD-011205\nORD-000481\nORD-001719\nORD-012275\nORD-001048\nORD-008748\nORD-011286\nORD-007538\nORD-002523\nORD-014231\nORD-005796\nORD-004945\nORD-002428\nORD-008437\nORD-013262\nORD-012452\nORD-009916\nORD-003172\nORD-000350\nORD-008121\nORD-006827\nORD-002386\nORD-008959\nORD-005946\nORD-010142\nORD-007988\nORD-012940\nORD-004316\nORD-014805\nORD-003944\nORD-013636\nORD-000262\nORD-006240\nORD-004411\nORD-014355\nORD-007925\nORD-010687\nORD-005690\nORD-009274\nORD-009287\nORD-010850\nORD-012557\nORD-010954\nORD-010434\nORD-002118\nORD-006371\nORD-011899\nORD-011507\nORD-006880\nORD-009666\nORD-004553\nORD-006619\nORD-014139\nORD-005907\nORD-007717\nORD-002247\nORD-012627\nORD-002597\nORD-002827\nORD-002322\nORD-009189\nORD-008615\nORD-011093\nORD-014532\nORD-007813\nORD-008181\nORD-012009\nORD-010338\nORD-013795\nORD-003242\nORD-002264\nORD-013998\nORD-013027\nORD-010144\nORD-014257\nORD-004912\nORD-004962\nORD-014685\nORD-009659\nORD-000016\nORD-014847\nORD-014183\nORD-013284\nORD-008281\nORD-009341\nORD-005283\nORD-005671\nORD-014779\nORD-002349\nORD-008644\nORD-013526\nORD-009485\nORD-000825\nORD-010103\nORD-007596\nORD-000542\nORD-014311\nORD-000724\nORD-014922\nORD-001827\nORD-006488\nORD-001103\nORD-004439\nORD-006089\nORD-000304\nORD-010806\nORD-012664\nORD-011096\nORD-014321\nORD-005857\nORD-012126\nORD-013381\nORD-006035\nORD-000701\nORD-011897\nORD-014978\nORD-011999\nORD-000795\nORD-012311\nORD-006436\nORD-009579\nORD-013987\nORD-001984\nORD-007403\nORD-006348\nORD-003569\nORD-013111\nORD-012840\nORD-009407\nORD-011083\nORD-007157\nORD-003710\nORD-011148\nORD-012108\nORD-007380\nORD-012218\nORD-011952\nORD-009236\nORD-001541\nORD-006046\nORD-007777\nORD-009393\nORD-008906\nORD-006864\nORD-007196\nORD-001498\nORD-002315\nORD-006546\nORD-014147\nORD-002423\nORD-010762\nORD-000607\nORD-007038\nORD-012420\nORD-000696\nORD-001068\nORD-007206\nORD-005881\nORD-014871\nORD-003513\nORD-013982\nORD-003750\nORD-013913\nORD-004754\nORD-012338\nORD-001177\nORD-013065\nORD-014396\nORD-000480\nORD-008353\nORD-008059\nORD-013613\nORD-013363\nORD-001882\nORD-011350\nORD-008334\nORD-005292\nORD-007715\nORD-000674\nORD-007243\nORD-005674\nORD-004324\nORD-005286\nORD-008389\nORD-014787\nORD-003083\nORD-010845\nORD-007914\nORD-014848\nORD-006754\nORD-008262\nORD-012950\nORD-008623\nORD-002506\nORD-005260\nORD-012853\nORD-013691\nORD-003123\nORD-010608\nORD-002137\nORD-003982\nORD-006426\nORD-014290\nORD-002872\nORD-006520\nORD-004722\nORD-007267\nORD-009089\nORD-009833\nORD-013448\nORD-007719\nORD-008471\nORD-005147\nORD-014539\nORD-011703\nORD-000874\nORD-001661\nORD-013445\nORD-006187\nORD-009616\nORD-004892\nORD-010701\nORD-005388\nORD-008768\nORD-008813'

In [ ]:
test_drone_rag("Which drone routes exceed their vehicle capacity?")

======================================================================
QUESTION:
Which drone routes exceed their vehicle capacity?
----------------------------------------------------------------------
Retrieved rows: 288
Total verified rows: 288
ANSWER:
ORD-002549
ORD-012343
ORD-000680
ORD-009988
ORD-011103
ORD-013759
ORD-009549
ORD-013534
ORD-003907
ORD-014531
ORD-014960
ORD-011168
ORD-001245
ORD-004200
ORD-014348
ORD-012625
ORD-008272
ORD-005888
ORD-011323
ORD-010911
ORD-009512
ORD-005054
ORD-008528
ORD-009819
ORD-009934
ORD-001622
ORD-001691
ORD-011958
ORD-002595
ORD-009820
ORD-010704
ORD-001532
ORD-002676
ORD-003107
ORD-004846
ORD-013949
ORD-000821
ORD-008743
ORD-005589
ORD-013791
ORD-000943
ORD-000495
ORD-007031
ORD-003709
ORD-010443
ORD-005127
ORD-006254
ORD-004802
ORD-004921
ORD-000199
ORD-000228
ORD-007187
ORD-005278
ORD-012715
ORD-011935
ORD-007863
ORD-003150
ORD-010847
ORD-002867
ORD-014740
ORD-003921
ORD-005692
ORD-014845
ORD-010179
ORD-014429
ORD-004543
ORD-002136
ORD-009577
ORD-013537
ORD-008123
ORD-011763
ORD-008022
ORD-008681
ORD-008966
ORD-007284
ORD-014555
ORD-002444
ORD-010519
ORD-007938
ORD-008263
ORD-009163
ORD-004526
ORD-008452
ORD-001482
ORD-008055
ORD-000303
ORD-002851
ORD-005345
ORD-006882
ORD-006462
ORD-003887
ORD-002236
ORD-001937
ORD-007240
ORD-002976
ORD-005298
ORD-003084
ORD-009136
ORD-006259
ORD-005134
ORD-011532
ORD-005500
ORD-014236
ORD-005178
ORD-008679
ORD-004304
ORD-008212
ORD-009601
ORD-014258
ORD-010146
ORD-011437
ORD-013656
ORD-002589
ORD-001989
ORD-014537
ORD-005351
ORD-009784
ORD-004827
ORD-003725
ORD-010403
ORD-005033
ORD-001368
ORD-010709
ORD-008631
ORD-012325
ORD-012191
ORD-011606
ORD-008133
ORD-004833
ORD-003556
ORD-007046
ORD-013510
ORD-011571
ORD-002645
ORD-014869
ORD-012534
ORD-004901
ORD-014128
ORD-010223
ORD-013436
ORD-014458
ORD-014944
ORD-014166
ORD-003727
ORD-005353
ORD-002904
ORD-001490
ORD-007453
ORD-006165
ORD-003626
ORD-008426
ORD-004676
ORD-006316
ORD-014651
ORD-014575
ORD-010840
ORD-014065
ORD-002189
ORD-009299
ORD-011335
ORD-002094
ORD-004590
ORD-002194
ORD-003776
ORD-001701
ORD-013148
ORD-010027
ORD-009479
ORD-014435
ORD-011936
ORD-012680
ORD-003992
ORD-011538
ORD-006771
ORD-003828
ORD-014967
ORD-000183
ORD-003780
ORD-006772
ORD-006085
ORD-004637
ORD-010029
ORD-014316
ORD-006916
ORD-014558
ORD-001569
ORD-011422
ORD-005480
ORD-010084
ORD-002520
ORD-010759
ORD-007784
ORD-001950
ORD-012602
ORD-000281
ORD-005645
ORD-014045
ORD-008971
ORD-000359
ORD-006157
ORD-000928
ORD-002334
ORD-006560
ORD-000484
ORD-008222
ORD-004131
ORD-013021
ORD-014564
ORD-005271
ORD-011457
ORD-007611
ORD-013649
ORD-003889
ORD-007323
ORD-009651
ORD-006118
ORD-014768
ORD-009470
ORD-000046
ORD-000005
ORD-011275
ORD-000704
ORD-008064
ORD-007978
ORD-013283
ORD-014789
ORD-005132
ORD-000881
ORD-013705
ORD-010526
ORD-007237
ORD-002293
ORD-011698
ORD-014269
ORD-001677
ORD-001791
ORD-005113
ORD-000748
ORD-013325
ORD-012660
ORD-010159
ORD-012945
ORD-014637
ORD-005473
ORD-005756
ORD-005354
ORD-000900
ORD-013248
ORD-004144
ORD-009718
ORD-003778
ORD-003325
ORD-001627
ORD-001105
ORD-014750
ORD-007995
ORD-001344
ORD-011634
ORD-000414
ORD-013923
ORD-009373
ORD-006242
ORD-003414
ORD-008070
ORD-008078
ORD-009177
ORD-009415
ORD-012389
ORD-007579
ORD-008812
ORD-007464
ORD-002760
ORD-014873
ORD-001256
ORD-013969
ORD-013733
ORD-000892
ORD-009164
ORD-003032
ORD-008136
ORD-008663
ORD-008547
ORD-011444
ORD-010396
ORD-001138
ORD-000124
ORD-005238
ORD-006315
======================================================================

'ORD-002549\nORD-012343\nORD-000680\nORD-009988\nORD-011103\nORD-013759\nORD-009549\nORD-013534\nORD-003907\nORD-014531\nORD-014960\nORD-011168\nORD-001245\nORD-004200\nORD-014348\nORD-012625\nORD-008272\nORD-005888\nORD-011323\nORD-010911\nORD-009512\nORD-005054\nORD-008528\nORD-009819\nORD-009934\nORD-001622\nORD-001691\nORD-011958\nORD-002595\nORD-009820\nORD-010704\nORD-001532\nORD-002676\nORD-003107\nORD-004846\nORD-013949\nORD-000821\nORD-008743\nORD-005589\nORD-013791\nORD-000943\nORD-000495\nORD-007031\nORD-003709\nORD-010443\nORD-005127\nORD-006254\nORD-004802\nORD-004921\nORD-000199\nORD-000228\nORD-007187\nORD-005278\nORD-012715\nORD-011935\nORD-007863\nORD-003150\nORD-010847\nORD-002867\nORD-014740\nORD-003921\nORD-005692\nORD-014845\nORD-010179\nORD-014429\nORD-004543\nORD-002136\nORD-009577\nORD-013537\nORD-008123\nORD-011763\nORD-008022\nORD-008681\nORD-008966\nORD-007284\nORD-014555\nORD-002444\nORD-010519\nORD-007938\nORD-008263\nORD-009163\nORD-004526\nORD-008452\nORD-001482\nORD-008055\nORD-000303\nORD-002851\nORD-005345\nORD-006882\nORD-006462\nORD-003887\nORD-002236\nORD-001937\nORD-007240\nORD-002976\nORD-005298\nORD-003084\nORD-009136\nORD-006259\nORD-005134\nORD-011532\nORD-005500\nORD-014236\nORD-005178\nORD-008679\nORD-004304\nORD-008212\nORD-009601\nORD-014258\nORD-010146\nORD-011437\nORD-013656\nORD-002589\nORD-001989\nORD-014537\nORD-005351\nORD-009784\nORD-004827\nORD-003725\nORD-010403\nORD-005033\nORD-001368\nORD-010709\nORD-008631\nORD-012325\nORD-012191\nORD-011606\nORD-008133\nORD-004833\nORD-003556\nORD-007046\nORD-013510\nORD-011571\nORD-002645\nORD-014869\nORD-012534\nORD-004901\nORD-014128\nORD-010223\nORD-013436\nORD-014458\nORD-014944\nORD-014166\nORD-003727\nORD-005353\nORD-002904\nORD-001490\nORD-007453\nORD-006165\nORD-003626\nORD-008426\nORD-004676\nORD-006316\nORD-014651\nORD-014575\nORD-010840\nORD-014065\nORD-002189\nORD-009299\nORD-011335\nORD-002094\nORD-004590\nORD-002194\nORD-003776\nORD-001701\nORD-013148\nORD-010027\nORD-009479\nORD-014435\nORD-011936\nORD-012680\nORD-003992\nORD-011538\nORD-006771\nORD-003828\nORD-014967\nORD-000183\nORD-003780\nORD-006772\nORD-006085\nORD-004637\nORD-010029\nORD-014316\nORD-006916\nORD-014558\nORD-001569\nORD-011422\nORD-005480\nORD-010084\nORD-002520\nORD-010759\nORD-007784\nORD-001950\nORD-012602\nORD-000281\nORD-005645\nORD-014045\nORD-008971\nORD-000359\nORD-006157\nORD-000928\nORD-002334\nORD-006560\nORD-000484\nORD-008222\nORD-004131\nORD-013021\nORD-014564\nORD-005271\nORD-011457\nORD-007611\nORD-013649\nORD-003889\nORD-007323\nORD-009651\nORD-006118\nORD-014768\nORD-009470\nORD-000046\nORD-000005\nORD-011275\nORD-000704\nORD-008064\nORD-007978\nORD-013283\nORD-014789\nORD-005132\nORD-000881\nORD-013705\nORD-010526\nORD-007237\nORD-002293\nORD-011698\nORD-014269\nORD-001677\nORD-001791\nORD-005113\nORD-000748\nORD-013325\nORD-012660\nORD-010159\nORD-012945\nORD-014637\nORD-005473\nORD-005756\nORD-005354\nORD-000900\nORD-013248\nORD-004144\nORD-009718\nORD-003778\nORD-003325\nORD-001627\nORD-001105\nORD-014750\nORD-007995\nORD-001344\nORD-011634\nORD-000414\nORD-013923\nORD-009373\nORD-006242\nORD-003414\nORD-008070\nORD-008078\nORD-009177\nORD-009415\nORD-012389\nORD-007579\nORD-008812\nORD-007464\nORD-002760\nORD-014873\nORD-001256\nORD-013969\nORD-013733\nORD-000892\nORD-009164\nORD-003032\nORD-008136\nORD-008663\nORD-008547\nORD-011444\nORD-010396\nORD-001138\nORD-000124\nORD-005238\nORD-006315'

In [ ]:
test_drone_rag("Which drone routes are within their maximum range?")

======================================================================
QUESTION:
Which drone routes are within their maximum range?
----------------------------------------------------------------------
Retrieved rows: 602
Total verified rows: 602
ANSWER:
ORD-005379
ORD-014884
ORD-003137
ORD-002549
ORD-000415
ORD-008479
ORD-011188
ORD-004441
ORD-007387
ORD-012343
ORD-012665
ORD-000680
ORD-009988
ORD-012992
ORD-009872
ORD-013759
ORD-012142
ORD-013768
ORD-008918
ORD-008532
ORD-007438
ORD-013850
ORD-001348
ORD-013534
ORD-013888
ORD-006961
ORD-014531
ORD-012792
ORD-001245
ORD-004237
ORD-008067
ORD-004657
ORD-011363
ORD-001297
ORD-007391
ORD-000186
ORD-008998
ORD-004200
ORD-014348
ORD-006065
ORD-009511
ORD-011616
ORD-012625
ORD-008272
ORD-005888
ORD-011323
ORD-010911
ORD-009512
ORD-009848
ORD-005054
ORD-003601
ORD-012859
ORD-014136
ORD-000618
ORD-013702
ORD-011207
ORD-009021
ORD-008528
ORD-009934
ORD-014080
ORD-011297
ORD-001622
ORD-011958
ORD-009918
ORD-003550
ORD-002375
ORD-002595
ORD-011525
ORD-010704
ORD-006171
ORD-002411
ORD-004846
ORD-014314
ORD-008386
ORD-000821
ORD-013211
ORD-008743
ORD-005829
ORD-006293
ORD-005635
ORD-013791
ORD-000943
ORD-010656
ORD-007314
ORD-009266
ORD-007031
ORD-010311
ORD-003709
ORD-010443
ORD-012484
ORD-001708
ORD-012172
ORD-002098
ORD-010173
ORD-007627
ORD-004790
ORD-005127
ORD-006254
ORD-006343
ORD-006033
ORD-003707
ORD-013831
ORD-012121
ORD-010906
ORD-010772
ORD-008815
ORD-005441
ORD-001028
ORD-007310
ORD-004921
ORD-000199
ORD-008976
ORD-005972
ORD-007187
ORD-004772
ORD-008589
ORD-012715
ORD-010847
ORD-002867
ORD-012593
ORD-014740
ORD-003921
ORD-011513
ORD-014553
ORD-011962
ORD-007472
ORD-014835
ORD-005692
ORD-012272
ORD-007127
ORD-006393
ORD-010300
ORD-014429
ORD-007659
ORD-008049
ORD-004543
ORD-002136
ORD-002758
ORD-009577
ORD-001071
ORD-003211
ORD-006163
ORD-001938
ORD-009378
ORD-003993
ORD-014191
ORD-008123
ORD-011763
ORD-004531
ORD-008022
ORD-008681
ORD-008966
ORD-002550
ORD-007284
ORD-014555
ORD-013310
ORD-012145
ORD-002444
ORD-014099
ORD-009352
ORD-007938
ORD-003842
ORD-007390
ORD-007325
ORD-012127
ORD-008263
ORD-004526
ORD-008916
ORD-009810
ORD-009165
ORD-002308
ORD-008452
ORD-014730
ORD-005060
ORD-001482
ORD-004648
ORD-011035
ORD-011237
ORD-003309
ORD-013621
ORD-001198
ORD-009724
ORD-000303
ORD-011038
ORD-009059
ORD-002851
ORD-005700
ORD-009943
ORD-005345
ORD-013848
ORD-006282
ORD-006462
ORD-008618
ORD-006883
ORD-000901
ORD-012978
ORD-000133
ORD-010014
ORD-008865
ORD-004279
ORD-000449
ORD-000256
ORD-002964
ORD-003887
ORD-012802
ORD-009160
ORD-003000
ORD-001937
ORD-007240
ORD-002976
ORD-005298
ORD-003084
ORD-007937
ORD-010402
ORD-014883
ORD-004917
ORD-006259
ORD-007646
ORD-007917
ORD-005134
ORD-011532
ORD-000673
ORD-005178
ORD-006511
ORD-008679
ORD-014799
ORD-001975
ORD-008212
ORD-012241
ORD-009601
ORD-002781
ORD-004555
ORD-014258
ORD-007163
ORD-010146
ORD-004004
ORD-011437
ORD-014095
ORD-004896
ORD-013573
ORD-006552
ORD-013656
ORD-002589
ORD-014537
ORD-014163
ORD-009784
ORD-010339
ORD-010709
ORD-008631
ORD-011776
ORD-006630
ORD-011166
ORD-012191
ORD-014784
ORD-006720
ORD-009366
ORD-004169
ORD-003946
ORD-003871
ORD-004693
ORD-005154
ORD-006747
ORD-011284
ORD-011606
ORD-000127
ORD-004552
ORD-005598
ORD-007046
ORD-007277
ORD-008808
ORD-013510
ORD-001667
ORD-010119
ORD-012831
ORD-006541
ORD-011205
ORD-000481
ORD-001719
ORD-012275
ORD-001048
ORD-014869
ORD-012534
ORD-004901
ORD-008748
ORD-011286
ORD-007538
ORD-002523
ORD-014231
ORD-005796
ORD-004945
ORD-002428
ORD-008437
ORD-013262
ORD-014458
ORD-012452
ORD-009916
ORD-014166
ORD-003172
ORD-000350
ORD-008121
ORD-006827
ORD-003727
ORD-002386
ORD-008959
ORD-005946
ORD-010142
ORD-007988
ORD-012940
ORD-005353
ORD-004316
ORD-014805
ORD-003944
ORD-001490
ORD-013636
ORD-000262
ORD-006240
ORD-007453
ORD-004411
ORD-014355
ORD-007925
ORD-010687
ORD-005690
ORD-009274
ORD-009287
ORD-004676
ORD-010850
ORD-006316
ORD-014651
ORD-014575
ORD-010840
ORD-014065
ORD-002189
ORD-009299
ORD-011335
ORD-012557
ORD-010954
ORD-010434
ORD-002118
ORD-006371
ORD-011899
ORD-002194
ORD-011507
ORD-003776
ORD-001701
ORD-006880
ORD-009666
ORD-004553
ORD-006619
ORD-014139
ORD-005907
ORD-007717
ORD-002247
ORD-012627
ORD-002597
ORD-014435
ORD-011936
ORD-002827
ORD-002322
ORD-009189
ORD-011538
ORD-008615
ORD-011093
ORD-006771
ORD-014532
ORD-007813
ORD-003828
ORD-008181
ORD-012009
ORD-010338
ORD-013795
ORD-003242
ORD-002264
ORD-000183
ORD-013998
ORD-013027
ORD-010144
ORD-014257
ORD-004912
ORD-004962
ORD-014685
ORD-009659
ORD-000016
ORD-014847
ORD-014183
ORD-006772
ORD-006085
ORD-013284
ORD-004637
ORD-010029
ORD-014316
ORD-006916
ORD-008281
ORD-009341
ORD-005283
ORD-014558
ORD-005671
ORD-014779
ORD-002349
ORD-008644
ORD-013526
ORD-001569
ORD-009485
ORD-005480
ORD-000825
ORD-002520
ORD-010103
ORD-007596
ORD-010759
ORD-000542
ORD-014311
ORD-007784
ORD-000724
ORD-014922
ORD-001827
ORD-006488
ORD-001103
ORD-004439
ORD-000281
ORD-006089
ORD-005645
ORD-000304
ORD-014045
ORD-008971
ORD-000359
ORD-010806
ORD-006157
ORD-000928
ORD-012664
ORD-006560
ORD-000484
ORD-011096
ORD-008222
ORD-014321
ORD-005857
ORD-012126
ORD-013381
ORD-004131
ORD-006035
ORD-000701
ORD-011897
ORD-014978
ORD-014564
ORD-005271
ORD-011457
ORD-011999
ORD-000795
ORD-012311
ORD-006436
ORD-009579
ORD-013987
ORD-003889
ORD-007323
ORD-001984
ORD-009651
ORD-007403
ORD-006348
ORD-006118
ORD-014768
ORD-003569
ORD-013111
ORD-009470
ORD-000046
ORD-000005
ORD-011275
ORD-000704
ORD-012840
ORD-007978
ORD-009407
ORD-013283
ORD-011083
ORD-007157
ORD-003710
ORD-005132
ORD-000881
ORD-013705
ORD-010526
ORD-011148
ORD-002293
ORD-012108
ORD-007380
ORD-012218
ORD-011952
ORD-009236
ORD-001541
ORD-014269
ORD-006046
ORD-001791
ORD-007777
ORD-005113
ORD-009393
ORD-008906
ORD-006864
ORD-007196
ORD-001498
ORD-002315
ORD-006546
ORD-014147
ORD-002423
ORD-013325
ORD-010762
ORD-000607
ORD-007038
ORD-012420
ORD-000696
ORD-001068
ORD-007206
ORD-005881
ORD-014871
ORD-003513
ORD-012945
ORD-013982
ORD-014637
ORD-003750
ORD-005354
ORD-000900
ORD-013913
ORD-004754
ORD-012338
ORD-001177
ORD-013065
ORD-014396
ORD-000480
ORD-004144
ORD-008353
ORD-008059
ORD-009718
ORD-013613
ORD-013363
ORD-001882
ORD-003778
ORD-011350
ORD-003325
ORD-008334
ORD-005292
ORD-007715
ORD-000674
ORD-007243
ORD-014750
ORD-001344
ORD-011634
ORD-005674
ORD-000414
ORD-004324
ORD-013923
ORD-009373
ORD-006242
ORD-003414
ORD-005286
ORD-008389
ORD-014787
ORD-003083
ORD-008070
ORD-010845
ORD-007914
ORD-008078
ORD-009177
ORD-014848
ORD-006754
ORD-008262
ORD-012950
ORD-008623
ORD-002506
ORD-007579
ORD-005260
ORD-012853
ORD-013691
ORD-003123
ORD-010608
ORD-002137
ORD-008812
ORD-007464
ORD-003982
ORD-002760
ORD-006426
ORD-014290
ORD-002872
ORD-006520
ORD-004722
ORD-007267
ORD-009089
ORD-009833
ORD-013448
ORD-007719
ORD-013733
ORD-008471
ORD-005147
ORD-008547
ORD-014539
ORD-011703
ORD-010396
ORD-000874
ORD-001661
ORD-013445
ORD-006187
ORD-009616
ORD-004892
ORD-010701
ORD-000124
ORD-005388
ORD-008768
ORD-006315
ORD-008813
======================================================================

'ORD-005379\nORD-014884\nORD-003137\nORD-002549\nORD-000415\nORD-008479\nORD-011188\nORD-004441\nORD-007387\nORD-012343\nORD-012665\nORD-000680\nORD-009988\nORD-012992\nORD-009872\nORD-013759\nORD-012142\nORD-013768\nORD-008918\nORD-008532\nORD-007438\nORD-013850\nORD-001348\nORD-013534\nORD-013888\nORD-006961\nORD-014531\nORD-012792\nORD-001245\nORD-004237\nORD-008067\nORD-004657\nORD-011363\nORD-001297\nORD-007391\nORD-000186\nORD-008998\nORD-004200\nORD-014348\nORD-006065\nORD-009511\nORD-011616\nORD-012625\nORD-008272\nORD-005888\nORD-011323\nORD-010911\nORD-009512\nORD-009848\nORD-005054\nORD-003601\nORD-012859\nORD-014136\nORD-000618\nORD-013702\nORD-011207\nORD-009021\nORD-008528\nORD-009934\nORD-014080\nORD-011297\nORD-001622\nORD-011958\nORD-009918\nORD-003550\nORD-002375\nORD-002595\nORD-011525\nORD-010704\nORD-006171\nORD-002411\nORD-004846\nORD-014314\nORD-008386\nORD-000821\nORD-013211\nORD-008743\nORD-005829\nORD-006293\nORD-005635\nORD-013791\nORD-000943\nORD-010656\nORD-007314\nORD-009266\nORD-007031\nORD-010311\nORD-003709\nORD-010443\nORD-012484\nORD-001708\nORD-012172\nORD-002098\nORD-010173\nORD-007627\nORD-004790\nORD-005127\nORD-006254\nORD-006343\nORD-006033\nORD-003707\nORD-013831\nORD-012121\nORD-010906\nORD-010772\nORD-008815\nORD-005441\nORD-001028\nORD-007310\nORD-004921\nORD-000199\nORD-008976\nORD-005972\nORD-007187\nORD-004772\nORD-008589\nORD-012715\nORD-010847\nORD-002867\nORD-012593\nORD-014740\nORD-003921\nORD-011513\nORD-014553\nORD-011962\nORD-007472\nORD-014835\nORD-005692\nORD-012272\nORD-007127\nORD-006393\nORD-010300\nORD-014429\nORD-007659\nORD-008049\nORD-004543\nORD-002136\nORD-002758\nORD-009577\nORD-001071\nORD-003211\nORD-006163\nORD-001938\nORD-009378\nORD-003993\nORD-014191\nORD-008123\nORD-011763\nORD-004531\nORD-008022\nORD-008681\nORD-008966\nORD-002550\nORD-007284\nORD-014555\nORD-013310\nORD-012145\nORD-002444\nORD-014099\nORD-009352\nORD-007938\nORD-003842\nORD-007390\nORD-007325\nORD-012127\nORD-008263\nORD-004526\nORD-008916\nORD-009810\nORD-009165\nORD-002308\nORD-008452\nORD-014730\nORD-005060\nORD-001482\nORD-004648\nORD-011035\nORD-011237\nORD-003309\nORD-013621\nORD-001198\nORD-009724\nORD-000303\nORD-011038\nORD-009059\nORD-002851\nORD-005700\nORD-009943\nORD-005345\nORD-013848\nORD-006282\nORD-006462\nORD-008618\nORD-006883\nORD-000901\nORD-012978\nORD-000133\nORD-010014\nORD-008865\nORD-004279\nORD-000449\nORD-000256\nORD-002964\nORD-003887\nORD-012802\nORD-009160\nORD-003000\nORD-001937\nORD-007240\nORD-002976\nORD-005298\nORD-003084\nORD-007937\nORD-010402\nORD-014883\nORD-004917\nORD-006259\nORD-007646\nORD-007917\nORD-005134\nORD-011532\nORD-000673\nORD-005178\nORD-006511\nORD-008679\nORD-014799\nORD-001975\nORD-008212\nORD-012241\nORD-009601\nORD-002781\nORD-004555\nORD-014258\nORD-007163\nORD-010146\nORD-004004\nORD-011437\nORD-014095\nORD-004896\nORD-013573\nORD-006552\nORD-013656\nORD-002589\nORD-014537\nORD-014163\nORD-009784\nORD-010339\nORD-010709\nORD-008631\nORD-011776\nORD-006630\nORD-011166\nORD-012191\nORD-014784\nORD-006720\nORD-009366\nORD-004169\nORD-003946\nORD-003871\nORD-004693\nORD-005154\nORD-006747\nORD-011284\nORD-011606\nORD-000127\nORD-004552\nORD-005598\nORD-007046\nORD-007277\nORD-008808\nORD-013510\nORD-001667\nORD-010119\nORD-012831\nORD-006541\nORD-011205\nORD-000481\nORD-001719\nORD-012275\nORD-001048\nORD-014869\nORD-012534\nORD-004901\nORD-008748\nORD-011286\nORD-007538\nORD-002523\nORD-014231\nORD-005796\nORD-004945\nORD-002428\nORD-008437\nORD-013262\nORD-014458\nORD-012452\nORD-009916\nORD-014166\nORD-003172\nORD-000350\nORD-008121\nORD-006827\nORD-003727\nORD-002386\nORD-008959\nORD-005946\nORD-010142\nORD-007988\nORD-012940\nORD-005353\nORD-004316\nORD-014805\nORD-003944\nORD-001490\nORD-013636\nORD-000262\nORD-006240\nORD-007453\nORD-004411\nORD-014355\nORD-007925\nORD-010687\nORD-005690\nORD-009274\nORD-009287\nORD-004676\nORD-010850\nORD-006316\nORD-014651\nORD-014575\nORD-010840\nORD-014065\nORD-002189\nORD-009299\nORD-011335\nORD-012557\nORD-010954\nORD-010434\nORD-002118\nORD-006371\nORD-011899\nORD-002194\nORD-011507\nORD-003776\nORD-001701\nORD-006880\nORD-009666\nORD-004553\nORD-006619\nORD-014139\nORD-005907\nORD-007717\nORD-002247\nORD-012627\nORD-002597\nORD-014435\nORD-011936\nORD-002827\nORD-002322\nORD-009189\nORD-011538\nORD-008615\nORD-011093\nORD-006771\nORD-014532\nORD-007813\nORD-003828\nORD-008181\nORD-012009\nORD-010338\nORD-013795\nORD-003242\nORD-002264\nORD-000183\nORD-013998\nORD-013027\nORD-010144\nORD-014257\nORD-004912\nORD-004962\nORD-014685\nORD-009659\nORD-000016\nORD-014847\nORD-014183\nORD-006772\nORD-006085\nORD-013284\nORD-004637\nORD-010029\nORD-014316\nORD-006916\nORD-008281\nORD-009341\nORD-005283\nORD-014558\nORD-005671\nORD-014779\nORD-002349\nORD-008644\nORD-013526\nORD-001569\nORD-009485\nORD-005480\nORD-000825\nORD-002520\nORD-010103\nORD-007596\nORD-010759\nORD-000542\nORD-014311\nORD-007784\nORD-000724\nORD-014922\nORD-001827\nORD-006488\nORD-001103\nORD-004439\nORD-000281\nORD-006089\nORD-005645\nORD-000304\nORD-014045\nORD-008971\nORD-000359\nORD-010806\nORD-006157\nORD-000928\nORD-012664\nORD-006560\nORD-000484\nORD-011096\nORD-008222\nORD-014321\nORD-005857\nORD-012126\nORD-013381\nORD-004131\nORD-006035\nORD-000701\nORD-011897\nORD-014978\nORD-014564\nORD-005271\nORD-011457\nORD-011999\nORD-000795\nORD-012311\nORD-006436\nORD-009579\nORD-013987\nORD-003889\nORD-007323\nORD-001984\nORD-009651\nORD-007403\nORD-006348\nORD-006118\nORD-014768\nORD-003569\nORD-013111\nORD-009470\nORD-000046\nORD-000005\nORD-011275\nORD-000704\nORD-012840\nORD-007978\nORD-009407\nORD-013283\nORD-011083\nORD-007157\nORD-003710\nORD-005132\nORD-000881\nORD-013705\nORD-010526\nORD-011148\nORD-002293\nORD-012108\nORD-007380\nORD-012218\nORD-011952\nORD-009236\nORD-001541\nORD-014269\nORD-006046\nORD-001791\nORD-007777\nORD-005113\nORD-009393\nORD-008906\nORD-006864\nORD-007196\nORD-001498\nORD-002315\nORD-006546\nORD-014147\nORD-002423\nORD-013325\nORD-010762\nORD-000607\nORD-007038\nORD-012420\nORD-000696\nORD-001068\nORD-007206\nORD-005881\nORD-014871\nORD-003513\nORD-012945\nORD-013982\nORD-014637\nORD-003750\nORD-005354\nORD-000900\nORD-013913\nORD-004754\nORD-012338\nORD-001177\nORD-013065\nORD-014396\nORD-000480\nORD-004144\nORD-008353\nORD-008059\nORD-009718\nORD-013613\nORD-013363\nORD-001882\nORD-003778\nORD-011350\nORD-003325\nORD-008334\nORD-005292\nORD-007715\nORD-000674\nORD-007243\nORD-014750\nORD-001344\nORD-011634\nORD-005674\nORD-000414\nORD-004324\nORD-013923\nORD-009373\nORD-006242\nORD-003414\nORD-005286\nORD-008389\nORD-014787\nORD-003083\nORD-008070\nORD-010845\nORD-007914\nORD-008078\nORD-009177\nORD-014848\nORD-006754\nORD-008262\nORD-012950\nORD-008623\nORD-002506\nORD-007579\nORD-005260\nORD-012853\nORD-013691\nORD-003123\nORD-010608\nORD-002137\nORD-008812\nORD-007464\nORD-003982\nORD-002760\nORD-006426\nORD-014290\nORD-002872\nORD-006520\nORD-004722\nORD-007267\nORD-009089\nORD-009833\nORD-013448\nORD-007719\nORD-013733\nORD-008471\nORD-005147\nORD-008547\nORD-014539\nORD-011703\nORD-010396\nORD-000874\nORD-001661\nORD-013445\nORD-006187\nORD-009616\nORD-004892\nORD-010701\nORD-000124\nORD-005388\nORD-008768\nORD-006315\nORD-008813'

# RAG Phase 2: Intent Detection

In [ ]:

# RAG PHASE 2 - STEP 1
# INTENT DETECTION

def detect_drone_intent(question):

    q = question.lower().strip()

    # --------------------------------------------------------
    # GENERAL FEASIBILITY
    # --------------------------------------------------------

    if (
        ("which" in q or "what" in q)
        and "drone route" in q
        and "feasible" in q
    ):
        return "GENERAL_FEASIBLE"


    # --------------------------------------------------------
    # GENERAL CAPACITY
    # --------------------------------------------------------

    if (
        ("which" in q or "what" in q)
        and "drone route" in q
        and (
            "exceed capacity" in q
            or "exceeds capacity" in q
            or "too heavy" in q
            or "vehicle capacity" in q
        )
    ):
        return "GENERAL_CAPACITY"


    # --------------------------------------------------------
    # GENERAL RANGE
    # --------------------------------------------------------

    if (
        ("which" in q or "what" in q)
        and "drone route" in q
        and (
            "within range" in q
            or "within maximum range" in q
            or "maximum range" in q
            or "max range" in q
        )
    ):
        return "GENERAL_RANGE"


    # ========================================================
    # SPECIFIC ORDER - FEASIBILITY
    # ========================================================

    feasibility_patterns = [

        "feasible",
        "feasibility",

        "suitable for drone",
        "suitable for drone delivery",
        "suitable for delivery",

        "can be delivered",
        "can be delivered by drone",

        "can the drone deliver",
        "can this drone deliver",

        "can i send",
        "can we send",

        "safe to send",
        "okay to send",

        "eligible for drone",

        "drone delivery"
    ]

    if any(pattern in q for pattern in feasibility_patterns):
        return "FEASIBILITY"


    # --------------------------------------------------------
    # NATURAL LANGUAGE:
    # "Can ORD-005379 be delivered by drone?"
    # --------------------------------------------------------

    if re.search(
        r"\bcan\s+ord-\d+\s+be\s+delivered\s+by\s+drone\b",
        q
    ):
        return "FEASIBILITY"


    # --------------------------------------------------------
    # NATURAL LANGUAGE:
    # "Can ORD-005379 be delivered?"
    # --------------------------------------------------------

    if re.search(
        r"\bcan\s+ord-\d+\s+be\s+delivered\b",
        q
    ):
        return "FEASIBILITY"


    # ========================================================
    # SPECIFIC ORDER - CAPACITY
    # ========================================================

    capacity_patterns = [

        "exceed capacity",
        "exceeds capacity",

        "too heavy",
        "heavy for the drone",

        "can the drone carry",
        "can drone carry",

        "weight limit",
        "vehicle capacity",
        "capacity"
    ]

    if any(pattern in q for pattern in capacity_patterns):
        return "CAPACITY"


    # ========================================================
    # SPECIFIC ORDER - RANGE
    # ========================================================

    range_patterns = [

        "maximum range",
        "max range",

        "within range",
        "within maximum range",

        "too far",
        "far for the drone",

        "reach the order",

        "can the drone reach",
        "can drone reach",

        "route too far",

        "range"
    ]

    if any(pattern in q for pattern in range_patterns):
        return "RANGE"


    # --------------------------------------------------------
    # UNKNOWN
    # --------------------------------------------------------

    return "UNKNOWN"

# Order ID Extraction

In [ ]:

def extract_order_id(question):

    match = re.search(
        r'\bORD-\d+\b',
        question,
        re.IGNORECASE
    )

    if match:
        return match.group(0).upper()

    return None

In [ ]:
# Test Order ID Extraction

test_questions = [
    "Can ORD-005379 be delivered by drone?",
    "Is ORD-014884 suitable for drone delivery?",
    "Can the drone carry ORD-005379?",
    "Which drone routes are feasible?"
]

for question in test_questions:

    order_id = extract_order_id(question)

    print("Question:", question)
    print("Order ID:", order_id)
    print("-" * 60)

Question: Can ORD-005379 be delivered by drone?
Order ID: ORD-005379
------------------------------------------------------------
Question: Is ORD-014884 suitable for drone delivery?
Order ID: ORD-014884
------------------------------------------------------------
Question: Can the drone carry ORD-005379?
Order ID: ORD-005379
------------------------------------------------------------
Question: Which drone routes are feasible?
Order ID: None
------------------------------------------------------------

# Connect to Retrieval

In [ ]:

# CONNECT INTENT + ORDER ID + RAG RETRIEVAL

def rag_phase2_retrieve(question):

    print("\n" + "=" * 70)
    print("RAG PHASE 2 - RETRIEVAL")
    print("=" * 70)

    print("QUESTION:")
    print(question)

    # --------------------------------------------------------
    # 1. DETECT INTENT
    # --------------------------------------------------------

    intent = detect_drone_intent(question)

    print("\nDETECTED INTENT:")
    print(intent)

    # --------------------------------------------------------
    # 2. EXTRACT ORDER ID
    # --------------------------------------------------------

    order_id = extract_order_id(question)

    print("\nORDER ID:")
    print(order_id)

    # --------------------------------------------------------
    # 3. UNKNOWN QUESTION
    # --------------------------------------------------------

    if intent == "UNKNOWN":

        print("\nSTATUS:")
        print("Unknown drone operation.")

        return None


    # --------------------------------------------------------
    # 4. SPECIFIC ORDER
    # --------------------------------------------------------

    if order_id is not None:

        retrieved = retrieve_drone_routes(
            f"order {order_id}"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:

            print("\nSTATUS:")
            print("No matching order found.")

            return None

        print("\nRETRIEVED ORDER:")
        print(order_id)

        return retrieved


    # --------------------------------------------------------
    # 5. GENERAL QUESTION
    # --------------------------------------------------------

    print("\nSTATUS:")
    print("General drone-route question.")

    return None

In [ ]:
test_question = "Can ORD-005379 be delivered by drone?"

retrieved = rag_phase2_retrieve(test_question)

======================================================================
RAG PHASE 2 - RETRIEVAL
======================================================================
QUESTION:
Can ORD-005379 be delivered by drone?

DETECTED INTENT:
FEASIBILITY

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

RETRIEVED ORDER:
ORD-005379

# DRONE DECISION VALUES

In [ ]:

# RAG PHASE 2 - STEP 4
# EXTRACT DRONE DECISION VALUES


def get_drone_order_data(question):

    # Detect intent
    intent = detect_drone_intent(question)

    # Extract order ID
    order_id = extract_order_id(question)

    print("\n" + "=" * 70)
    print("RAG PHASE 2 - ORDER DATA")
    print("=" * 70)

    print("QUESTION:")
    print(question)

    print("\nINTENT:")
    print(intent)

    print("\nORDER ID:")
    print(order_id)

    # No order ID
    if order_id is None:
        print("\nNo specific order ID found.")
        return None

    # Retrieve verified order
    retrieved = retrieve_drone_routes(
        f"order {order_id}"
    )

    print("\nRETRIEVED ROWS:")
    print(len(retrieved))

    # Order not found
    if retrieved.empty:
        print("\nOrder not found.")
        return None

    # Take verified row
    row = retrieved.iloc[0]

    # Extract values
    package_weight = float(row["package_weight"])
    capacity_kg = float(row["capacity_kg"])
    distance_km = float(row["distance_km"])
    max_range_km = float(row["max_range_km"])

    print("\nDRONE DATA:")
    print("Package Weight:", package_weight, "kg")
    print("Drone Capacity:", capacity_kg, "kg")
    print("Route Distance:", distance_km, "km")
    print("Maximum Range:", max_range_km, "km")

    return {
        "intent": intent,
        "order_id": order_id,
        "package_weight": package_weight,
        "capacity_kg": capacity_kg,
        "distance_km": distance_km,
        "max_range_km": max_range_km
    }

In [ ]:

test_question = "Can ORD-005379 be delivered by drone?"

drone_data = get_drone_order_data(test_question)

======================================================================
RAG PHASE 2 - ORDER DATA
======================================================================
QUESTION:
Can ORD-005379 be delivered by drone?

INTENT:
FEASIBILITY

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

DRONE DATA:
Package Weight: 1.54 kg
Drone Capacity: 2.0 kg
Route Distance: 5.01 km
Maximum Range: 15.2 km

# FEASIBILITY DECISION

In [ ]:

# RAG PHASE 2 - FEASIBILITY DECISION


def check_drone_feasibility(package_weight,
                             capacity_kg,
                             distance_km,
                             max_range_km):

    # Capacity check
    capacity_ok = package_weight <= capacity_kg

    # Range check
    range_ok = distance_km <= max_range_km

    # Overall feasibility
    feasible = capacity_ok and range_ok

    return capacity_ok, range_ok, feasible

In [ ]:

capacity_ok, range_ok, feasible = check_drone_feasibility(
    package_weight=1.54,
    capacity_kg=2.0,
    distance_km=5.01,
    max_range_km=15.2
)

print("=" * 70)
print("RAG PHASE 2 - FEASIBILITY DECISION")
print("=" * 70)

print("Capacity OK:", capacity_ok)
print("Range OK:", range_ok)
print("Overall Feasible:", feasible)

======================================================================
RAG PHASE 2 - FEASIBILITY DECISION
======================================================================
Capacity OK: True
Range OK: True
Overall Feasible: True

# NATURAL LANGUAGE FEASIBILITY ANSWER

In [ ]:


def generate_feasibility_answer(
    order_id,
    package_weight,
    capacity_kg,
    distance_km,
    max_range_km
):

    capacity_ok, range_ok, feasible = check_drone_feasibility(
        package_weight,
        capacity_kg,
        distance_km,
        max_range_km
    )

    if feasible:
        return (
            f"Yes, {order_id} can be delivered by drone. "
            f"The package weighs {package_weight} kg, "
            f"which is within the drone capacity of {capacity_kg} kg, "
            f"and the route distance is {distance_km} km, "
            f"which is within the maximum range of {max_range_km} km."
        )

    reasons = []

    if not capacity_ok:
        reasons.append(
            f"package weight ({package_weight} kg) exceeds "
            f"drone capacity ({capacity_kg} kg)"
        )

    if not range_ok:
        reasons.append(
            f"route distance ({distance_km} km) exceeds "
            f"maximum range ({max_range_km} km)"
        )

    return (
        f"No, {order_id} cannot be delivered by drone because "
        + " and ".join(reasons)
        + "."
    )

In [ ]:
answer = generate_feasibility_answer(
    order_id="ORD-005379",
    package_weight=1.54,
    capacity_kg=2.0,
    distance_km=5.01,
    max_range_km=15.2
)

print("=" * 70)
print("RAG PHASE 2 - FINAL ANSWER")
print("=" * 70)
print(answer)

======================================================================
RAG PHASE 2 - FINAL ANSWER
======================================================================
Yes, ORD-005379 can be delivered by drone. The package weighs 1.54 kg, which is within the drone capacity of 2.0 kg, and the route distance is 5.01 km, which is within the maximum range of 15.2 km.

# connect everything into ONE function

In [ ]:
# ============================================================
# RAG PHASE 2 - COMPLETE SPECIFIC ORDER PIPELINE
# ============================================================

def rag_phase2_order(question):

    print("\n" + "=" * 70)
    print("RAG PHASE 2 - COMPLETE PIPELINE")
    print("=" * 70)

    print("\nQUESTION:")
    print(question)

    # --------------------------------------------------------
    # 1. Detect intent
    # --------------------------------------------------------

    intent = detect_drone_intent(question)

    print("\nINTENT:")
    print(intent)

    # --------------------------------------------------------
    # 2. Extract order ID
    # --------------------------------------------------------

    order_id = extract_order_id(question)

    print("\nORDER ID:")
    print(order_id)

    # --------------------------------------------------------
    # 3. Validate
    # --------------------------------------------------------

    if intent == "UNKNOWN":

        return (
            "I could not determine the drone operation "
            "from the question."
        )

    if order_id is None:

        return "Please provide a valid order ID."

    # --------------------------------------------------------
    # 4. Retrieve order
    # --------------------------------------------------------

    retrieved = retrieve_drone_routes(
        f"order {order_id}"
    )

    print("\nRETRIEVED ROWS:")
    print(len(retrieved))

    if retrieved.empty:

        return (
            f"No matching drone order was found for {order_id}."
        )

    # --------------------------------------------------------
    # 5. Get first matching order
    # --------------------------------------------------------

    row = retrieved.iloc[0]

    package_weight = float(
        row["package_weight"]
    )

    capacity_kg = float(
        row["capacity_kg"]
    )

    distance_km = float(
        row["distance_km"]
    )

    max_range_km = float(
        row["max_range_km"]
    )

    print("\nDRONE DATA:")

    print(
        "Package Weight:",
        package_weight,
        "kg"
    )

    print(
        "Drone Capacity:",
        capacity_kg,
        "kg"
    )

    print(
        "Route Distance:",
        distance_km,
        "km"
    )

    print(
        "Maximum Range:",
        max_range_km,
        "km"
    )

    # ========================================================
    # 6. FEASIBILITY
    # ========================================================

    if intent == "FEASIBILITY":

        answer = generate_feasibility_answer(
            order_id,
            package_weight,
            capacity_kg,
            distance_km,
            max_range_km
        )

        print("\nFINAL ANSWER:")
        print(answer)

        return answer

    # ========================================================
    # 7. CAPACITY
    # ========================================================

    if intent == "CAPACITY":

        if package_weight <= capacity_kg:

            answer = (
                f"Yes, the drone can carry {order_id}. "
                f"The package weighs {package_weight} kg, "
                f"which is within the drone capacity of "
                f"{capacity_kg} kg."
            )

        else:

            answer = (
                f"No, the drone cannot carry {order_id}. "
                f"The package weighs {package_weight} kg, "
                f"which exceeds the drone capacity of "
                f"{capacity_kg} kg."
            )

        print("\nFINAL ANSWER:")
        print(answer)

        return answer

    # ========================================================
    # 8. RANGE
    # ========================================================

    if intent == "RANGE":

        if distance_km <= max_range_km:

            answer = (
                f"Yes, {order_id} is within maximum range "
                f"({distance_km} km <= {max_range_km} km)."
            )

        else:

            answer = (
                f"No, {order_id} exceeds maximum range "
                f"({distance_km} km > {max_range_km} km)."
            )

        print("\nFINAL ANSWER:")
        print(answer)

        return answer

    # ========================================================
    # 9. FALLBACK
    # ========================================================

    return "This drone operation is not yet implemented."

In [ ]:
result = rag_phase2_order(
    "Can the drone carry ORD-005379?"
)

print("\nRETURNED RESULT:")
print(result)

======================================================================
RAG PHASE 2 - COMPLETE PIPELINE
======================================================================

QUESTION:
Can the drone carry ORD-005379?

INTENT:
CAPACITY

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

DRONE DATA:
Package Weight: 1.54 kg
Drone Capacity: 2.0 kg
Route Distance: 5.01 km
Maximum Range: 15.2 km

FINAL ANSWER:
Yes, the drone can carry ORD-005379. The package weighs 1.54 kg, which is within the drone capacity of 2.0 kg.

RETURNED RESULT:
Yes, the drone can carry ORD-005379. The package weighs 1.54 kg, which is within the drone capacity of 2.0 kg.

In [ ]:
tests = [
    "Can ORD-005379 be delivered by drone?",
    "Can the drone carry ORD-005379?",
    "Can the drone reach ORD-005379?"
]

for q in tests:
    result = rag_phase2_order(q)

    print("\nRETURNED RESULT:")
    print(result)

======================================================================
RAG PHASE 2 - COMPLETE PIPELINE
======================================================================

QUESTION:
Can ORD-005379 be delivered by drone?

INTENT:
FEASIBILITY

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

DRONE DATA:
Package Weight: 1.54 kg
Drone Capacity: 2.0 kg
Route Distance: 5.01 km
Maximum Range: 15.2 km

FINAL ANSWER:
Yes, ORD-005379 can be delivered by drone. The package weighs 1.54 kg, which is within the drone capacity of 2.0 kg, and the route distance is 5.01 km, which is within the maximum range of 15.2 km.

RETURNED RESULT:
Yes, ORD-005379 can be delivered by drone. The package weighs 1.54 kg, which is within the drone capacity of 2.0 kg, and the route distance is 5.01 km, which is within the maximum range of 15.2 km.

======================================================================
RAG PHASE 2 - COMPLETE PIPELINE
======================================================================

QUESTION:
Can the drone carry ORD-005379?

INTENT:
CAPACITY

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

DRONE DATA:
Package Weight: 1.54 kg
Drone Capacity: 2.0 kg
Route Distance: 5.01 km
Maximum Range: 15.2 km

FINAL ANSWER:
Yes, the drone can carry ORD-005379. The package weighs 1.54 kg, which is within the drone capacity of 2.0 kg.

RETURNED RESULT:
Yes, the drone can carry ORD-005379. The package weighs 1.54 kg, which is within the drone capacity of 2.0 kg.

======================================================================
RAG PHASE 2 - COMPLETE PIPELINE
======================================================================

QUESTION:
Can the drone reach ORD-005379?

INTENT:
RANGE

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

DRONE DATA:
Package Weight: 1.54 kg
Drone Capacity: 2.0 kg
Route Distance: 5.01 km
Maximum Range: 15.2 km

FINAL ANSWER:
Yes, ORD-005379 is within maximum range (5.01 km <= 15.2 km).

RETURNED RESULT:
Yes, ORD-005379 is within maximum range (5.01 km <= 15.2 km).

# GENERAL QUERY PIPELINE

In [ ]:
# ============================================================
# RAG PHASE 2 - COMPLETE SPECIFIC + GENERAL QUERY PIPELINE
# ============================================================

def rag_phase2_order(question):

    print("\n" + "=" * 70)
    print("RAG PHASE 2 - COMPLETE PIPELINE")
    print("=" * 70)

    print("\nQUESTION:")
    print(question)

    # --------------------------------------------------------
    # 1. Detect intent
    # --------------------------------------------------------

    intent = detect_drone_intent(question)

    print("\nINTENT:")
    print(intent)

    # --------------------------------------------------------
    # 2. Extract order ID
    # --------------------------------------------------------

    order_id = extract_order_id(question)

    print("\nORDER ID:")
    print(order_id)

    # ========================================================
    # 3. HANDLE GENERAL QUERIES FIRST
    # ========================================================

    # --------------------------------------------------------
    # GENERAL FEASIBLE ROUTES
    # --------------------------------------------------------

    if intent == "GENERAL_FEASIBLE":

        retrieved = retrieve_drone_routes(
            "feasible drone routes"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            return "No feasible drone routes were found."

        feasible_routes = []

        for _, row in retrieved.iterrows():

            package_weight = float(row["package_weight"])
            capacity_kg = float(row["capacity_kg"])
            distance_km = float(row["distance_km"])
            max_range_km = float(row["max_range_km"])

            if (
                package_weight <= capacity_kg
                and distance_km <= max_range_km
            ):
                feasible_routes.append(row["order_id"])

        print("\nGENERAL FEASIBLE ROUTES:")
        print("Total:", len(feasible_routes))

        for order in feasible_routes:
            print(order)

        return feasible_routes

    # --------------------------------------------------------
    # GENERAL CAPACITY VIOLATIONS
    # --------------------------------------------------------

    if intent == "GENERAL_CAPACITY":

        print("\nRETRIEVED ROWS:")
        print(len(df))

    # Directly calculate capacity violations from the full dataframe
    capacity_violations_df = df[
        df["package_weight"] > df["capacity_kg"]
    ]

    print("\nGENERAL CAPACITY VIOLATIONS:")
    print("Total:", len(capacity_violations_df))

    capacity_violations = capacity_violations_df["order_id"].tolist()

    for order in capacity_violations:
        print(order)

    return capacity_violations
    # --------------------------------------------------------
    # GENERAL RANGE ROUTES
    # --------------------------------------------------------

    if intent == "GENERAL_RANGE":

        retrieved = retrieve_drone_routes(
            "drone routes within maximum range"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            return "No routes within maximum range were found."

        range_routes = []

        for _, row in retrieved.iterrows():

            distance_km = float(row["distance_km"])
            max_range_km = float(row["max_range_km"])

            if distance_km <= max_range_km:
                range_routes.append(row["order_id"])

        print("\nGENERAL RANGE ROUTES:")
        print("Total:", len(range_routes))

        for order in range_routes:
            print(order)

        return range_routes

    # ========================================================
    # 4. SPECIFIC ORDER VALIDATION
    # ========================================================

    if intent == "UNKNOWN":
        return "I could not determine the drone operation from the question."

    if order_id is None:
        return "Please provide a valid order ID."

    # ========================================================
    # 5. RETRIEVE SPECIFIC ORDER
    # ========================================================

    retrieved = retrieve_drone_routes(
        f"order {order_id}"
    )

    print("\nRETRIEVED ROWS:")
    print(len(retrieved))

    if retrieved.empty:
        return f"No matching drone order was found for {order_id}."

    # --------------------------------------------------------
    # 6. Get first matching order
    # --------------------------------------------------------

    row = retrieved.iloc[0]

    package_weight = float(row["package_weight"])
    capacity_kg = float(row["capacity_kg"])
    distance_km = float(row["distance_km"])
    max_range_km = float(row["max_range_km"])

    print("\nDRONE DATA:")
    print("Package Weight:", package_weight, "kg")
    print("Drone Capacity:", capacity_kg, "kg")
    print("Route Distance:", distance_km, "km")
    print("Maximum Range:", max_range_km, "km")

    # ========================================================
    # 7. FEASIBILITY
    # ========================================================

    if intent == "FEASIBILITY":

        answer = generate_feasibility_answer(
            order_id,
            package_weight,
            capacity_kg,
            distance_km,
            max_range_km
        )

        print("\nFINAL ANSWER:")
        print(answer)

        return answer

    # ========================================================
    # 8. CAPACITY
    # ========================================================

    if intent == "CAPACITY":

        # If the question is asking whether it exceeds capacity
        if "exceed" in question.lower():

            if package_weight > capacity_kg:

                answer = (
                    f"Yes, {order_id} exceeds the drone capacity. "
                    f"The package weighs {package_weight} kg, "
                    f"which is greater than the drone capacity "
                    f"of {capacity_kg} kg."
                )

            else:

                answer = (
                    f"No, {order_id} does not exceed the drone capacity. "
                    f"The package weighs {package_weight} kg, "
                    f"which is within the drone capacity "
                    f"of {capacity_kg} kg."
                )

        else:

            if package_weight <= capacity_kg:

                answer = (
                    f"Yes, the drone can carry {order_id}. "
                    f"The package weighs {package_weight} kg, "
                    f"which is within the drone capacity "
                    f"of {capacity_kg} kg."
                )

            else:

                answer = (
                    f"No, the drone cannot carry {order_id}. "
                    f"The package weighs {package_weight} kg, "
                    f"which exceeds the drone capacity "
                    f"of {capacity_kg} kg."
                )

        print("\nFINAL ANSWER:")
        print(answer)

        return answer

    # ========================================================
    # 9. RANGE
    # ========================================================

    if intent == "RANGE":

        # If question asks whether route is too far
        if "too far" in question.lower():

            if distance_km > max_range_km:

                answer = (
                    f"Yes, the route for {order_id} is too far. "
                    f"The route distance is {distance_km} km, "
                    f"which exceeds the maximum range of "
                    f"{max_range_km} km."
                )

            else:

                answer = (
                    f"No, the route for {order_id} is not too far. "
                    f"The route distance is {distance_km} km, "
                    f"which is within the maximum range of "
                    f"{max_range_km} km."
                )

        else:

            if distance_km <= max_range_km:

                answer = (
                    f"Yes, {order_id} is within maximum range "
                    f"({distance_km} km <= {max_range_km} km)."
                )

            else:

                answer = (
                    f"No, {order_id} exceeds maximum range "
                    f"({distance_km} km > {max_range_km} km)."
                )

        print("\nFINAL ANSWER:")
        print(answer)

        return answer

    # ========================================================
    # 10. FALLBACK
    # ========================================================

    return "This drone operation is not yet implemented."

In [ ]:
tests = [
    "Can ORD-005379 be delivered by drone?",
    "Can the drone carry ORD-005379?",
    "Can the drone reach ORD-005379?",
    "Is ORD-005379 too heavy for the drone?",
    "Does ORD-005379 exceed the drone capacity?",
    "Is the route for ORD-005379 too far?",
    "Which drone routes are feasible?",
    "Which drone routes exceed capacity?",
    "Which drone routes are within maximum range?"
]

for q in tests:

    result = rag_phase2_order(q)

    print("\nRETURNED RESULT:")
    print(result)

======================================================================
RAG PHASE 2 - COMPLETE PIPELINE
======================================================================

QUESTION:
Can ORD-005379 be delivered by drone?

INTENT:
FEASIBILITY

ORDER ID:
ORD-005379

GENERAL CAPACITY VIOLATIONS:
Total: 288
ORD-002549
ORD-012343
ORD-000680
ORD-009988
ORD-011103
ORD-013759
ORD-009549
ORD-013534
ORD-003907
ORD-014531
ORD-014960
ORD-011168
ORD-001245
ORD-004200
ORD-014348
ORD-012625
ORD-008272
ORD-005888
ORD-011323
ORD-010911
ORD-009512
ORD-005054
ORD-008528
ORD-009819
ORD-009934
ORD-001622
ORD-001691
ORD-011958
ORD-002595
ORD-009820
ORD-010704
ORD-001532
ORD-002676
ORD-003107
ORD-004846
ORD-013949
ORD-000821
ORD-008743
ORD-005589
ORD-013791
ORD-000943
ORD-000495
ORD-007031
ORD-003709
ORD-010443
ORD-005127
ORD-006254
ord-004802
ORD-004921
ORD-000199
ORD-000228
ORD-007187
ORD-005278
ORD-012715
ORD-011935
ORD-007863
ORD-003150
ORD-010847
ORD-002867
ORD-014740
ORD-003921
ORD-005692
ORD-014845
ORD-010179
ORD-014429
ORD-004543
ORD-002136
ORD-009577
ORD-013537
ORD-008123
ORD-011763
ORD-008022
ORD-008681
ORD-008966
ORD-007284
ORD-014555
ORD-002444
ORD-010519
ORD-007938
ORD-008263
ORD-009163
ORD-004526
ORD-008452
ORD-001482
ORD-008055
ORD-000303
ORD-002851
ORD-005345
ORD-006882
ORD-006462
ORD-003887
ORD-002236
ORD-001937
ORD-007240
ORD-002976
ORD-005298
ORD-003084
ORD-009136
ORD-006259
ORD-005134
ORD-011532
ORD-005500
ORD-014236
ORD-005178
ORD-008679
ORD-004304
ORD-008212
ORD-009601
ORD-014258
ORD-010146
ORD-011437
ORD-013656
ORD-002589
ORD-001989
ORD-014537
ORD-005351
ORD-009784
ORD-004827
ORD-003725
ORD-010403
ORD-005033
ORD-001368
ORD-010709
ORD-008631
ORD-012325
ORD-012191
ORD-011606
ORD-008133
ORD-004833
ORD-003556
ORD-007046
ORD-013510
ORD-011571
ORD-002645
ORD-014869
ORD-012534
ORD-004901
ORD-014128
ORD-010223
ORD-013436
ORD-014458
ORD-014944
ORD-014166
ORD-003727
ORD-005353
ORD-002904
ORD-001490
ORD-007453
ORD-006165
ORD-003626
ORD-008426
ORD-004676
ORD-006316
ORD-014651
ORD-014575
ORD-010840
ORD-014065
ORD-002189
ORD-009299
ORD-011335
ORD-002094
ORD-004590
ORD-002194
ORD-003776
ORD-001701
ORD-013148
ORD-010027
ORD-009479
ORD-014435
ORD-011936
ORD-012680
ORD-003992
ORD-011538
ORD-006771
ORD-003828
ORD-014967
ORD-000183
ORD-003780
ORD-006772
ORD-006085
ORD-004637
ORD-010029
ORD-014316
ORD-006916
ORD-014558
ORD-001569
ORD-011422
ORD-005480
ORD-010084
ORD-002520
ORD-010759
ORD-007784
ORD-001950
ORD-012602
ORD-000281
ORD-005645
ORD-014045
ORD-008971
ORD-000359
ORD-006157
ORD-000928
ORD-002334
ORD-006560
ORD-000484
ORD-008222
ORD-004131
ORD-013021
ORD-014564
ORD-005271
ORD-011457
ORD-007611
ORD-013649
ORD-003889
ORD-007323
ORD-009651
ORD-006118
ORD-014768
ORD-009470
ORD-000046
ORD-000005
ORD-011275
ORD-000704
ORD-008064
ORD-007978
ORD-013283
ORD-014789
ORD-005132
ORD-000881
ORD-013705
ORD-010526
ORD-007237
ORD-002293
ORD-011698
ORD-014269
ORD-001677
ORD-001791
ORD-005113
ORD-000748
ORD-013325
ORD-012660
ORD-010159
ORD-012945
ORD-014637
ORD-005473
ORD-005756
ORD-005354
ORD-000900
ORD-013248
ORD-004144
ORD-009718
ORD-003778
ORD-003325
ORD-001627
ORD-001105
ORD-014750
ORD-007995
ORD-001344
ORD-011634
ORD-000414
ORD-013923
ORD-009373
ORD-006242
ORD-003414
ORD-008070
ORD-008078
ORD-009177
ORD-009415
ORD-012389
ORD-007579
ORD-008812
ORD-007464
ORD-002760
ORD-014873
ORD-001256
ORD-013969
ORD-013733
ORD-000892
ORD-009164
ORD-003032
ORD-008136
ORD-008663
ORD-008547
ORD-011444
ORD-010396
ORD-001138
ORD-000124
ORD-005238
ORD-006315

RETURNED RESULT:
['ORD-002549', 'ORD-012343', 'ORD-000680', 'ORD-009988', 'ORD-011103', 'ORD-013759', 'ORD-009549', 'ORD-013534', 'ORD-003907', 'ORD-014531', 'ORD-014960', 'ORD-011168', 'ORD-001245', 'ORD-004200', 'ORD-014348', 'ORD-012625', 'ORD-008272', 'ORD-005888', 'ORD-011323', 'ORD-010911', 'ORD-009512', 'ORD-005054', 'ORD-008528', 'ORD-009819', 'ORD-009934', 'ORD-001622', 'ORD-001691', 'ORD-011958', 'ORD-002595', 'ORD-009820', 'ORD-010704', 'ORD-001532', 'ORD-002676', 'ORD-003107', 'ORD-004846', 'ORD-013949', 'ORD-000821', 'ORD-008743', 'ORD-005589', 'ORD-013791', 'ORD-000943', 'ORD-000495', 'ORD-007031', 'ORD-003709', 'ORD-010443', 'ORD-005127', 'ORD-006254', 'ord-004802', 'ORD-004921', 'ORD-000199', 'ORD-000228', 'ORD-007187', 'ORD-005278', 'ORD-012715', 'ORD-011935', 'ORD-007863', 'ORD-003150', 'ORD-010847', 'ORD-002867', 'ORD-014740', 'ORD-003921', 'ORD-005692', 'ORD-014845', 'ORD-010179', 'ORD-014429', 'ORD-004543', 'ORD-002136', 'ORD-009577', 'ORD-013537', 'ORD-008123', 'ORD-011763', 'ORD-008022', 'ORD-008681', 'ORD-008966', 'ORD-007284', 'ORD-014555', 'ORD-002444', 'ORD-010519', 'ORD-007938', 'ORD-008263', 'ORD-009163', 'ORD-004526', 'ORD-008452', 'ORD-001482', 'ORD-008055', 'ORD-000303', 'ORD-002851', 'ORD-005345', 'ORD-006882', 'ORD-006462', 'ORD-003887', 'ORD-002236', 'ORD-001937', 'ORD-007240', 'ORD-002976', 'ORD-005298', 'ORD-003084', 'ORD-009136', 'ORD-006259', 'ORD-005134', 'ORD-011532', 'ORD-005500', 'ORD-014236', 'ORD-005178', 'ORD-008679', 'ORD-004304', 'ORD-008212', 'ORD-009601', 'ORD-014258', 'ORD-010146', 'ORD-011437', 'ORD-013656', 'ORD-002589', 'ORD-001989', 'ORD-014537', 'ORD-005351', 'ORD-009784', 'ORD-004827', 'ORD-003725', 'ORD-010403', 'ORD-005033', 'ORD-001368', 'ORD-010709', 'ORD-008631', 'ORD-012325', 'ORD-012191', 'ORD-011606', 'ORD-008133', 'ORD-004833', 'ORD-003556', 'ORD-007046', 'ORD-013510', 'ORD-011571', 'ORD-002645', 'ORD-014869', 'ORD-012534', 'ORD-004901', 'ORD-014128', 'ORD-010223', 'ORD-013436', 'ORD-014458', 'ORD-014944', 'ORD-014166', 'ORD-003727', 'ORD-005353', 'ORD-002904', 'ORD-001490', 'ORD-007453', 'ORD-006165', 'ORD-003626', 'ORD-008426', 'ORD-004676', 'ORD-006316', 'ORD-014651', 'ORD-014575', 'ORD-010840', 'ORD-014065', 'ORD-002189', 'ORD-009299', 'ORD-011335', 'ORD-002094', 'ORD-004590', 'ORD-002194', 'ORD-003776', 'ORD-001701', 'ORD-013148', 'ORD-010027', 'ORD-009479', 'ORD-014435', 'ORD-011936', 'ORD-012680', 'ORD-003992', 'ORD-011538', 'ORD-006771', 'ORD-003828', 'ORD-014967', 'ORD-000183', 'ORD-003780', 'ORD-006772', 'ORD-006085', 'ORD-004637', 'ORD-010029', 'ORD-014316', 'ORD-006916', 'ORD-014558', 'ORD-001569', 'ORD-011422', 'ORD-005480', 'ORD-010084', 'ORD-002520', 'ORD-010759', 'ORD-007784', 'ORD-001950', 'ORD-012602', 'ORD-000281', 'ORD-005645', 'ORD-014045', 'ORD-008971', 'ORD-000359', 'ORD-006157', 'ORD-000928', 'ORD-002334', 'ORD-006560', 'ORD-000484', 'ORD-008222', 'ORD-004131', 'ORD-013021', 'ORD-014564', 'ORD-005271', 'ORD-011457', 'ORD-007611', 'ORD-013649', 'ORD-003889', 'ORD-007323', 'ORD-009651', 'ORD-006118', 'ORD-014768', 'ORD-009470', 'ORD-000046', 'ORD-000005', 'ORD-011275', 'ORD-000704', 'ORD-008064', 'ORD-007978', 'ORD-013283', 'ORD-014789', 'ORD-005132', 'ORD-000881', 'ORD-013705', 'ORD-010526', 'ORD-007237', 'ORD-002293', 'ORD-011698', 'ORD-014269', 'ORD-001677', 'ORD-001791', 'ORD-005113', 'ORD-000748', 'ORD-013325', 'ORD-012660', 'ORD-010159', 'ORD-012945', 'ORD-014637', 'ORD-005473', 'ORD-005756', 'ORD-005354', 'ORD-000900', 'ORD-013248', 'ORD-004144', 'ORD-009718', 'ORD-003778', 'ORD-003325', 'ORD-001627', 'ORD-001105', 'ORD-014750', 'ORD-007995', 'ORD-001344', 'ORD-011634', 'ORD-000414', 'ORD-013923', 'ORD-009373', 'ORD-006242', 'ORD-003414', 'ORD-008070', 'ORD-008078', 'ORD-009177', 'ORD-009415', 'ORD-012389', 'ORD-007579', 'ORD-008812', 'ORD-007464', 'ORD-002760', 'ORD-014873', 'ORD-001256', 'ORD-013969', 'ORD-013733', 'ORD-000892', 'ORD-009164', 'ORD-003032', 'ORD-008136', 'ORD-008663', 'ORD-008547', 'ORD-011444', 'ORD-010396', 'ORD-001138', 'ORD-000124', 'ORD-005238', 'ORD-006315']

======================================================================
RAG PHASE 2 - COMPLETE PIPELINE
======================================================================

QUESTION:
Can the drone carry ORD-005379?

INTENT:
CAPACITY

ORDER ID:
ORD-005379

GENERAL CAPACITY VIOLATIONS:
Total: 288
ORD-002549
ORD-012343
ORD-000680
ORD-009988
ORD-011103
ORD-013759
ORD-009549
ORD-013534
ORD-003907
ORD-014531
ORD-014960
ORD-011168
ORD-001245
ORD-004200
ORD-014348
ORD-012625
ORD-008272
ORD-005888
ORD-011323
ORD-010911
ORD-009512
ORD-005054
ORD-008528
ORD-009819
ORD-009934
ORD-001622
ORD-001691
ORD-011958
ORD-002595
ORD-009820
ORD-010704
ORD-001532
ORD-002676
ORD-003107
ORD-004846
ORD-013949
ORD-000821
ORD-008743
ORD-005589
ORD-013791
ORD-000943
ORD-000495
ORD-007031
ORD-003709
ORD-010443
ORD-005127
ORD-006254
ord-004802
ORD-004921
ORD-000199
ORD-000228
ORD-007187
ORD-005278
ORD-012715
ORD-011935
ORD-007863
ORD-003150
ORD-010847
ORD-002867
ORD-014740
ORD-003921
ORD-005692
ORD-014845
ORD-010179
ORD-014429
ORD-004543
ORD-002136
ORD-009577
ORD-013537
ORD-008123
ORD-011763
ORD-008022
ORD-008681
ORD-008966
ORD-007284
ORD-014555
ORD-002444
ORD-010519
ORD-007938
ORD-008263
ORD-009163
ORD-004526
ORD-008452
ORD-001482
ORD-008055
ORD-000303
ORD-002851
ORD-005345
ORD-006882
ORD-006462
ORD-003887
ORD-002236
ORD-001937
ORD-007240
ORD-002976
ORD-005298
ORD-003084
ORD-009136
ORD-006259
ORD-005134
ORD-011532
ORD-005500
ORD-014236
ORD-005178
ORD-008679
ORD-004304
ORD-008212
ORD-009601
ORD-014258
ORD-010146
ORD-011437
ORD-013656
ORD-002589
ORD-001989
ORD-014537
ORD-005351
ORD-009784
ORD-004827
ORD-003725
ORD-010403
ORD-005033
ORD-001368
ORD-010709
ORD-008631
ORD-012325
ORD-012191
ORD-011606
ORD-008133
ORD-004833
ORD-003556
ORD-007046
ORD-013510
ORD-011571
ORD-002645
ORD-014869
ORD-012534
ORD-004901
ORD-014128
ORD-010223
ORD-013436
ORD-014458
ORD-014944
ORD-014166
ORD-003727
ORD-005353
ORD-002904
ORD-001490
ORD-007453
ORD-006165
ORD-003626
ORD-008426
ORD-004676
ORD-006316
ORD-014651
ORD-014575
ORD-010840
ORD-014065
ORD-002189
ORD-009299
ORD-011335
ORD-002094
ORD-004590
ORD-002194
ORD-003776
ORD-001701
ORD-013148
ORD-010027
ORD-009479
ORD-014435
ORD-011936
ORD-012680
ORD-003992
ORD-011538
ORD-006771
ORD-003828
ORD-014967
ORD-000183
ORD-003780
ORD-006772
ORD-006085
ORD-004637
ORD-010029
ORD-014316
ORD-006916
ORD-014558
ORD-001569
ORD-011422
ORD-005480
ORD-010084
ORD-002520
ORD-010759
ORD-007784
ORD-001950
ORD-012602
ORD-000281
ORD-005645
ORD-014045
ORD-008971
ORD-000359
ORD-006157
ORD-000928
ORD-002334
ORD-006560
ORD-000484
ORD-008222
ORD-004131
ORD-013021
ORD-014564
ORD-005271
ORD-011457
ORD-007611
ORD-013649
ORD-003889
ORD-007323
ORD-009651
ORD-006118
ORD-014768
ORD-009470
ORD-000046
ORD-000005
ORD-011275
ORD-000704
ORD-008064
ORD-007978
ORD-013283
ORD-014789
ORD-005132
ORD-000881
ORD-013705
ORD-010526
ORD-007237
ORD-002293
ORD-011698
ORD-014269
ORD-001677
ORD-001791
ORD-005113
ORD-000748
ORD-013325
ORD-012660
ORD-010159
ORD-012945
ORD-014637
ORD-005473
ORD-005756
ORD-005354
ORD-000900
ORD-013248
ORD-004144
ORD-009718
ORD-003778
ORD-003325
ORD-001627
ORD-001105
ORD-014750
ORD-007995
ORD-001344
ORD-011634
ORD-000414
ORD-013923
ORD-009373
ORD-006242
ORD-003414
ORD-008070
ORD-008078
ORD-009177
ORD-009415
ORD-012389
ORD-007579
ORD-008812
ORD-007464
ORD-002760
ORD-014873
ORD-001256
ORD-013969
ORD-013733
ORD-000892
ORD-009164
ORD-003032
ORD-008136
ORD-008663
ORD-008547
ORD-011444
ORD-010396
ORD-001138
ORD-000124
ORD-005238
ORD-006315

RETURNED RESULT:
['ORD-002549', 'ORD-012343', 'ORD-000680', 'ORD-009988', 'ORD-011103', 'ORD-013759', 'ORD-009549', 'ORD-013534', 'ORD-003907', 'ORD-014531', 'ORD-014960', 'ORD-011168', 'ORD-001245', 'ORD-004200', 'ORD-014348', 'ORD-012625', 'ORD-008272', 'ORD-005888', 'ORD-011323', 'ORD-010911', 'ORD-009512', 'ORD-005054', 'ORD-008528', 'ORD-009819', 'ORD-009934', 'ORD-001622', 'ORD-001691', 'ORD-011958', 'ORD-002595', 'ORD-009820', 'ORD-010704', 'ORD-001532', 'ORD-002676', 'ORD-003107', 'ORD-004846', 'ORD-013949', 'ORD-000821', 'ORD-008743', 'ORD-005589', 'ORD-013791', 'ORD-000943', 'ORD-000495', 'ORD-007031', 'ORD-003709', 'ORD-010443', 'ORD-005127', 'ORD-006254', 'ord-004802', 'ORD-004921', 'ORD-000199', 'ORD-000228', 'ORD-007187', 'ORD-005278', 'ORD-012715', 'ORD-011935', 'ORD-007863', 'ORD-003150', 'ORD-010847', 'ORD-002867', 'ORD-014740', 'ORD-003921', 'ORD-005692', 'ORD-014845', 'ORD-010179', 'ORD-014429', 'ORD-004543', 'ORD-002136', 'ORD-009577', 'ORD-013537', 'ORD-008123', 'ORD-011763', 'ORD-008022', 'ORD-008681', 'ORD-008966', 'ORD-007284', 'ORD-014555', 'ORD-002444', 'ORD-010519', 'ORD-007938', 'ORD-008263', 'ORD-009163', 'ORD-004526', 'ORD-008452', 'ORD-001482', 'ORD-008055', 'ORD-000303', 'ORD-002851', 'ORD-005345', 'ORD-006882', 'ORD-006462', 'ORD-003887', 'ORD-002236', 'ORD-001937', 'ORD-007240', 'ORD-002976', 'ORD-005298', 'ORD-003084', 'ORD-009136', 'ORD-006259', 'ORD-005134', 'ORD-011532', 'ORD-005500', 'ORD-014236', 'ORD-005178', 'ORD-008679', 'ORD-004304', 'ORD-008212', 'ORD-009601', 'ORD-014258', 'ORD-010146', 'ORD-011437', 'ORD-013656', 'ORD-002589', 'ORD-001989', 'ORD-014537', 'ORD-005351', 'ORD-009784', 'ORD-004827', 'ORD-003725', 'ORD-010403', 'ORD-005033', 'ORD-001368', 'ORD-010709', 'ORD-008631', 'ORD-012325', 'ORD-012191', 'ORD-011606', 'ORD-008133', 'ORD-004833', 'ORD-003556', 'ORD-007046', 'ORD-013510', 'ORD-011571', 'ORD-002645', 'ORD-014869', 'ORD-012534', 'ORD-004901', 'ORD-014128', 'ORD-010223', 'ORD-013436', 'ORD-014458', 'ORD-014944', 'ORD-014166', 'ORD-003727', 'ORD-005353', 'ORD-002904', 'ORD-001490', 'ORD-007453', 'ORD-006165', 'ORD-003626', 'ORD-008426', 'ORD-004676', 'ORD-006316', 'ORD-014651', 'ORD-014575', 'ORD-010840', 'ORD-014065', 'ORD-002189', 'ORD-009299', 'ORD-011335', 'ORD-002094', 'ORD-004590', 'ORD-002194', 'ORD-003776', 'ORD-001701', 'ORD-013148', 'ORD-010027', 'ORD-009479', 'ORD-014435', 'ORD-011936', 'ORD-012680', 'ORD-003992', 'ORD-011538', 'ORD-006771', 'ORD-003828', 'ORD-014967', 'ORD-000183', 'ORD-003780', 'ORD-006772', 'ORD-006085', 'ORD-004637', 'ORD-010029', 'ORD-014316', 'ORD-006916', 'ORD-014558', 'ORD-001569', 'ORD-011422', 'ORD-005480', 'ORD-010084', 'ORD-002520', 'ORD-010759', 'ORD-007784', 'ORD-001950', 'ORD-012602', 'ORD-000281', 'ORD-005645', 'ORD-014045', 'ORD-008971', 'ORD-000359', 'ORD-006157', 'ORD-000928', 'ORD-002334', 'ORD-006560', 'ORD-000484', 'ORD-008222', 'ORD-004131', 'ORD-013021', 'ORD-014564', 'ORD-005271', 'ORD-011457', 'ORD-007611', 'ORD-013649', 'ORD-003889', 'ORD-007323', 'ORD-009651', 'ORD-006118', 'ORD-014768', 'ORD-009470', 'ORD-000046', 'ORD-000005', 'ORD-011275', 'ORD-000704', 'ORD-008064', 'ORD-007978', 'ORD-013283', 'ORD-014789', 'ORD-005132', 'ORD-000881', 'ORD-013705', 'ORD-010526', 'ORD-007237', 'ORD-002293', 'ORD-011698', 'ORD-014269', 'ORD-001677', 'ORD-001791', 'ORD-005113', 'ORD-000748', 'ORD-013325', 'ORD-012660', 'ORD-010159', 'ORD-012945', 'ORD-014637', 'ORD-005473', 'ORD-005756', 'ORD-005354', 'ORD-000900', 'ORD-013248', 'ORD-004144', 'ORD-009718', 'ORD-003778', 'ORD-003325', 'ORD-001627', 'ORD-001105', 'ORD-014750', 'ORD-007995', 'ORD-001344', 'ORD-011634', 'ORD-000414', 'ORD-013923', 'ORD-009373', 'ORD-006242', 'ORD-003414', 'ORD-008070', 'ORD-008078', 'ORD-009177', 'ORD-009415', 'ORD-012389', 'ORD-007579', 'ORD-008812', 'ORD-007464', 'ORD-002760', 'ORD-014873', 'ORD-001256', 'ORD-013969', 'ORD-013733', 'ORD-000892', 'ORD-009164', 'ORD-003032', 'ORD-008136', 'ORD-008663', 'ORD-008547', 'ORD-011444', 'ORD-010396', 'ORD-001138', 'ORD-000124', 'ORD-005238', 'ORD-006315']

======================================================================
RAG PHASE 2 - COMPLETE PIPELINE
======================================================================

QUESTION:
Can the drone reach ORD-005379?

INTENT:
RANGE

ORDER ID:
ORD-005379

GENERAL CAPACITY VIOLATIONS:
Total: 288
ORD-002549
ORD-012343
ORD-000680
ORD-009988
ORD-011103
ORD-013759
ORD-009549
ORD-013534
ORD-003907
ORD-014531
ORD-014960
ORD-011168
ORD-001245
ORD-004200
ORD-014348
ORD-012625
ORD-008272
ORD-005888
ORD-011323
ORD-010911
ORD-009512
ORD-005054
ORD-008528
ORD-009819
ORD-009934
ORD-001622
ORD-001691
ORD-011958
ORD-002595
ORD-009820
ORD-010704
ORD-001532
ORD-002676
ORD-003107
ORD-004846
ORD-013949
ORD-000821
ORD-008743
ORD-005589
ORD-013791
ORD-000943
ORD-000495
ORD-007031
ORD-003709
ORD-010443
ORD-005127
ORD-006254
ord-004802
ORD-004921
ORD-000199
ORD-000228
ORD-007187
ORD-005278
ORD-012715
ORD-011935
ORD-007863
ORD-003150
ORD-010847
ORD-002867
ORD-014740
ORD-003921
ORD-005692
ORD-014845
ORD-010179
ORD-014429
ORD-004543
ORD-002136
ORD-009577
ORD-013537
ORD-008123
ORD-011763
ORD-008022
ORD-008681
ORD-008966
ORD-007284
ORD-014555
ORD-002444
ORD-010519
ORD-007938
ORD-008263
ORD-009163
ORD-004526
ORD-008452
ORD-001482
ORD-008055
ORD-000303
ORD-002851
ORD-005345
ORD-006882
ORD-006462
ORD-003887
ORD-002236
ORD-001937
ORD-007240
ORD-002976
ORD-005298
ORD-003084
ORD-009136
ORD-006259
ORD-005134
ORD-011532
ORD-005500
ORD-014236
ORD-005178
ORD-008679
ORD-004304
ORD-008212
ORD-009601
ORD-014258
ORD-010146
ORD-011437
ORD-013656
ORD-002589
ORD-001989
ORD-014537
ORD-005351
ORD-009784
ORD-004827
ORD-003725
ORD-010403
ORD-005033
ORD-001368
ORD-010709
ORD-008631
ORD-012325
ORD-012191
ORD-011606
ORD-008133
ORD-004833
ORD-003556
ORD-007046
ORD-013510
ORD-011571
ORD-002645
ORD-014869
ORD-012534
ORD-004901
ORD-014128
ORD-010223
ORD-013436
ORD-014458
ORD-014944
ORD-014166
ORD-003727
ORD-005353
ORD-002904
ORD-001490
ORD-007453
ORD-006165
ORD-003626
ORD-008426
ORD-004676
ORD-006316
ORD-014651
ORD-014575
ORD-010840
ORD-014065
ORD-002189
ORD-009299
ORD-011335
ORD-002094
ORD-004590
ORD-002194
ORD-003776
ORD-001701
ORD-013148
ORD-010027
ORD-009479
ORD-014435
ORD-011936
ORD-012680
ORD-003992
ORD-011538
ORD-006771
ORD-003828
ORD-014967
ORD-000183
ORD-003780
ORD-006772
ORD-006085
ORD-004637
ORD-010029
ORD-014316
ORD-006916
ORD-014558
ORD-001569
ORD-011422
ORD-005480
ORD-010084
ORD-002520
ORD-010759
ORD-007784
ORD-001950
ORD-012602
ORD-000281
ORD-005645
ORD-014045
ORD-008971
ORD-000359
ORD-006157
ORD-000928
ORD-002334
ORD-006560
ORD-000484
ORD-008222
ORD-004131
ORD-013021
ORD-014564
ORD-005271
ORD-011457
ORD-007611
ORD-013649
ORD-003889
ORD-007323
ORD-009651
ORD-006118
ORD-014768
ORD-009470
ORD-000046
ORD-000005
ORD-011275
ORD-000704
ORD-008064
ORD-007978
ORD-013283
ORD-014789
ORD-005132
ORD-000881
ORD-013705
ORD-010526
ORD-007237
ORD-002293
ORD-011698
ORD-014269
ORD-001677
ORD-001791
ORD-005113
ORD-000748
ORD-013325
ORD-012660
ORD-010159
ORD-012945
ORD-014637
ORD-005473
ORD-005756
ORD-005354
ORD-000900
ORD-013248
ORD-004144
ORD-009718
ORD-003778
ORD-003325
ORD-001627
ORD-001105
ORD-014750
ORD-007995
ORD-001344
ORD-011634
ORD-000414
ORD-013923
ORD-009373
ORD-006242
ORD-003414
ORD-008070
ORD-008078
ORD-009177
ORD-009415
ORD-012389
ORD-007579
ORD-008812
ORD-007464
ORD-002760
ORD-014873
ORD-001256
ORD-013969
ORD-013733
ORD-000892
ORD-009164
ORD-003032
ORD-008136
ORD-008663
ORD-008547
ORD-011444
ORD-010396
ORD-001138
ORD-000124
ORD-005238
ORD-006315

RETURNED RESULT:

In [ ]:
print("Total rows:", len(df))

Total rows: 759

In [ ]:
print(df.columns.tolist())

['order_id', 'package_weight', 'vehicle_type', 'capacity_kg', 'distance_km', 'max_range_km', 'weight_exceeds_capacity']

In [ ]:
print(df[[
    "order_id",
    "package_weight",
    "capacity_kg",
    "weight_exceeds_capacity"
]].head(10))

     order_id  package_weight  capacity_kg  weight_exceeds_capacity
0  ORD-005379            1.54          2.0                    False
1  ORD-002865            2.66          4.5                    False
2  ORD-014884            2.39          4.8                    False
3  ORD-003137            2.12          5.4                    False
4  ORD-007665            4.26          6.0                    False
5  ORD-002549            4.64          1.9                     True
6  ORD-000415            2.91          3.6                    False
7  ORD-008479            2.60          2.8                    False
8  ORD-011188            1.81          4.4                    False
9  ORD-004441            0.64          5.3                    False

Check the actual violations

In [ ]:
capacity_violations = df[df["weight_exceeds_capacity"] == True]

print("Capacity violations:", len(capacity_violations))
print(capacity_violations[[
    "order_id",
    "package_weight",
    "capacity_kg",
    "weight_exceeds_capacity"
]].head(20))

Capacity violations: 288
      order_id  package_weight  capacity_kg  weight_exceeds_capacity
5   ORD-002549            4.64          1.9                     True
11  ORD-012343           10.59          3.8                     True
13  ORD-000680            3.14          1.0                     True
14  ORD-009988            3.80          2.8                     True
15  ORD-011103           26.28          4.8                     True
18  ORD-013759            5.00          1.5                     True
22  ORD-009549            3.34          2.4                     True
27  ORD-013534            6.30          4.3                     True
29  ORD-003907           10.59          4.5                     True
31  ORD-014531            3.48          2.9                     True
32  ORD-014960           72.98          5.9                     True
34  ORD-011168            4.59          1.9                     True
36  ORD-001245           10.59          1.8                     True
46  ORD-004200            1.13          1.1                     True
47  ORD-014348            2.00          1.9                     True
51  ORD-012625            1.41          1.3                     True
52  ORD-008272           10.71          5.4                     True
53  ORD-005888            4.65          2.5                     True
54  ORD-011323           65.86          1.0                     True
55  ORD-010911            3.90          3.0                     True

Independently verify the calculation

In [ ]:
df["capacity_check"] = df["package_weight"] > df["capacity_kg"]

print("Calculated violations:", df["capacity_check"].sum())

Calculated violations: 288

In [ ]:
print(
    "Stored violations:",
    df["weight_exceeds_capacity"].sum()
)

print(
    "Calculated violations:",
    df["capacity_check"].sum()
)

Stored violations: 288
Calculated violations: 288

# GENERAL_RANGE

In [ ]:
# ================================================================
# RAG PHASE 2 - INTENT DETECTION + GENERAL RANGE
# ================================================================

def detect_intent(question):
    """
    Detect the intent of the user's question.
    """

    question = question.lower().strip()

    # Capacity-related questions
    if (
        "capacity" in question
        or "overloaded" in question
        or "exceeding capacity" in question
        or "exceeds capacity" in question
        or "weight limit" in question
    ):
        return "GENERAL_CAPACITY"

    # Range-related questions
    if (
        "range" in question
        or "maximum distance" in question
        or "max distance" in question
        or "within maximum" in question
        or "within max" in question
    ):
        return "GENERAL_RANGE"

    # Default
    return "GENERAL"


def rag_pipeline(question):

    # ------------------------------------------------------------
    # 1. Detect intent
    # ------------------------------------------------------------

    intent = detect_intent(question)

    print("\nINTENT:")
    print(intent)

    # ------------------------------------------------------------
    # 2. GENERAL CAPACITY
    # ------------------------------------------------------------

    if intent == "GENERAL_CAPACITY":

        retrieved = retrieve_drone_routes(
            "drone routes exceeding capacity"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            return "No capacity violations were found."

        capacity_violations = []

        for _, row in retrieved.iterrows():

            package_weight = float(row["package_weight"])
            capacity_kg = float(row["capacity_kg"])

            if package_weight > capacity_kg:
                capacity_violations.append(
                    row["order_id"]
                )

        print("\nGENERAL CAPACITY VIOLATIONS:")
        print("Total:", len(capacity_violations))

        for order in capacity_violations:
            print(order)

        return capacity_violations

    # ------------------------------------------------------------
    # 3. GENERAL RANGE
    # ------------------------------------------------------------
    if intent == "GENERAL_RANGE":

        retrieved = retrieve_drone_routes(
        "drone routes within maximum range"
    )

    print("\nRETRIEVED ROWS:")
    print(len(retrieved))

    if retrieved.empty:
        return "No drone routes were found."

    range_routes = []

    for _, row in retrieved.iterrows():

        distance_km = float(row["distance_km"])
        max_range_km = float(row["max_range_km"])

        if distance_km <= max_range_km:
            range_routes.append(row["order_id"])

    print("\nGENERAL RANGE ROUTES:")
    print("Total:", len(range_routes))

    for order in range_routes:
        print(order)

    return range_routes

    # ------------------------------------------------------------
    # 4. UNKNOWN / GENERAL
    # ------------------------------------------------------------

    return "I could not determine the requested analysis."

In [ ]:
def detect_intent(question):

    question = question.lower().strip()

    # Capacity questions
    if (
        "capacity" in question
        or "exceeding capacity" in question
        or "exceeds capacity" in question
        or "over capacity" in question
        or "weight exceeds" in question
    ):
        return "GENERAL_CAPACITY"

    # Range questions
    elif (
        "range" in question
        or "maximum range" in question
        or "max range" in question
        or "within range" in question
        or "exceeding range" in question
        or "out of range" in question
    ):
        return "GENERAL_RANGE"

    else:
        return "UNKNOWN"

In [ ]:
print("=" * 70)
print("RAG PHASE 2 - GENERAL RANGE TEST")
print("=" * 70)

question = "Which drone routes are within maximum range?"

print("\nQUESTION:")
print(question)

result = rag_pipeline(question)

print("\nRETURNED RESULT:")
print(result)

print("\nTOTAL ROUTES RETURNED:")
print(len(result))

======================================================================
RAG PHASE 2 - GENERAL RANGE TEST
======================================================================

QUESTION:
Which drone routes are within maximum range?

INTENT:
GENERAL_RANGE

RETRIEVED ROWS:
602

GENERAL RANGE ROUTES:
Total: 602
ORD-005379
ORD-014884
ORD-003137
ORD-002549
ORD-000415
ORD-008479
ORD-011188
ORD-004441
ORD-007387
ORD-012343
ORD-012665
ORD-000680
ORD-009988
ORD-012992
ORD-009872
ORD-013759
ORD-012142
ORD-013768
ORD-008918
ORD-008532
ORD-007438
ORD-013850
ORD-001348
ORD-013534
ORD-013888
ORD-006961
ORD-014531
ORD-012792
ORD-001245
ORD-004237
ORD-008067
ORD-004657
ORD-011363
ORD-001297
ORD-007391
ORD-000186
ORD-008998
ORD-004200
ORD-014348
ORD-006065
ORD-009511
ORD-011616
ORD-012625
ORD-008272
ORD-005888
ORD-011323
ORD-010911
ORD-009512
ORD-009848
ORD-005054
ORD-003601
ORD-012859
ORD-014136
ORD-000618
ORD-013702
ORD-011207
ORD-009021
ORD-008528
ORD-009934
ORD-014080
ORD-011297
ORD-001622
ORD-011958
ORD-009918
ORD-003550
ORD-002375
ORD-002595
ORD-011525
ORD-010704
ORD-006171
ORD-002411
ORD-004846
ORD-014314
ORD-008386
ORD-000821
ORD-013211
ORD-008743
ORD-005829
ORD-006293
ORD-005635
ORD-013791
ORD-000943
ORD-010656
ORD-007314
ORD-009266
ORD-007031
ORD-010311
ORD-003709
ORD-010443
ORD-012484
ORD-001708
ORD-012172
ORD-002098
ORD-010173
ORD-007627
ORD-004790
ORD-005127
ORD-006254
ORD-006343
ORD-006033
ORD-003707
ORD-013831
ORD-012121
ORD-010906
ORD-010772
ORD-008815
ORD-005441
ORD-001028
ORD-007310
ORD-004921
ORD-000199
ORD-008976
ORD-005972
ORD-007187
ORD-004772
ORD-008589
ORD-012715
ORD-010847
ORD-002867
ORD-012593
ORD-014740
ORD-003921
ORD-011513
ORD-014553
ORD-011962
ORD-007472
ORD-014835
ORD-005692
ORD-012272
ORD-007127
ORD-006393
ORD-010300
ORD-014429
ORD-007659
ORD-008049
ORD-004543
ORD-002136
ORD-002758
ORD-009577
ORD-001071
ORD-003211
ORD-006163
ORD-001938
ORD-009378
ORD-003993
ORD-014191
ORD-008123
ORD-011763
ORD-004531
ORD-008022
ORD-008681
ORD-008966
ORD-002550
ORD-007284
ORD-014555
ORD-013310
ORD-012145
ORD-002444
ORD-014099
ORD-009352
ORD-007938
ORD-003842
ORD-007390
ORD-007325
ORD-012127
ORD-008263
ORD-004526
ORD-008916
ORD-009810
ORD-009165
ORD-002308
ORD-008452
ORD-014730
ORD-005060
ORD-001482
ORD-004648
ORD-011035
ORD-011237
ORD-003309
ORD-013621
ORD-001198
ORD-009724
ORD-000303
ORD-011038
ORD-009059
ORD-002851
ORD-005700
ORD-009943
ORD-005345
ORD-013848
ORD-006282
ORD-006462
ORD-008618
ORD-006883
ORD-000901
ORD-012978
ORD-000133
ORD-010014
ORD-008865
ORD-004279
ORD-000449
ORD-000256
ORD-002964
ORD-003887
ORD-012802
ORD-009160
ORD-003000
ORD-001937
ORD-007240
ORD-002976
ORD-005298
ORD-003084
ORD-007937
ORD-010402
ORD-014883
ORD-004917
ORD-006259
ORD-007646
ORD-007917
ORD-005134
ORD-011532
ORD-000673
ORD-005178
ORD-006511
ORD-008679
ORD-014799
ORD-001975
ORD-008212
ORD-012241
ORD-009601
ORD-002781
ORD-004555
ORD-014258
ORD-007163
ORD-010146
ORD-004004
ORD-011437
ORD-014095
ORD-004896
ORD-013573
ORD-006552
ORD-013656
ORD-002589
ORD-014537
ORD-014163
ORD-009784
ORD-010339
ORD-010709
ORD-008631
ORD-011776
ORD-006630
ORD-011166
ORD-012191
ORD-014784
ORD-006720
ORD-009366
ORD-004169
ORD-003946
ORD-003871
ORD-004693
ORD-005154
ORD-006747
ORD-011284
ORD-011606
ORD-000127
ORD-004552
ORD-005598
ORD-007046
ORD-007277
ORD-008808
ORD-013510
ORD-001667
ORD-010119
ORD-012831
ORD-006541
ORD-011205
ORD-000481
ORD-001719
ORD-012275
ORD-001048
ORD-014869
ORD-012534
ORD-004901
ORD-008748
ORD-011286
ORD-007538
ORD-002523
ORD-014231
ORD-005796
ORD-004945
ORD-002428
ORD-008437
ORD-013262
ORD-014458
ORD-012452
ORD-009916
ORD-014166
ORD-003172
ORD-000350
ORD-008121
ORD-006827
ORD-003727
ORD-002386
ORD-008959
ORD-005946
ORD-010142
ORD-007988
ORD-012940
ORD-005353
ORD-004316
ORD-014805
ORD-003944
ORD-001490
ORD-013636
ORD-000262
ORD-006240
ORD-007453
ORD-004411
ORD-014355
ORD-007925
ORD-010687
ORD-005690
ORD-009274
ORD-009287
ORD-004676
ORD-010850
ORD-006316
ORD-014651
ORD-014575
ORD-010840
ORD-014065
ORD-002189
ORD-009299
ORD-011335
ORD-012557
ORD-010954
ORD-010434
ORD-002118
ORD-006371
ORD-011899
ORD-002194
ORD-011507
ORD-003776
ORD-001701
ORD-006880
ORD-009666
ORD-004553
ORD-006619
ORD-014139
ORD-005907
ORD-007717
ORD-002247
ORD-012627
ORD-002597
ORD-014435
ORD-011936
ORD-002827
ORD-002322
ORD-009189
ORD-011538
ORD-008615
ORD-011093
ORD-006771
ORD-014532
ORD-007813
ORD-003828
ORD-008181
ORD-012009
ORD-010338
ORD-013795
ORD-003242
ORD-002264
ORD-000183
ORD-013998
ORD-013027
ORD-010144
ORD-014257
ORD-004912
ORD-004962
ORD-014685
ORD-009659
ORD-000016
ORD-014847
ORD-014183
ORD-006772
ORD-006085
ORD-013284
ORD-004637
ORD-010029
ORD-014316
ORD-006916
ORD-008281
ORD-009341
ORD-005283
ORD-014558
ORD-005671
ORD-014779
ORD-002349
ORD-008644
ORD-013526
ORD-001569
ORD-009485
ORD-005480
ORD-000825
ORD-002520
ORD-010103
ORD-007596
ORD-010759
ORD-000542
ORD-014311
ORD-007784
ORD-000724
ORD-014922
ORD-001827
ORD-006488
ORD-001103
ORD-004439
ORD-000281
ORD-006089
ORD-005645
ORD-000304
ORD-014045
ORD-008971
ORD-000359
ORD-010806
ORD-006157
ORD-000928
ORD-012664
ORD-006560
ORD-000484
ORD-011096
ORD-008222
ORD-014321
ORD-005857
ORD-012126
ORD-013381
ORD-004131
ORD-006035
ORD-000701
ORD-011897
ORD-014978
ORD-014564
ORD-005271
ORD-011457
ORD-011999
ORD-000795
ORD-012311
ORD-006436
ORD-009579
ORD-013987
ORD-003889
ORD-007323
ORD-001984
ORD-009651
ORD-007403
ORD-006348
ORD-006118
ORD-014768
ORD-003569
ORD-013111
ORD-009470
ORD-000046
ORD-000005
ORD-011275
ORD-000704
ORD-012840
ORD-007978
ORD-009407
ORD-013283
ORD-011083
ORD-007157
ORD-003710
ORD-005132
ORD-000881
ORD-013705
ORD-010526
ORD-011148
ORD-002293
ORD-012108
ORD-007380
ORD-012218
ORD-011952
ORD-009236
ORD-001541
ORD-014269
ORD-006046
ORD-001791
ORD-007777
ORD-005113
ORD-009393
ORD-008906
ORD-006864
ORD-007196
ORD-001498
ORD-002315
ORD-006546
ORD-014147
ORD-002423
ORD-013325
ORD-010762
ORD-000607
ORD-007038
ORD-012420
ORD-000696
ORD-001068
ORD-007206
ORD-005881
ORD-014871
ORD-003513
ORD-012945
ORD-013982
ORD-014637
ORD-003750
ORD-005354
ORD-000900
ORD-013913
ORD-004754
ORD-012338
ORD-001177
ORD-013065
ORD-014396
ORD-000480
ORD-004144
ORD-008353
ORD-008059
ORD-009718
ORD-013613
ORD-013363
ORD-001882
ORD-003778
ORD-011350
ORD-003325
ORD-008334
ORD-005292
ORD-007715
ORD-000674
ORD-007243
ORD-014750
ORD-001344
ORD-011634
ORD-005674
ORD-000414
ORD-004324
ORD-013923
ORD-009373
ORD-006242
ORD-003414
ORD-005286
ORD-008389
ORD-014787
ORD-003083
ORD-008070
ORD-010845
ORD-007914
ORD-008078
ORD-009177
ORD-014848
ORD-006754
ORD-008262
ORD-012950
ORD-008623
ORD-002506
ORD-007579
ORD-005260
ORD-012853
ORD-013691
ORD-003123
ORD-010608
ORD-002137
ORD-008812
ORD-007464
ORD-003982
ORD-002760
ORD-006426
ORD-014290
ORD-002872
ORD-006520
ORD-004722
ORD-007267
ORD-009089
ORD-009833
ORD-013448
ORD-007719
ORD-013733
ORD-008471
ORD-005147
ORD-008547
ORD-014539
ORD-011703
ORD-010396
ORD-000874
ORD-001661
ORD-013445
ORD-006187
ORD-009616
ORD-004892
ORD-010701
ORD-000124
ORD-005388
ORD-008768
ORD-006315
ORD-008813

RETURNED RESULT:
['ORD-005379', 'ORD-014884', 'ORD-003137', 'ORD-002549', 'ORD-000415', 'ORD-008479', 'ORD-011188', 'ORD-004441', 'ORD-007387', 'ORD-012343', 'ORD-012665', 'ORD-000680', 'ORD-009988', 'ORD-012992', 'ORD-009872', 'ORD-013759', 'ORD-012142', 'ORD-013768', 'ORD-008918', 'ORD-008532', 'ORD-007438', 'ORD-013850', 'ORD-001348', 'ORD-013534', 'ORD-013888', 'ORD-006961', 'ORD-014531', 'ORD-012792', 'ORD-001245', 'ORD-004237', 'ORD-008067', 'ORD-004657', 'ORD-011363', 'ORD-001297', 'ORD-007391', 'ORD-000186', 'ORD-008998', 'ORD-004200', 'ORD-014348', 'ORD-006065', 'ORD-009511', 'ORD-011616', 'ORD-012625', 'ORD-008272', 'ORD-005888', 'ORD-011323', 'ORD-010911', 'ORD-009512', 'ORD-009848', 'ORD-005054', 'ORD-003601', 'ORD-012859', 'ORD-014136', 'ORD-000618', 'ORD-013702', 'ORD-011207', 'ORD-009021', 'ORD-008528', 'ORD-009934', 'ORD-014080', 'ORD-011297', 'ORD-001622', 'ORD-011958', 'ORD-009918', 'ORD-003550', 'ORD-002375', 'ORD-002595', 'ORD-011525', 'ORD-010704', 'ORD-006171', 'ORD-002411', 'ORD-004846', 'ORD-014314', 'ORD-008386', 'ORD-000821', 'ORD-013211', 'ORD-008743', 'ORD-005829', 'ORD-006293', 'ORD-005635', 'ORD-013791', 'ORD-000943', 'ORD-010656', 'ORD-007314', 'ORD-009266', 'ORD-007031', 'ORD-010311', 'ORD-003709', 'ORD-010443', 'ORD-012484', 'ORD-001708', 'ORD-012172', 'ORD-002098', 'ORD-010173', 'ORD-007627', 'ORD-004790', 'ORD-005127', 'ORD-006254', 'ORD-006343', 'ORD-006033', 'ORD-003707', 'ORD-013831', 'ORD-012121', 'ORD-010906', 'ORD-010772', 'ORD-008815', 'ORD-005441', 'ORD-001028', 'ORD-007310', 'ORD-004921', 'ORD-000199', 'ORD-008976', 'ORD-005972', 'ORD-007187', 'ORD-004772', 'ORD-008589', 'ORD-012715', 'ORD-010847', 'ORD-002867', 'ORD-012593', 'ORD-014740', 'ORD-003921', 'ORD-011513', 'ORD-014553', 'ORD-011962', 'ORD-007472', 'ORD-014835', 'ORD-005692', 'ORD-012272', 'ORD-007127', 'ORD-006393', 'ORD-010300', 'ORD-014429', 'ORD-007659', 'ORD-008049', 'ORD-004543', 'ORD-002136', 'ORD-002758', 'ORD-009577', 'ORD-001071', 'ORD-003211', 'ORD-006163', 'ORD-001938', 'ORD-009378', 'ORD-003993', 'ORD-014191', 'ORD-008123', 'ORD-011763', 'ORD-004531', 'ORD-008022', 'ORD-008681', 'ORD-008966', 'ORD-002550', 'ORD-007284', 'ORD-014555', 'ORD-013310', 'ORD-012145', 'ORD-002444', 'ORD-014099', 'ORD-009352', 'ORD-007938', 'ORD-003842', 'ORD-007390', 'ORD-007325', 'ORD-012127', 'ORD-008263', 'ORD-004526', 'ORD-008916', 'ORD-009810', 'ORD-009165', 'ORD-002308', 'ORD-008452', 'ORD-014730', 'ORD-005060', 'ORD-001482', 'ORD-004648', 'ORD-011035', 'ORD-011237', 'ORD-003309', 'ORD-013621', 'ORD-001198', 'ORD-009724', 'ORD-000303', 'ORD-011038', 'ORD-009059', 'ORD-002851', 'ORD-005700', 'ORD-009943', 'ORD-005345', 'ORD-013848', 'ORD-006282', 'ORD-006462', 'ORD-008618', 'ORD-006883', 'ORD-000901', 'ORD-012978', 'ORD-000133', 'ORD-010014', 'ORD-008865', 'ORD-004279', 'ORD-000449', 'ORD-000256', 'ORD-002964', 'ORD-003887', 'ORD-012802', 'ORD-009160', 'ORD-003000', 'ORD-001937', 'ORD-007240', 'ORD-002976', 'ORD-005298', 'ORD-003084', 'ORD-007937', 'ORD-010402', 'ORD-014883', 'ORD-004917', 'ORD-006259', 'ORD-007646', 'ORD-007917', 'ORD-005134', 'ORD-011532', 'ORD-000673', 'ORD-005178', 'ORD-006511', 'ORD-008679', 'ORD-014799', 'ORD-001975', 'ORD-008212', 'ORD-012241', 'ORD-009601', 'ORD-002781', 'ORD-004555', 'ORD-014258', 'ORD-007163', 'ORD-010146', 'ORD-004004', 'ORD-011437', 'ORD-014095', 'ORD-004896', 'ORD-013573', 'ORD-006552', 'ORD-013656', 'ORD-002589', 'ORD-014537', 'ORD-014163', 'ORD-009784', 'ORD-010339', 'ORD-010709', 'ORD-008631', 'ORD-011776', 'ORD-006630', 'ORD-011166', 'ORD-012191', 'ORD-014784', 'ORD-006720', 'ORD-009366', 'ORD-004169', 'ORD-003946', 'ORD-003871', 'ORD-004693', 'ORD-005154', 'ORD-006747', 'ORD-011284', 'ORD-011606', 'ORD-000127', 'ORD-004552', 'ORD-005598', 'ORD-007046', 'ORD-007277', 'ORD-008808', 'ORD-013510', 'ORD-001667', 'ORD-010119', 'ORD-012831', 'ORD-006541', 'ORD-011205', 'ORD-000481', 'ORD-001719', 'ORD-012275', 'ORD-001048', 'ORD-014869', 'ORD-012534', 'ORD-004901', 'ORD-008748', 'ORD-011286', 'ORD-007538', 'ORD-002523', 'ORD-014231', 'ORD-005796', 'ORD-004945', 'ORD-002428', 'ORD-008437', 'ORD-013262', 'ORD-014458', 'ORD-012452', 'ORD-009916', 'ORD-014166', 'ORD-003172', 'ORD-000350', 'ORD-008121', 'ORD-006827', 'ORD-003727', 'ORD-002386', 'ORD-008959', 'ORD-005946', 'ORD-010142', 'ORD-007988', 'ORD-012940', 'ORD-005353', 'ORD-004316', 'ORD-014805', 'ORD-003944', 'ORD-001490', 'ORD-013636', 'ORD-000262', 'ORD-006240', 'ORD-007453', 'ORD-004411', 'ORD-014355', 'ORD-007925', 'ORD-010687', 'ORD-005690', 'ORD-009274', 'ORD-009287', 'ORD-004676', 'ORD-010850', 'ORD-006316', 'ORD-014651', 'ORD-014575', 'ORD-010840', 'ORD-014065', 'ORD-002189', 'ORD-009299', 'ORD-011335', 'ORD-012557', 'ORD-010954', 'ORD-010434', 'ORD-002118', 'ORD-006371', 'ORD-011899', 'ORD-002194', 'ORD-011507', 'ORD-003776', 'ORD-001701', 'ORD-006880', 'ORD-009666', 'ORD-004553', 'ORD-006619', 'ORD-014139', 'ORD-005907', 'ORD-007717', 'ORD-002247', 'ORD-012627', 'ORD-002597', 'ORD-014435', 'ORD-011936', 'ORD-002827', 'ORD-002322', 'ORD-009189', 'ORD-011538', 'ORD-008615', 'ORD-011093', 'ORD-006771', 'ORD-014532', 'ORD-007813', 'ORD-003828', 'ORD-008181', 'ORD-012009', 'ORD-010338', 'ORD-013795', 'ORD-003242', 'ORD-002264', 'ORD-000183', 'ORD-013998', 'ORD-013027', 'ORD-010144', 'ORD-014257', 'ORD-004912', 'ORD-004962', 'ORD-014685', 'ORD-009659', 'ORD-000016', 'ORD-014847', 'ORD-014183', 'ORD-006772', 'ORD-006085', 'ORD-013284', 'ORD-004637', 'ORD-010029', 'ORD-014316', 'ORD-006916', 'ORD-008281', 'ORD-009341', 'ORD-005283', 'ORD-014558', 'ORD-005671', 'ORD-014779', 'ORD-002349', 'ORD-008644', 'ORD-013526', 'ORD-001569', 'ORD-009485', 'ORD-005480', 'ORD-000825', 'ORD-002520', 'ORD-010103', 'ORD-007596', 'ORD-010759', 'ORD-000542', 'ORD-014311', 'ORD-007784', 'ORD-000724', 'ORD-014922', 'ORD-001827', 'ORD-006488', 'ORD-001103', 'ORD-004439', 'ORD-000281', 'ORD-006089', 'ORD-005645', 'ORD-000304', 'ORD-014045', 'ORD-008971', 'ORD-000359', 'ORD-010806', 'ORD-006157', 'ORD-000928', 'ORD-012664', 'ORD-006560', 'ORD-000484', 'ORD-011096', 'ORD-008222', 'ORD-014321', 'ORD-005857', 'ORD-012126', 'ORD-013381', 'ORD-004131', 'ORD-006035', 'ORD-000701', 'ORD-011897', 'ORD-014978', 'ORD-014564', 'ORD-005271', 'ORD-011457', 'ORD-011999', 'ORD-000795', 'ORD-012311', 'ORD-006436', 'ORD-009579', 'ORD-013987', 'ORD-003889', 'ORD-007323', 'ORD-001984', 'ORD-009651', 'ORD-007403', 'ORD-006348', 'ORD-006118', 'ORD-014768', 'ORD-003569', 'ORD-013111', 'ORD-009470', 'ORD-000046', 'ORD-000005', 'ORD-011275', 'ORD-000704', 'ORD-012840', 'ORD-007978', 'ORD-009407', 'ORD-013283', 'ORD-011083', 'ORD-007157', 'ORD-003710', 'ORD-005132', 'ORD-000881', 'ORD-013705', 'ORD-010526', 'ORD-011148', 'ORD-002293', 'ORD-012108', 'ORD-007380', 'ORD-012218', 'ORD-011952', 'ORD-009236', 'ORD-001541', 'ORD-014269', 'ORD-006046', 'ORD-001791', 'ORD-007777', 'ORD-005113', 'ORD-009393', 'ORD-008906', 'ORD-006864', 'ORD-007196', 'ORD-001498', 'ORD-002315', 'ORD-006546', 'ORD-014147', 'ORD-002423', 'ORD-013325', 'ORD-010762', 'ORD-000607', 'ORD-007038', 'ORD-012420', 'ORD-000696', 'ORD-001068', 'ORD-007206', 'ORD-005881', 'ORD-014871', 'ORD-003513', 'ORD-012945', 'ORD-013982', 'ORD-014637', 'ORD-003750', 'ORD-005354', 'ORD-000900', 'ORD-013913', 'ORD-004754', 'ORD-012338', 'ORD-001177', 'ORD-013065', 'ORD-014396', 'ORD-000480', 'ORD-004144', 'ORD-008353', 'ORD-008059', 'ORD-009718', 'ORD-013613', 'ORD-013363', 'ORD-001882', 'ORD-003778', 'ORD-011350', 'ORD-003325', 'ORD-008334', 'ORD-005292', 'ORD-007715', 'ORD-000674', 'ORD-007243', 'ORD-014750', 'ORD-001344', 'ORD-011634', 'ORD-005674', 'ORD-000414', 'ORD-004324', 'ORD-013923', 'ORD-009373', 'ORD-006242', 'ORD-003414', 'ORD-005286', 'ORD-008389', 'ORD-014787', 'ORD-003083', 'ORD-008070', 'ORD-010845', 'ORD-007914', 'ORD-008078', 'ORD-009177', 'ORD-014848', 'ORD-006754', 'ORD-008262', 'ORD-012950', 'ORD-008623', 'ORD-002506', 'ORD-007579', 'ORD-005260', 'ORD-012853', 'ORD-013691', 'ORD-003123', 'ORD-010608', 'ORD-002137', 'ORD-008812', 'ORD-007464', 'ORD-003982', 'ORD-002760', 'ORD-006426', 'ORD-014290', 'ORD-002872', 'ORD-006520', 'ORD-004722', 'ORD-007267', 'ORD-009089', 'ORD-009833', 'ORD-013448', 'ORD-007719', 'ORD-013733', 'ORD-008471', 'ORD-005147', 'ORD-008547', 'ORD-014539', 'ORD-011703', 'ORD-010396', 'ORD-000874', 'ORD-001661', 'ORD-013445', 'ORD-006187', 'ORD-009616', 'ORD-004892', 'ORD-010701', 'ORD-000124', 'ORD-005388', 'ORD-008768', 'ORD-006315', 'ORD-008813']

TOTAL ROUTES RETURNED:
602

In [ ]:
def detect_intent(question):

    question = question.lower().strip()

    # Capacity questions
    if (
        "capacity" in question
        or "exceeding capacity" in question
        or "exceeds capacity" in question
        or "over capacity" in question
        or "weight exceeds" in question
    ):
        return "GENERAL_CAPACITY"

    # Range questions
    elif (
        "range" in question
        or "maximum range" in question
        or "max range" in question
        or "within range" in question
        or "exceeding range" in question
        or "out of range" in question
    ):
        return "GENERAL_RANGE"

    else:
        return "UNKNOWN"

# rag_pipeline()

In [ ]:
# =============================================================
# INTENT DETECTION
# =============================================================

def detect_intent(question):

    import re

    question = question.lower().strip()

    # ---------------------------------------------------------
    # Extract ORDER ID
    # ---------------------------------------------------------

    order_match = re.search(
        r"ord-\d+",
        question,
        re.IGNORECASE
    )

    has_order = order_match is not None

    # ---------------------------------------------------------
    # SPECIFIC ORDER + CAPACITY
    # ---------------------------------------------------------

    if has_order and "capacity" in question:
        return "ORDER_CAPACITY"

    if has_order and (
        "too heavy" in question
        or ("weight" in question and "capacity" in question)
    ):
        return "ORDER_CAPACITY"

    # ---------------------------------------------------------
    # SPECIFIC ORDER + VEHICLE
    # ---------------------------------------------------------

    if has_order and (
        "vehicle" in question
        or "drone type" in question
        or "vehicle type" in question
    ):
        return "ORDER_VEHICLE"

    # ---------------------------------------------------------
    # SPECIFIC ORDER + RANGE EXCEEDED
    # ---------------------------------------------------------

    if has_order and "range" in question:

        if (
            "exceed" in question
            or "exceeds" in question
            or "exceeded" in question
            or "beyond" in question
            or "outside" in question
            or "too far" in question
        ):
            return "ORDER_RANGE_EXCEEDED"

        return "ORDER_RANGE"

    # ---------------------------------------------------------
    # GENERAL CAPACITY EXCEEDED
    # ---------------------------------------------------------

    if (
        "capacity" in question
        and (
            "exceed" in question
            or "exceeds" in question
            or "exceeded" in question
            or "beyond" in question
            or "outside" in question
        )
    ):
        return "GENERAL_CAPACITY"

    if "too heavy" in question and not has_order:
        return "GENERAL_CAPACITY"

    # ---------------------------------------------------------
    # GENERAL RANGE EXCEEDED
    # ---------------------------------------------------------

    if (
        "range" in question
        and (
            "exceed" in question
            or "exceeds" in question
            or "exceeded" in question
            or "beyond" in question
            or "outside" in question
        )
    ):
        return "GENERAL_RANGE_EXCEEDED"

    if "too far" in question and not has_order:
        return "GENERAL_RANGE_EXCEEDED"

    # ---------------------------------------------------------
    # GENERAL FEASIBLE ROUTES
    # ---------------------------------------------------------

    if (
        "feasible" in question
        or "feasible routes" in question
        or "possible routes" in question
        or "valid routes" in question
    ):
        return "GENERAL_FEASIBLE"

    # ---------------------------------------------------------
    # GENERAL RANGE / WITHIN RANGE
    # ---------------------------------------------------------

    if "range" in question:
        return "GENERAL_RANGE"

    # ---------------------------------------------------------
    # UNKNOWN
    # ---------------------------------------------------------

    return "UNKNOWN"

In [ ]:
print(detect_intent("What vehicle type is used for ORD-005379?"))
print(detect_intent("Which drone routes are feasible?"))

ORDER_VEHICLE
GENERAL_FEASIBLE

In [ ]:
print(df.columns.tolist())

['order_id', 'package_weight', 'vehicle_type', 'capacity_kg', 'distance_km', 'max_range_km', 'weight_exceeds_capacity', 'capacity_check']

# Specific Order Vehicle Type

In [ ]:
# =============================================================
# SPECIFIC ORDER VEHICLE TYPE
# =============================================================

import re


def get_order_vehicle_type(question):

    # ---------------------------------------------------------
    # Extract ORDER ID
    # ---------------------------------------------------------

    order_match = re.search(
        r"ord-\d+",
        question,
        re.IGNORECASE
    )

    if not order_match:
        return "No order ID was found."

    order_id = order_match.group(0).upper()


    # ---------------------------------------------------------
    # Retrieve complete dataset
    # ---------------------------------------------------------

    retrieved = retrieve_drone_routes(
        f"drone route {order_id}"
    )

    print("\nRETRIEVED ROWS:")
    print(len(retrieved))


    # ---------------------------------------------------------
    # Find specific order
    # ---------------------------------------------------------

    order_data = retrieved[
        retrieved["order_id"]
        .astype(str)
        .str.upper()
        == order_id
    ]


    if order_data.empty:
        return f"Order {order_id} was not found."


    # ---------------------------------------------------------
    # Get vehicle type
    # ---------------------------------------------------------

    row = order_data.iloc[0]

    vehicle_type = str(
        row["vehicle_type"]
    )


    # ---------------------------------------------------------
    # Display result
    # ---------------------------------------------------------

    print("\nORDER VEHICLE TYPE:")
    print("Order ID:", order_id)
    print("Vehicle Type:", vehicle_type)


    return {
        "order_id": order_id,
        "vehicle_type": vehicle_type
    }


# =============================================================
# TEST - SPECIFIC ORDER VEHICLE TYPE
# =============================================================

print("=" * 70)
print("RAG PHASE 2 - SPECIFIC ORDER VEHICLE TEST")
print("=" * 70)

question = "What vehicle type is used for ORD-005379?"

print("\nQUESTION:")
print(question)

result = get_order_vehicle_type(question)

print("\nRETURNED RESULT:")
print(result)

======================================================================
RAG PHASE 2 - SPECIFIC ORDER VEHICLE TEST
======================================================================

QUESTION:
What vehicle type is used for ORD-005379?

RETRIEVED ROWS:
1

ORDER VEHICLE TYPE:
Order ID: ORD-005379
Vehicle Type: Drone

RETURNED RESULT:
{'order_id': 'ORD-005379', 'vehicle_type': 'Drone'}

# # FINAL RAG PIPELINE

In [ ]:
# =============================================================
# FINAL RAG PIPELINE
# =============================================================

import re


def rag_pipeline(question):

    # =========================================================
    # 1. DETECT INTENT
    # =========================================================

    intent = detect_intent(question)

    print("\n" + "=" * 70)
    print("FINAL RAG PIPELINE")
    print("=" * 70)

    print("\nQUESTION:")
    print(question)

    print("\nINTENT:")
    print(intent)


    # =========================================================
    # 2. GENERAL CAPACITY
    # =========================================================

    if intent == "GENERAL_CAPACITY":

        retrieved = retrieve_drone_routes(
            "drone routes exceeding capacity"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            answer = "No capacity violations were found."
            print("\nANSWER:")
            print(answer)
            return answer

        capacity_violations = []

        for _, row in retrieved.iterrows():

            try:
                package_weight = float(row["package_weight"])
                capacity_kg = float(row["capacity_kg"])

                if package_weight > capacity_kg:
                    capacity_violations.append(
                        str(row["order_id"]).upper()
                    )

            except (ValueError, TypeError, KeyError):
                continue

        # Remove duplicates
        capacity_violations = list(
            dict.fromkeys(capacity_violations)
        )

        print("\nGENERAL CAPACITY VIOLATIONS:")
        print("Total:", len(capacity_violations))

        print("\nFirst 10 violations:")

        for order in capacity_violations[:10]:
            print(order)

        if len(capacity_violations) > 10:
            print("...")

        print("\nANSWER:")
        print(
            f"{len(capacity_violations)} routes/orders found."
        )

        print("\nFirst 10 results:")

        for order in capacity_violations[:10]:
            print(order)

        if len(capacity_violations) > 10:
            print("...")

        return capacity_violations


    # =========================================================
    # 3. SPECIFIC ORDER CAPACITY
    # =========================================================

    elif intent == "ORDER_CAPACITY":

        order_match = re.search(
            r"ord-\d+",
            question,
            re.IGNORECASE
        )

        if not order_match:
            return "No order ID was found."

        order_id = order_match.group(0).upper()

        print("\nORDER ID:")
        print(order_id)

        retrieved = retrieve_drone_routes(
            f"drone route {order_id}"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            return f"Order {order_id} was not found."

        order_data = retrieved[
            retrieved["order_id"]
            .astype(str)
            .str.upper()
            == order_id
        ]

        if order_data.empty:
            return f"Order {order_id} was not found."

        row = order_data.iloc[0]

        package_weight = float(row["package_weight"])
        capacity_kg = float(row["capacity_kg"])

        within_capacity = package_weight <= capacity_kg

        print("\nORDER CAPACITY CHECK:")
        print("Order ID:", order_id)
        print("Package Weight:", package_weight, "kg")
        print("Maximum Capacity:", capacity_kg, "kg")

        if within_capacity:
            print("Status: WITHIN CAPACITY")
            status = "WITHIN capacity"
        else:
            print("Status: EXCEEDS CAPACITY")
            status = "EXCEEDS capacity"

        answer = (
            f"{order_id} is {status}. "
            f"Package weight: {package_weight} kg, "
            f"Maximum capacity: {capacity_kg} kg."
        )

        print("\nANSWER:")
        print(answer)

        return {
            "order_id": order_id,
            "package_weight": package_weight,
            "capacity_kg": capacity_kg,
            "within_capacity": within_capacity
        }


    # =========================================================
    # 4. GENERAL RANGE - WITHIN RANGE
    # =========================================================

    elif intent == "GENERAL_RANGE":

        retrieved = retrieve_drone_routes(
            "drone routes within maximum range"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            answer = "No drone routes within maximum range were found."
            print("\nANSWER:")
            print(answer)
            return answer

        range_routes = []

        for _, row in retrieved.iterrows():

            try:
                distance_km = float(row["distance_km"])
                max_range_km = float(row["max_range_km"])

                if distance_km <= max_range_km:
                    range_routes.append(
                        str(row["order_id"]).upper()
                    )

            except (ValueError, TypeError, KeyError):
                continue

        range_routes = list(
            dict.fromkeys(range_routes)
        )

        print("\nGENERAL RANGE ROUTES:")
        print("Total:", len(range_routes))

        print("\nFirst 10 routes:")

        for order in range_routes[:10]:
            print(order)

        if len(range_routes) > 10:
            print("...")

        print("\nANSWER:")
        print(
            f"{len(range_routes)} routes/orders found."
        )

        print("\nFirst 10 results:")

        for order in range_routes[:10]:
            print(order)

        if len(range_routes) > 10:
            print("...")

        return range_routes


    # =========================================================
    # 5. GENERAL RANGE EXCEEDED
    # =========================================================

    elif intent == "GENERAL_RANGE_EXCEEDED":

        retrieved = retrieve_drone_routes(
            "drone routes exceeding maximum range"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            answer = (
                "No drone routes exceeding maximum range were found."
            )
            print("\nANSWER:")
            print(answer)
            return answer

        exceeded_routes = []

        for _, row in retrieved.iterrows():

            try:
                distance_km = float(row["distance_km"])
                max_range_km = float(row["max_range_km"])

                if distance_km > max_range_km:
                    exceeded_routes.append(
                        str(row["order_id"]).upper()
                    )

            except (ValueError, TypeError, KeyError):
                continue

        # Remove duplicates
        exceeded_routes = list(
            dict.fromkeys(exceeded_routes)
        )

        print("\nGENERAL RANGE EXCEEDED:")
        print("Total:", len(exceeded_routes))

        print("\nFirst 10 routes:")

        for order in exceeded_routes[:10]:
            print(order)

        if len(exceeded_routes) > 10:
            print("...")

        print("\nANSWER:")
        print(
            f"{len(exceeded_routes)} routes/orders found."
        )

        print("\nFirst 10 results:")

        for order in exceeded_routes[:10]:
            print(order)

        if len(exceeded_routes) > 10:
            print("...")

        return exceeded_routes


    # =========================================================
    # 6. GENERAL FEASIBLE ROUTES
    # =========================================================

    elif intent == "GENERAL_FEASIBLE":

        retrieved = retrieve_drone_routes(
            "drone routes feasible"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            answer = "No feasible drone routes were found."
            print("\nANSWER:")
            print(answer)
            return answer

        feasible_routes = []

        for _, row in retrieved.iterrows():

            try:
                package_weight = float(row["package_weight"])
                capacity_kg = float(row["capacity_kg"])

                distance_km = float(row["distance_km"])
                max_range_km = float(row["max_range_km"])

                # A route is feasible when BOTH conditions pass
                within_capacity = (
                    package_weight <= capacity_kg
                )

                within_range = (
                    distance_km <= max_range_km
                )

                if within_capacity and within_range:
                    feasible_routes.append(
                        str(row["order_id"]).upper()
                    )

            except (ValueError, TypeError, KeyError):
                continue

        # Remove duplicates
        feasible_routes = list(
            dict.fromkeys(feasible_routes)
        )

        print("\nGENERAL FEASIBLE ROUTES:")
        print("Total:", len(feasible_routes))

        print("\nFirst 10 feasible routes:")

        for order in feasible_routes[:10]:
            print(order)

        if len(feasible_routes) > 10:
            print("...")

        print("\nANSWER:")
        print(
            f"{len(feasible_routes)} routes/orders found."
        )

        print("\nFirst 10 results:")

        for order in feasible_routes[:10]:
            print(order)

        if len(feasible_routes) > 10:
            print("...")

        return feasible_routes


    # =========================================================
    # 7. SPECIFIC ORDER RANGE
    # =========================================================

    elif intent == "ORDER_RANGE":

        order_match = re.search(
            r"ord-\d+",
            question,
            re.IGNORECASE
        )

        if not order_match:
            return "No order ID was found."

        order_id = order_match.group(0).upper()

        print("\nORDER ID:")
        print(order_id)

        retrieved = retrieve_drone_routes(
            f"drone route {order_id}"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            return f"Order {order_id} was not found."

        order_data = retrieved[
            retrieved["order_id"]
            .astype(str)
            .str.upper()
            == order_id
        ]

        if order_data.empty:
            return f"Order {order_id} was not found."

        row = order_data.iloc[0]

        distance_km = float(row["distance_km"])
        max_range_km = float(row["max_range_km"])

        within_range = distance_km <= max_range_km

        print("\nORDER RANGE CHECK:")
        print("Order ID:", order_id)
        print("Distance:", distance_km, "km")
        print("Maximum Range:", max_range_km, "km")

        if within_range:
            print("Status: WITHIN MAXIMUM RANGE")
            status = "WITHIN maximum range"
        else:
            print("Status: EXCEEDS MAXIMUM RANGE")
            status = "EXCEEDS maximum range"

        answer = (
            f"{order_id} is {status}. "
            f"Distance: {distance_km} km, "
            f"Maximum range: {max_range_km} km."
        )

        print("\nANSWER:")
        print(answer)

        return {
            "order_id": order_id,
            "distance_km": distance_km,
            "max_range_km": max_range_km,
            "within_max_range": within_range
        }


    # =========================================================
    # 8. SPECIFIC ORDER RANGE EXCEEDED
    # =========================================================

    elif intent == "ORDER_RANGE_EXCEEDED":

        order_match = re.search(
            r"ord-\d+",
            question,
            re.IGNORECASE
        )

        if not order_match:
            return "No order ID was found."

        order_id = order_match.group(0).upper()

        print("\nORDER ID:")
        print(order_id)

        retrieved = retrieve_drone_routes(
            f"drone route {order_id}"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            return f"Order {order_id} was not found."

        order_data = retrieved[
            retrieved["order_id"]
            .astype(str)
            .str.upper()
            == order_id
        ]

        if order_data.empty:
            return f"Order {order_id} was not found."

        row = order_data.iloc[0]

        distance_km = float(row["distance_km"])
        max_range_km = float(row["max_range_km"])

        exceeds_range = distance_km > max_range_km

        print("\nORDER RANGE EXCEEDED CHECK:")
        print("Order ID:", order_id)
        print("Distance:", distance_km, "km")
        print("Maximum Range:", max_range_km, "km")

        if exceeds_range:
            print("Status: EXCEEDS MAXIMUM RANGE")
            status = "EXCEEDS maximum range"
        else:
            print("Status: WITHIN MAXIMUM RANGE")
            status = "WITHIN maximum range"

        answer = (
            f"{order_id} {status}. "
            f"Distance: {distance_km} km, "
            f"Maximum range: {max_range_km} km."
        )

        print("\nANSWER:")
        print(answer)

        return {
            "order_id": order_id,
            "distance_km": distance_km,
            "max_range_km": max_range_km,
            "exceeds_max_range": exceeds_range
        }


    # =========================================================
    # 9. SPECIFIC ORDER VEHICLE
    # =========================================================

    elif intent == "ORDER_VEHICLE":

        order_match = re.search(
            r"ord-\d+",
            question,
            re.IGNORECASE
        )

        if not order_match:
            return "No order ID was found."

        order_id = order_match.group(0).upper()

        print("\nORDER ID:")
        print(order_id)

        retrieved = retrieve_drone_routes(
            f"drone route {order_id}"
        )

        print("\nRETRIEVED ROWS:")
        print(len(retrieved))

        if retrieved.empty:
            return f"Order {order_id} was not found."

        order_data = retrieved[
            retrieved["order_id"]
            .astype(str)
            .str.upper()
            == order_id
        ]

        if order_data.empty:
            return f"Order {order_id} was not found."

        row = order_data.iloc[0]

        vehicle_type = str(
            row["vehicle_type"]
        ).strip()

        print("\nORDER VEHICLE TYPE:")
        print("Order ID:", order_id)
        print("Vehicle Type:", vehicle_type)

        answer = (
            f"{order_id} uses a {vehicle_type}."
        )

        print("\nANSWER:")
        print(answer)

        return {
            "order_id": order_id,
            "vehicle_type": vehicle_type
        }


    # =========================================================
    # 10. UNKNOWN INTENT
    # =========================================================

    else:

        answer = (
            "Sorry, I could not understand the question."
        )

        print("\nANSWER:")
        print(answer)

        return answer

In [ ]:
run_final_test("What is the capacity status of ORD-005379?")

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
What is the capacity status of ORD-005379?

DETECTED INTENT:
ORDER_CAPACITY

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

ORDER CAPACITY CHECK:
Order ID: ORD-005379
Package Weight: 1.54 kg
Maximum Capacity: 2.0 kg
Status: WITHIN CAPACITY

FINAL RESULT:
{'order_id': 'ORD-005379', 'package_weight': 1.54, 'capacity_kg': 2.0, 'within_capacity': True}

======================================================================

{'order_id': 'ORD-005379',
 'package_weight': 1.54,
 'capacity_kg': 2.0,
 'within_capacity': True}

In [ ]:
run_final_test("Does ORD-002865 exceed maximum range?")

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
Does ORD-002865 exceed maximum range?

DETECTED INTENT:
ORDER_RANGE_EXCEEDED

ORDER ID:
ORD-002865

RETRIEVED ROWS:
1

ORDER RANGE EXCEEDED CHECK:
Order ID: ORD-002865
Distance: 3.45 km
Maximum Range: -8.6 km
Status: EXCEEDS MAXIMUM RANGE

FINAL RESULT:
{'order_id': 'ORD-002865', 'distance_km': 3.45, 'max_range_km': -8.6, 'exceeds_max_range': True}

======================================================================

{'order_id': 'ORD-002865',
 'distance_km': 3.45,
 'max_range_km': -8.6,
 'exceeds_max_range': True}

In [ ]:
run_final_test("What vehicle type is used for ORD-005379?")

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
What vehicle type is used for ORD-005379?

DETECTED INTENT:
ORDER_VEHICLE

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

ORDER VEHICLE TYPE:
Order ID: ORD-005379
Vehicle Type: Drone

FINAL RESULT:
{'order_id': 'ORD-005379', 'vehicle_type': 'Drone'}

======================================================================

{'order_id': 'ORD-005379', 'vehicle_type': 'Drone'}

In [ ]:
run_final_test("Which drone routes exceed capacity?")

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
Which drone routes exceed capacity?

DETECTED INTENT:
GENERAL_CAPACITY

ORDER ID:
None

RETRIEVED ROWS:
288

GENERAL CAPACITY VIOLATIONS:
Total: 288

First 10 violations:
ORD-002549
ORD-012343
ORD-000680
ORD-009988
ORD-011103
ORD-013759
ORD-009549
ORD-013534
ORD-003907
ORD-014531
...

FINAL RESULT:
288 routes/orders returned

First 10 results:
ORD-002549
ORD-012343
ORD-000680
ORD-009988
ORD-011103
ORD-013759
ORD-009549
ORD-013534
ORD-003907
ORD-014531
...

======================================================================

['ORD-002549',
 'ORD-012343',
 'ORD-000680',
 'ORD-009988',
 'ORD-011103',
 'ORD-013759',
 'ORD-009549',
 'ORD-013534',
 'ORD-003907',
 'ORD-014531',
 'ORD-014960',
 'ORD-011168',
 'ORD-001245',
 'ORD-004200',
 'ORD-014348',
 'ORD-012625',
 'ORD-008272',
 'ORD-005888',
 'ORD-011323',
 'ORD-010911',
 'ORD-009512',
 'ORD-005054',
 'ORD-008528',
 'ORD-009819',
 'ORD-009934',
 'ORD-001622',
 'ORD-001691',
 'ORD-011958',
 'ORD-002595',
 'ORD-009820',
 'ORD-010704',
 'ORD-001532',
 'ORD-002676',
 'ORD-003107',
 'ORD-004846',
 'ORD-013949',
 'ORD-000821',
 'ORD-008743',
 'ORD-005589',
 'ORD-013791',
 'ORD-000943',
 'ORD-000495',
 'ORD-007031',
 'ORD-003709',
 'ORD-010443',
 'ORD-005127',
 'ORD-006254',
 'ORD-004802',
 'ORD-004921',
 'ORD-000199',
 'ORD-000228',
 'ORD-007187',
 'ORD-005278',
 'ORD-012715',
 'ORD-011935',
 'ORD-007863',
 'ORD-003150',
 'ORD-010847',
 'ORD-002867',
 'ORD-014740',
 'ORD-003921',
 'ORD-005692',
 'ORD-014845',
 'ORD-010179',
 'ORD-014429',
 'ORD-004543',
 'ORD-002136',
 'ORD-009577',
 'ORD-013537',
 'ORD-008123',
 'ORD-011763',
 'ORD-008022',
 'ORD-008681',
 'ORD-008966',
 'ORD-007284',
 'ORD-014555',
 'ORD-002444',
 'ORD-010519',
 'ORD-007938',
 'ORD-008263',
 'ORD-009163',
 'ORD-004526',
 'ORD-008452',
 'ORD-001482',
 'ORD-008055',
 'ORD-000303',
 'ORD-002851',
 'ORD-005345',
 'ORD-006882',
 'ORD-006462',
 'ORD-003887',
 'ORD-002236',
 'ORD-001937',
 'ORD-007240',
 'ORD-002976',
 'ORD-005298',
 'ORD-003084',
 'ORD-009136',
 'ORD-006259',
 'ORD-005134',
 'ORD-011532',
 'ORD-005500',
 'ORD-014236',
 'ORD-005178',
 'ORD-008679',
 'ORD-004304',
 'ORD-008212',
 'ORD-009601',
 'ORD-014258',
 'ORD-010146',
 'ORD-011437',
 'ORD-013656',
 'ORD-002589',
 'ORD-001989',
 'ORD-014537',
 'ORD-005351',
 'ORD-009784',
 'ORD-004827',
 'ORD-003725',
 'ORD-010403',
 'ORD-005033',
 'ORD-001368',
 'ORD-010709',
 'ORD-008631',
 'ORD-012325',
 'ORD-012191',
 'ORD-011606',
 'ORD-008133',
 'ORD-004833',
 'ORD-003556',
 'ORD-007046',
 'ORD-013510',
 'ORD-011571',
 'ORD-002645',
 'ORD-014869',
 'ORD-012534',
 'ORD-004901',
 'ORD-014128',
 'ORD-010223',
 'ORD-013436',
 'ORD-014458',
 'ORD-014944',
 'ORD-014166',
 'ORD-003727',
 'ORD-005353',
 'ORD-002904',
 'ORD-001490',
 'ORD-007453',
 'ORD-006165',
 'ORD-003626',
 'ORD-008426',
 'ORD-004676',
 'ORD-006316',
 'ORD-014651',
 'ORD-014575',
 'ORD-010840',
 'ORD-014065',
 'ORD-002189',
 'ORD-009299',
 'ORD-011335',
 'ORD-002094',
 'ORD-004590',
 'ORD-002194',
 'ORD-003776',
 'ORD-001701',
 'ORD-013148',
 'ORD-010027',
 'ORD-009479',
 'ORD-014435',
 'ORD-011936',
 'ORD-012680',
 'ORD-003992',
 'ORD-011538',
 'ORD-006771',
 'ORD-003828',
 'ORD-014967',
 'ORD-000183',
 'ORD-003780',
 'ORD-006772',
 'ORD-006085',
 'ORD-004637',
 'ORD-010029',
 'ORD-014316',
 'ORD-006916',
 'ORD-014558',
 'ORD-001569',
 'ORD-011422',
 'ORD-005480',
 'ORD-010084',
 'ORD-002520',
 'ORD-010759',
 'ORD-007784',
 'ORD-001950',
 'ORD-012602',
 'ORD-000281',
 'ORD-005645',
 'ORD-014045',
 'ORD-008971',
 'ORD-000359',
 'ORD-006157',
 'ORD-000928',
 'ORD-002334',
 'ORD-006560',
 'ORD-000484',
 'ORD-008222',
 'ORD-004131',
 'ORD-013021',
 'ORD-014564',
 'ORD-005271',
 'ORD-011457',
 'ORD-007611',
 'ORD-013649',
 'ORD-003889',
 'ORD-007323',
 'ORD-009651',
 'ORD-006118',
 'ORD-014768',
 'ORD-009470',
 'ORD-000046',
 'ORD-000005',
 'ORD-011275',
 'ORD-000704',
 'ORD-008064',
 'ORD-007978',
 'ORD-013283',
 'ORD-014789',
 'ORD-005132',
 'ORD-000881',
 'ORD-013705',
 'ORD-010526',
 'ORD-007237',
 'ORD-002293',
 'ORD-011698',
 'ORD-014269',
 'ORD-001677',
 'ORD-001791',
 'ORD-005113',
 'ORD-000748',
 'ORD-013325',
 'ORD-012660',
 'ORD-010159',
 'ORD-012945',
 'ORD-014637',
 'ORD-005473',
 'ORD-005756',
 'ORD-005354',
 'ORD-000900',
 'ORD-013248',
 'ORD-004144',
 'ORD-009718',
 'ORD-003778',
 'ORD-003325',
 'ORD-001627',
 'ORD-001105',
 'ORD-014750',
 'ORD-007995',
 'ORD-001344',
 'ORD-011634',
 'ORD-000414',
 'ORD-013923',
 'ORD-009373',
 'ORD-006242',
 'ORD-003414',
 'ORD-008070',
 'ORD-008078',
 'ORD-009177',
 'ORD-009415',
 'ORD-012389',
 'ORD-007579',
 'ORD-008812',
 'ORD-007464',
 'ORD-002760',
 'ORD-014873',
 'ORD-001256',
 'ORD-013969',
 'ORD-013733',
 'ORD-000892',
 'ORD-009164',
 'ORD-003032',
 'ORD-008136',
 'ORD-008663',
 'ORD-008547',
 'ORD-011444',
 'ORD-010396',
 'ORD-001138',
 'ORD-000124',
 'ORD-005238',
 'ORD-006315']

In [ ]:
run_final_test("Which drone routes exceed maximum range?")

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
Which drone routes exceed maximum range?

DETECTED INTENT:
GENERAL_RANGE_EXCEEDED

ORDER ID:
None

RETRIEVED ROWS:
602

GENERAL RANGE EXCEEDED:
Total: 0

First 10 routes:

FINAL RESULT:
0 routes/orders returned

First 10 results:

======================================================================

[]

In [ ]:
run_final_test("What is the range status of ORD-005379?")

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
What is the range status of ORD-005379?

DETECTED INTENT:
ORDER_RANGE

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

ORDER RANGE CHECK:
Order ID: ORD-005379
Distance: 5.01 km
Maximum Range: 15.2 km
Status: WITHIN MAXIMUM RANGE

FINAL RESULT:
{'order_id': 'ORD-005379', 'distance_km': 5.01, 'max_range_km': 15.2, 'within_max_range': True}

======================================================================

{'order_id': 'ORD-005379',
 'distance_km': 5.01,
 'max_range_km': 15.2,
 'within_max_range': True}

# GENERAL_FEASIBLE

In [ ]:
# =============================================================
# FINAL RAG PIPELINE - FEASIBLE ROUTES TEST
# =============================================================

question = "Which drone routes are feasible?"

print("=" * 70)
print("FINAL RAG PIPELINE")
print("=" * 70)

print("\nQUESTION:")
print(question)

result = rag_pipeline(question)

print("\nFINAL RESULT:")

if isinstance(result, list):
    print(f"{len(result)} feasible routes/orders returned")

    print("\nFirst 10 results:")
    for order in result[:10]:
        print(order)

    if len(result) > 10:
        print("...")
else:
    print(result)

print("=" * 70)

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
Which drone routes are feasible?

INTENT:
GENERAL_FEASIBLE

RETRIEVED ROWS:
411

GENERAL FEASIBLE ROUTES:
Total: 411

First 10 feasible routes:
ORD-005379
ORD-014884
ORD-003137
ORD-000415
ORD-008479
ORD-011188
ORD-004441
ORD-007387
ORD-012665
ORD-012992
...

FINAL RESULT:
411 feasible routes/orders returned

First 10 results:
ORD-005379
ORD-014884
ORD-003137
ORD-000415
ORD-008479
ORD-011188
ORD-004441
ORD-007387
ORD-012665
ORD-012992
...
======================================================================

# Final User-Facing Pipeline

In [ ]:
# =============================================================
# FINAL USER-FACING RAG PIPELINE
# =============================================================

while True:

    question = input("\nAsk a drone operations question (or type 'exit'): ")

    if question.lower().strip() == "exit":
        print("\nExiting RAG pipeline.")
        break

    result = rag_pipeline(question)

    print("\nANSWER:")

    if isinstance(result, dict):

        if "within_capacity" in result:

            if result["within_capacity"]:
                print(
                    f"{result['order_id']} is WITHIN capacity. "
                    f"Package weight: {result['package_weight']} kg, "
                    f"Maximum capacity: {result['capacity_kg']} kg."
                )
            else:
                print(
                    f"{result['order_id']} EXCEEDS capacity. "
                    f"Package weight: {result['package_weight']} kg, "
                    f"Maximum capacity: {result['capacity_kg']} kg."
                )

        elif "within_max_range" in result:

            if result["within_max_range"]:
                print(
                    f"{result['order_id']} is WITHIN maximum range. "
                    f"Distance: {result['distance_km']} km, "
                    f"Maximum range: {result['max_range_km']} km."
                )
            else:
                print(
                    f"{result['order_id']} EXCEEDS maximum range. "
                    f"Distance: {result['distance_km']} km, "
                    f"Maximum range: {result['max_range_km']} km."
                )

        elif "exceeds_max_range" in result:

            if result["exceeds_max_range"]:
                print(
                    f"{result['order_id']} EXCEEDS maximum range. "
                    f"Distance: {result['distance_km']} km, "
                    f"Maximum range: {result['max_range_km']} km."
                )
            else:
                print(
                    f"{result['order_id']} is WITHIN maximum range. "
                    f"Distance: {result['distance_km']} km, "
                    f"Maximum range: {result['max_range_km']} km."
                )

        elif "vehicle_type" in result:

            print(
                f"{result['order_id']} uses a "
                f"{result['vehicle_type']}."
            )

        else:
            print(result)

    elif isinstance(result, list):

        print(f"{len(result)} routes/orders found.")

        print("\nFirst 10 results:")

        for order in result[:10]:
            print(order)

        if len(result) > 10:
            print("...")

    else:
        print(result)

INTENT:
GENERAL_CAPACITY

RETRIEVED ROWS:
288

GENERAL CAPACITY VIOLATIONS:
Total: 288

First 10 violations:
ORD-002549
ORD-012343
ORD-000680
ORD-009988
ORD-011103
ORD-013759
ORD-009549
ORD-013534
ORD-003907
ORD-014531
...

ANSWER:
288 routes/orders found.

First 10 results:
ORD-002549
ORD-012343
ORD-000680
ORD-009988
ORD-011103
ORD-013759
ORD-009549
ORD-013534
ORD-003907
ORD-014531
...

INTENT:
GENERAL_RANGE_EXCEEDED

RETRIEVED ROWS:
602

GENERAL RANGE EXCEEDED:
Total: 0

First 10 routes:

ANSWER:
0 routes/orders found.

First 10 results:

INTENT:
GENERAL_FEASIBLE

RETRIEVED ROWS:
411

GENERAL FEASIBLE ROUTES:
Total: 411

First 10 feasible routes:
ORD-005379
ORD-014884
ORD-003137
ORD-000415
ORD-008479
ORD-011188
ORD-004441
ORD-007387
ORD-012665
ORD-012992
...

ANSWER:
411 routes/orders found.

First 10 results:
ORD-005379
ORD-014884
ORD-003137
ORD-000415
ORD-008479
ORD-011188
ORD-004441
ORD-007387
ORD-012665
ORD-012992
...

Exiting RAG pipeline.

# Add this helper function

In [ ]:
# =============================================================
# FINAL ANSWER FORMATTER
# =============================================================

def format_rag_answer(result, intent):

    # ---------------------------------------------------------
    # Specific Order Capacity
    # ---------------------------------------------------------
    if intent == "ORDER_CAPACITY":

        if isinstance(result, dict):

            status = (
                "WITHIN capacity"
                if result["within_capacity"]
                else "EXCEEDS capacity"
            )

            return (
                f'{result["order_id"]} is {status}.\n'
                f'Package weight: {result["package_weight"]} kg\n'
                f'Maximum capacity: {result["capacity_kg"]} kg'
            )


    # ---------------------------------------------------------
    # Specific Order Range
    # ---------------------------------------------------------
    if intent == "ORDER_RANGE":

        if isinstance(result, dict):

            status = (
                "WITHIN maximum range"
                if result["within_max_range"]
                else "EXCEEDS maximum range"
            )

            return (
                f'{result["order_id"]} is {status}.\n'
                f'Distance: {result["distance_km"]} km\n'
                f'Maximum range: {result["max_range_km"]} km'
            )


    # ---------------------------------------------------------
    # Specific Order Range Exceeded
    # ---------------------------------------------------------
    if intent == "ORDER_RANGE_EXCEEDED":

        if isinstance(result, dict):

            status = (
                "EXCEEDS maximum range"
                if result["exceeds_max_range"]
                else "WITHIN maximum range"
            )

            return (
                f'{result["order_id"]} {status}.\n'
                f'Distance: {result["distance_km"]} km\n'
                f'Maximum range: {result["max_range_km"]} km'
            )


    # ---------------------------------------------------------
    # Specific Order Vehicle
    # ---------------------------------------------------------
    if intent == "ORDER_VEHICLE":

        if isinstance(result, dict):

            return (
                f'{result["order_id"]} uses a '
                f'{result["vehicle_type"]}.'
            )


    # ---------------------------------------------------------
    # General Capacity
    # ---------------------------------------------------------
    if intent == "GENERAL_CAPACITY":

        if isinstance(result, list):

            answer = (
                f'{len(result)} routes/orders exceed maximum capacity.'
            )

            if result:

                answer += "\n\nFirst 10 results:"

                for order in result[:10]:
                    answer += f"\n{order}"

                if len(result) > 10:
                    answer += "\n..."

            return answer


    # ---------------------------------------------------------
    # General Range Exceeded
    # ---------------------------------------------------------
    if intent == "GENERAL_RANGE_EXCEEDED":

        if isinstance(result, list):

            answer = (
                f'{len(result)} routes/orders exceed maximum range.'
            )

            if result:

                answer += "\n\nFirst 10 results:"

                for order in result[:10]:
                    answer += f"\n{order}"

                if len(result) > 10:
                    answer += "\n..."

            return answer


    # ---------------------------------------------------------
    # General Feasible Routes
    # ---------------------------------------------------------
    if intent == "GENERAL_FEASIBLE":

        if isinstance(result, list):

            answer = (
                f'{len(result)} feasible routes/orders found.'
            )

            if result:

                answer += "\n\nFirst 10 results:"

                for order in result[:10]:
                    answer += f"\n{order}"

                if len(result) > 10:
                    answer += "\n..."

            return answer


    # ---------------------------------------------------------
    # General Range
    # ---------------------------------------------------------
    if intent == "GENERAL_RANGE":

        if isinstance(result, list):

            answer = (
                f'{len(result)} routes/orders are within maximum range.'
            )

            if result:

                answer += "\n\nFirst 10 results:"

                for order in result[:10]:
                    answer += f"\n{order}"

                if len(result) > 10:
                    answer += "\n..."

            return answer


    # ---------------------------------------------------------
    # Fallback
    # ---------------------------------------------------------

    return str(result)

In [ ]:
# =============================================================
# TEST FINAL ANSWER FORMATTER
# =============================================================

questions = [
    "What is the capacity status of ORD-005379?",
    "Does ORD-002865 exceed maximum range?",
    "What vehicle type is used for ORD-005379?",
    "Which drone routes exceed capacity?",
    "Which drone routes exceed maximum range?",
    "Which drone routes are feasible?"
]

for question in questions:

    intent = detect_intent(question)

    result = rag_pipeline(question)

    print("\n" + "=" * 70)
    print("FINAL USER ANSWER")
    print("=" * 70)

    print(format_rag_answer(result, intent))

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
What is the capacity status of ORD-005379?

INTENT:
ORDER_CAPACITY

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

ORDER CAPACITY CHECK:
Order ID: ORD-005379
Package Weight: 1.54 kg
Maximum Capacity: 2.0 kg
Status: WITHIN CAPACITY

ANSWER:
ORD-005379 is WITHIN capacity. Package weight: 1.54 kg, Maximum capacity: 2.0 kg.

======================================================================
FINAL USER ANSWER
======================================================================
ORD-005379 is WITHIN capacity.
Package weight: 1.54 kg
Maximum capacity: 2.0 kg

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
Does ORD-002865 exceed maximum range?

INTENT:
ORDER_RANGE_EXCEEDED

ORDER ID:
ORD-002865

RETRIEVED ROWS:
1

ORDER RANGE EXCEEDED CHECK:
Order ID: ORD-002865
Distance: 3.45 km
Maximum Range: -8.6 km
Status: EXCEEDS MAXIMUM RANGE

ANSWER:
ORD-002865 EXCEEDS maximum range. Distance: 3.45 km, Maximum range: -8.6 km.

======================================================================
FINAL USER ANSWER
======================================================================
ORD-002865 EXCEEDS maximum range.
Distance: 3.45 km
Maximum range: -8.6 km

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
What vehicle type is used for ORD-005379?

INTENT:
ORDER_VEHICLE

ORDER ID:
ORD-005379

RETRIEVED ROWS:
1

ORDER VEHICLE TYPE:
Order ID: ORD-005379
Vehicle Type: Drone

ANSWER:
ORD-005379 uses a Drone.

======================================================================
FINAL USER ANSWER
======================================================================
ORD-005379 uses a Drone.

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
Which drone routes exceed capacity?

INTENT:
GENERAL_CAPACITY

RETRIEVED ROWS:
0

ANSWER:
No capacity violations were found.

======================================================================
FINAL USER ANSWER
======================================================================
No capacity violations were found.

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
Which drone routes exceed maximum range?

INTENT:
GENERAL_RANGE_EXCEEDED

RETRIEVED ROWS:
602

GENERAL RANGE EXCEEDED:
Total: 0

First 10 routes:

ANSWER:
0 routes/orders found.

First 10 results:

======================================================================
FINAL USER ANSWER
======================================================================
0 routes/orders exceed maximum range.

======================================================================
FINAL RAG PIPELINE
======================================================================

QUESTION:
Which drone routes are feasible?

INTENT:
GENERAL_FEASIBLE

RETRIEVED ROWS:
411

GENERAL FEASIBLE ROUTES:
Total: 411

First 10 feasible routes:
ORD-005379
ORD-014884
ORD-003137
ORD-000415
ORD-008479
ORD-011188
ORD-004441
ORD-007387
ORD-012665
ORD-012992
...

ANSWER:
411 routes/orders found.

First 10 results:
ORD-005379
ORD-014884
ORD-003137
ORD-000415
ORD-008479
ORD-011188
ORD-004441
ORD-007387
ORD-012665
ORD-012992
...

======================================================================
FINAL USER ANSWER
======================================================================
411 feasible routes/orders found.

First 10 results:
ORD-005379
ORD-014884
ORD-003137
ORD-000415
ORD-008479
ORD-011188
ORD-004441
ORD-007387
ORD-012665
ORD-012992
...

#  CLEAN RAG PIPELINE

In [24]:

# SMARTLOGIX AI - CLEAN RAG PIPELINE
# Phase 1: Drone Route Intelligence


import re
import pandas as pd


# ============================================================
# 1. DATABASE RETRIEVAL
# ============================================================

def retrieve_drone_data(question):

    q = question.lower().strip()

    # --------------------------------------------------------
    # Extract Order ID
    # Example: ORD-005379
    # --------------------------------------------------------

    order_match = re.search(r'\bord-\d+\b', q, re.IGNORECASE)

    # ========================================================
    # SPECIFIC ORDER QUERY
    # ========================================================

    if order_match:

        order_id = order_match.group(0).upper()

        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE UPPER(order_id) = %s
        """

        try:

            with engine.connect() as conn:

                result = pd.read_sql_query(
                    sql,
                    conn,
                    params=(order_id,)
                )

            return result

        except Exception as e:

            print("Database error:", e)

            return pd.DataFrame()


    # ========================================================
    # GENERAL DRONE QUESTIONS
    # ========================================================

    # --------------------------------------------------------
    # Feasible drone routes
    # --------------------------------------------------------

    if (
        "feasible" in q
        or "possible" in q
        or "eligible" in q
    ):

        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND package_weight <= capacity_kg
          AND distance_km <= max_range_km
        """


    # --------------------------------------------------------
    # Capacity violations
    # --------------------------------------------------------

    elif (
        "capacity" in q
        and (
            "exceed" in q
            or "over" in q
            or "violation" in q
            or "violat" in q
            or "limit" in q
        )
    ):

        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND package_weight > capacity_kg
        """


    # --------------------------------------------------------
    # Range queries
    # --------------------------------------------------------

    elif (
        "range" in q
        or "maximum distance" in q
        or "max distance" in q
    ):

        sql = """
        SELECT
            order_id,
            package_weight,
            vehicle_type,
            capacity_kg,
            distance_km,
            max_range_km,
            weight_exceeds_capacity
        FROM orders_raw
        WHERE LOWER(vehicle_type) = 'drone'
          AND distance_km <= max_range_km
        """


    # --------------------------------------------------------
    # Unknown query
    # --------------------------------------------------------

    else:

        return pd.DataFrame()


    # --------------------------------------------------------
    # Execute general query
    # --------------------------------------------------------

    try:

        with engine.connect() as conn:

            result = pd.read_sql_query(
                sql,
                conn
            )

        return result

    except Exception as e:

        print("Database error:", e)

        return pd.DataFrame()


# ============================================================
# 2. INTENT DETECTION
# ============================================================

def detect_intent(question):

    q = question.lower().strip()


    # --------------------------------------------------------
    # Specific order query
    # --------------------------------------------------------

    if re.search(r'\bord-\d+\b', q):

        return "ORDER_QUERY"


    # --------------------------------------------------------
    # Capacity query
    # --------------------------------------------------------

    if (
        "capacity" in q
        or "overloaded" in q
        or "weight limit" in q
        or "weight exceeds" in q
        or "too heavy" in q
    ):

        return "CAPACITY_QUERY"


    # --------------------------------------------------------
    # Range query
    # --------------------------------------------------------

    if (
        "range" in q
        or "maximum distance" in q
        or "max distance" in q
    ):

        return "RANGE_QUERY"


    # --------------------------------------------------------
    # Feasibility query
    # --------------------------------------------------------

    if (
        "feasible" in q
        or "can be delivered" in q
        or "deliver by drone" in q
        or "drone delivery" in q
        or "possible by drone" in q
    ):

        return "FEASIBILITY_QUERY"


    # --------------------------------------------------------
    # Unknown
    # --------------------------------------------------------

    return "UNKNOWN"


# ============================================================
# 3. BUSINESS LOGIC
# ============================================================

def analyze_drone_order(df):

    # --------------------------------------------------------
    # Order not found
    # --------------------------------------------------------

    if df.empty:

        return {
            "status": "NOT_FOUND",
            "message": "Order not found in the verified database."
        }


    # --------------------------------------------------------
    # Get first matching order
    # --------------------------------------------------------

    row = df.iloc[0]


    # --------------------------------------------------------
    # Extract values safely
    # --------------------------------------------------------

    package_weight = float(row["package_weight"])
    capacity = float(row["capacity_kg"])
    distance = float(row["distance_km"])
    max_range = float(row["max_range_km"])


    # --------------------------------------------------------
    # Capacity check
    # --------------------------------------------------------

    capacity_ok = package_weight <= capacity


    # --------------------------------------------------------
    # Range check
    # --------------------------------------------------------

    range_ok = distance <= max_range


    # --------------------------------------------------------
    # Final drone feasibility
    # --------------------------------------------------------

    feasible = capacity_ok and range_ok


    # --------------------------------------------------------
    # Return complete analysis
    # --------------------------------------------------------

    return {

        "status": "FOUND",

        "order_id": row["order_id"],

        "package_weight_kg": package_weight,

        "capacity_kg": capacity,

        "distance_km": distance,

        "max_range_km": max_range,

        "capacity_ok": capacity_ok,

        "range_ok": range_ok,

        "drone_feasible": feasible
    }


# ============================================================
# 4. SMARTLOGIX RAG PIPELINE
# ============================================================

def smartlogix_rag(question):

    print("=" * 70)
    print("SMARTLOGIX AI - RAG")
    print("=" * 70)


    # --------------------------------------------------------
    # Display question
    # --------------------------------------------------------

    print("\nQUESTION:")
    print(question)


    # --------------------------------------------------------
    # Detect intent
    # --------------------------------------------------------

    intent = detect_intent(question)

    print("\nINTENT:")
    print(intent)


    # --------------------------------------------------------
    # Retrieve information from PostgreSQL
    # --------------------------------------------------------

    retrieved = retrieve_drone_data(question)

    print("\nRETRIEVED ROWS:")
    print(len(retrieved))


    # ========================================================
    # ORDER QUERY
    # ========================================================

    if intent == "ORDER_QUERY":

        analysis = analyze_drone_order(retrieved)


        # ----------------------------------------------------
        # Order not found
        # ----------------------------------------------------

        if analysis["status"] == "NOT_FOUND":

            return analysis["message"]


        # ----------------------------------------------------
        # Drone is feasible
        # ----------------------------------------------------

        if analysis["drone_feasible"]:

            answer = (

                f"Yes. {analysis['order_id']} is feasible "
                f"for drone delivery. "

                f"The package weighs "
                f"{analysis['package_weight_kg']:.2f} kg, "

                f"while the drone capacity is "
                f"{analysis['capacity_kg']:.2f} kg. "

                f"The route distance is "
                f"{analysis['distance_km']:.2f} km, "

                f"which is within the maximum range of "
                f"{analysis['max_range_km']:.2f} km."
            )


        # ----------------------------------------------------
        # Drone is NOT feasible
        # ----------------------------------------------------

        else:

            reasons = []


            # Capacity failure
            if not analysis["capacity_ok"]:

                reasons.append(

                    f"package weight "
                    f"({analysis['package_weight_kg']:.2f} kg) "
                    f"exceeds drone capacity "
                    f"({analysis['capacity_kg']:.2f} kg)"
                )


            # Range failure
            if not analysis["range_ok"]:

                reasons.append(

                    f"route distance "
                    f"({analysis['distance_km']:.2f} km) "
                    f"exceeds maximum range "
                    f"({analysis['max_range_km']:.2f} km)"
                )


            answer = (

                f"No. {analysis['order_id']} is not feasible "
                f"for drone delivery because "

                + " and ".join(reasons)

                + "."
            )


        return answer


    # ========================================================
    # GENERAL CAPACITY QUERY
    # ========================================================

    if intent == "CAPACITY_QUERY":

        if retrieved.empty:

            return (
                "No drone capacity violations "
                "were found."
            )


        return (

            f"There are {len(retrieved)} drone routes "
            f"where the package weight exceeds "
            f"the vehicle capacity."
        )


    # ========================================================
    # GENERAL RANGE QUERY
    # ========================================================

    if intent == "RANGE_QUERY":

        if retrieved.empty:

            return (
                "No drone routes were found "
                "within the maximum range."
            )


        return (

            f"There are {len(retrieved)} drone routes "
            f"within their maximum range."
        )


    # ========================================================
    # GENERAL FEASIBILITY QUERY
    # ========================================================

    if intent == "FEASIBILITY_QUERY":

        if retrieved.empty:

            return (
                "No feasible drone routes were found."
            )


        return (

            f"There are {len(retrieved)} feasible "
            f"drone routes based on both vehicle "
            f"capacity and maximum range."
        )


    # ========================================================
    # UNKNOWN QUERY
    # ========================================================

    return (

        "I could not determine the requested "
        "logistics analysis. "

        "Please ask about an order, drone capacity, "
        "drone range, or delivery feasibility."
    )


# ============================================================
# PIPELINE READY
# ============================================================

print("SmartLogix RAG pipeline loaded successfully.")

SmartLogix RAG pipeline loaded successfully.

In [25]:

# TEST 1 - SPECIFIC ORDER

question = "Can ORD-005379 be delivered by drone?"

answer = smartlogix_rag(question)

print("\nANSWER:")
print(answer)

======================================================================
SMARTLOGIX AI - RAG
======================================================================

QUESTION:
Can ORD-005379 be delivered by drone?

INTENT:
ORDER_QUERY

RETRIEVED ROWS:
1

ANSWER:
Yes. ORD-005379 is feasible for drone delivery. The package weighs 1.54 kg, while the drone capacity is 2.00 kg. The route distance is 5.01 km, which is within the maximum range of 15.20 km.

# connect Ollama + DeepSeek

In [26]:

# SMARTLOGIX AI - OLLAMA LLM CONNECTION


import requests
import json


# ------------------------------------------------------------
# Ollama configuration
# ------------------------------------------------------------

OLLAMA_URL = "http://localhost:11434/api/generate"

OLLAMA_MODEL = "deepseek-r1:7b"


# ------------------------------------------------------------
# Test Ollama connection
# ------------------------------------------------------------

def test_ollama():

    try:

        response = requests.get(
            "http://localhost:11434/api/tags",
            timeout=10
        )

        if response.status_code == 200:

            models = response.json().get("models", [])

            model_names = [
                model.get("name", "")
                for model in models
            ]

            print("Ollama connection: SUCCESS")

            print("\nAvailable models:")

            for model in model_names:
                print(" -", model)

            if OLLAMA_MODEL in model_names:

                print(
                    f"\n{OLLAMA_MODEL} is available."
                )

            else:

                print(
                    f"\nWARNING: {OLLAMA_MODEL} "
                    f"was not found."
                )

        else:

            print(
                "Ollama responded with status:",
                response.status_code
            )

    except Exception as e:

        print("Ollama connection failed.")
        print("Error:", e)


# ------------------------------------------------------------
# Run connection test
# ------------------------------------------------------------

test_ollama()

Ollama connection: SUCCESS

Available models:
 - deepseek-r1:7b

deepseek-r1:7b is available.

# LLM generation layer

In [27]:

# SMARTLOGIX AI - LLM RESPONSE GENERATOR
# Ollama + DeepSeek-R1:7b


import requests


# ------------------------------------------------------------
# Ollama settings
# ------------------------------------------------------------

OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "deepseek-r1:7b"


# ------------------------------------------------------------
# Generate response using Ollama
# ------------------------------------------------------------

def generate_llm_response(question, context):

    prompt = f"""
You are SmartLogix AI, an intelligent logistics assistant.

Answer the user's question using ONLY the verified information
provided in the context below.

IMPORTANT RULES:
1. Do not invent or assume information.
2. Do not change any numbers from the context.
3. If the context does not contain enough information, clearly say so.
4. Give a concise and professional answer.
5. Explain the reasoning when useful.
6. Do not mention databases, SQL, RAG, prompts, or internal processing
   unless the user asks about the system itself.

USER QUESTION:
{question}

VERIFIED CONTEXT:
{context}

Now provide the best answer to the user.
"""

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.2
        }
    }

    try:

        response = requests.post(
            OLLAMA_URL,
            json=payload,
            timeout=120
        )

        response.raise_for_status()

        result = response.json()

        answer = result.get("response", "").strip()

        if not answer:
            return "I could not generate a response."

        return answer

    except requests.exceptions.ConnectionError:

        return (
            "Unable to connect to Ollama. "
            "Please make sure Ollama is running."
        )

    except requests.exceptions.Timeout:

        return (
            "The AI model took too long to respond. "
            "Please try again."
        )

    except Exception as e:

        return f"LLM error: {e}"


print("SmartLogix LLM response generator loaded successfully.")

SmartLogix LLM response generator loaded successfully.

# Test DeepSeek directly

In [29]:

# TEST 2 - DIRECT LLM TEST


question = "What is SmartLogix AI?"

context = """
SmartLogix AI is an intelligent logistics system that combines
machine learning, route optimization, computer vision, RAG,
LLMs, and AI agents to support logistics operations.
"""

answer = generate_llm_response(question, context)

print("\nLLM ANSWER:")
print(answer)

LLM ANSWER:
SmartLogix AI is an advanced intelligent logistics system that integrates multiple technologies to optimize logistics operations. It combines machine learning for data analysis, route optimization for efficient delivery paths, computer vision for real-time monitoring, RAG (Retrieval-Augmented Generation) for enhanced search capabilities, LLMs (Large Language Models) for natural language processing, and AI agents for automated decision-making. This integrated approach enables the system to improve efficiency, accuracy, and decision-making in logistics management.

# Connect RAG → DeepSeek

In [30]:

# SMARTLOGIX AI - RAG + LLM INTEGRATION

def smartlogix_rag_llm(question):

    print("=" * 70)
    print("SMARTLOGIX AI - RAG + LLM")
    print("=" * 70)

    print("\nQUESTION:")
    print(question)

    # --------------------------------------------------------
    # 1. Detect intent
    # --------------------------------------------------------

    intent = detect_intent(question)

    print("\nINTENT:")
    print(intent)

    # --------------------------------------------------------
    # 2. Retrieve verified information
    # --------------------------------------------------------

    retrieved = retrieve_drone_data(question)

    print("\nRETRIEVED ROWS:")
    print(len(retrieved))

    # --------------------------------------------------------
    # 3. Handle specific order query
    # --------------------------------------------------------

    if intent == "ORDER_QUERY":

        analysis = analyze_drone_order(retrieved)

        # Order not found
        if analysis["status"] == "NOT_FOUND":

            return analysis["message"]

        # ----------------------------------------------------
        # Create verified context
        # ----------------------------------------------------

        context = f"""
Order ID: {analysis['order_id']}

Package weight: {analysis['package_weight_kg']:.2f} kg

Drone capacity: {analysis['capacity_kg']:.2f} kg

Route distance: {analysis['distance_km']:.2f} km

Maximum drone range: {analysis['max_range_km']:.2f} km

Capacity check: {
    'PASS' if analysis['capacity_ok'] else 'FAIL'
}

Range check: {
    'PASS' if analysis['range_ok'] else 'FAIL'
}

Drone delivery feasibility: {
    'FEASIBLE' if analysis['drone_feasible'] else 'NOT FEASIBLE'
}
"""

        # ----------------------------------------------------
        # Send verified context to LLM
        # ----------------------------------------------------

        answer = generate_llm_response(
            question,
            context
        )

        return answer


    # ========================================================
    # 4. General capacity query
    # ========================================================

    if intent == "CAPACITY_QUERY":

        if retrieved.empty:

            context = """
No drone capacity violations were found
in the verified database.
"""

        else:

            context = f"""
Verified database result:

Number of drone routes where package weight
exceeds vehicle capacity: {len(retrieved)}

These are capacity-violation routes.
"""

        return generate_llm_response(
            question,
            context
        )


    # ========================================================
    # 5. General range query
    # ========================================================

    if intent == "RANGE_QUERY":

        if retrieved.empty:

            context = """
No drone routes were found within their
maximum permitted range.
"""

        else:

            context = f"""
Verified database result:

Number of drone routes within their
maximum permitted range: {len(retrieved)}
"""

        return generate_llm_response(
            question,
            context
        )


    # ========================================================
    # 6. General feasibility query
    # ========================================================

    if intent == "FEASIBILITY_QUERY":

        if retrieved.empty:

            context = """
No feasible drone routes were found
in the verified database.
"""

        else:

            context = f"""
Verified database result:

Number of feasible drone routes:
{len(retrieved)}

A route is considered feasible when:

1. Package weight is less than or equal
   to drone capacity.

2. Route distance is less than or equal
   to maximum drone range.
"""

        return generate_llm_response(
            question,
            context
        )


    # ========================================================
    # 7. Unknown query
    # ========================================================

    return (
        "I can currently help with drone delivery "
        "questions such as order feasibility, "
        "drone capacity, and drone range."
    )


print("SmartLogix RAG + LLM pipeline loaded successfully.")

SmartLogix RAG + LLM pipeline loaded successfully.

In [31]:

# TEST 3 - COMPLETE RAG + LLM PIPELINE

question = "Can ORD-005379 be delivered by drone?"

answer = smartlogix_rag_llm(question)

print("\nFINAL SMARTLOGIX AI ANSWER:")
print(answer)

======================================================================
SMARTLOGIX AI - RAG + LLM
======================================================================

QUESTION:
Can ORD-005379 be delivered by drone?

INTENT:
ORDER_QUERY

RETRIEVED ROWS:
1

FINAL SMARTLOGIX AI ANSWER:
Yes, ORD-005379 can be delivered by drone. The drone's capacity of 2.00 kg is sufficient for the package weight of 1.54 kg, and the route distance of 5.01 km is within the drone's maximum range of 15.20 km. Both the capacity check and range check have been passed, making drone delivery feasible.

# Test more RAG scenarios

In [33]:
# ============================================================
# SMARTLOGIX AI - RAG + LLM TEST SUITE
# ============================================================

test_questions = [

    "Can ORD-005379 be delivered by drone?",

    "How many drone routes are feasible?",

    "How many drone routes have capacity violations?",

    "How many drone routes are within their maximum range?",

    "Can ORD-999999 be delivered by drone?"
]


for i, question in enumerate(test_questions, start=1):

    print("\n")
    print("=" * 80)
    print(f"TEST {i}")
    print("=" * 80)

    answer = smartlogix_rag_llm(question)

    print("\nFINAL ANSWER:")
    print(answer)

================================================================================
TEST 1
================================================================================
======================================================================
SMARTLOGIX AI - RAG + LLM
======================================================================

QUESTION:
Can ORD-005379 be delivered by drone?

INTENT:
ORDER_QUERY

RETRIEVED ROWS:
1

FINAL ANSWER:
Yes, ORD-005379 can be delivered by drone. The package weight (1.54 kg) is within the drone's capacity (2.00 kg), and the delivery distance (5.01 km) is within the drone's maximum range (15.20 km). Both the capacity check and range check have passed, making drone delivery feasible.


================================================================================
TEST 2
================================================================================
======================================================================
SMARTLOGIX AI - RAG + LLM
======================================================================

QUESTION:
How many drone routes are feasible?

INTENT:
FEASIBILITY_QUERY

RETRIEVED ROWS:
411

FINAL ANSWER:
Based on the verified database result, the number of feasible drone routes is **411**. This figure is derived from the criteria that each route must meet: the package weight being within the drone's capacity and the route distance not exceeding the drone's maximum range.


================================================================================
TEST 3
================================================================================
======================================================================
SMARTLOGIX AI - RAG + LLM
======================================================================

QUESTION:
How many drone routes have capacity violations?

INTENT:
CAPACITY_QUERY

RETRIEVED ROWS:
288

FINAL ANSWER:
The number of drone routes with capacity violations is 288. These routes involve package weights exceeding the vehicle capacity.


================================================================================
TEST 4
================================================================================
======================================================================
SMARTLOGIX AI - RAG + LLM
======================================================================

QUESTION:
How many drone routes are within their maximum range?

INTENT:
RANGE_QUERY

RETRIEVED ROWS:
602

FINAL ANSWER:
The number of drone routes within their maximum permitted range is **602**.


================================================================================
TEST 5
================================================================================
======================================================================
SMARTLOGIX AI - RAG + LLM
======================================================================

QUESTION:
Can ORD-999999 be delivered by drone?

INTENT:
ORDER_QUERY

RETRIEVED ROWS:
0

FINAL ANSWER:
Order not found in the verified database.